# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-32: Perfurocortantes e Acidentes (40 questões)
"""

def get_nr32_perfuro_questions():
    items = [
        # 1
        ("Em relação ao manuseio de materiais perfurocortantes, o subitem 32.2.4.15 da NR-32 estabelece taxativamente que:",
         "O reencape manual de agulhas é permitido se realizado com técnica passiva de uma mão.",
         "São vedados o reencape e a desconexão manual de agulhas com as mãos.",
         "A agulha deve ser entortada ou quebrada com alicate cirúrgico antes do descarte.",
         "A desconexão manual de agulhas é permitida se o profissional utilizar luvas cirúrgicas duplas.",
         "O reencape só é proibido para agulhas de calibre superior a 25x8 mm.",
         "B",
         "O item 32.2.4.15 da NR-32 proíbe terminantemente o reencape e a desconexão manual de agulhas.",
         "NR-32, item 32.2.4.15",
         "fácil"),
        # 2
        ("A Portaria MTE nº 939/2006 (atualizada e incorporada à NR-32) estabeleceu a obrigatoriedade da implantação de dispositivos de segurança em:",
         "Apenas em bisturis descartáveis utilizados em centros cirúrgicos terciários.",
         "Todos os materiais perfurocortantes utilizados nos serviços de saúde para prevenir acidentes ocupacionais.",
         "Exclusivamente nas agulhas de anestesia peridural e raquidiana.",
         "Apenas nas seringas de insulina distribuídas para uso domiciliar de pacientes.",
         "Somente em equipamentos hospitalares importados de países da União Europeia.",
         "B",
         "A Portaria 939/2006 determina que todos os materiais perfurocortantes devem possuir dispositivo de segurança integrado ou passivo.",
         "Portaria MTE 939/2006 e NR-32",
         "fácil"),
        # 3
        ("Um dispositivo de segurança para perfurocortantes, para atender às exigências da NR-32, deve possuir as seguintes características técnicas:",
         "Ser de acionamento complexo, exigindo o uso de ferramentas externas e chaves manuais.",
         "Ser parte integrante do dispositivo (ou pré-acoplado), de acionamento fácil, seguro e que impeça a reutilização da agulha após travamento.",
         "Permitir o destravamento mecânico repetido pelo técnico para reaproveitar a agulha em outro paciente.",
         "Exigir que o profissional use as duas mãos simultaneamente em frente à ponta da agulha para ativá-lo.",
         "Ser confeccionado exclusivamente em vidro temperado semitransparente.",
         "B",
         "O dispositivo de segurança deve ser parte integrante, com mecanismo de travamento irreversível, de preferência passivo ou acionável com uma única mão.",
         "NR-32 e Portaria 939/2006",
         "média"),
        # 4
        ("Qual é o limite máximo de preenchimento dos recipientes para acondicionamento de materiais perfurocortantes (caixas rígidas amarelas) conforme a NR-32 e normas sanitárias?",
         "Até a borda superior externa da tampa plástica.",
         "Até a linha indicadora de capacidade máxima demarcada pelo fabricante (cerca de 5 cm abaixo do bocal / 2/3 a 3/4 do volume).",
         "Até 100% de sua capacidade volumétrica, comprimindo com as mãos para caber mais agulhas.",
         "Até a metade da caixa (50%), devendo ser descartada após 24 horas independentemente do volume.",
         "Até 95% do volume total, lacrando com fita crepe comum.",
         "B",
         "Os coletores de perfurocortantes devem ser preenchidos somente até a linha tracejada de segurança fixada a cerca de 5 cm abaixo da abertura superior.",
         "NR-32, item 32.2.4.15 e RDC 222/2018",
         "fácil"),
        # 5
        ("Em relação à localização e instalação dos coletores rígidos de descarte de perfurocortantes nos leitos e postos da FHCGV, a NR-32 determina que:",
         "Devem ser colocados diretamente apoiados sobre o piso próximo à lixeira comum.",
         "Devem estar fixados em suportes exclusivos, em altura que permita a visualização da abertura e linha de enchimento pelo trabalhador, próximo ao local de geração.",
         "Devem ser guardados trancados dentro dos armários do almoxarifado central.",
         "Devem ficar pendurados em cabides móveis na altura de 2,20 metros do solo.",
         "Devem ser instalados exclusivamente nos banheiros públicos dos visitantes.",
         "B",
         "Os coletores de perfurocortantes devem ser mantidos em suporte apropriado, em altura acessível e visível (ergonômica), junto ao local do procedimento.",
         "NR-32, item 32.2.4.15",
         "média"),
        # 6
        ("Ocorrendo um acidente perfurocortante com agulha contaminada por sangue de paciente, qual deve ser a PRIMEIRA conduta imediata no local da lesão pelo trabalhador acidentado?",
         "Espremer a ferida com força até sair sangue arterial por 10 minutos.",
         "Lavar exaustivamente o local ferido com água e sabão (ou soro fisiológico em caso de mucosa), sem espremer a lesão.",
         "Fazer torniquete apertado no membro afetado e aplicar álcool puro a 99% na incisão.",
         "Cauterizar a ferida com ferro quente ou chama de isqueiro no balcão da farmácia.",
         "Colocar açúcar cristal ou borra de café para estancar o sangramento imediato.",
         "B",
         "A conduta inicial é lavar exaustivamente o ferimento com água e sabão; espremer a lesão é contraindicado pois aumenta o trauma e a circulação local do vírus.",
         "Protocolo de Exposição Ocupacional a Material Biológico / Ministério da Saúde e NR-32",
         "fácil"),
        # 7
        ("Caso o acidente com material biológico envolva respingo de sangue nos olhos ou na mucosa oral do trabalhador da FHCGV, a recomendação oficial é:",
         "Pingar colírio anestésico concentrado sem lavar os olhos.",
         "Lavar a mucosa exaustivamente com soro fisiológico a 0,9% ou água corrente limpa.",
         "Instilar solução alcoólica a 70% na conjuntiva ocular.",
         "Friccionar os olhos com as mãos enluvadas sujas para remover o sangue.",
         "Vedar os olhos com gaze seca por 48 horas sem qualquer irrigação líquida.",
         "B",
         "A exposição de mucosas exige lavagem exaustiva com solução salina isotônica (soro fisiológico) ou água corrente em abundância.",
         "Protocolos de Biossegurança MS e NR-32",
         "fácil"),
        # 8
        ("A Profilaxia Pós-Exposição (PEP) para o vírus da imunodeficiência humana (HIV) após acidente perfurocortante grave deve ser iniciada idealmente nas primeiras:",
         "2 horas após o acidente, tolerando-se início em até 72 horas.",
         "48 a 96 horas, não tendo eficácia se iniciada antes de 24 horas.",
         "7 a 14 dias após a confirmação sorológica do paciente-fonte.",
         "30 dias após o fechamento do inquérito administrativo pela fundação.",
         "Qualquer momento dentro dos primeiros 6 meses após a ocorrência.",
         "A",
         "A quimioprofilaxia antirretroviral (PEP HIV) tem máxima eficácia se iniciada nas primeiras 2 horas pós-acidente, tendo limite de benefício até 72 horas.",
         "Protocolo Clínico e Diretrizes Terapêuticas para PEP (Ministério da Saúde) e NR-32",
         "média"),
        # 9
        ("A respeito da identificação do paciente-fonte em acidente com perfurocortante na FHCGV, a conduta correta do serviço de saúde compreende:",
         "Realizar testagem rápida para HIV, Hepatite B (HBsAg) e Hepatite C (Anti-HCV) do paciente-fonte, mediante consentimento informado, e teste basal do trabalhador.",
         "Obrigar o paciente-fonte a assinar termo de confissão de culpa pela transmissão viral.",
         "Colher sangue do paciente à força sem que ele saiba da realização dos testes.",
         "Dispensar a testagem da fonte caso o paciente aparente boa saúde visual e boa vestimenta.",
         "Testar apenas a urina do paciente para dosagem de glicose e ureia.",
         "A",
         "Deve-se buscar a identificação do paciente-fonte para realização de testes rápidos (HIV, HBsAg, HCV) com consentimento, avaliando o risco e conduta profilática para o trabalhador.",
         "Protocolo de Exposição Ocupacional MS e NR-32",
         "média"),
        # 10
        ("Em relação à emissão da Comunicação de Acidente de Trabalho (CAT) em acidentes com materiais perfurocortantes e exposição biológica:",
         "A CAT só deve ser emitida se o trabalhador sofrer amputação ou afastamento superior a 15 dias.",
         "A emissão da CAT é obrigatória para todo e qualquer acidente com material biológico perfurocortante, mesmo que não haja afastamento do trabalho.",
         "A CAT é dispensada se a fonte for sabidamente não reagente para HIV e Hepatite.",
         "Apenas o médico perito do INSS tem competência legal para preencher a primeira via da CAT.",
         "A empresa tem prazo de 30 dias úteis para comunicar o acidente à Previdência Social.",
         "B",
         "A emissão da CAT é obrigatória em qualquer acidente biológico com perfurocortante, com ou sem afastamento, até o 1º dia útil seguinte (Lei 8.213/91 e NR-32).",
         "Lei 8.213/91, Art. 22 e NR-32, item 32.2.4.15",
         "fácil"),
        # 11
        ("Além da CAT emitida pelo SESMT/Previdência, acidentes de trabalho com exposição a material biológico devem ser notificados no âmbito do SUS através do:",
         "SINAN (Sistema de Informação de Agravos de Notificação), por meio da Ficha de Notificação de Acidente de Trabalho com Exposição a Material Biológico.",
         "SIA-SUS exclusivamente para cobrança de taxas de internação.",
         "Cadastro Único de Programas Sociais do Governo Federal (CadÚnico).",
         "Livro de atas manuscrito do condomínio residencial do servidor.",
         "Sistema de Bilhetagem Eletrônica do transporte coletivo de Belém.",
         "A",
         "O agravo 'Acidente de Trabalho com Exposição a Material Biológico' é de notificação compulsória no SINAN em toda a rede de saúde pública e privada.",
         "Portaria de Consolidação GM/MS nº 4/2017 e NR-32",
         "média"),
        # 12
        ("Qual o tempo padrão de duração do esquema de Profilaxia Pós-Exposição (PEP) com medicamentos antirretrovirais para HIV quando indicada após acidente grave?",
         "7 dias corridos.",
         "28 dias ininterruptos.",
         "6 meses consecutivos sem pausas.",
         "1 único dia com dose tripla de ataque.",
         "1 ano completo com avaliações semanais.",
         "B",
         "O tratamento profilático pós-exposição ao HIV (PEP) tem duração padrão de 28 dias com terapia antirretroviral combinada.",
         "PCDT PEP HIV - Ministério da Saúde e NR-32",
         "média"),
        # 13
        ("No acompanhamento clínico e sorológico do trabalhador acidentado com perfurocortante biológico, os testes sorológicos de controle (HIV, HBV, HCV) são habitualmente repetidos em:",
         "Tempo zero (no momento do acidente), 6 semanas e 3 a 6 meses após a exposição.",
         "Apenas 10 anos após o acidente quando o servidor for se aposentar.",
         "Diariamente durante os primeiros 90 dias após a picada.",
         "Uma única vez após 5 anos sem necessidade de teste basal no momento do evento.",
         "Apenas se o trabalhador manifestar febre amarela nos primeiros 2 dias.",
         "A",
         "O protocolo do Ministério da Saúde preconiza testagem basal (tempo zero) e acompanhamento sorológico com 6 semanas e aos 3 e 6 meses após a exposição.",
         "Protocolo de Exposição Ocupacional MS",
         "média"),
        # 14
        ("Durante uma cirurgia na FHCGV, um cirurgião perfura a luva e o dedo com agulha de sutura cirúrgica. Qual conduta imediata deve ser adotada pela equipe de centro cirúrgico?",
         "Continuar operando o paciente por mais 4 horas com a mesma luva furada.",
         "Substituir imediatamente a agulha, retirar a luva contaminada, higienizar a lesão, trocar de luva e comunicar imediatamente o acidente para avaliação médica.",
         "Amarrar uma gaze estéril sobre a luva furada e terminar a cirurgia sem trocar o material.",
         "Queimar a luva na mesa cirúrgica estéril.",
         "Ignorar o fato, pois o sangue cirúrgico é considerado estéril por definição médica.",
         "B",
         "A troca imediata de luva e campo, assepsia, descarte seguro do instrumental pérfuro e acolhimento para PEP são exigências fundamentais de segurança cirúrgica e ocupacional.",
         "NR-32 e Protocolo de Centro Cirúrgico",
         "fácil"),
        # 15
        ("Na montagem e fechamento dos coletores de perfurocortantes, o técnico de segurança do trabalho deve orientar que o fechamento definitivo da caixa seja realizado:",
         "Pressionando as abas traváveis com as mãos nas áreas indicadas, sem empurrar agulhas excedentes para dentro com os dedos.",
         "Usando as duas mãos para socar os materiais que estão transbordando para dentro da caixa.",
         "Virando a caixa de cabeça para baixo sobre uma bancada para compactar o lixo.",
         "Colocando um peso de 20 kg de concreto sobre a tampa até amassar todo o papelão.",
         "Transferindo as seringas soltas da caixa cheia para uma caixa vazia com as mãos desnudas.",
         "A",
         "O fechamento dos recipientes deve ser feito pelas travas externas de segurança, sendo estritamente proibido empurrar materiais com as mãos ou pés.",
         "NR-32, item 32.2.4.15 e RDC 222/2018",
         "fácil"),
        # 16
        ("O Plano de Prevenção de Riscos de Acidentes com Materiais Perfurocortantes, exigido pela NR-32 e Portarias correlatas, tem como objetivo principal:",
         "Aumentar o número de horas extras trabalhadas pela enfermagem em setores críticos.",
         "Identificar os perfurocortantes em uso, substituir materiais convencionais por dispositivos de segurança, capacitar trabalhadores e monitorar acidentes.",
         "Substituir o uso de seringas hospitalares por colheres de plástico descartáveis.",
         "Transferir a responsabilidade civil de acidentes para os pacientes atendidos.",
         "Eliminar completamente as punções venosas no hospital, abolindo a medicação injetável.",
         "B",
         "O Plano visa à erradicação de acidentes com perfurantes por meio da aquisição de dispositivos seguros, treinamento contínuo e análise epidemiológica dos acidentes.",
         "NR-32 e Diretrizes MTE",
         "média"),
        # 17
        ("Se um trabalhador de limpeza hospitalar for ferido por uma agulha encontrada solta dentro de um saco plástico de lixo comum (Grupo D), a análise do acidente indica:",
         "Descarte irregular gravíssimo de perfurocortante fora do coletor rígido apropriado, gerando risco para a equipe de apoio e hotelaria.",
         "Procedimento rotineiro e padrão aceito pelas normas da ANVISA.",
         "Culpa exclusiva do faxineiro por não ter apalpado o saco antes de pegá-lo.",
         "Que o lixo comum é o local indicado na NR-32 para agulhas de pequeno calibre.",
         "Que a agulha não oferece risco biológico por já estar há mais de 10 minutos no lixo.",
         "A",
         "O descarte de agulha em saco de lixo comum viola as normas sanitárias e a NR-32, constituindo causa clássica de acidentes graves em trabalhadores de limpeza.",
         "NR-32 e RDC 222/2018",
         "fácil"),
        # 18
        ("A respeito da imunoglobulina humana hiperimune contra hepatite B (HBIG), qual é a sua indicação principal em acidentes ocupacionais com material biológico?",
         "Quando o trabalhador acidentado não é vacinado ou é sabidamente não respondedor (Anti-HBs negativo) e a fonte é HBsAg positivo ou de alto risco.",
         "Para todos os trabalhadores que já possuem vacinação completa e Anti-HBs positivo superior a 100 mUI/mL.",
         "Apenas como substituto de antibióticos para tratar infecções por gonorreia.",
         "Como xarope expectorante de rotina para tosse seca em trabalhadores da lavanderia.",
         "Para prevenção exclusiva do contágio pelo vírus da hepatite A transmitido por água.",
         "A",
         "A HBIG fornece imunidade passiva imediata ao acidentado não vacinado ou não respondedor quando exposto a sangue com vírus da hepatite B (HBsAg positivo).",
         "Manual de Condutas em Exposição Ocupacional MS e NR-32",
         "difícil"),
        # 19
        ("Em relação ao vírus da Hepatite C (HCV), caso ocorra acidente perfurocortante com fonte confirmadamente positiva para HCV:",
         "Existe vacina e imunoglobulina comercial de alta eficácia indicada imediatamente nas primeiras 2 horas.",
         "Não há vacina nem imunoglobulina disponível para profilaxia pós-exposição ao HCV; a conduta é o acompanhamento clínico e sorológico (anti-HCV e HCV-RNA) para tratamento precoce se houver viragem.",
         "O acidentado deve tomar antibióticos de amplo espectro por 60 dias.",
         "A ferida deve ser submetida a banho de radiação ultravioleta por 24 horas contínuas.",
         "O trabalhador deve ser aposentado por invalidez imediata no dia seguinte ao acidente.",
         "B",
         "Não existe profilaxia vacinal ou imunoglobulina pós-exposição para Hepatite C. Faz-se monitoramento laboratorial rigoroso para diagnóstico precoce e uso de antivirais diretos (DAA).",
         "Diretrizes Terapêuticas Hepatite C e NR-32",
         "difícil"),
        # 20
        ("Qual é a conduta do Técnico de Segurança do Trabalho (TST) ao realizar a investigação de um acidente com perfurocortante na FHCGV?",
         "Culpar verbalmente a vítima diante de todos os colegas para servir de exemplo punitivo.",
         "Aplicar métodos de análise causal (como Árvore de Causas), identificando fatores organizacionais, do dispositivo de segurança, jornada de trabalho e condições ambientais para propor medidas preventivas.",
         "Ocultar o registro do acidente para que o hospital não perca pontuação em auditorias.",
         "Arquivar o caso sem ouvir o acidentado nem inspecionar o posto de trabalho.",
         "Determinar a perda do adicional de insalubridade do trabalhador acidentado.",
         "B",
         "A investigação de acidentes visa identificar causas raízes no sistema de trabalho e fatores materiais para aprimorar as barreiras de prevenção, sem foco punitivo.",
         "NR-01, NR-32 e Metodologia de Investigação de Acidentes",
         "média"),
        # 21
        ("Durante a administração de medicamentos por via intramuscular na FHCGV, a NR-32 veda terminantemente que o profissional de saúde:",
         "Desconecte a agulha da seringa utilizando as próprias mãos sem dispositivo mecânico seguro.",
         "Utilize luvas descartáveis de procedimento durante a aplicação da injeção.",
         "Higienize a pele do paciente com algodão embebido em álcool a 70%.",
         "Verifique a prescrição médica e o nome do paciente antes da aplicação.",
         "Descarte o conjunto seringa/agulha imediatamente no coletor rígido de perfurocortantes.",
         "A",
         "O item 32.2.4.15 proíbe expressamente a desconexão manual de agulhas com as mãos.",
         "NR-32, item 32.2.4.15",
         "fácil"),
        # 22
        ("Os recipientes para descarte de materiais perfurocortantes (Grupo E) devem apresentar as seguintes características construtivas, EXCETO:",
         "Paredes rígidas, resistentes à punctura, ruptura e vazamento.",
         "Fechamento seguro com tampa estanque e alça de transporte que evite contato manual com o bocal.",
         "Símbolo internacional de risco biológico e inscrição de 'Material Perfurocortante'.",
         "Fabricação em sacos plásticos finos e flexíveis transparentes para visualização do conteúdo.",
         "Linha demarcatória indicando o volume máximo permitido para preenchimento seguro.",
         "D",
         "Coletores de perfurocortantes NUNCA são sacos plásticos flexíveis; devem ser caixas rígidas com revestimento interno e saco plástico estanque.",
         "RDC 222/2018 e NR-32",
         "fácil"),
        # 23
        ("Em relação aos acidentes de trabalho com agulhas contaminadas, qual é a doença infecciosa transmitida por via sanguínea com MAIOR risco estimado de transmissão após picada acidental de agulha com lúmen (agulha oca) em paciente-fonte positivo?",
         "Hepatite B (HBV) em indivíduo não vacinado (risco de 6% a 30%).",
         "Vírus da imunodeficiência humana - HIV (risco médio de 0,3%).",
         "Hepatite C - HCV (risco de 1,8%).",
         "Vírus do sarampo.",
         "Bactéria causadora da cólera.",
         "A",
         "O vírus da Hepatite B possui a mais alta infectividade sanguínea (cerca de 6% a 30%), muito superior ao HCV (1,8%) e ao HIV (0,3%). Por isso a vacinação é tão crucial.",
         "CDC, Ministério da Saúde e NR-32",
         "difícil"),
        # 24
        ("A retirada de agulhas e bisturis da mesa de instrumentação cirúrgica durante ou após a cirurgia deve ser feita:",
         "Utilizando pinças ou porta-agulhas adequados e caixas descartadoras na própria sala, evitando a passagem de lâminas mão-a-mão sem campo intermediário.",
         "Jogando as lâminas soltas na bandeja de metal para que a instrumentadora recolha com a ponta dos dedos.",
         "Passando a agulha destampada diretamente de ponta para os dedos do médico assistente.",
         "Deixando as lâminas sob os lençóis da maca cirúrgica para a equipe de limpeza achar depois.",
         "Guardando as lâminas usadas dentro da touca cirúrgica do anestesista.",
         "A",
         "A técnica de zona neutra ou campo intermediário sem passagem manual direta e o uso de instrumentos para desconexão previnem cortes em cirurgias.",
         "Normas de Biossegurança em Centro Cirúrgico e NR-32",
         "média"),
        # 25
        ("Ao trocar uma caixa coletora de perfurocortantes que atingiu a linha limite na FHCGV, o funcionário percebe que uma agulha ficou com a haste presa para fora da tampa. Ele deve:",
         "Empurrar a agulha com o polegar desprotegido até entrar totalmente.",
         "Utilizar uma pinça mecânica longa para empurrar o objeto para o interior da caixa, mantendo as mãos distantes do bocal antes de lacrar.",
         "Bater na caixa com um pedaço de pau até quebrar a agulha e a caixa.",
         "Abrir a tampa totalmente e retirar metade das agulhas da caixa com as mãos enluvadas.",
         "Deixar a caixa aberta com a agulha apontada para cima na beira da bancada.",
         "B",
         "Se houver material protuso, deve-se usar pinça auxiliar mecânica longa com cautela, nunca usando os dedos para empurrar perfurocortantes.",
         "Manual de Biossegurança e NR-32",
         "média"),
        # 26
        ("Se a empresa terceirizada contratada para serviços de limpeza na FHCGV não emitir a CAT de um faxineiro que sofreu picada de agulha contaminada no hospital:",
         "Nenhum outro ente pode emitir a CAT, ficando o acidente sem registro legal.",
         "A própria FHCGV (tomadora), o próprio trabalhador, o sindicato de sua categoria ou qualquer autoridade pública (médico, auditor) podem formalizar a emissão da CAT.",
         "A emissão da CAT é extinta automaticamente por decurso de prazo de 24 horas.",
         "O trabalhador deve pagar uma taxa de 5 salários mínimos para conseguir registrar o acidente.",
         "O acidente perde o caráter ocupacional e passa a ser considerado doença genética.",
         "B",
         "Conforme o Art. 22, § 2º da Lei 8.213/91, na falta de emissão pela empresa, a CAT pode ser formalizada pelo próprio acidentado, sindicato, médico assistente ou autoridade pública.",
         "Lei 8.213/91, Art. 22, § 2º e NR-32",
         "média"),
        # 27
        ("Sobre o uso de lancetas para punção digital (glicemia capilar) em pacientes hospitalizados na FHCGV:",
         "Devem ser utilizadas lancetas retráteis com dispositivo de segurança passivo de uso único que trave a ponta cortante automaticamente após o disparo.",
         "Podem ser utilizadas agulhas de sutura reaproveitáveis lavadas na pia do quarto.",
         "A mesma lanceta pode ser utilizada em todos os pacientes do mesmo quarto de enfermaria.",
         "As lancetas usadas devem ser jogadas diretamente no ralo do chuveiro do paciente.",
         "O profissional deve quebrar a ponta da lanceta com os dentes para inutilizá-la.",
         "A",
         "Lancetas para teste de glicemia devem possuir lâmina retrátil com travamento automático definitivo e descarte único em conformidade com a NR-32.",
         "Portaria MTE 939/2006 e NR-32",
         "fácil"),
        # 28
        ("A notificação de acidente de trabalho com material biológico deve ser comunicada ao SESMT e à CIPA do hospital para:",
         "Publicação do nome e foto do trabalhador no mural de avisos da recepção central.",
         "Alimentação do banco de dados de acidentes, planejamento de ações corretivas, avaliação dos dispositivos de segurança e revisão dos treinamentos operacionais.",
         "Aplicação de advertência disciplinar com suspensão de 30 dias sem vencimentos.",
         "Cancelamento imediato de todos os adicionais de insalubridade do setor.",
         "Abertura de inquérito criminal contra o técnico de enfermagem por danos ao hospital.",
         "B",
         "O fluxo interno para SESMT e CIPA tem caráter preventivo, estatístico e de melhoria contínua dos processos de trabalho e insumos seguros.",
         "NR-05 e NR-32",
         "fácil"),
        # 29
        ("A NR-32 estabelece que em caso de ocorrência de acidente com material biológico, o atendimento médico imediato e as medidas profiláticas devem ser prestados:",
         "Exclusivamente após a homologação de parecer jurídico em processo judicial de 6 meses.",
         "De forma imediata e ininterrupta, garantindo atendimento médico 24 horas e acesso aos medicamentos profiláticos e exames laboratoriais.",
         "Apenas nas segundas-feiras em horário comercial das 9h às 11h da manhã.",
         "Mediante pagamento prévio em dinheiro pelo acidentado diretamente ao médico plantonista.",
         "Somente após a alta hospitalar do paciente-fonte que causou o acidente.",
         "B",
         "A instituição de saúde deve garantir fluxo imediato e 24 horas para atendimento médico pós-exposição a material biológico, testagem e acesso a antirretrovirais/vacinas.",
         "NR-32, item 32.2.3.5",
         "fácil"),
        # 30
        ("Qual é o papel do Técnico em Segurança do Trabalho (TST) no monitoramento dos coletores de perfurocortantes nas diversas unidades da FHCGV?",
         "Substituir pessoalmente todas as caixas de perfurocortantes do hospital duas vezes ao dia.",
         "Inspecionar periodicamente os setores, verificando a integridade dos suportes, correta altura, ausência de caixas no chão, respeito ao limite de enchimento e treinamento das equipes.",
         "Proibir a compra de caixas de perfurocortantes para reduzir despesas de custeio.",
         "Determinar que os coletores cheios sejam queimados em fogueira no jardim do hospital.",
         "Autorizar o reaproveitamento das caixas de papelão após esvaziamento manual.",
         "B",
         "Cabe ao TST auditar as condições de segurança nos postos, orientar quanto ao nível de enchimento e altura ergonômica e assegurar o cumprimento da NR-32.",
         "Atribuições do TST e NR-32",
         "média"),
        # 31
        ("Em relação à utilização de agulhas e seringas com dispositivo de segurança em serviços de radiologia intervencionista e hemodinâmica da FHCGV:",
         "A exigência de dispositivos de segurança da NR-32 não se aplica a setores de diagnóstico.",
         "Todos os perfurocortantes utilizados em procedimentos hemodinâmicos e radiológicos invasivos devem conter dispositivos de segurança contra acidentes.",
         "O uso de dispositivos de segurança é facultativo caso os médicos usem óculos escuros.",
         "As agulhas radiológicas devem ser reencapadas com fita isolante após o exame.",
         "Os perfurocortantes de hemodinâmica devem ser descartados no lixo comum de escritório.",
         "B",
         "A obrigatoriedade de dispositivos de segurança abrange todos os serviços e setores onde se manipulam perfurocortantes, incluindo hemodinâmica e radiologia intervencionista.",
         "NR-32 e Portaria 939/2006",
         "fácil"),
        # 32
        ("Qual dos fatores organizacionais abaixo costuma ser causa primária frequente de acidentes com perfurocortantes na rotina de enfermagem hospitalar?",
         "Iluminação excessiva e ambiente excessivamente silencioso.",
         "Sobrecarga de trabalho, ritmo acelerado, número insuficiente de profissionais e descarte em coletores superlotados distantes do leito.",
         "Uso de cadeiras estofadas confortáveis no posto de enfermagem.",
         "Disponibilização de sabonete líquido aromatizado nos lavatórios.",
         "Presença constante de bebedouros de água mineral nos corredores.",
         "B",
         "Fatores como pressa, fadiga, dimensionamento inadequado de pessoal e coletores cheios ou distantes multiplicam o risco de acidentes perfurocortantes.",
         "Estudos de Ergonomia e Acidentalidade em Saúde e NR-32",
         "média"),
        # 33
        ("Em caso de acidente com agulha onde o paciente-fonte é desconhecido (ex: agulha encontrada perfurando um hamper de roupa suja na lavanderia):",
         "A profilaxia pós-exposição ao HIV e Hepatite B deve ser avaliada pelo médico assistente considerando a gravidade do acidente, o perfil epidemiológico do local e a condição vacinal do trabalhador.",
         "O acidente deve ser ignorado sumariamente, pois sem paciente identificado não se adota nenhuma medida.",
         "O acidentado deve ser submetido a cirurgia imediata de amputação da mão ferida.",
         "Deve-se obrigar todos os pacientes internados no hospital a fazerem teste de DNA.",
         "O trabalhador deve tomar dose única de vacina contra raiva humana.",
         "A",
         "Em acidentes com fonte desconhecida, a decisão médica sobre PEP considera a prevalência local, o tipo de exposição e o estado vacinal do trabalhador.",
         "Manual de Condutas em Exposição Ocupacional MS",
         "média"),
        # 34
        ("Durante a infusão de medicação endovenosa através de cateter venoso periférico tipo 'scalp' ou agulhado, a NR-32 exige:",
         "A utilização exclusiva de cateteres com mecanismo retrátil ou capa protetora de travamento automático de segurança que cubra a agulha ao ser retirada.",
         "Que a agulha fique exposta na mesa de cabeceira do paciente durante todo o período de internação.",
         "O reencape da agulha usando a boca do profissional para segurar a tampa plástica.",
         "A lavagem do cateter em álcool comum para reutilização no mesmo paciente após 7 dias.",
         "O descarte do scalp no ralo da pia do quarto de enfermaria.",
         "A",
         "Os dispositivos de infusão com agulha devem possuir mecanismos de segurança que protejam o bisel imediatamente após a retirada da veia.",
         "Portaria MTE 939/2006 e NR-32",
         "fácil"),
        # 35
        ("Se um profissional de enfermagem da FHCGV que sofreu acidente biológico grave recusar expressamente tomar a PEP antirretroviral indicada pelo médico:",
         "Ele deve ser forçado fisicamente pelos seguranças do hospital a engolir a medicação.",
         "Ele tem o direito de recusar, devendo ser orientado detalhadamente sobre os riscos e assinar um Termo de Esclarecimento e Recusa formal no prontuário.",
         "Ele deve ser demitido imediatamente com perda de todos os direitos trabalhistas.",
         "Ele deve ser preso em cela de isolamento por 28 dias seguidos.",
         "O médico deve adulterar a água do trabalhador para administrar o remédio escondido.",
         "B",
         "A autonomia do paciente e do trabalhador é garantida pela bioética e pelo ordenamento jurídico; a recusa deve ser esclarecida e registrada formalmente em termo de recusa.",
         "Código de Ética Médica e Diretrizes MS",
         "média"),
        # 36
        ("A realização de testes sorológicos admissionais para HIV de candidatos em concurso público ou seleção de emprego em serviços de saúde da FHCGV é:",
         "Obrigatória pela NR-32 para todos os profissionais de saúde.",
         "Terminantemente proibida pela legislação brasileira e normas do MTE/OIT, sendo considerada prática discriminatória ilegal.",
         "Facultativa se o candidato tiver mais de 40 anos de idade.",
         "Exigida apenas para técnicos que forem atuar na UTI Neonatal.",
         "Permitida desde que a diretoria do hospital assine o pedido de exame.",
         "B",
         "A testagem discriminatória para HIV em processos admissionais é ilegal e expressamente proibida pela Portaria MTE 1.246/2010 e Lei 12.984/2014.",
         "Portaria MTE 1.246/2010 e Lei 12.984/2014",
         "fácil"),
        # 37
        ("Qual a recomendação pós-exposição quando o trabalhador acidentado possui comprovação documental de vacinação completa contra hepatite B e exame laboratorial com Anti-HBs maior que 10 mUI/mL?",
         "Ele deve reiniciar o esquema de 3 doses de vacina e tomar imunoglobulina de emergência.",
         "Ele é considerado imunizado e protegido contra o vírus da Hepatite B, não necessitando de nenhuma profilaxia adicional específica contra o HBV.",
         "Ele deve tomar antibióticos profiláticos por 14 dias contra hepatite B.",
         "Ele deve ficar em quarentena respiratória em sua residência por 30 dias.",
         "Ele deve realizar transplante de fígado preventivo no mês seguinte.",
         "B",
         "Trabalhador com Anti-HBs >= 10 mUI/mL comprovado é considerado respondedor e imune à infecção pelo vírus da hepatite B, dispensando vacina ou HBIG.",
         "Protocolos de Imunização Ocupacional MS e NR-32",
         "fácil"),
        # 38
        ("A proibição de entortar ou quebrar agulhas manualmente antes do descarte baseia-se no fato comprovado de que:",
         "O aço inoxidável da agulha perde o valor comercial para venda como sucata hospitalar.",
         "O ato de quebrar ou entortar a agulha produz estresse mecânico, risco iminente de perfuração das mãos e dispersão de gotículas biológicas.",
         "A agulha entortada ocupa o dobro do espaço dentro do coletor de perfurocortantes.",
         "As agulhas quebradas podem furar os ímãs da máquina de ressonância magnética.",
         "A NR-32 autoriza entortar agulhas desde que se utilize luva de couro de cano longo.",
         "B",
         "Entortar ou quebrar agulhas constitui ação de extremo risco de picada acidental e projeção de sangue contaminado, sendo terminantemente proibida.",
         "NR-32, item 32.2.4.15",
         "fácil"),
        # 39
        ("A comissão multidisciplinar responsável pela implantação e avaliação dos dispositivos de segurança em perfurocortantes no hospital deve ser integrada prioritariamente por:",
         "Apenas o gerente de compras e finanças do hospital sem representantes da assistência.",
         "Representantes do SESMT (engenheiro/técnico de segurança e médico do trabalho), CIPA, CCIH, Enfermagem e setor de suprimentos/farmácia.",
         "Exclusivamente membros eleitos do conselho municipal de saúde externa.",
         "Apenas auditores fiscais da Receita Federal do Brasil.",
         "Somente os pacientes internados nas enfermarias do hospital.",
         "B",
         "A escolha e avaliação dos materiais com dispositivos de segurança exige abordagem multidisciplinar envolvendo quem compra, quem avalia o risco (SESMT/CIPA) e quem usa (enfermagem/médicos).",
         "NR-32 e Portaria 939/2006",
         "média"),
        # 40
        ("Em relação à caixa coletora de perfurocortantes após o fechamento definitivo, o transporte interno até o abrigo temporário de resíduos da FHCGV deve ser realizado:",
         "Carregando a caixa encostada diretamente contra o peito ou abdome do funcionário.",
         "Segurando a caixa pelas alças externas de transporte, mantendo-a afastada do corpo, em carro de transporte fechado e exclusivo de resíduos.",
         "Jogando a caixa pelos dutos de ar comprimido ou escadarias de emergência.",
         "Arrastando a caixa pelo chão com uma corda amarrada no bocal de plástico.",
         "Equilibrando a caixa sobre a cabeça do assistente de limpeza sem proteção.",
         "B",
         "O transporte de recipientes rígidos deve ser feito pelas alças apropriadas, sem contato com o corpo do profissional, em carrinhos estanques com tampa fechada.",
         "NR-32 e RDC 222/2018",
         "fácil")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-32",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr32_perfuro_questions()
    print(f"Perfuro questions generated: {len(q)}")
