# -*- coding: utf-8 -*-
"""
Gerador de Questões de Resíduos de Serviços de Saúde (40 questões)
- Grupos de Resíduos (A, B, C, D, E): 30 questões
- PGRSS: 10 questões
Normas de referência: RDC ANVISA nº 222/2018 e Resolução CONAMA nº 358/2005
"""

def get_residuos_questions():
    items = [
        # =========================================================
        # 1. GRUPOS DE RESÍDUOS (A, B, C, D, E) (30 questões)
        # =========================================================
        # 1
        ("A RDC ANVISA nº 222/2018 e a Resolução CONAMA nº 358/2005 classificam os Resíduos de Serviços de Saúde (RSS) em quantos grandes grupos?",
         "Cinco grupos: Grupo A (biológicos), Grupo B (químicos), Grupo C (rejeitos radioativos), Grupo D (resíduos comuns/recicláveis) e Grupo E (perfurocortantes).",
         "Apenas dois grupos: resíduos caros e resíduos baratos.",
         "Dez grupos divididos pelas cores da bandeira do Brasil.",
         "Três grupos: sólidos, líquidos e invisíveis.",
         "Vinte grupos conforme a idade do paciente atendido.",
         "A",
         "A classificação oficial dos RSS no Brasil divide-se nos 5 grupos clássicos: Grupo A (biológico), B (químico), C (radioativo), D (comum) e E (perfurocortante).",
         "RDC 222/2018 e CONAMA 358/2005",
         "fácil"),
        # 2
        ("Os resíduos que contêm agentes biológicos que, por suas características de maior virulência ou concentração, podem apresentar risco de infecção humana ou animal pertencem ao:",
         "Grupo A (Resíduos com a possível presença de agentes biológicos).",
         "Grupo D (Resíduos comuns de escritório).",
         "Grupo B (Resíduos químicos e farmacêuticos).",
         "Grupo C (Rejeitos radioativos com emissores gama).",
         "Grupo E (Resíduos de jardinagem e poda de grama).",
         "A",
         "O Grupo A engloba os resíduos com risco biológico potencial ou confirmado, divididos nos subgrupos A1, A2, A3, A4 e A5.",
         "RDC 222/2018, Art. 4º",
         "fácil"),
        # 3
        ("Culturas microbiológicas puras de laboratório, estoques de microrganismos patogênicos e meios de cultura inoculados são classificados no subgrupo:",
         "A1 (exigem obrigatoriamente tratamento prévio antes da destinação final externa).",
         "D (podem ser jogados diretamente na lixeira comum da praça).",
         "B (considerados medicamentos anti-inflamatórios vencidos).",
         "C (fontes seladas de césio-137).",
         "A3 (peças anatômicas de membros amputados).",
         "A",
         "O subgrupo A1 inclui culturas e estoques de microrganismos de alta patogenicidade que devem ser submetidos a processo de inativação microbiana (ex: autoclave) na própria unidade geradora.",
         "RDC 222/2018, Anexo I",
         "média"),
        # 4
        ("Membros amputados humanos, placentas, órgãos e fragmentos de tecidos humanos retirados em procedimentos cirúrgicos pertencem ao subgrupo:",
         "A3 (Peças anatômicas de seres humanos).",
         "Grupo B (Resíduos com características corrosivas).",
         "Grupo D (Lixo comum de cozinha).",
         "Subgrupo A5 (Resíduos com suspeita de príons).",
         "Grupo E (Materiais perfurantes descartáveis).",
         "A",
         "O subgrupo A3 abrange órgãos, tecidos humanos e peças anatômicas cirúrgicas, com destinação própria (sepultamento em cemitério, cremação ou incineração).",
         "RDC 222/2018, Anexo I",
         "fácil"),
        # 5
        ("Algodão, gazes, curativos saturados com sangue, compressas, fraldas de pacientes acamados e kits de linhas de infusão sem agulhas enquadram-se no subgrupo:",
         "A4.",
         "A1.",
         "A3.",
         "Grupo B.",
         "Grupo C.",
         "A",
         "O subgrupo A4 engloba resíduos biológicos rotineiros da assistência direta ao paciente (curativos com sangue, drenos, sondas, bolsas transfusionais vazias).",
         "RDC 222/2018, Anexo I",
         "fácil"),
        # 6
        ("Materiais e tecidos provenientes de pacientes suspeitos ou confirmados de encefalopatias espongiformes transmissíveis (doença de Creutzfeldt-Jakob causada por PRÍONS) são classificados como:",
         "Subgrupo A5 (exigem incineração em usina licenciada ou tratamento térmico específico).",
         "Subgrupo A2 (animais de experimentação sadios).",
         "Grupo D (resíduo reciclável de plástico comum).",
         "Grupo E (frascos de vidro vazios de xarope).",
         "Grupo B (saneantes alcalinos concentrados).",
         "A",
         "Os príons possuem extrema resistência a desinfetantes e autoclaves comuns; seus resíduos compõem o subgrupo A5 e devem ser submetidos à incineração.",
         "RDC 222/2018, Anexo I",
         "média"),
        # 7
        ("Os sacos plásticos utilizados para o acondicionamento dos resíduos infectantes do Grupo A devem ser confeccionados em material:",
         "Plástico branco leitoso, impermeável, resistente a ruptura e perfuração, contendo impresso o símbolo internacional de risco biológico e a inscrição 'RESÍDUO INFECTANTE'.",
         "Papel pardo biodegradável com furos decorativos no fundo.",
         "Plástico transparente fino de supermercado com nó frouxo.",
         "Tecido de linho ou juta costurado manualmente.",
         "Plástico preto comum sem qualquer símbolo visual de advertência.",
         "A",
         "A RDC 222/2018 exige saco plástico branco leitoso, com espessura e solda contínua adequadas (norma ABNT NBR 9191) e símbolo padronizado de risco biológico.",
         "RDC 222/2018 e ABNT NBR 9191",
         "fácil"),
        # 8
        ("Qual é o limite máximo seguro de preenchimento dos sacos plásticos de resíduos dos Grupos A e D estipulado pela RDC ANVISA nº 222/2018 para permitir o fechamento sem compressão manual?",
         "Até 2/3 (dois terços) ou 70% de sua capacidade volumétrica.",
         "Até transbordar pelas bordas superiores com o trabalhador pisando em cima.",
         "Exatamente 100% da capacidade com o saco estufado e amarrado com fita adesiva.",
         "Apenas 5% do volume total do saco.",
         "Não há qualquer limite, o saco pode ser enchido até rasgar.",
         "A",
         "Os sacos de resíduos só devem ser preenchidos até 2/3 ou no máximo 70% de sua capacidade para permitir fechamento seguro (lacre duplo) sem risco de vazamento ou rompimento.",
         "RDC 222/2018, Art. 15",
         "fácil"),
        # 9
        ("Os resíduos do GRUPO B compreendem produtos químicos que apresentem periculosidade à saúde ou ao meio ambiente. São exemplos clássicos de resíduos do Grupo B na FHCGV:",
         "Medicamentos vencidos, sobras de quimioterápicos citostáticos, reagentes de laboratório, desinfetantes concentrados e termômetros contendo mercúrio líquido.",
         "Folhas secas varridas do jardim do hospital e aparas de grama.",
         "Membros amputados humanos e tecidos de biópsia cirúrgica.",
         "Agulhas descartáveis com sangue e bisturis usados em cirurgias.",
         "Papéis toalha secos utilizados na secagem de mãos em escritórios.",
         "A",
         "O Grupo B reúne os resíduos químicos perigosos: fármacos, citostáticos, reveladores radiográficos, reagentes laboratoriais e metais pesados (mercúrio).",
         "RDC 222/2018, Art. 4º",
         "fácil"),
        # 10
        ("O mercúrio metálico presente em termômetros clínicos e esfigmomanômetros antigos de pressão é classificado no Grupo B e apresenta gravidade ambiental porque:",
         "É um metal pesado altamente tóxico, cumulativo nos tecidos biológicos e neurotóxico persistente no meio ambiente.",
         "É uma substância radioativa com meia-vida de 1 milhão de anos.",
         "É um gás incolor que faz o ser humano perder peso rapidamente.",
         "É um nutriente essencial que purifica rios e igarapés.",
         "Transforma-se espontaneamente em ouro puro quando exposto ao sol.",
         "A",
         "O mercúrio é um poluente tóxico persistente e bioacumulativo; a Convenção de Minamata e a ANVISA determinaram a sua eliminação e substituição por aparelhos digitais.",
         "RDC 222/2018 e Convenção de Minamata",
         "média"),
        # 11
        ("Os efluentes químicos gerados no processamento e revelação de filmes radiográficos analógicos (líquidos fixadores e reveladores) pertencem ao:",
         "Grupo B (resíduos químicos) e devem ser coletados e tratados para neutralização ou recuperação da prata, sendo proibido o descarte direto na rede de esgoto.",
         "Grupo D (podem ser jogados na pia do banheiro sem nenhum tratamento).",
         "Grupo A (considerados bactérias hospitalares atenuadas).",
         "Grupo E (considerados objetos perfurocortantes afiados).",
         "Grupo C (rejeitos atômicos enriquecidos).",
         "A",
         "Fixadores contêm prata e reveladores possuem hidroquinona e álcalis tóxicos (Grupo B); é proibido lançá-los na rede de esgoto sem tratamento prévio.",
         "RDC 222/2018 e CONAMA 358/2005",
         "média"),
        # 12
        ("O GRUPO C na classificação da RDC ANVISA nº 222/2018 é reservado exclusivamente para os:",
         "Rejeitos radioativos (materiais contendo radionuclídeos em quantidade ou atividade superior aos limites de isenção estabelecidos pela CNEN).",
         "Resíduos de alimentação coletiva do refeitório de funcionários.",
         "Medicamentos comuns como dipirona e paracetamol vencidos.",
         "Frascos de vidro quebrados de refrigerante comum.",
         "Seringas descartáveis de plástico sem agulha.",
         "A",
         "O Grupo C abrange todos os rejeitos radioativos gerados em serviços de medicina nuclear, radioterapia e laboratórios de pesquisa, regulados pela CNEN e ANVISA.",
         "RDC 222/2018, Art. 4º e Normas CNEN",
         "fácil"),
        # 13
        ("Os rejeitos radioativos do Grupo C devem ser armazenados em área de decaimento específica até que:",
         "A sua atividade radioativa atinja os níveis de liberação/dispensa regulamentados pela Comissão Nacional de Energia Nuclear (CNEN), podendo então ser desclassificados.",
         "O prédio do hospital complete 100 anos de inauguração.",
         "Todos os pacientes do hospital recebam alta médica.",
         "O técnico de radiologia assine uma declaração no livro de atas do sindicato.",
         "A chuva lave os recipientes no estacionamento descoberto.",
         "A",
         "O manejo de rejeitos radioativos no hospital prevê o armazenamento em abrigo de decaimento; decaída a atividade até o limite seguro da CNEN, são descartados conforme o grupo de risco residual.",
         "Normas CNEN e RDC 222/2018",
         "média"),
        # 14
        ("O GRUPO D é constituído por resíduos que não apresentem risco biológico, químico ou radiológico à saúde ou ao meio ambiente, podendo ser equiparados aos resíduos:",
         "Domiciliares ou comuns (papéis de escritório, restos de poda de jardins, sobras de alimentos de refeitórios sadios, copos plásticos descartáveis).",
         "Hospitalares de alto contágio e virulência extrema.",
         "Citotóxicos e mutagênicos de pacientes em quimioterapia.",
         "Perfurantes infectados por sangue contaminado por HIV.",
         "Radioativos com emissores de partículas alfa.",
         "A",
         "O Grupo D compreende os resíduos comuns da hotelaria, administração e alimentação sem contato com fluidos infecciosos, passíveis de reciclagem ou aterro sanitário comum.",
         "RDC 222/2018, Art. 4º",
         "fácil"),
        # 15
        ("Para estimular a reciclagem no Grupo D, a segregação dos resíduos recicláveis secos (papel, plástico, vidro, metal) deve seguir o padrão de cores da Resolução CONAMA nº 275/2001, sendo:",
         "Azul para papel, Vermelho para plástico, Verde para vidro e Amarelo para metal.",
         "Preto para plástico, Branco para vidro, Rosa para papel e Roxo para metal.",
         "Marrom para metal, Dourado para papel, Prata para plástico e Azul para vidro.",
         "Todas as lixeiras devem ser pintadas de cinza escuro sem distinção.",
         "Laranja para papel, Bege para plástico, Azul-marinho para vidro e Verde para metal.",
         "A",
         "O código de cores internacional e CONAMA 275 é universal: Azul = Papel/Papelão; Vermelho = Plástico; Verde = Vidro; Amarelo = Metal; Marrom = Orgânico.",
         "Resolução CONAMA nº 275/2001",
         "fácil"),
        # 16
        ("O GRUPO E engloba os resíduos perfurocortantes ou escarificantes gerados na assistência hospitalar, tais como:",
         "Agulhas hipodérmicas, lâminas de bisturi, ampolas de vidro quebradas, lancetas, fios-guia metálicos e tubos capilares laboratoriais.",
         "Toalhas de banho e lençóis de algodão da lavanderia hospitalar.",
         "Comprimidos de vitamina C e cápsulas de antibiótico íntegras.",
         "Caixas de papelão vazias e copos descartáveis de café.",
         "Restos de cascas de banana e maçã do lanche dos médicos.",
         "A",
         "O Grupo E compreende todo material capaz de perfurar ou cortar tecidos humanos: agulhas, bisturis, ampolas de vidro, micropipetas e lâminas de microscopia.",
         "RDC 222/2018, Art. 4º",
         "fácil"),
        # 17
        ("Os resíduos do Grupo E (perfurocortantes) devem ser descartados obrigatoriamente em recipientes coletores que possuam as seguintes características técnicas:",
         "Rígidos, resistentes a punctura, perfuração, ruptura e vazamento, com tampa e bocal seguro, dotados de símbolo de risco biológico e linha indicadora de limite máximo de preenchimento.",
         "Sacos plásticos transparentes pendurados em maçanetas de portas de madeira.",
         "Caixas de papelão comuns de supermercado com o topo aberto.",
         "Baldes de lata enferrujados sem tampa no chão do banheiro.",
         "Vidros de conserva de azeitona com tampa de rosca metálica.",
         "A",
         "A caixa amarela de perfurocortante (tipo Descarpack) deve atender à NBR 13853: parede rígida anti-punctura, bocal de retenção, tampa e limite visual de capacidade.",
         "RDC 222/2018 e ABNT NBR 13853",
         "fácil"),
        # 18
        ("A linha indicadora de nível máximo de preenchimento no coletor rígido de perfurocortantes (Grupo E) localiza-se a:",
         "Aproximadamente 5 cm abaixo do bocal (correspondendo a cerca de 2/3 a 3/4 do volume útil da caixa).",
         "Exatamente 1 metro acima da borda superior da caixa.",
         "No fundo da caixa, no nível de 1% do volume total.",
         "Não existe nenhuma linha, deve-se encher até cair no chão.",
         "Na tampa externa após o fechamento e lacre total.",
         "A",
         "O limite de segurança (linha tracejada a 5 cm do bocal ou 2/3-3/4 da caixa) impede que agulhas fiquem salientes no bocal, prevenindo acidentes com as mãos ao descartar.",
         "RDC 222/2018 e NBR 13853",
         "fácil"),
        # 19
        ("Ao atingir o limite de enchimento da caixa coletora de perfurocortantes (Grupo E), qual a conduta CORRETA a ser executada?",
         "Fechar e travar a tampa definitivamente pelo mecanismo de lacre próprio da caixa, segurando-a pelas alças externas de transporte, e encaminhá-la ao armazenamento temporário.",
         "Empurrar o conteúdo com a palma da mão ou com os pés para caber mais agulhas.",
         "Esvaziar o conteúdo em um saco plástico no chão para reaproveitar a caixa de papelão.",
         "Pressionar os materiais com uma régua de plástico até quebrarem as ampolas.",
         "Deixar a caixa aberta no corredor para que as agulhas evaporem com o calor.",
         "A",
         "Ao atingir o nível máximo, a caixa é lacrada permanentemente e transportada pelas alças, sendo expressamente proibido compactar materiais ou esvaziar/reutilizar o coletor.",
         "RDC 222/2018, Art. 19 e NR-32",
         "fácil"),
        # 20
        ("É TERMINANTEMENTE PROIBIDO aos profissionais de saúde e trabalhadores da limpeza em relação às caixas de perfurocortantes (Grupo E):",
         "Superlotar o coletor, empurrar materiais com os dedos ou descarregar o conteúdo em sacos plásticos para reaproveitamento do recipiente.",
         "Utilizar o coletor com o suporte metálico fixado na parede.",
         "Verificar se a linha de preenchimento máximo foi atingida antes de usar.",
         "Descartar agulhas acopladas à seringa imediatamente após a punção venosa.",
         "Identificar a data de fechamento e o setor na etiqueta frontal do recipiente.",
         "A",
         "Superlotação e transbordo de agulhas e compactação manual são as maiores causas de perfurações acidentais graves em equipes assistenciais e de limpeza hospitalar.",
         "NR-32 e RDC 222/2018",
         "fácil"),
        # 21
        ("O descarte de uma seringa COM AGULHA utilizada na aplicação de medicação intramuscular no paciente deve ser feito:",
         "Imediatamente no coletor rígido de perfurocortantes (Grupo E), em conjunto (seringa e agulha conectadas), SEM desconectar e SEM reencapar a agulha.",
         "Desconectando a agulha com a boca e jogando a seringa no lixo comum.",
         "Reencapando a agulha com as duas mãos e guardando no bolso do jaleco.",
         "Entortando a agulha na borda da cama antes de jogar no saco plástico branco.",
         "Lavando a agulha na torneira da pia para reaproveitamento no próximo plantão.",
         "A",
         "A NR-32 e a RDC 222 proíbem terminantemente o reencape ou desconexão manual de agulhas; o conjunto seringa-agulha vai inteiro para a caixa de perfurocortante.",
         "NR-32, item 32.2.4.15 e RDC 222/2018",
         "fácil"),
        # 22
        ("Frascos e ampolas de vidro de medicamentos (como dipirona ou antibióticos injetáveis) vazios ou quebrados devem ser descartados no:",
         "Grupo E (recipiente rígido coletor de perfurocortantes), para evitar cortes e perfurações nas equipes de higienização que manipulam os sacos plásticos.",
         "Grupo D comum dentro de saco plástico fino transparente.",
         "Grupo A em saco branco leitoso rasgável.",
         "Vaso sanitário da enfermaria com descarga contínua de água.",
         "Jardim externo do hospital para serem triturados pelas chuvas.",
         "A",
         "Vidros e ampolas, mesmo vazios, têm potencial perfurocortante caso quebrem ou lasquem, devendo ser descartados em caixas rígidas do Grupo E.",
         "RDC 222/2018 e Manual de Gerenciamento de Resíduos ANVISA",
         "fácil"),
        # 23
        ("Frascos de vidro quebrados que continham medicamentos quimioterápicos citostáticos apresentam risco duplo e devem ser enquadrados prioritariamente com base no risco:",
         "Químico do Grupo B com acondicionamento em recipiente rígido resistente a puncturas do Grupo E, devidamente rotulado com o perigo citotóxico/antineoplásico.",
         "Biológico comum do Grupo A4.",
         "Comum reciclável do Grupo D de vidros.",
         "Rejeito nuclear atômico do Grupo C.",
         "Isento de qualquer risco de toxicidade.",
         "A",
         "Perfurocortantes contaminados com agentes químicos perigosos (ex: citostáticos) exigem acondicionamento rígido (Grupo E) e tratamento/destinação de resíduo químico perigoso (Grupo B).",
         "RDC 222/2018, Art. 47",
         "média"),
        # 24
        ("Os papéis toalha utilizados unicamente para secagem de mãos limpas nas pias dos consultórios médicos e banheiros de funcionários devem ser descartados no:",
         "Grupo D (Resíduo comum não reciclável).",
         "Grupo A1 (Resíduo com agentes biológicos de classe 4).",
         "Grupo E (Coletor de agulhas perfurocortantes).",
         "Grupo B (Resíduos químicos inflamáveis).",
         "Grupo C (Rejeitos radioativos enriquecidos).",
         "A",
         "Papel toalha de secagem de mãos em sanitários e pias de higienização rotineira classifica-se no Grupo D (resíduo comum), não sendo resíduo infectante infectocontagiante.",
         "RDC 222/2018, Anexo I",
         "fácil"),
        # 25
        ("Em relação aos restos alimentares de pacientes internados em quartos de ISOLAMENTO por doenças infectocontagiosas de transmissão aérea ou por contato:",
         "Devem ser classificados no Grupo A e acondicionados em sacos plásticos brancos leitosos com símbolo de risco biológico para tratamento ou destinação adequada.",
         "Devem ser reaproveitados para preparar a sopa dos funcionários do hospital.",
         "Podem ser doados para alimentação de suínos em granjas vizinhas.",
         "Devem ser jogados no vaso sanitário com detergente comum.",
         "São considerados resíduos recicláveis secos do Grupo D.",
         "A",
         "Restos de refeições servidas a pacientes em isolamento por doenças infectocontagiosas são contaminados biologicamente, sendo classificados no Grupo A (RDC 222/2018).",
         "RDC 222/2018, Art. 38",
         "média"),
        # 26
        ("Qual é o símbolo padronizado internacionalmente que deve constar no rótulo de sacos e caixas de resíduos infectantes do Grupo A?",
         "O símbolo internacional de risco biológico (três semicírculos entrelaçados em torno de um círculo central).",
         "Uma caveira com ossos cruzados em fundo vermelho brilhante.",
         "A chama de fogo com fundo amarelo de produtos inflamáveis.",
         "O trifólio com três hélices de radiação ionizante.",
         "Uma gota de água pingando sobre uma lâmina de aço enferrujado.",
         "A",
         "O pictograma de risco biológico é padronizado pela norma ABNT NBR 7500, composto pelas três meias-luvas concêntricas entrelaçadas.",
         "ABNT NBR 7500 e RDC 222/2018",
         "fácil"),
        # 27
        ("As bolsas de sangue e hemocomponentes descartadas por validade vencida, alteração de sorologia ou rejeição na triagem hemoterápica são enquadradas no subgrupo:",
         "A1 (exigem tratamento prévio antes da disposição final ambiental).",
         "Grupo D (podem ser esvaziadas no gramado do pátio).",
         "Grupo B (resíduos corrosivos de laboratório).",
         "Grupo C (rejeitos atômicos de urânio).",
         "Subgrupo A2 (animais de experimentação com mormo).",
         "A",
         "Bolsas transfusionais contendo sangue rejeitado por sorologia ou descartadas sem uso são resíduos do subgrupo A1, exigindo desnaturação/inativação prévia.",
         "RDC 222/2018, Anexo I",
         "média"),
        # 28
        ("Os gessos ortopédicos retirados de pacientes sem ferimentos abertos ou drenagem de secreções purulentas são classificados no:",
         "Grupo D (Resíduo comum).",
         "Grupo A1 (Resíduo de alto risco infectante biológico).",
         "Grupo E (Resíduo perfurocortante rígido).",
         "Grupo B (Resíduo químico explosivo).",
         "Grupo C (Rejeito de radioterapia).",
         "A",
         "Gesso ortopédico sem contaminação por sangue ou secreções corporais é resíduo comum do Grupo D; apenas o gesso embebido em sangue/pus passa para o Grupo A4.",
         "RDC 222/2018, Anexo I",
         "fácil"),
        # 29
        ("A segregação dos resíduos de serviços de saúde na FHCGV é considerada a etapa MAIS CRÍTICA e fundamental de todo o processo de gerenciamento porque:",
         "Se for realizada corretamente na fonte e no momento da geração, evita a contaminação cruzada, reduz drasticamente o volume de resíduos perigosos e diminui os custos de incineração.",
         "Permite que o hospital demita todos os funcionários do setor de limpeza.",
         "Garante que os resíduos biológicos sejam vendidos para indústrias de brinquedos.",
         "Elimina a necessidade de utilizar sacos plásticos ou recipientes rígidos.",
         "Faz com que o lixo desapareça magicamente do hospital em segundos.",
         "A",
         "A segregação no local e instante da geração é o alicerce do PGRSS: impede que lixo comum vire lixo infectante e garante segurança jurídica, ocupacional e ambiental.",
         "RDC 222/2018, Art. 10",
         "fácil"),
        # 30
        ("O que ocorre se um trabalhador descartar papéis de escritório comuns (Grupo D) dentro do saco branco leitoso de resíduos infectantes (Grupo A)?",
         "Todo o conteúdo do saco passa a ser considerado resíduo biológico infectante do Grupo A, aumentando desnecessariamente o volume de resíduos de alto custo de incineração e tratamento especial.",
         "O lixo infectante se desinfeta automaticamente pelo contato com o papel comum.",
         "O saco de lixo explode espontaneamente liberando fumaça cinzenta.",
         "O hospital recebe uma bonificação em dinheiro do Ministério do Meio Ambiente.",
         "O Ministério do Trabalho cancela o registro de todos os médicos do hospital.",
         "A",
         "A mistura indevida de resíduos contamina o material inócuo, encarecendo o tratamento e desrespeitando o princípio da segregação na fonte.",
         "RDC 222/2018, Art. 11",
         "fácil"),

        # =========================================================
        # 2. PLANO DE GERENCIAMENTO DE RESÍDUOS - PGRSS (10 questões)
        # =========================================================
        # 31
        ("O Plano de Gerenciamento de Resíduos de Serviços de Saúde (PGRSS), exigido pela RDC ANVISA nº 222/2018 e Resolução CONAMA nº 358/2005, é:",
         "O documento técnico que aponta e descreve as ações relativas ao manejo dos resíduos de serviços de saúde, contemplando os aspectos da geração, segregação, acondicionamento, coleta, armazenamento, transporte, tratamento e disposição final.",
         "O contrato de aluguel dos veículos de passeio da diretoria executiva.",
         "A escala de plantão de finais de semana dos médicos ortopedistas.",
         "O cardápio alimentar fornecido aos acompanhantes de pacientes nos leitos.",
         "O manual de instruções do elevador social do bloco cirúrgico.",
         "A",
         "O PGRSS é o instrumento técnico e administrativo que planeja e disciplina todo o fluxo dos resíduos da geração à disposição final ambientalmente segura.",
         "RDC 222/2018, Art. 5º",
         "fácil"),
        # 32
        ("A elaboração, implantação e monitoramento do PGRSS em estabelecimentos de saúde como a FHCGV deve ser de responsabilidade de:",
         "Profissional de nível superior, legalmente habilitado pelo seu respectivo conselho de classe profissional, com a devida Anotação de Responsabilidade Técnica (ART) ou equivalente.",
         "Qualquer paciente que estiver aguardando consulta na sala de espera.",
         "Motorista de táxi que atenda passageiros na porta de entrada da fundação.",
         "Estagiário de ensino fundamental menor de 14 anos.",
         "Vendedor ambulante de lanches da calçada do hospital.",
         "A",
         "O PGRSS exige responsabilidade técnica formal de profissional de nível superior habilitado (engenheiro ambiental/sanitário, biólogo, farmacêutico, enfermeiro, médico) com ART.",
         "RDC 222/2018, Art. 7º",
         "fácil"),
        # 33
        ("A sequência ordenada das etapas de MANEJO dos resíduos sólidos de serviços de saúde no PGRSS compreende:",
         "Segregação, acondicionamento, identificação, transporte interno, armazenamento temporário, armazenamento externo, coleta/transporte externo, tratamento e disposição final.",
         "Incineração direta no quarto do paciente, trituração no vaso e enterro na calçada.",
         "Transporte nas mãos dos enfermeiros, descarte no rio e lavagem dos sacos na chuva.",
         "Armazenamento debaixo dos leitos, queima com álcool e descarte na praça pública.",
         "Venda no mercado livre, mistura com comida do refeitório e reciclagem de agulhas.",
         "A",
         "A ordem lógica padronizada da ANVISA é: Segregação -> Acondicionamento -> Identificação -> Transporte interno -> Armazenamento -> Coleta externa -> Tratamento -> Disposição final.",
         "RDC 222/2018, Art. 9º",
         "fácil"),
        # 34
        ("O TRANSPORTE INTERNO de resíduos de serviços de saúde da FHCGV deve ser realizado:",
         "Em horários pré-determinados e de menor fluxo de pessoas, em recipientes coletores móveis rígidos, laváveis, estanques, dotados de tampa e rodas com travas.",
         "Com sacos plásticos abertos arrastados pelo chão cerâmico dos corredores.",
         "Nos mesmos carrinhos utilizados para servir as refeições dos pacientes.",
         "Jogando os sacos pelas escadarias de emergência para descerem rápido.",
         "Através dos dutos de ventilação do ar condicionado central das UTIs.",
         "A",
         "O transporte interno requer rotas traçadas, horários de baixo movimento, carrinhos específicos com tampa fechada e proibição expressa de arrastar sacos pelo piso.",
         "RDC 222/2018, Art. 21 e NR-32",
         "fácil"),
        # 35
        ("O local destinado ao ARMAZENAMENTO EXTERNO (abrigo de resíduos) do hospital deve possuir:",
         "Piso e paredes laváveis e impermeáveis, ponto de água, esgoto com ralo sifonado, ventilação natural ou mecânica, iluminação, cobertura, acesso restrito e fechamento com chave, e separação física para cada grupo de resíduos.",
         "Piso de terra batida aberta onde circulem cães e gatos de rua livremente.",
         "Localização dentro da copa central de preparação das mamadeiras do berçário.",
         "Portas sempre abertas sem qualquer cerca ou cadeado de segurança.",
         "Ausência total de água corrente e esgoto sanitário.",
         "A",
         "O abrigo externo (conforme RDC 222/2018) deve ser estanque, protegido contra intempéries e vetores, higienizável, trancado e com compartimentos separados para cada grupo de resíduo.",
         "RDC 222/2018, Arts. 26 a 31",
         "fácil"),
        # 36
        ("Em relação ao tratamento térmico de incineração de resíduos biológicos e químicos hospitalares perigosos:",
         "Deve ser realizado em usinas ou instalações com licenciamento ambiental específico emitido pelo órgão ambiental competente, com controle contínuo de emissões gasosas.",
         "Pode ser feito em fogueiras abertas no estacionamento de veículos do hospital.",
         "Deve ser realizado em churrasqueiras portáteis na varanda da diretoria.",
         "Pode ser executado com queima de pneus velhos no pátio interno da enfermaria.",
         "Fica dispensado de qualquer filtro ou tratamento de fumaça pela legislação.",
         "A",
         "A incineração de RSS exige licenciamento ambiental severo do órgão estadual de meio ambiente (SEMAS/PA) e controle de emissão de dioxinas e furanos (CONAMA 316/2002).",
         "Resolução CONAMA nº 316/2002 e RDC 222/2018",
         "média"),
        # 37
        ("O documento emitido pelo gerador, que acompanha o transporte de resíduos perigosos da unidade até o destinatário final comprovando a destinação ambientalmente adequada, é o:",
         "MTR (Manifesto de Transporte de Resíduos).",
         "DUT (Documento Único de Trânsito Veicular).",
         "CPF (Cadastro de Pessoas Físicas da Receita).",
         "RG (Registro Geral de Identidade Civil).",
         "IPTU (Imposto Predial e Territorial Urbano).",
         "A",
         "O MTR (Manifesto de Transporte de Resíduos) do SINIR/MMA rastreia a carga de resíduos perigosos desde o hospital gerador, transportador até o destino final licenciado.",
         "Portaria MMA 280/2020 e Política Nacional de Resíduos Sólidos",
         "média"),
        # 38
        ("A capacitação e o treinamento contínuo de todos os trabalhadores envolvidos direta ou indiretamente com o manejo de RSS na FHCGV devem contemplar:",
         "O conhecimento das classes de resíduos, riscos à saúde, uso correto de EPIs, higiene pessoal, procedimentos em casos de acidentes e conscientização ambiental.",
         "Aulas teóricas de pilotagem de aviões agrícolas no interior do estado.",
         "Técnicas de mineração subterrânea de pedras preciosas com dinamite.",
         "Apenas o treinamento para empurrar caixas de papelão no refeitório.",
         "Aprender a costurar uniformes cirúrgicos com máquinas elétricas.",
         "A",
         "A RDC 222/2018 (Art. 8º) e a NR-32 tornam compulsório o treinamento na admissão e periódico sobre biossegurança, classificação de RSS, uso de EPIs e ações de emergência.",
         "RDC 222/2018, Art. 8º e NR-32",
         "fácil"),
        # 39
        ("Qual a proibição expressa da RDC ANVISA nº 222/2018 em relação ao esvaziamento manual de recipientes coletores de resíduos perfurocortantes (Grupo E)?",
         "É expressamente proibido o esvaziamento manual de coletores de perfurocortantes para reaproveitamento do recipiente, bem como a transferência de resíduos de um coletor para outro.",
         "O esvaziamento manual é obrigatório a cada 30 minutos de plantão.",
         "O trabalhador deve retirar as agulhas com a mão esquerda desprotegida.",
         "O recipiente deve ser lavado com refrigerante de cola antes de ser reutilizado.",
         "As agulhas retiradas devem ser doadas para crianças confeccionarem artesanato.",
         "A",
         "A manipulação e esvaziamento manual de agulhas e vidros descartados viola a integridade física do trabalhador e é infração sanitária e de segurança gravíssima.",
         "RDC 222/2018, Art. 19 e NR-32",
         "fácil"),
        # 40
        ("A destinação final em Aterros Sanitários licenciados no Brasil é permitida para:",
         "Resíduos do Grupo D (comuns) e resíduos do Grupo A após terem sido submetidos a processo de tratamento prévio de descaracterização do risco biológico (autoclavagem/micro-ondas).",
         "Rejeitos radioativos de alta energia do Grupo C sem blindagem.",
         "Resíduos químicos perigosos do Grupo B altamente corrosivos ou inflamáveis.",
         "Agulhas e bisturis com sangue do Grupo E sem qualquer embalagem rígida.",
         "Frascos de vidro quebrados contendo quimioterápicos citostáticos líquidos.",
         "A",
         "Resíduos comuns do Grupo D e biológicos do Grupo A previamente tratados e desinfetados podem ser dispostos em aterros sanitários municipais licenciados.",
         "RDC 222/2018 e Resolução CONAMA 358/2005",
         "média")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "Resíduos de Saúde",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_residuos_questions()
    print(f"Resíduos de Saúde questions generated: {len(q)}")
