# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-32 (150 questões)
- Risco biológico: 50 questões
- Perfurocortantes e acidentes: 40 questões
- Vacinação e EPIs específicos: 30 questões
- Risco químico (anestésicos, citostáticos): 20 questões
- Risco físico (radiações): 10 questões
"""

def get_nr32_questions():
    questions = []
    
    # -------------------------------------------------------------
    # 1. RISCO BIOLÓGICO (50 questões)
    # -------------------------------------------------------------
    bio_items = [
        # 1
        ("Em relação à classificação dos agentes biológicos que podem causar infecção no homem, a NR-32 adota a classificação em classes de risco de 1 a 4. Um agente com baixo risco individual e baixo risco para a coletividade, que dificilmente causa doença no ser humano sadio, pertence à:",
         "Classe de risco 1.",
         "Classe de risco 2.",
         "Classe de risco 3.",
         "Classe de risco 4.",
         "Classe especial hospitalar.",
         "A",
         "A Classe de Risco 1 compreende agentes com baixo risco individual para o trabalhador e baixa probabilidade de propagação para a coletividade.",
         "NR-32, Anexo I e Diretrizes do Ministério da Saúde",
         "fácil"),
        # 2
        ("Os agentes biológicos da Classe de Risco 2 são definidos pela NR-32 como aqueles que:",
         "Nunca causam doença humana ou animal em qualquer hipótese.",
         "Podem causar doenças no ser humano e constituir perigo para os trabalhadores, mas há profilaxia e tratamento eficaz disponíveis e o risco de propagação comunitária é limitado.",
         "Causam doenças humanas graves, sem tratamento eficaz nem vacina disponível, com altíssimo contágio comunitário.",
         "Apresentam exclusivamente risco toxicológico por inalação de solventes orgânicos.",
         "São exclusivamente derivados de organismos geneticamente modificados de nível industrial.",
         "B",
         "A Classe 2 abrange agentes com risco individual moderado e risco comunitário limitado, havendo tratamento ou medidas profiláticas eficazes (ex: Klebsiella pneumoniae, Staphylococcus aureus).",
         "NR-32, Anexo I",
         "média"),
        # 3
        ("O Mycobacterium tuberculosis, agente etiológico da tuberculose, comum na rotina hospitalar de pacientes internados na FHCGV, é classificado biologicamente como pertencente à:",
         "Classe de risco 1.",
         "Classe de risco 2.",
         "Classe de risco 3.",
         "Classe de risco 4.",
         "Classe de risco zero.",
         "C",
         "O Mycobacterium tuberculosis pertence à Classe de Risco 3: agentes que causam patologias humanas graves, de transmissão respiratória, para os quais usualmente existem tratamento e prevenção.",
         "NR-32, Anexo I",
         "média"),
        # 4
        ("Agentes biológicos que possuem alta patogenicidade, representam grave ameaça aos trabalhadores, com elevado risco de propagação na comunidade e para os quais não se dispõe de tratamento ou profilaxia eficaz (como vírus Ebola e Marburg) enquadram-se na:",
         "Classe de risco 1.",
         "Classe de risco 2.",
         "Classe de risco 3.",
         "Classe de risco 4.",
         "Classe residual sanitária.",
         "D",
         "A Classe de Risco 4 contempla agentes patogênicos de máxima gravidade, facilidade de propagação e ausência de medidas profiláticas ou terapêuticas conhecidas.",
         "NR-32, Anexo I",
         "fácil"),
        # 5
        ("Sobre o uso de adornos em serviços de saúde da FHCGV, a NR-32 estabelece categoricamente no subitem 32.2.4.5 que:",
         "É permitido o uso de alianças lisas e brincos discretos durante a assistência direta ao leito.",
         "O uso de adornos deve ser vedado a todos os trabalhadores que exerçam atividades com risco de exposição a agentes biológicos.",
         "Adornos de ouro ou platina são permitidos por serem materiais inertes e bactericidas.",
         "Somente os médicos-cirurgiões são impedidos de usar anéis e relógios de pulso.",
         "A proibição do uso de adornos restringe-se exclusivamente aos setores de isolamento de doenças infectocontagiosas.",
         "B",
         "O subitem 32.2.4.5 da NR-32 determina que o empregador deve vedar o uso de adornos pelos trabalhadores com risco de exposição a agente biológico (inclui anéis, alianças, relógios, colares, brincos, piercings, etc.).",
         "NR-32, item 32.2.4.5",
         "fácil"),
        # 6
        ("Com relação ao vestuário e calçados dos profissionais de saúde atuantes em enfermarias, UTI e pronto-socorro da FHCGV, a NR-32 proíbe expressamente:",
         "O uso de calçados impermeáveis de borracha tipo clog fechado.",
         "O uso de calçados abertos, devendo ser utilizados calçados completamente fechados na região superior e posterior.",
         "O uso de meias de algodão de cor branca ou escura.",
         "O uso de calçados com sola de poliuretano antiderrapante.",
         "A utilização de jalecos de mangas compridas em áreas assistenciais.",
         "B",
         "A NR-32, item 32.2.4.7, proíbe expressamente o uso de calçados abertos aos trabalhadores com exposição a agentes biológicos.",
         "NR-32, item 32.2.4.7",
         "fácil"),
        # 7
        ("Nos locais de trabalho hospitalares onde há exposição a agentes biológicos, a NR-32 estipula que é expressamente proibido:",
         "O consumo de alimentos e bebidas, bem como fumar e o uso de cosméticos e armazenamento de alimentos nas bancadas ou postos.",
         "A conversa profissional entre técnicos de enfermagem durante a troca de plantão.",
         "A anotação de prontuários em pranchetas eletrônicas ou tablets higienizáveis.",
         "O uso de dispensers de sabonete líquido acionados por sensor óptico.",
         "A presença de recipientes de álcool em gel 70% fixados nas portas das enfermarias.",
         "A",
         "Conforme o item 32.2.4.4 da NR-32, aos trabalhadores é vedado fumar, usar cosméticos, consumir ou guardar alimentos nos postos de trabalho sujeitos a agentes biológicos.",
         "NR-32, item 32.2.4.4",
         "fácil"),
        # 8
        ("A respeito dos lavatórios destinados à higienização das mãos nas instalações da FHCGV, a NR-32 determina que esses devem:",
         "Possuir torneiras com registro de acionamento manual por chave de rosca convencional.",
         "Ser dotados de torneira de fechamento que não necessite de contato manual para fechamento (ex: pedal, cotovelo ou sensor), sabonete líquido, toalhas descartáveis e lixeira com pedal.",
         "Utilizar toalhas coletivas de tecido de algodão com troca semanal programada.",
         "Possuir secadores de ar quente em substituição integral ao papel toalha nas salas de isolamento.",
         "Ser compartilhados indiscriminadamente com as pias de expurgo e lavagem de instrumentais sujos.",
         "B",
         "Os lavatórios para higienização das mãos devem ser exclusivos, providos de torneiras sem contato manual, sabonete líquido, toalhas descartáveis e lixeira acionada sem as mãos (NR-32, item 32.2.4.1).",
         "NR-32, item 32.2.4.1",
         "média"),
        # 9
        ("Na higienização das mãos em ambiente hospitalar, o uso de preparação alcoólica a 70% (gel ou solução) é indicado prioritariamente quando:",
         "As mãos estiverem visivelmente sujas com sangue ou secreções purulentas.",
         "As mãos não estiverem visivelmente sujas, promovendo rápida antissepsia entre o contato com diferentes pacientes.",
         "Houver contaminação direta por esporos de Clostridioides difficile.",
         "O profissional for manipular diretamente alimentos na copa do hospital.",
         "Em substituição à lavagem das mãos após o uso do sanitário.",
         "B",
         "A fricção com solução alcoólica é o método de escolha para antissepsia das mãos quando estas não apresentam sujidade visível. Com sujidade visível ou esporos, a lavagem com água e sabonete é mandatória.",
         "Diretrizes de Higiene das Mãos ANVISA e NR-32",
         "média"),
        # 10
        ("Em relação à guarda de vestimentas e uniformes, os trabalhadores expostos a agentes biológicos na FHCGV devem dispor de vestiários com armários dotados de:",
         "Compartimento único compartilhado entre dois servidores.",
         "Compartimentos duplos que permitam isolar a roupa de uso pessoal da vestimenta utilizada na atividade hospitalar.",
         "Prateleiras abertas e coletivas sem tranca para ventilação contínua.",
         "Fechaduras biométricas conectadas à central de faturamento do hospital.",
         "Estrutura exclusivamente de madeira porosa para absorver a umidade ambiental.",
         "B",
         "O item 32.2.4.3 da NR-32 exige armários de compartimento duplo para separar roupas de uso comum das vestimentas de trabalho com exposição biológica.",
         "NR-32, item 32.2.4.3",
         "média"),
        # 11
        ("Quanto à higienização das vestimentas e uniformes de trabalho utilizados em setores hospitalares com risco biológico, a NR-32 estipula que:",
         "A responsabilidade pela lavagem é exclusiva do trabalhador, que deve levá-los para sua residência ao final de cada plantão.",
         "O empregador é o responsável pelo processo de descontaminação e higienização das vestimentas quando houver contato com material biológico.",
         "O trabalhador deve receber um vale-lavanderia comercial com desconto de 20% em folha de pagamento.",
         "As roupas contaminadas devem ser descartadas em incinerador após cada uso individual de 12 horas.",
         "O empregador deve pagar um adicional indenizatório de insalubridade de 10% em troca da lavagem doméstica pelo empregado.",
         "B",
         "A higienização de vestimentas de trabalho utilizadas em ambientes com risco biológico é de responsabilidade do empregador (NR-32, subitem 32.2.4.6.4).",
         "NR-32, item 32.2.4.6.4",
         "média"),
        # 12
        ("Durante o procedimento de limpeza de piso em enfermarias e corredores da FHCGV, a equipe de higiene hospitalar deve observar que a NR-32 veda terminantemente:",
         "A utilização de esfregonas tipo mop úmido com solução desinfetante.",
         "A varredura a seco nas áreas internas assistenciais.",
         "O uso de placas móveis de sinalização de 'piso molhado'.",
         "A troca periódica de água do balde de desinfecção.",
         "O uso de luvas de borracha nitrílica de cano longo pelos higienizadores.",
         "B",
         "A varredura a seco em áreas internas de serviços de saúde é proibida pela NR-32 (item 32.2.4.9) devido à aerossolização de patógenos.",
         "NR-32, item 32.2.4.9",
         "fácil"),
        # 13
        ("Em relação aos quartos de isolamento respiratório para pacientes portadores de tuberculose pulmonar bacilífera na FHCGV, o sistema de climatização deve garantir:",
         "Pressão positiva em relação ao corredor para expulsar o ar contaminado para fora do quarto.",
         "Pressão negativa em relação às áreas adjacentes, exaustão de ar com filtragem HEPA ou descarga direta para o exterior.",
         "Ventilador de teto comum mantido em velocidade máxima sem recirculação.",
         "Ar condicionado tipo split doméstico operando em modo recirculação fechada.",
         "Fechamento hermético sem qualquer renovação de ar ambiente.",
         "B",
         "Quartos de isolamento para aerossóis exigem pressão negativa para impedir o escape de partículas infectantes para o corredor, com troca contínua de ar e filtragem HEPA.",
         "NR-32 e RDC 50/ANVISA",
         "difícil"),
        # 14
        ("O equipamento de proteção respiratória indicado para proteger o profissional de saúde contra a inalação de partículas aerossolizadas contendo Mycobacterium tuberculosis é:",
         "Máscara cirúrgica descartável simples de TNT de camada única.",
         "Respirador purificador de ar semifacial filtrante para partículas PFF2 ou equivalente N95.",
         "Máscara de tecido de algodão de fabricação caseira lavável.",
         "Protetor facial acrílico (face shield) isoladamente sem máscara.",
         "Máscara de carvão ativado sem classificação contra partículas biológicas.",
         "B",
         "Para aerossóis biológicos (como bacilo da TB e vírus influenza/covid em intubação), exige-se respirador PFF2/N95. A máscara cirúrgica protege apenas contra gotículas.",
         "NR-32 e Diretrizes ANVISA",
         "média"),
        # 15
        ("Ao utilizar um respirador descartável PFF2 / N95 antes de entrar no quarto de isolamento de um paciente, o trabalhador de saúde deve obrigatoriamente realizar:",
         "A lavagem do respirador em solução de hipoclorito a 1%.",
         "A verificação de vedação (teste de pressão positiva e negativa / fit check) cobrindo o respirador com as mãos e expirando/inspirando.",
         "A perfuração de um orifício central com alfinete para facilitar a entrada de oxigênio.",
         "A aplicação de álcool gel 70% sobre as fibras externas do filtro.",
         "O corte dos elásticos para fixação frouxa atrás das orelhas.",
         "B",
         "A checagem de vedação (fit check) é o teste rápido feito pelo trabalhador a cada colocação para garantir que não há vazamentos pelas bordas do respirador.",
         "NR-32 e NR-06",
         "média"),
        # 16
        ("O Programa de Gerenciamento de Riscos (PGR) da FHCGV, no que se refere aos agentes biológicos previsto na NR-32, deve conter inventário de riscos com:",
         "Apenas a indicação genérica 'risco biológico hospitalar' sem detalhar atividades.",
         "Identificação das fontes de exposição, agentes patogênicos mais prováveis, vias de transmissão, persistência no ambiente e avaliação dos trabalhadores expostos.",
         "Dispensa de inventário caso o hospital tenha menos de 500 leitos ativos.",
         "Substituição das análises técnicas por uma simples declaração anual firmada pela ouvidoria.",
         "Omissão das medidas de prevenção adotadas em setores de pronto-socorro.",
         "B",
         "A avaliação de riscos biológicos deve detalhar fontes, vias de transmissão, agentes patogênicos prováveis e medidas preventivas aplicadas a cada setor e função.",
         "NR-32, item 32.2.2.1",
         "difícil"),
        # 17
        ("Os recipientes de coleta interna de roupas sujas (hamper) nos leitos hospitalares da FHCGV devem ser:",
         "Construídos em madeira porosa para absorver os fluidos corporais dos lençóis.",
         "Dotados de sacos resistentes, impermeáveis, de cor diferenciada e manipulados sem contato direto com o corpo do profissional.",
         "Apoiados sobre as mesas de refeição dos pacientes para facilitar o descarte pelo técnico.",
         "Esvaziados diretamente no chão do corredor antes da pesagem geral.",
         "Lavados somente com água da chuva coletada sem adição de tensoativos.",
         "B",
         "Os hampers devem possuir sacos impermeáveis resistentes, preenchidos até o limite seguro e fechados no próprio local de geração para transporte seguro.",
         "NR-32, item 32.7",
         "fácil"),
        # 18
        ("Em relação à manipulação de carcaças ou cadáveres no setor de anatomia patológica e necrotério do hospital, a NR-32 exige que:",
         "Os técnicos trabalhem desprovidos de luvas para aumentar a sensibilidade tátil.",
         "O ambiente seja provido de sistema de exaustão de ar, mesas em aço inoxidável com escoamento de líquidos e EPIs adequados (avental impermeável, botas, luvas resistentes e proteção respiratória).",
         "Os cadáveres sejam mantidos em temperatura ambiente de 35ºC para acelerar a necropsia.",
         "Seja permitida a ingestão de café dentro da sala de necropsia caso o exame demore mais de 2 horas.",
         "A água servida da lavagem de vísceras seja despejada diretamente na sarjeta da via pública externa.",
         "B",
         "Salas de necropsia e patologia exigem infraestrutura com exaustão, mesas inoxidáveis laváveis e uso rigoroso de EPIs impermeáveis e de proteção biológica.",
         "NR-32, item 32.6",
         "média"),
        # 19
        ("A respeito do colchão e travesseiros hospitalares utilizados nas enfermarias da FHCGV, a NR-32 e normas sanitárias exigem que:",
         "Possuam revestimento impermeável e lavável, que permita fácil desinfecção química entre a saída de um paciente e a admissão de outro.",
         "Sejam confeccionados exclusivamente em tecido de linho cru sem impermeabilização.",
         "Permaneçam com as espumas expostas caso haja rasgos provocados por uso continuado.",
         "Sejam trocados por colchões novos somente a cada 10 anos de uso hospitalar contínuo.",
         "Possam ser lavados por imersão em água fervente com os pacientes ainda deitados sobre eles.",
         "A",
         "Colchões e travesseiros hospitalares devem ter revestimento lavável e impermeável, íntegro, que permita a desinfecção adequada entre internações.",
         "NR-32 e RDC ANVISA",
         "fácil"),
        # 20
        ("Em caso de derramamento acidental de sangue ou fluidos corporais de grande volume no piso de uma enfermaria, o procedimento técnico correto de limpeza e desinfecção é:",
         "Jogar água em abundância com mangueira pressurizada sem recolher o sangue.",
         "Colocar papel absorvente sobre o líquido, aplicar solução desinfetante hospitalar (como hipoclorito a 1%), aguardar o tempo de contato e recolher com pá descartável.",
         "Varrer a poça de sangue seco com vassoura de cerdas duras para formar aerossol.",
         "Deixar o sangue secar naturalmente por 24 horas para que os vírus morram com o calor ambiente.",
         "Cobrir a poça de sangue com um lençol limpo e manter a passagem de pedestres liberada.",
         "B",
         "A contenção de derramamentos biológicos requer absorção imediata, uso de EPIs, aplicação de desinfetante compatível no tempo de ação preconizado e descarte no lixo Grupo A.",
         "Manual de Biossegurança Hospitalar e NR-32",
         "média"),
        # 21
        ("A transmissão de agentes patogênicos hospitalares por via aérea difere da transmissão por gotículas principalmente porque:",
         "Os aerossóis possuem partículas menores que 5 micrômetros que permanecem suspensas no ar por longos períodos e atingem alvéolos pulmonares.",
         "As gotículas flutuam por horas a distâncias superiores a 20 metros sem cair ao chão.",
         "Os aerossóis são gerados unicamente durante o sono tranquilo do paciente.",
         "As gotículas exigem o uso permanente de escafandro com suprimento de oxigênio de mergulho.",
         "Os aerossóis não requerem qualquer medida de ventilação mecânica ou EPI.",
         "A",
         "Aerossóis têm diâmetro inferior a 5 micrômetros, mantêm-se suspensos no ar e viajam grandes distâncias, exigindo PFF2/N95 e pressão negativa.",
         "Diretrizes ANVISA e NR-32",
         "média"),
        # 22
        ("Qual dos seguintes procedimentos hospitalares é considerado um PROCEDIMENTO GERADOR DE AEROSSÓIS (PGA) de alto risco para contaminação biológica respiratória da equipe:",
         "Aferição manual da pressão arterial com esfigmomanômetro.",
         "Intubação orotraqueal e aspiração de secreções em vias aéreas abertas.",
         "Administração de comprimido oral com meio copo de água.",
         "Eletrocardiograma de repouso com eletrodos adesivos.",
         "Inspeção visual da pele do abdome do paciente.",
         "B",
         "Intubação traqueal, aspiração endotraqueal, ressuscitação cardiopulmonar e broncoscopia são geradores de aerossóis, exigindo máscara PFF2, capote impermeável, gorro e óculos/face shield.",
         "NR-32 e Protocolos de Biossegurança",
         "fácil"),
        # 23
        ("Em relação à Central de Material e Esterilização (CME) da FHCGV, a NR-32 estabelece que a área de recepção e limpeza dos instrumentais cirúrgicos sujos (expurgo):",
         "Deve ser completamente aberta e integrada sem paredes com a sala de guarda de materiais estéreis.",
         "Deve constituir um ambiente isolado (área suja), dotado de sistema de exaustão de ar e bancadas com cubas profundas para evitar respingos.",
         "Não necessita de ponto de água corrente ou pias para lavagem manual.",
         "Deve permitir a circulação livre de visitantes e familiares de pacientes internados.",
         "Pode ser utilizada como refeitório secundário para os técnicos em plantões noturnos.",
         "B",
         "O expurgo da CME é área suja crítica, devendo ter barreira física para as demais áreas, cubas adequadas, EPIs impermeáveis e fluxo unidirecional.",
         "NR-32 e RDC 15/2012 ANVISA",
         "média"),
        # 24
        ("Durante a lavagem manual de instrumentais cirúrgicos com matéria orgânica aderida na CME, o trabalhador deve utilizar obrigatoriamente:",
         "Luvas cirúrgicas estéreis finas de espessura de 0,05 mm sem avental.",
         "Avental impermeável de manga longa, protetor facial ou óculos com máscara, luvas de borracha nitrílica ou látex cano longo e calçado fechado antiderrapante.",
         "Apenas chinelos de borracha e máscara de tecido comum.",
         "Roupas privativas de algodão sem qualquer proteção ocular ou facial.",
         "Luvas de lã tricotada para reter a umidade nas mãos.",
         "B",
         "A limpeza de instrumentais expõe a respingos biológicos e perfuração, exigindo avental plástico impermeável, proteção facial/ocular e luvas grossas de borracha.",
         "NR-32 e RDC 15/2012",
         "fácil"),
        # 25
        ("O fluxo de trabalho na Central de Material e Esterilização (CME) deve ser estritamente unidirecional, o que significa que o material segue na sequência:",
         "Área de guarda estéril -> Expurgo -> Esterilização -> Preparo.",
         "Expurgo (recebimento/limpeza) -> Preparo e empacotamento -> Esterilização -> Guarda e distribuição de material esterilizado.",
         "Esterilização -> Expurgo -> Descarte -> Devolução.",
         "Expurgo -> Guarda de material estéril -> Lavagem manual -> Embalagem.",
         "Guarda -> Distribuição -> Preparo -> Expurgo.",
         "B",
         "O fluxo unidirecional impede o cruzamento de materiais sujos com materiais limpos e estéreis (Expurgo -> Preparo -> Esterilização -> Guarda).",
         "RDC 15/ANVISA e NR-32",
         "fácil"),
        # 26
        ("A respeito do treinamento em prevenção de riscos biológicos preconizado pela NR-32, assinale a opção correta:",
         "O treinamento deve ser ministrado antes do início das atividades do empregado e continuado a cada 1 ano ou sempre que houver alteração nas condições de risco.",
         "O treinamento é opcional para profissionais de nível superior com diploma de graduação.",
         "Basta a assinatura de uma lista de presença pelo trabalhador, sem necessidade de transmissão de conteúdo técnico.",
         "O treinamento pode ser realizado após 6 meses de trabalho do novo empregado no hospital.",
         "A comprovação do treinamento pode ser descartada após 30 dias de sua realização.",
         "A",
         "O item 32.2.4.9 determina treinamento prévio à admissão e continuado, com registro documentado comprovando a capacitação dos trabalhadores.",
         "NR-32, item 32.2.4.9",
         "média"),
        # 27
        ("Dentre os conteúdos programáticos OBRIGATÓRIOS no treinamento da NR-32 para trabalhadores expostos a agentes biológicos, NÃO se inclui:",
         "Dados sobre a vigilância epidemiológica e vias de transmissão dos patógenos.",
         "Técnicas de elaboração do plano plurianual de faturamento orçamentário do hospital.",
         "Orientações sobre uso, higienização, limitações e descarte correto dos EPIs.",
         "Condutas a serem adotadas em caso de acidentes e incidentes com sangue e fluidos.",
         "Uso correto dos dispositivos de segurança em perfurocortantes.",
         "B",
         "O faturamento orçamentário não faz parte do treinamento de segurança e saúde no trabalho da NR-32, que foca na biossegurança e proteção do trabalhador.",
         "NR-32, item 32.2.4.9.1",
         "fácil"),
        # 28
        ("Nos laboratórios de análises clínicas da FHCGV que manipulam amostras biológicas humanas, a centrifugação de tubos de ensaio deve ser realizada:",
         "Com a centrífuga totalmente aberta para permitir visualização contínua pelo técnico.",
         "Em centrífugas com tampa de segurança dotada de trava eletromecânica que impeça a abertura com o rotor em movimento e caçapas com tampas herméticas contra aerossóis.",
         "Segurando os tubos de vidro manualmente com uma pinça de madeira enquanto o motor gira.",
         "Apenas à noite com as janelas e portas do laboratório escancaradas.",
         "Utilizando copos de plástico descartáveis de café como suporte de tubos.",
         "B",
         "As centrífugas laboratoriais devem ter travas de segurança e caçapas seladas para evitar formação e dispersão de aerossóis biológicos em caso de quebra de tubos.",
         "NR-32 e Boas Práticas de Laboratório",
         "média"),
        # 29
        ("A pipetagem manual de sangue ou líquidos corporais com a boca é classificada pelas normas de biossegurança e pela NR-32 como:",
         "Permitida apenas se a amostra biológica for previamente diluída em água destilada.",
         "Prática terminantemente proibida, sendo obrigatório o uso de micropipetadores mecânicos ou pipetadores automáticos com ponteiras adequadas.",
         "Recomendada para dosagens de eletrólitos de emergência em UTI.",
         "Autorizada exclusivamente para farmacêuticos e biomédicos graduados.",
         "Permitida quando os técnicos estiverem em jejum de pelo menos 8 horas.",
         "B",
         "A pipetagem com a boca é expressamente vedada em quaisquer circunstâncias devido ao altíssimo risco de ingestão e aspiração de patógenos.",
         "NR-32 e Diretrizes de Biossegurança",
         "fácil"),
        # 30
        ("Em relação aos filtros de ar-condicionado de setores hospitalares críticos como Bloco Cirúrgico e UTI Cardiológica da FHCGV, a manutenção deve garantir:",
         "Limpeza e substituição periódica com registro formal no PMOC (Plano de Manutenção, Operação e Controle) para evitar acúmulo de fungos e bactérias.",
         "Uso permanente de filtros de lã de vidro sem troca por até 20 anos consecutivos.",
         "Borrifação de perfume automotivo nos dutos de ventilação para neutralizar odores.",
         "Desligamento do sistema de ar durante todas as cirurgias de grande porte.",
         "Dispensa de qualquer controle de qualidade do ar interior nas salas limpas.",
         "A",
         "O PMOC e as normas sanitárias exigem inspeção, higienização e troca periódica dos filtros (especialmente filtros HEPA) para garantir a qualidade biológica do ar.",
         "Lei 13.589/2018, RE 09/ANVISA e NR-32",
         "média"),
        # 31
        ("Na hotelaria hospitalar da FHCGV, a separação da lavanderia em 'Área Suja' e 'Área Limpa' tem por objetivo primordial de segurança:",
         "Reduzir o consumo de energia elétrica das lavadoras industriais.",
         "Impedir a contaminação cruzada do enxoval limpo e esterilizado por microrganismos patogênicos provenientes das roupas recém-retiradas dos leitos.",
         "Facilitar o acesso livre de ambulantes para venda de sabão em pó.",
         "Permitir que os trabalhadores fumem na área limpa sem incomodar os da área suja.",
         "Eliminar a necessidade de pagamento do adicional de insalubridade aos lavadores.",
         "B",
         "A barreira física entre área suja e limpa impede que bactérias e vírus carreados nas roupas sujas contaminem as roupas higienizadas prontas para uso.",
         "NR-32, item 32.7",
         "fácil"),
        # 32
        ("Qual a recomendação da NR-32 a respeito do consumo de alimentos pelo trabalhador durante seu intervalo de refeição no hospital?",
         "Os trabalhadores podem almoçar dentro do posto de enfermagem ou na bancada de esterilização se estiverem vigiando o setor.",
         "O empregador deve disponibilizar refeitório ou local exclusivo para refeições, fora das áreas de assistência e postos com risco de contaminação biológica.",
         "As refeições devem ser realizadas em pé nos corredores ao lado dos carrinhos de curativo.",
         "É expressamente proibido qualquer tipo de intervalo para refeições na jornada de 12 horas.",
         "O trabalhador deve alimentar-se no próprio leito vago do paciente de enfermaria.",
         "B",
         "A NR-32 exige locais próprios e adequados para refeições fora das áreas assistenciais e longe de fontes de agentes biológicos.",
         "NR-32, item 32.2.4.4 e NR-24",
         "fácil"),
        # 33
        ("Em relação à higienização das mãos com água e sabonete pelos profissionais de enfermagem, o uso de toalhas de papel deve ser:",
         "Em folhas duplas ou simples descartáveis, sendo proibida a reutilização ou o uso de toalhas de rolo coletivo de tecido não lavável.",
         "Substituído por aventais de pano que os próprios trabalhadores amarram à cintura.",
         "Dispensado, devendo os trabalhadores secar as mãos nas calças de seus uniformes privativos.",
         "Realizado com folhas de jornal reciclado comum picado.",
         "Limitado a uma única folha por dia de plantão para economizar recursos públicos.",
         "A",
         "A secagem de mãos deve ser feita exclusivamente com papel toalha descartável de boa absorção, vedadas toalhas de uso coletivo (NR-32, item 32.2.4.1).",
         "NR-32, item 32.2.4.1",
         "fácil"),
        # 34
        ("A respeito do uso de luvas de procedimentos por técnicos de enfermagem ao prestar assistência hospitalar, a NR-32 e manuais da ANVISA determinam que:",
         "O uso de luvas substitui completamente a necessidade de higienizar as mãos com água e sabão.",
         "O profissional deve higienizar as mãos imediatamente antes de calçar as luvas e logo após a sua retirada entre um paciente e outro.",
         "As luvas de procedimento podem ser lavadas na torneira com detergente para reutilização em até cinco pacientes consecutivos.",
         "O profissional deve aplicar álcool em gel 70% sobre as luvas calçadas para limpá-las e continuar o atendimento ao próximo leito.",
         "As luvas descartáveis devem ser guardadas no bolso do jaleco para o próximo plantão semanal.",
         "B",
         "As luvas nunca substituem a higienização das mãos. A fricção com álcool ou lavagem com água e sabão deve ocorrer antes de calçar e imediatamente após retirá-las.",
         "Diretrizes ANVISA e NR-32",
         "média"),
        # 35
        ("Na assistência a pacientes colonizados ou infectados por bactérias multirresistentes (ex: KPC, VRE, Acinetobacter baumannii), as precauções de contato preconizam:",
         "Uso de quarto privativo (ou coorte), avental de mangas longas e luvas de procedimento durante todo o contato com o paciente ou ambiente próximo, com higienização estrita das mãos.",
         "Uso exclusivo de respirador PFF3 sem necessidade de luvas ou higienização de mãos.",
         "Proibição de qualquer atendimento de saúde ao paciente por mais de 30 dias.",
         "Manter a porta do quarto aberta com exaustor soprando o ar para o posto de enfermagem.",
         "Dispensa de paramentação se o profissional permanecer a menos de 2 metros da cama.",
         "A",
         "As precauções de contato para multirresistentes exigem avental impermeável/limpo e luvas durante o contato com o paciente e mobiliário, além de limpeza terminal rigorosa.",
         "Protocolos de Infecção Hospitalar e NR-32",
         "média"),
        # 36
        ("Em relação à identificação visual de recipientes contendo amostras biológicas nos laboratórios e setores hospitalares da FHCGV, é MANDATÓRIO:",
         "A aposição do símbolo internacional de risco biológico e identificação clara do conteúdo e do paciente.",
         "A utilização exclusiva de fitas adesivas pretas sem nenhum tipo de inscrição gráfica.",
         "A colocação de frases publicitárias sobre a fundação hospitalar cobrindo o rótulo.",
         "A dispensa de identificação caso a amostra seja transportada em temperatura ambiente.",
         "O preenchimento do rótulo apenas com as iniciais do técnico de segurança do trabalho.",
         "A",
         "A NR-32 exige que todos os recipientes contendo material biológico sejam identificados com o símbolo internacional de risco biológico e dados adequados da amostra.",
         "NR-32, item 32.2.4.14",
         "fácil"),
        # 37
        ("Ao término da jornada de trabalho, o trabalhador exposto a agentes biológicos que utiliza vestimenta fornecida pelo hospital para uso exclusivo interno deve:",
         "Permanecer vestindo a mesma roupa para retornar para casa em transporte coletivo urbano.",
         "Retirar a vestimenta de trabalho no vestiário hospitalar, acondicioná-la no local destinado e vestir suas roupas civis de uso comum.",
         "Vender o uniforme a outro colega do plantão que esteja sem roupa limpa.",
         "Levar a vestimenta contaminada em sacola aberta para lavar juntamente com as roupas de seus familiares.",
         "Fazer compras em supermercados e frequentar restaurantes trajando o uniforme do hospital.",
         "B",
         "A NR-32 veda terminantemente ao trabalhador sair do estabelecimento com vestimentas de trabalho utilizadas nas áreas com risco de exposição biológica (item 32.2.4.6.3).",
         "NR-32, item 32.2.4.6.3",
         "fácil"),
        # 38
        ("Um técnico de enfermagem foi flagrado utilizando seu jaleco de trabalho no refeitório externo e nas lanchonetes da vizinhança da FHCGV. À luz da NR-32, a conduta desse servidor:",
         "É plenamente amparada pela CLT, pois o jaleco confere autoridade visual na comunidade.",
         "Constitui violação expressa à NR-32, que proíbe expressamente sair do ambiente hospitalar com os EPIs e vestimentas de trabalho utilizados na assistência.",
         "É recomendada pelas comissões de controle de infecção para desinfecção do jaleco pela luz solar.",
         "Só seria infração se o funcionário estivesse portando agulhas usadas no bolso do jaleco.",
         "É permitida desde que o jaleco tenha sido passado a ferro na manhã do mesmo dia.",
         "B",
         "O subitem 32.2.4.6.3 da NR-32 proíbe os trabalhadores de saírem do local de trabalho com os equipamentos de proteção individual e as vestimentas utilizadas em suas atividades assistenciais.",
         "NR-32, item 32.2.4.6.3",
         "fácil"),
        # 39
        ("A respeito do Comitê de Biossegurança e da Comissão de Controle de Infecção Hospitalar (CCIH) em relação à segurança ocupacional:",
         "O TST deve atuar de forma articulada com a CCIH, integrando medidas de prevenção contra infecções hospitalares com a proteção dos próprios trabalhadores do hospital.",
         "A CCIH preocupa-se unicamente com custos financeiros de antibióticos, sem qualquer relação com a segurança da equipe de enfermagem.",
         "A NR-32 proíbe o SESMT de trocar informações com os médicos e enfermeiros da CCIH.",
         "O TST tem poder hierárquico unilateral para extinguir a CCIH em hospitais estaduais.",
         "O controle de infecção hospitalar é tarefa restrita à vigilância privada contratada do hospital.",
         "A",
         "A integração entre SESMT, CIPA e CCIH é fundamental para garantir a proteção simultânea dos pacientes e dos trabalhadores de saúde contra patógenos hospitalares.",
         "NR-32 e Portaria MS 2.616/1998",
         "média"),
        # 40
        ("Em relação à circulação de ar em enfermarias de isolamento por gotículas (ex: meningite meningocócica, coqueluche), a diretriz técnica orienta:",
         "Apenas o uso de máscara cirúrgica pelo trabalhador ao se aproximar a menos de 1 metro do paciente e máscara no paciente durante transportes necessários.",
         "A instalação obrigatória de filtros nucleares de carvão com temperatura de 100ºC no teto.",
         "A proibição da entrada de qualquer profissional de saúde na enfermaria por 14 dias.",
         "O uso contínuo de respirador motorizado com ar comprimido mandado para toda a equipe.",
         "A vedação hermética da porta com fita adesiva cinza e lacre chumbado.",
         "A",
         "Gotículas são partículas pesadas (> 5 micrômetros) que decaem em até 1 a 2 metros da fonte; exigem máscara cirúrgica para a equipe próxima e no paciente durante deslocamentos.",
         "Diretrizes ANVISA e NR-32",
         "média"),
        # 41
        ("Em serviços de odontologia hospitalar e bucomaxilofacial da FHCGV, o uso de turbinas de alta rotação e aparelhos de ultrassom gera grande quantidade de névoa biológica. A medida adequada é:",
         "Uso de máscara cirúrgica simples frouxa com a janela da sala fechada.",
         "Uso de respirador PFF2/N95, protetor facial acrílico (face shield), óculos com vedação lateral, sugador de alta potência e avental impermeável.",
         "Substituição das luvas de procedimento por luvas térmicas de forno micro-ondas.",
         "Realização dos procedimentos odontológicos na penumbra para diminuir a dispersão da saliva.",
         "Dispensa de óculos de proteção caso o cirurgião-dentista use óculos de grau comum.",
         "B",
         "Procedimentos odontológicos de alta rotação produzem aerossóis intensos com sangue e saliva, exigindo proteção facial completa, respiradores PFF2 e sucção potente.",
         "NR-32, item 32.3 e Manual de Biossegurança em Odontologia",
         "média"),
        # 42
        ("Sobre a limpeza de vidros quebrados contaminados com matéria orgânica (ex: frasco de hemocultura quebrado no chão), a equipe de higiene hospitalar deve:",
         "Recolher os cacos de vidro com as mãos desnudas para não estragar as luvas de borracha.",
         "Utilizar instrumentos auxiliares mecânicos como pá e pinça ou vassourinha, nunca recolhendo fragmentos pontiagudos diretamente com as mãos.",
         "Empurrar os cacos de vidro com os pés descalços até o ralo mais próximo da enfermaria.",
         "Jogar ácido clorídrico sobre os vidros para tentar dissolvê-los no piso do hospital.",
         "Cobrir com toalha de papel e permitir que os transeuntes pisem por cima até triturar o vidro.",
         "B",
         "Fragmentos de vidro contaminados jamais devem ser manipulados diretamente com as mãos, devendo-se empregar pás, pinças e descartar em recipiente para perfurocortantes (Grupo E).",
         "NR-32, item 32.2.4.15 e RDC 222/2018",
         "fácil"),
        # 43
        ("Em relação aos dispensers de sabonete líquido e de álcool em gel 70% fixados nas paredes dos setores do hospital:",
         "Devem ser reabastecidos somente após esvaziamento completo, com limpeza e desinfecção periódica do reservatório para evitar contaminação do insumo.",
         "Podem ser completados com água de torneira quando o nível de sabonete estiver abaixo de 20%.",
         "Devem conter sabão em barra coletivo apoiado em saboneteiras com acúmulo de água estagnada.",
         "Devem ser retirados das enfermarias para evitar desperdício de insumos sanitários.",
         "Podem ser abastecidos com desinfetante cremoso de uso doméstico não regulamentado pela ANVISA.",
         "A",
         "Dispensadores de sabonete e antisséptico devem ser higienizados periodicamente; o reabastecimento sobre restos sem higienização favorece a contaminação intrínseca por bactérias.",
         "Boas Práticas ANVISA e NR-32",
         "média"),
        # 44
        ("Durante a punção venosa periférica para coleta de sangue em laboratório da FHCGV, o procedimento técnico de biossegurança preconiza:",
         "Uso de luvas de procedimento descartáveis, higienização prévia das mãos e descarte imediato do conjunto agulha/seringa ou sistema a vácuo em caixa coletora sem reencape.",
         "Reencape imediato da agulha com as duas mãos antes de se levantar da bancada.",
         "Colocação da agulha usada sobre a bancada acolchoada para descarte posterior ao final do turno.",
         "Entrega da seringa com agulha destampada nas mãos do paciente para que ele jogue no lixo.",
         "Retirada das luvas antes da punção para encontrar melhor a veia e descarte no ralo da pia.",
         "A",
         "A punção venosa exige luvas, assepsia prévia, proibição estrita de reencape e descarte imediato do perfurocortante em coletor rígido no ponto de assistência.",
         "NR-32, item 32.2.4.15",
         "fácil"),
        # 45
        ("A NR-32 estabelece que em todo local onde exista a possibilidade de exposição a agentes biológicos, devem ser disponibilizadas aos trabalhadores instruções escritas sobre:",
         "A rotina de solicitação de férias e licenças-prêmio dos servidores estaduais.",
         "A conduta imediata a ser adotada em caso de acidente de trabalho ou incidente envolvendo material biológico humano.",
         "A tabela de preços dos procedimentos particulares cobrados pela ouvidoria hospitalar.",
         "O regulamento eleitoral para escolha do diretor-geral da fundação hospitalar.",
         "A lista de compras de mobiliário administrativo para a diretoria executiva.",
         "B",
         "A NR-32 exige que haja instruções escritas e acessíveis com o fluxo de condutas pós-exposição a material biológico em todos os setores com risco.",
         "NR-32, item 32.2.3.5",
         "média"),
        # 46
        ("A descontaminação de superfícies fixas (mesas de exame, bancadas de laboratório, suportes de soro) contaminadas por matéria orgânica em leitos hospitalares da FHCGV deve ser realizada:",
         "Utilizando desinfetantes de nível intermediário ou baixo aprovados pela ANVISA (ex: álcool a 70% ou compostos clorados), após limpeza prévia com água e detergente.",
         "Apenas soprando ar quente com secador de cabelo por 30 segundos.",
         "Com a aplicação direta de querosene ou óleo diesel para dar brilho ao mobiliário.",
         "Deixando o móvel exposto à chuva no pátio externo do hospital por uma semana.",
         "Lavando a seco com espanador de penas de avestruz sem desinfetante químico.",
         "A",
         "Superfícies hospitalares exigem remoção mecânica prévia de matéria orgânica e posterior fricção com álcool a 70% ou desinfetante padronizado pela CCIH.",
         "Manual de Limpeza de Superfícies ANVISA e NR-32",
         "fácil"),
        # 47
        ("Em relação à higienização das mãos, a técnica correta com água e sabonete para remoção de sujidade e redução de microrganismos deve durar aproximadamente:",
         "De 5 a 10 segundos, molhando apenas as pontas dos dedos indicador e polegar.",
         "De 40 a 60 segundos, friccionando palmas, dorso das mãos, espaços interdigitais, polegares, articulações e punhos.",
         "Exatamente 15 minutos cronometrados com cronômetro cirúrgico digital.",
         "Cerca de 2 segundos, bastando colocar as mãos sob a água corrente sem sabão.",
         "1 hora ininterrupta com escova de cerdas de aço de uso comunitário.",
         "B",
         "Conforme diretrizes da OMS e ANVISA, a higienização com água e sabão dura de 40 a 60 segundos; a fricção antisséptica com álcool em gel dura de 20 a 30 segundos.",
         "Diretrizes ANVISA/OMS e NR-32",
         "fácil"),
        # 48
        ("Caso um trabalhador apresente lesões exsudativas ou dermatite ativa nas mãos, a conduta recomendada pelas diretrizes de saúde ocupacional da NR-32 e PCMSO é:",
         "Obrigar o trabalhador a realizar punções venosas e trocas de curativo sem luvas para cicatrizar com o ar.",
         "Avaliação médica ocupacional com eventual afastamento temporário de atividades de assistência direta a pacientes com risco biológico até a cicatrização da lesão de pele.",
         "Cobrir a lesão aberta com fita isolante industrial e continuar trabalhando normalmente.",
         "Injetar antibióticos diretamente nas feridas no próprio balcão de enfermagem.",
         "Demissão sumária do trabalhador por justa causa médica.",
         "B",
         "Lesões de pele íntegra constituem porta de entrada para patógenos sanguíneos e de transmissão biológica; o trabalhador deve ser avaliado pelo médico do trabalho do SESMT.",
         "NR-32 e NR-07",
         "média"),
        # 49
        ("A respeito do transporte interno de amostras biológicas (tubos de sangue, frascos de urina, biópsias) entre as enfermarias e o laboratório da FHCGV, a NR-32 exige:",
         "Que as amostras sejam carregadas diretamente nas mãos desprotegidas dos estagiários sem apoio.",
         "O uso de caixas térmicas ou recipientes rígidos de transporte impermeáveis, estanques, com tampa e identificados com o símbolo de risco biológico.",
         "Que os tubos fiquem soltos nos bolsos dos jalecos dos maqueiros para amortecer impactos.",
         "O transporte em sacos de compras de supermercado plásticos translúcidos com furos de ventilação.",
         "O transporte exclusivo por drone elétrico através dos corredores do hospital.",
         "B",
         "Amostras biológicas devem ser transportadas em recipientes secundários rígidos, estanques, laváveis, com trava e identificados contra vazamentos em caso de queda.",
         "NR-32, item 32.2.4.13",
         "fácil"),
        # 50
        ("Qual a definição de 'Agente Biológico' adotada pela Norma Regulamentadora nº 32 para fins de aplicação de suas medidas de segurança?",
         "Substâncias puramente químicas minerais com capacidade corrosiva sobre ligas metálicas.",
         "Os microrganismos, geneticamente modificados ou não; as culturas de células; os parasitas; as toxinas e os príons.",
         "Apenas vírus da imunodeficiência humana (HIV) e vírus da hepatite C.",
         "Quaisquer animais vertebrados vivos internados no biotério de pesquisas do hospital.",
         "Poeiras minerais de sílica livre e fibras de amianto respirável em suspensão aérea.",
         "B",
         "Conforme o item 32.2.1.1 da NR-32, consideram-se agentes biológicos os microrganismos (geneticamente modificados ou não), culturas de células, parasitas, toxinas e príons.",
         "NR-32, item 32.2.1.1",
         "fácil"),
    ]
    
    for item in bio_items:
        questions.append({
            "materia": "NR-32",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })

    return questions

if __name__ == '__main__':
    q = get_nr32_questions()
    print(f"NR-32 Bio generated: {len(q)} questions")
