# -*- coding: utf-8 -*-
"""
Gerador de Questões de Legislação do SUS (80 questões)
- Lei 8.080/90: 30 questões
- Lei 8.142/90: 20 questões
- Constituição Federal (Arts. 196 a 200): 20 questões
- PNSST (Decreto 7.602/2011): 10 questões
"""

def get_sus_questions():
    items = [
        # =========================================================
        # 1. LEI 8.080/1990 (30 questões)
        # =========================================================
        # 1
        ("De acordo com o Art. 2º da Lei Orgânica da Saúde (Lei nº 8.080/1990), a saúde é um direito fundamental do ser humano, cabendo ao Estado:",
         "Prover as condições indispensáveis ao seu pleno exercício, mediante políticas econômicas e sociais que visem ao bem-estar físico, mental e social.",
         "Garantir a cura imediata de qualquer doença degenerativa sem necessidade de hospitais.",
         "Restringir o acesso a medicamentos apenas a cidadãos contribuintes da previdência social.",
         "Cobrar copagamento financeiro compulsório por todos os exames laboratoriais realizados.",
         "Transferir integralmente o custeio da saúde pública para as seguradoras de saúde privadas.",
         "A",
         "O Art. 2º da Lei 8.080/90 estabelece que a saúde é direito fundamental do homem, devendo o Estado prover as condições indispensáveis ao seu pleno exercício.",
         "Lei 8.080/90, Art. 2º",
         "fácil"),
        # 2
        ("Conforme o § 2º do Art. 2º da Lei nº 8.080/1990, o dever do Estado de garantir a saúde às pessoas:",
         "Exclui expressamente o dever das pessoas, das famílias, das empresas e da sociedade.",
         "Não exclui o dever das pessoas, da família, das empresas e da sociedade na busca do bem-estar.",
         "Obriga a família a pagar multas se algum parente adoecer.",
         "Isenta completamente as empresas de qualquer encargo com medicina e segurança do trabalho.",
         "Limita-se exclusivamente a vacinar crianças menores de um ano de idade.",
         "B",
         "O Art. 2º, § 2º afirma taxativamente que o dever do Estado não exclui o das pessoas, da família, das empresas e da sociedade.",
         "Lei 8.080/90, Art. 2º, § 2º",
         "fácil"),
        # 3
        ("Os fatores determinantes e condicionantes da saúde expressamente arrolados no Art. 3º da Lei nº 8.080/1990 compreendem, entre outros:",
         "Alimentação, moradia, saneamento básico, meio ambiente, trabalho, renda, educação, atividade física, transporte, lazer e acesso aos bens e serviços essenciais.",
         "Exclusivamente o patrimônio genético herdado dos pais biológicos.",
         "Apenas o número de médicos concursados por quilômetro quadrado.",
         "A pontualidade do pagamento da tarifa de iluminação pública urbana.",
         "A posse de veículos particulares automotores novos.",
         "A",
         "O Art. 3º traz o conceito ampliado de saúde, incluindo alimentação, habitação, saneamento, meio ambiente, trabalho, renda, transporte e lazer como condicionantes da saúde.",
         "Lei 8.080/90, Art. 3º",
         "fácil"),
        # 4
        ("Dentre os objetivos do Sistema Único de Saúde (SUS) elencados no Art. 5º da Lei nº 8.080/1990, inclui-se:",
         "A identificação e divulgação dos fatores condicionantes e determinantes da saúde, a formulação da política de saúde e a assistência às pessoas por intermédio de ações integradas de promoção, proteção e recuperação da saúde.",
         "A comercialização internacional com fins lucrativos de sangue e hemoderivados.",
         "O faturamento de lucro empresarial para remessa ao exterior de capital multinacional.",
         "A garantia de plano de saúde privado vitalício para os servidores da saúde.",
         "A substituição do Poder Judiciário nos julgamentos de acidentes automobilísticos.",
         "A",
         "O Art. 5º da Lei 8.080/90 define os objetivos do SUS: identificação de determinantes, formulação de políticas e assistência integral com promoção, proteção e recuperação.",
         "Lei 8.080/90, Art. 5º",
         "média"),
        # 5
        ("O Art. 6º da Lei nº 8.080/1990 inclui no campo de atuação do Sistema Único de Saúde a execução de ações de:",
         "Vigilância sanitária, vigilância epidemiológica e saúde do trabalhador.",
         "Apenas policiamento militar de fronteiras e controle de trânsito rodoviário.",
         "Fiscalização tributária sobre produtos importados dos países vizinhos.",
         "Construção civil de conjuntos habitacionais e rodovias federais.",
         "Auditoria contábil de bancos comerciais privados.",
         "A",
         "O Art. 6º, I da Lei 8.080/90 inclui no campo de atuação do SUS a execução de ações de vigilância sanitária, epidemiológica, de saúde do trabalhador e de assistência terapêutica integral.",
         "Lei 8.080/90, Art. 6º, I",
         "fácil"),
        # 6
        ("Nos termos do Art. 6º, § 1º da Lei nº 8.080/1990, entende-se por VIGILÂNCIA SANITÁRIA:",
         "Um conjunto de ações capaz de eliminar, diminuir ou prevenir riscos à saúde e de intervir nos problemas sanitários decorrentes do meio ambiente, da produção e circulação de bens e da prestação de serviços de interesse da saúde.",
         "O recolhimento compulsório de tributos municipais sobre imóveis prediais.",
         "A contagem semanal de óbitos provocados por acidentes de moto nas vias urbanas.",
         "O patrulhamento das portas de farmácias por guardas municipais armados.",
         "A apreensão de documentos de identidade de pacientes com doenças transmissíveis.",
         "A",
         "O conceito legal de vigilância sanitária (Art. 6º, § 1º) engloba ações de controle sobre bens, produtos, ambientes e serviços relacionados à saúde humana.",
         "Lei 8.080/90, Art. 6º, § 1º",
         "média"),
        # 7
        ("Conforme o Art. 6º, § 2º da Lei nº 8.080/1990, a VIGILÂNCIA EPIDEMIOLÓGICA é definida como um conjunto de ações que:",
         "Proporciona o conhecimento, a detecção ou prevenção de qualquer mudança nos fatores determinantes e condicionantes de saúde individual ou coletiva, com a finalidade de recomendar e adotar as medidas de prevenção e controle das doenças ou agravos.",
         "Cobra mensalidades escolares em creches públicas municipais.",
         "Fiscaliza o cumprimento da lei seca em bares e casas noturnas da capital.",
         "Emite passaportes internacionais para viagens diplomáticas de urgência.",
         "Determina a demolição sumária de moradias com infiltração de água da chuva.",
         "A",
         "A vigilância epidemiológica reúne dados, detecta surtos, monitora agravos e orienta intervenções sanitárias de controle de doenças na população.",
         "Lei 8.080/90, Art. 6º, § 2º",
         "média"),
        # 8
        ("A Lei nº 8.080/1990 conceitua expressamente a SAÚDE DO TRABALHADOR no Art. 6º, § 3º, como um conjunto de atividades que se destina, através das ações de vigilância epidemiológica e sanitária, à:",
         "Promoção e proteção da saúde dos trabalhadores, assim como visa à recuperação e reabilitação da saúde dos trabalhadores submetidos aos riscos e agravos advindos das condições de trabalho.",
         "Arrecadação de contribuições sindicais compulsórias dos empregados celetistas.",
         "Substituição das gerências de recursos humanos na contratação de estagiários.",
         "Criação de fundos bancários privados de investimentos em ações de risco.",
         "Aplicação de penalidades criminais de prisão a trabalhadores que faltarem ao plantão.",
         "A",
         "A saúde do trabalhador no SUS articula vigilância e assistência para promoção, proteção, recuperação e reabilitação da saúde frente aos riscos do trabalho.",
         "Lei 8.080/90, Art. 6º, § 3º",
         "fácil"),
        # 9
        ("Segundo o Art. 6º, § 3º da Lei nº 8.080/1990, são ações abrangidas no campo da Saúde do Trabalhador, EXCETO:",
         "A assistência ao trabalhador vítima de acidentes de trabalho ou portador de doença profissional e do trabalho.",
         "A participação na normatização, fiscalização e controle das condições de produção, extração, armazenamento, transporte, distribuição e manuseio de substâncias e produtos que apresentem risco à saúde do trabalhador.",
         "A avaliação do impacto que as tecnologias provocam à saúde humana.",
         "A informação ao trabalhador e à sua respectiva entidade sindical a respeito dos riscos de acidentes e doenças a que está exposto.",
         "A cobrança de honorários advocatícios privados pelo SUS em ações trabalhistas movidas contra a empresa.",
         "E",
         "O SUS não cobra honorários nem atua como escritório de advocacia privada em litígios trabalhistas; suas ações são de vigilância, normatização, assistência e informação em SST.",
         "Lei 8.080/90, Art. 6º, § 3º",
         "média"),
        # 10
        ("O princípio do SUS que assegura que todas as pessoas têm direito ao acesso a todos os serviços de saúde em todos os níveis de complexidade, sem discriminação de qualquer natureza, denomina-se:",
         "Universalidade de acesso.",
         "Privatização seletiva.",
         "Descentralização tarifária.",
         "Duplicidade assistencial.",
         "Hierarquização monetária.",
         "A",
         "A universalidade de acesso aos serviços de saúde em todos os níveis de assistência é princípio doutrinário basilar do SUS previsto no Art. 7º, I da Lei 8.080/90.",
         "Lei 8.080/90, Art. 7º, I",
         "fácil"),
        # 11
        ("O princípio da INTEGRALIDADE da assistência, consagrado no Art. 7º, II da Lei nº 8.080/1990, compreende:",
         "Um conjunto articulado e contínuo das ações e serviços preventivos e curativos, individuais e coletivos, exigidos para cada caso em todos os níveis de complexidade do sistema.",
         "A internação compulsória de todo cidadão que complete 65 anos de idade.",
         "O fornecimento apenas de consultas preventivas, sendo o tratamento curativo repassado aos planos privados.",
         "A exclusão de tratamentos de reabilitação e próteses pelo sistema público.",
         "A obrigatoriedade de o paciente realizar todos os procedimentos médicos em um único dia.",
         "A",
         "A integralidade abrange ações preventivas, curativas e de reabilitação, integrando o cuidado do indivíduo em todos os graus de complexidade médica.",
         "Lei 8.080/90, Art. 7º, II",
         "fácil"),
        # 12
        ("A respeito da IGUALDADE na assistência à saúde (Art. 7º, IV da Lei nº 8.080/1990), o texto legal determina expressamente:",
         "A assistência à saúde sem preconceitos ou privilégios de qualquer espécie.",
         "O atendimento preferencial para autoridades públicas e seus parentes consanguíneos.",
         "A triagem de pacientes em filas separadas de acordo com a renda mensal comprovada.",
         "A cobrança de taxa de estacionamento para quem não possui convênio médico.",
         "A dispensa de atendimento a trabalhadores que não residam na capital do estado.",
         "A",
         "A igualdade da assistência à saúde veda privilégios e preconceitos de classe, cor, sexo ou posição social na atenção prestada pelo SUS.",
         "Lei 8.080/90, Art. 7º, IV",
         "fácil"),
        # 13
        ("No que tange à DESCENTRALIZAÇÃO político-administrativa do SUS (Art. 7º, IX da Lei nº 8.080/1990), a sua diretriz orienta:",
         "A concentração de todo o poder decisório e orçamentário exclusivamente em Brasília.",
         "A descentralização com direção única em cada esfera de governo e ênfase na municipalização dos serviços de saúde.",
         "A transferência das decisões de saúde para a Organização das Nações Unidas.",
         "A extinção definitiva das Secretarias Estaduais de Saúde.",
         "A terceirização da gestão do Ministério da Saúde para bancos internacionais.",
         "B",
         "A descentralização do SUS fortalece o município (municipalização) com direção única em cada esfera de governo (União, Estados e Municípios).",
         "Lei 8.080/90, Art. 7º, IX",
         "fácil"),
        # 14
        ("O direito das pessoas assistidas à INFORMAÇÃO sobre sua saúde, garantido no Art. 7º, V da Lei nº 8.080/1990, implica que o paciente ou seu responsável legal tem o direito de:",
         "Saber seu diagnóstico, prognóstico, riscos e objetivos dos tratamentos propostos pela equipe de saúde.",
         "Assumir o controle dos estoques de medicamentos da farmácia hospitalar.",
         "Receber o salário integral do médico responsável pela cirurgia.",
         "Escolher os horários de fiscalização sanitária que a Anvisa deve realizar.",
         "Alterar os dados do prontuário médico de outros pacientes da enfermaria.",
         "A",
         "O direito à informação assegura ao usuário ciência clara sobre seu estado clínico, opções terapêuticas, prognóstico e riscos inerentes aos procedimentos médicos.",
         "Lei 8.080/90, Art. 7º, V",
         "fácil"),
        # 15
        ("Sobre a participação da comunidade na gestão do SUS prevista no Art. 7º, VIII da Lei nº 8.080/1990 e detalhada na Lei nº 8.142/1990, ela ocorre por meio de:",
         "Conferências de Saúde e Conselhos de Saúde em cada esfera de governo.",
         "Eleição direta de diretores hospitalares por sufrágio universal de todos os moradores do bairro.",
         "Sorteio lotérico federal de representantes comissionados.",
         "Petições anônimas em redes sociais sem valor jurídico institucional.",
         "Proibição de qualquer participação popular nas reuniões orçamentárias.",
         "A",
         "A participação comunitária institucionaliza-se nas Conferências e Conselhos de Saúde, instâncias colegiadas do SUS em nível federal, estadual e municipal.",
         "Lei 8.080/90, Art. 7º, VIII e Lei 8.142/90",
         "fácil"),
        # 16
        ("Em relação à DIREÇÃO ÚNICA do SUS em cada esfera de governo (Art. 9º da Lei nº 8.080/1990), assinale a correlação CORRETA entre a esfera e seu órgão gestor:",
         "Na União: Ministério da Saúde; nos Estados e DF: Secretaria de Estado da Saúde; nos Municípios: Secretaria Municipal de Saúde ou órgão equivalente.",
         "Na União: Forças Armadas; nos Estados: Tribunal de Justiça; nos Municípios: Câmara de Vereadores.",
         "Na União: Banco Central; nos Estados: Detran; nos Municípios: Guarda Municipal.",
         "Na União: Conselho Federal de Farmácia; nos Estados: Cruz Vermelha; nos Municípios: Lions Clube.",
         "Em todas as esferas simultaneamente: a Diretoria-Geral da OIT.",
         "A",
         "O SUS possui direção única em cada esfera de governo: Ministério da Saúde na União, Secretaria Estadual no Estado/DF e Secretaria Municipal no Município.",
         "Lei 8.080/90, Art. 9º",
         "fácil"),
        # 17
        ("As Comissões Intergestores Bipartite (CIB) e Tripartite (CIT), reconhecidas na Lei nº 8.080/1990 e no Decreto nº 7.508/2011, são espaços de:",
         "Negociação e pactuação consensual entre os gestores das diferentes esferas governamentais sobre aspectos operacionais do SUS.",
         "Julgamento de crimes comuns com aplicação de penas de reclusão a infratores de trânsito.",
         "Cobrança coercitiva de impostos prediais em atraso de empresas privadas.",
         "Leilão público de hospitais filantrópicos deficitários.",
         "Disputa esportiva anual entre os servidores da administração direta.",
         "A",
         "A CIT (União, Estados e Municípios) e as CIBs (Estados e Municípios) são fóruns de pactuação federativa e gestão compartilhada das diretrizes do SUS.",
         "Lei 8.080/90 e Decreto 7.508/2011",
         "média"),
        # 18
        ("Conforme o Art. 17 da Lei nº 8.080/1990, compete especificamente à Direção Estadual do SUS (Secretaria de Estado de Saúde do Pará - SESPA), em relação à FHCGV e hospitais estaduais:",
         "Acompanhar, controlar e avaliar as redes hierarquizadas do SUS e gerir e executar serviços públicos de saúde de referência estadual ou regional.",
         "Definir a política monetária cambial e a taxa de juros do país.",
         "Nomear os juízes federais de primeiro grau da comarca de Belém.",
         "Emitir passaportes para cidadãos estrangeiros que visitam a Amazônia.",
         "Extinguir todas as normas de segurança do trabalho baixadas pelo Ministério do Trabalho.",
         "A",
         "À direção estadual cabe coordenar e gerir serviços de alta complexidade e referência regional/estadual, como os hospitais estaduais (ex: FHCGV).",
         "Lei 8.080/90, Art. 17",
         "média"),
        # 19
        ("Segundo o Art. 18 da Lei nº 8.080/1990, a execução dos serviços de vigilância sanitária e epidemiológica e das ações de saúde do trabalhador no âmbito local compete precipuamente à direção:",
         "Municipal do SUS (Secretarias Municipais de Saúde).",
         "Exclusiva da Organização Mundial da Saúde sediada na Suíça.",
         "Do Ministério da Fazenda em conjunto com a Receita Federal.",
         "Das empresas petrolíferas concessionárias de blocos marítimos.",
         "Do Supremo Tribunal Federal em sessão plenária extraordinária.",
         "A",
         "A gestão executiva e direta das ações de vigilância epidemiológica, sanitária e saúde do trabalhador no território local é competência municipal do SUS.",
         "Lei 8.080/90, Art. 18, IV",
         "fácil"),
        # 20
        ("Sobre a participação complementar da rede privada no Sistema Único de Saúde (Arts. 24 a 26 da Lei nº 8.080/1990):",
         "O SUS pode recorrer aos serviços prestados pela iniciativa privada quando as suas disponibilidades forem insuficientes para garantir a assistência integral à população de uma região.",
         "Os hospitais privados podem cobrar do paciente atendido pelo SUS uma taxa extra em dinheiro.",
         "Os serviços privados conveniados passam a ditar as diretrizes ideológicas do Ministério da Saúde.",
         "A contratação de serviços privados é obrigatória mesmo se a rede pública tiver 100% de leitos ociosos.",
         "A rede pública fica proibida de atender pacientes que possuam renda formal superior a 2 salários mínimos.",
         "A",
         "A iniciativa privada participa do SUS em caráter complementar mediante contrato público ou convênio quando as unidades públicas forem insuficientes.",
         "Lei 8.080/90, Art. 24",
         "fácil"),
        # 21
        ("Na celebração de contratos ou convênios para participação complementar no SUS (Art. 25 da Lei nº 8.080/1990), terão preferência:",
         "As entidades filantrópicas e as sem fins lucrativos.",
         "As clínicas particulares com fins lucrativos de maior capital social.",
         "As corporações hospitalares com sede em paraísos fiscais.",
         "Os laboratórios farmacêuticos que pagarem comissão aos diretores de compras.",
         "As empresas de seguro de saúde estrangeiras.",
         "A",
         "A Constituição e a Lei 8.080/90 dão preferência explícita às entidades filantrópicas e às sem fins lucrativos na celebração de convênios com o SUS.",
         "Lei 8.080/90, Art. 25 e CF/88 Art. 199, § 1º",
         "fácil"),
        # 22
        ("O Art. 26 da Lei nº 8.080/1990 estipula que os critérios, valores e formas de remuneração de serviços e procedimentos da assistência complementar contratada no SUS são fixados pelo:",
         "Conselho Nacional de Saúde, aprovados pela Direção Nacional do SUS (Ministério da Saúde).",
         "Presidente do sindicato patronal dos hospitais privados lucrativos.",
         "Gerente de câmbio da Bolsa de Valores de São Paulo.",
         "Paciente no momento de sua alta médica com base em sua satisfação subjetiva.",
         "Ministério do Planejamento sem ouvir nenhum órgão do setor de saúde.",
         "A",
         "A tabela de remuneração de serviços conveniados ao SUS é fixada pela direção nacional do SUS com aprovação do Conselho Nacional de Saúde.",
         "Lei 8.080/90, Art. 26",
         "média"),
        # 23
        ("É VEDADA expressamente pela Lei nº 8.080/1990 e pela Constituição Federal a destinação de recursos públicos para:",
         "Auxílios ou subvenções a instituições privadas com fins lucrativos na área da saúde.",
         "A compra de medicamentos essenciais pelo Ministério da Saúde.",
         "O pagamento de salários de médicos e enfermeiros concursados do SUS.",
         "A reforma estrutural de leitos de UTI em hospitais públicos estaduais.",
         "O treinamento de técnicos de segurança do trabalho no âmbito do SUS.",
         "A",
         "É terminantemente proibida a destinação de verbas públicas para auxílios ou subvenções a entidades com fins lucrativos (CF/88 Art. 199, § 2º e Lei 8.080/90).",
         "Lei 8.080/90 e CF/88 Art. 199, § 2º",
         "fácil"),
        # 24
        ("A respeito da política de recursos humanos na área da saúde no âmbito do SUS (Art. 27 a 30 da Lei nº 8.080/1990):",
         "Os serviços públicos que integram o SUS constituem campo de prática para ensino e pesquisa mediante normas específicas elaboradas em conjunto com o setor de educação.",
         "Os hospitais públicos são proibidos de receber estagiários de enfermagem ou medicina.",
         "A admissão de servidores deve ser feita exclusivamente por indicação política de vereadores locais sem concurso.",
         "Os planos de carreira, cargos e salários são considerados proibidos pelo ordenamento sanitário.",
         "A qualificação profissional deve ser custeada individualmente sem apoio institucional do SUS.",
         "A",
         "Os estabelecimentos do SUS atuam como campo de prática e integração docente-assistencial para formação de recursos humanos da saúde (Art. 27 da Lei 8.080/90).",
         "Lei 8.080/90, Art. 27",
         "fácil"),
        # 25
        ("De acordo com o Art. 33 da Lei nº 8.080/1990, os recursos financeiros do Sistema Único de Saúde (SUS) serão depositados em conta especial, em cada esfera de fixação, e movimentados sob a fiscalização do respectivo:",
         "Conselho de Saúde.",
         "Comitê de trânsito rodoviário.",
         "Clube esportivo de futebol regional.",
         "Sindicato dos lojistas da capital.",
         "Juizado de pequenas causas imobiliárias.",
         "A",
         "Os Fundos de Saúde têm seus recursos movimentados sob a fiscalização e controle deliberativo do respectivo Conselho de Saúde.",
         "Lei 8.080/90, Art. 33",
         "fácil"),
        # 26
        ("A assistência farmacêutica no SUS (Lei nº 8.080/1990, com as alterações da Lei nº 12.401/2011) compreende a dispensação de medicamentos constantes da Relação Nacional de Medicamentos Essenciais (RENAME) baseada em:",
         "Evidências científicas de eficácia, acurácia, efetividade e segurança, além de avaliação econômica comparativa.",
         "Indicações de influenciadores digitais e postagens em redes sociais não científicas.",
         "Preço mais alto do remédio, comprando-se obrigatoriamente a opção mais cara do mercado.",
         "Sorteio aleatório mensal de substâncias químicas em audiência pública.",
         "Exclusivamente produtos homeopáticos sem aprovação de registro na ANVISA.",
         "A",
         "A incorporação e oferta de tecnologias e medicamentos no SUS é regulada pela CONITEC, exigindo estudos científicos de custo-efetividade e segurança.",
         "Lei 8.080/90, Art. 19-Q (incluído pela Lei 12.401/2011)",
         "média"),
        # 27
        ("Nos termos da Lei nº 8.080/1990, os serviços de saúde do trabalhador nos órgãos do SUS têm a prerrogativa legal de:",
         "Notificar os acidentes de trabalho e investigar os ambientes e processos de trabalho, inclusive propondo interdições e medidas corretivas às autoridades competentes.",
         "Determinar a falência comercial da empresa sem decisão do Poder Judiciário.",
         "Confiscar a mercadoria produzida pela fábrica para venda particular na feira.",
         "Obrigar a demissão de gerentes de recursos humanos de empresas privadas.",
         "Criar impostos sobre o consumo de energia elétrica das indústrias.",
         "A",
         "A vigilância em saúde do trabalhador no SUS inspeciona ambientes laborais, investiga agravos e acidentes e adota medidas sanitárias de proteção.",
         "Lei 8.080/90, Art. 6º, § 3º",
         "média"),
        # 28
        ("A articulação das políticas e planos de saúde com as políticas de saneamento básico e de meio ambiente pelo SUS (Art. 12 da Lei nº 8.080/1990) decorre do fato de que:",
         "A salubridade ambiental e o saneamento são determinantes diretos na prevenção de endemias, parasitoses e agravos à saúde humana.",
         "O Ministério da Saúde é responsável pelo asfaltamento de ruas e construção de viadutos.",
         "Os médicos do SUS precisam lavar as ruas com água tratada após cada consulta.",
         "As Secretarias de Saúde devem arrecadar as contas de água dos imóveis residenciais.",
         "O esgoto a céu aberto é considerado elemento decorativo pelo planejamento urbano.",
         "A",
         "O saneamento básico e o meio ambiente equilibrado são condições estruturantes para redução de doenças transmissíveis e promoção da saúde coletiva.",
         "Lei 8.080/90, Art. 12 e Art. 3º",
         "fácil"),
        # 29
        ("A descentralização das ações de saúde do trabalhador para a rede básica e os Centros de Referência em Saúde do Trabalhador (CEREST) no SUS visa garantir:",
         "A atenção especializada, retaguarda técnica e vigilância dos agravos ocupacionais em trabalhadores formais, informais e rurais no território.",
         "A cobrança de imposto de renda sobre as horas extras dos técnicos de segurança.",
         "A emissão de carteiras de habilitação nacional de motorista.",
         "A realização de vistorias automotivas de ônibus interestaduais.",
         "A dispensa do uso de EPIs em todas as indústrias do estado.",
         "A",
         "A Rede Nacional de Atenção Integral à Saúde do Trabalhador (RENAST) e os CERESTs estruturam as ações de vigilância e assistência a todos os trabalhadores.",
         "Portaria de Consolidação GM/MS nº 2/2017 e Lei 8.080/90",
         "média"),
        # 30
        ("Em relação à capacidade resolutiva dos serviços de saúde em todos os níveis de assistência (Art. 7º, XII da Lei nº 8.080/1990), essa diretriz impõe que:",
         "Cada unidade de saúde deve ser capaz de solucionar os problemas de saúde da população no seu respectivo nível de competência ou encaminhar com garantia de fluxo ordenado para referência.",
         "O paciente com dor de cabeça simples deve ser submetido obrigatoriamente a cirurgia no cérebro no mesmo dia.",
         "Os postos de saúde de atenção básica devam fechar às 10 horas da manhã todos os dias.",
         "O hospital de alta complexidade atenda unicamente pacientes particulares pagantes.",
         "A população resolva seus próprios problemas médicos sem auxílio de profissionais diplomados.",
         "A",
         "A resolutividade significa a capacidade dos serviços de responder de forma eficiente aos problemas apresentados ou garantir contrarreferência qualificada.",
         "Lei 8.080/90, Art. 7º, XII",
         "fácil"),

        # =========================================================
        # 2. LEI 8.142/1990 (20 questões)
        # =========================================================
        # 31
        ("A Lei Federal nº 8.142/1990 dispõe essencialmente sobre dois grandes pilares da estruturação do Sistema Único de Saúde:",
         "A participação da comunidade na gestão do SUS e as transferências intergovernamentais de recursos financeiros na área da saúde.",
         "O código de trânsito brasileiro e a segurança em autoestradas.",
         "O plano de carreiras exclusivo dos diplomatas do Itamaraty.",
         "A privatização completa das Santas Casas de Misericórdia.",
         "A taxa de importação de insumos bélicos pelas Forças Armadas.",
         "A",
         "A ementa da Lei 8.142/90 define que ela dispõe sobre a participação da comunidade na gestão do SUS e sobre as transferências de recursos na saúde.",
         "Lei 8.142/90, Ementa",
         "fácil"),
        # 32
        ("Quais são as duas instâncias colegiadas previstas no Art. 1º da Lei nº 8.142/1990 que garantem a participação da comunidade na gestão do SUS em cada esfera de governo?",
         "A Conferência de Saúde e o Conselho de Saúde.",
         "O Congresso Nacional e o Supremo Tribunal Federal.",
         "A Câmara Municipal e o Tribunal de Contas do Estado.",
         "O Sindicato dos Bancários e a Federação das Indústrias.",
         "O Conselho Tutelar e a Vara da Infância e da Juventude.",
         "A",
         "O Art. 1º da Lei 8.142/90 institui duas instâncias colegiadas: a Conferência de Saúde e o Conselho de Saúde, existentes em âmbito nacional, estadual e municipal.",
         "Lei 8.142/90, Art. 1º",
         "fácil"),
        # 33
        ("A CONFERÊNCIA DE SAÚDE, de acordo com o Art. 1º, § 1º da Lei nº 8.142/1990, reúne-se ordinariamente:",
         "A cada quatro anos, com a representação dos vários segmentos sociais, para avaliar a situação de saúde e propor as diretrizes para a formulação da política de saúde.",
         "Mensalmente para homologar os balanços financeiros da farmácia popular.",
         "A cada dez anos exclusivamente na capital federal sem representantes dos estados.",
         "Apenas quando ocorrer uma pandemia mundial oficialmente declarada.",
         "Semanalmente com quórum exclusivo de prefeitos municipais.",
         "A",
         "A Conferência de Saúde reúne-se a cada quatro anos com ampla participação social para avaliar o cenário sanitário e traçar diretrizes da política de saúde.",
         "Lei 8.142/90, Art. 1º, § 1º",
         "fácil"),
        # 34
        ("O CONSELHO DE SAÚDE, nos termos do Art. 1º, § 2º da Lei nº 8.142/1990, caracteriza-se por ser um órgão colegiado de caráter:",
         "Permanente e deliberativo, composto por representantes do governo, prestadores de serviço, profissionais de saúde e usuários.",
         "Temporário e apenas consultivo, extinto automaticamente após 30 dias de funcionamento.",
         "Exclusivamente militar e subordinado ao comando do Exército.",
         "Remunerado com jetons de R$ 50.000,00 mensais para cada conselheiro.",
         "Composto exclusivamente por proprietários de planos de saúde privados.",
         "A",
         "O Conselho de Saúde tem caráter permanente e deliberativo, formulando estratégias e controlando a execução da política de saúde, inclusive nos aspectos econômicos.",
         "Lei 8.142/90, Art. 1º, § 2º",
         "fácil"),
        # 35
        ("Qual é a composição da representação dos USUÁRIOS nos Conselhos e Conferências de Saúde estabelecida pelo Art. 1º, § 4º da Lei nº 8.142/1990 e regulamentada pela Resolução CNS nº 453/2012?",
         "Paritária em relação ao conjunto dos demais segmentos (50% de usuários e 50% divididos entre governo, prestadores e profissionais de saúde).",
         "Restrita a 5% das vagas, sem direito a voz nem voto nas reuniões.",
         "100% composta apenas por pacientes internados em leitos de UTI.",
         "Apenas 1 usuário sorteado pelo número da carteira de trabalho.",
         "Usuários não têm direito a participar, apenas médicos diplomados com mestrado.",
         "A",
         "A representação dos usuários nos Conselhos e Conferências de Saúde é paritária em relação ao conjunto dos demais segmentos (50% de representantes dos usuários).",
         "Lei 8.142/90, Art. 1º, § 4º e Resolução CNS 453/2012",
         "fácil"),
        # 36
        ("As decisões tomadas pelo Conselho de Saúde no exercício de suas competências legais devem ser:",
         "Homologadas pelo chefe do poder legalmente constituído em cada esfera de governo (Ministro da Saúde, Governador ou Prefeito).",
         "Enviadas para aprovação prévia embaixada dos Estados Unidos da América.",
         "Ignoradas pelo poder público caso envolvam investimentos em saneamento básico.",
         "Publicadas apenas em jornais de língua inglesa de circulação internacional.",
         "Submetidas a referendo popular a cada 30 dias com voto obrigatório.",
         "A",
         "As deliberações do Conselho de Saúde são homologadas pelo chefe do Poder Executivo em cada esfera de governo no prazo regulamentar.",
         "Lei 8.142/90, Art. 1º, § 2º",
         "média"),
        # 37
        ("Os recursos do Fundo Nacional de Saúde (FNS) destinados a despesas de custeio e de capital dos serviços de saúde dos Estados e Municípios são repassados:",
         "De forma regular e automática, diretamente do Fundo Nacional de Saúde para os Fundos Estaduais e Municipais de Saúde (transferência fundo a fundo).",
         "Apenas mediante empréstimo bancário com taxa de juros do mercado comercial.",
         "Em cheques nominais entregues pessoalmente aos líderes partidários da Câmara.",
         "Somente se os municípios aceitarem pagar taxa de pedágio em todas as estradas vicinais.",
         "Através de sorteio anual transmitido pela emissora pública de televisão.",
         "A",
         "A transferência de recursos federais para Estados e Municípios ocorre de modo regular e automático (fundo a fundo), independentemente de convênios.",
         "Lei 8.142/90, Art. 3º e LC 141/2012",
         "média"),
        # 38
        ("Para que os Estados, o Distrito Federal e os Municípios recebam os repasses de recursos do Fundo Nacional de Saúde (FNS) previstos na Lei nº 8.142/1990, o Art. 4º exige a comprovação dos seguintes requisitos, EXCETO:",
         "Fundo de Saúde constituído e Plano de Saúde aprovado.",
         "Conselho de Saúde em funcionamento com composição paritária.",
         "Relatórios de gestão que permitam o controle e fiscalização das ações.",
         "Contrapartida de recursos para a saúde no respectivo orçamento.",
         "Construção obrigatória de heliporto particular na residência do prefeito municipal.",
         "E",
         "A exigência de heliporto é absurda. Os requisitos do Art. 4º são: Fundo, Conselho, Plano de Saúde, Relatórios de gestão, contrapartida orçamentária e Comissão para PCCS.",
         "Lei 8.142/90, Art. 4º",
         "fácil"),
        # 39
        ("O que ocorre com os recursos federais do SUS caso um Município NÃO cumpra os requisitos exigidos pelo Art. 4º da Lei nº 8.142/1990 (como não possuir Conselho de Saúde atuante)?",
         "Os recursos são automaticamente desviados para a construção de estádios de futebol.",
         "Os recursos serão administrados pelo respectivo Estado até que o Município regularize a situação exigida por lei.",
         "Os moradores do município perdem a nacionalidade brasileira.",
         "O município é obrigado a demitir todos os servidores da área da educação.",
         "Os recursos são extintos e queimados pelo Banco Central do Brasil.",
         "B",
         "O parágrafo único do Art. 4º prevê que, no caso de não atendimento dos requisitos pelo Município, os recursos passarão a ser administrados pelo Estado da Federação correspondente.",
         "Lei 8.142/90, Art. 4º, Parágrafo Único",
         "média"),
        # 40
        ("A participação popular na gestão do SUS por meio dos Conselhos de Saúde exerce o controle social sobre:",
         "Apenas as escalas de plantão de finais de semana dos maqueiros do hospital.",
         "As políticas de saúde implementadas, a alocação e execução de recursos financeiros, o plano de saúde e os relatórios de gestão do gestor público.",
         "As compras particulares de alimentos dos servidores fora do hospital.",
         "A cor das cortinas das enfermarias e os tipos de flores plantadas no jardim.",
         "A concessão de aposentadorias de servidores de outros ministérios federais.",
         "B",
         "O controle social nos Conselhos fiscaliza a formulação de diretrizes, execução de metas e gastos financeiros em saúde da respectiva esfera de governo.",
         "Lei 8.142/90 e Resolução CNS 453/2012",
         "fácil"),
        # 41
        ("Em relação à convocação extraordinária da Conferência de Saúde pelo Conselho de Saúde (Art. 1º, § 1º da Lei nº 8.142/1990):",
         "O Conselho de Saúde pode convocar a Conferência extraordinariamente se o Poder Executivo não o fizer no prazo legal.",
         "Apenas o Presidente da República pode convocar conferências municipais de saúde.",
         "A Conferência extraordinária só pode ocorrer em anos bissextos.",
         "O Conselho de Saúde não tem qualquer poder de convocação sob pena de crime de responsabilidade.",
         "A realização de conferências de saúde extraordinárias foi revogada pela Constituição.",
         "A",
         "As Conferências são convocadas pelo Poder Executivo ou, extraordinariamente, pelo Conselho de Saúde.",
         "Lei 8.142/90, Art. 1º, § 1º",
         "média"),
        # 42
        ("Qual é a composição percentual recomendada pelo Conselho Nacional de Saúde (Resolução nº 453/2012) para os membros dos Conselhos de Saúde?",
         "50% de entidades e movimentos de usuários, 25% de entidades de trabalhadores de saúde e 25% de representação de governo e prestadores de serviços de saúde privados conveniados/filantrópicos.",
         "70% de empresários de planos privados, 20% de políticos e 10% de militares.",
         "100% de médicos especialistas com título de doutorado universitário.",
         "25% de usuários e 75% de secretários municipais comissionados.",
         "50% de farmacêuticos industriais e 50% de auditores da Receita Estadual.",
         "A",
         "A estrutura do Conselho de Saúde obedece à paridade: 50% Usuários, 25% Trabalhadores de Saúde e 25% Gestores/Prestadores de Serviços de Saúde.",
         "Resolução CNS nº 453/2012 e Lei 8.142/90",
         "fácil"),
        # 43
        ("A função de Conselheiro de Saúde (titular ou suplente) no âmbito do SUS é considerada:",
         "Atividade remunerada com salário fixo mensal pago pelo Fundo de Saúde.",
         "Serviço público relevante, não remunerado, gerando presunção de idoneidade moral aos seus membros.",
         "Cargo vitalício de provimento em comissão sem possibilidade de substituição.",
         "Incompatível com qualquer atividade profissional privada do cidadão.",
         "Função restrita exclusivamente a advogados inscritos na OAB.",
         "B",
         "A atuação como membro de Conselho de Saúde não é remunerada; seu exercício é considerado serviço público de relevante valor social e cívico.",
         "Lei 8.142/90 e Resolução CNS 453/2012",
         "fácil"),
        # 44
        ("O Plano de Saúde, exigido como condição pelo Art. 4º da Lei nº 8.142/1990 para recebimento de repasses fundo a fundo:",
         "É o instrumento básico de planejamento governamental que define as diretrizes, prioridades e metas da política de saúde para um período de quatro anos (quadrienal).",
         "É a carteirinha de plástico azul vendida aos servidores públicos municipais.",
         "É uma apólice de seguro de vida contratada em banco particular pelos funcionários.",
         "É a relação de telefones úteis dos médicos plantonistas do pronto-socorro.",
         "É o cardápio semanal servido aos pacientes internados nas enfermarias.",
         "A",
         "O Plano de Saúde é a peça central do planejamento governamental na saúde, orientando prioridades, programas e recursos no horizonte de 4 anos.",
         "Lei 8.142/90, Art. 4º e Portaria de Consolidação 1/2017",
         "fácil"),
        # 45
        ("Sobre o Relatório Anual de Gestão (RAG) no âmbito do SUS fiscalizado pelos Conselhos de Saúde:",
         "Trata-se de instrumento que apresenta os resultados físicos e orçamentários alcançados pela gestão frente às metas fixadas na Programação Anual de Saúde.",
         "É uma lista de funcionários demitidos durante o ano civil.",
         "É um documento secreto que não pode ser divulgado para a população.",
         "É emitido a cada 50 anos pelo Senado Federal.",
         "Substitui a necessidade de prestar contas aos Tribunais de Contas do Estado.",
         "A",
         "O Relatório Anual de Gestão (RAG) comprova o cumprimento das diretrizes do Plano de Saúde e a aplicação orçamentária dos recursos do SUS no exercício anual.",
         "Lei 8.142/90 e Lei Complementar 141/2012",
         "média"),
        # 46
        ("A participação dos Técnicos de Segurança do Trabalho e demais profissionais da área ocupacional nos Conselhos de Saúde é garantida pelo segmento de:",
         "Trabalhadores da saúde (que compõem 25% da estrutura paritária do conselho).",
         "Prestadores privados com fins lucrativos exclusivamente.",
         "Governo e gestores estaduais em cota pessoal única.",
         "Auditoria externa independente da União Europeia.",
         "Conselheiros vitalícios de honra com direito a veto.",
         "A",
         "Os profissionais que atuam nos serviços de saúde (incluindo trabalhadores do SESMT e categorias profissionais da saúde) compõem a cota de 25% dos Trabalhadores.",
         "Resolução CNS nº 453/2012 e Lei 8.142/90",
         "média"),
        # 47
        ("As reuniões ordinárias dos Conselhos de Saúde nos Municípios e Estados da Federação devem ser:",
         "Públicas, com pauta divulgada previamente e atas registradas e disponibilizadas para consulta da sociedade.",
         "Secretas, realizadas na calada da noite com proibição de gravação de áudio ou vídeo.",
         "Exclusivas para membros filiados ao partido do governador em exercício.",
         "Fechadas com seguranças armados impedindo o acesso de qualquer cidadão.",
         "Realizadas apenas por correspondência postal sem debates presenciais.",
         "A",
         "O princípio da publicidade e da transparência rege o funcionamento dos Conselhos de Saúde, cujas sessões são abertas ao público e às entidades comunitárias.",
         "Resolução CNS 453/2012 e Lei 8.142/90",
         "fácil"),
        # 48
        ("Qual a importância da Lei nº 8.142/1990 para a consolidação democrática do SUS após os vetos presidenciais ocorridos na Lei nº 8.080/1990?",
         "Ela restaurou juridicamente a participação popular na gestão do sistema e garantiu os repasses automáticos federais aos Estados e Municípios.",
         "Ela revogou todos os artigos da Constituição Federal que tratavam de saúde pública.",
         "Ela extinguiu o Ministério da Saúde e criou uma agência reguladora multinacional.",
         "Ela proibiu os cidadãos de exigirem exames gratuitos em hospitais do SUS.",
         "Ela determinou a cobrança de mensalidade de todos os estudantes de faculdades públicas de medicina.",
         "A",
         "A Lei 8.142/90 foi sancionada justamente para resgatar os temas vetados no texto da Lei 8.080/90, institucionalizando os Conselhos, Conferências e repasses automáticos fundo a fundo.",
         "Contexto Histórico do SUS e Lei 8.142/90",
         "média"),
        # 49
        ("A Comissão Intersetorial de Saúde do Trabalhador e da Trabalhadora (CISTT), vinculada aos Conselhos de Saúde, tem por atribuição principal:",
         "Assessorar o Conselho de Saúde na formulação de políticas, planos e fiscalização das ações voltadas à saúde do trabalhador no território.",
         "Comprar uniformes para as bandas marciais das escolas municipais.",
         "Prender empregadores que atrasarem o salário dos trabalhadores rurais.",
         "Substituir o INSS na concessão de pensões por morte aos dependentes.",
         "Vender medicamentos genéricos com desconto aos associados do sindicato.",
         "A",
         "A CISTT é comissão intersetorial obrigatória nos Conselhos de Saúde para subsidiar o controle social nas pautas de saúde do trabalhador e meio ambiente laboral.",
         "Lei 8.080/90, Art. 13 e Lei 8.142/90",
         "média"),
        # 50
        ("Em relação à destinação dos recursos repassados aos Municípios pelo Fundo Nacional de Saúde, a Lei nº 8.142/1990 (Art. 3º) determina que:",
         "Pelo menos 70% desses recursos serão destinados aos Municípios, de acordo com critérios populacionais, perfil demográfico, epidemiológico e rede instalada.",
         "100% dos recursos devem ser devolvidos para o Tesouro Nacional ao final de cada semana.",
         "A totalidade dos recursos deve ser usada para pagar juros da dívida externa do governo federal.",
         "Os recursos só podem ser gastos se o prefeito obtiver autorização de embaixadas estrangeiras.",
         "Os recursos são incorporados à folha de pagamento de servidores do Poder Judiciário.",
         "A",
         "O Art. 3º da Lei 8.142/90 fixou a descentralização financeira com foco nos municípios, com base em critérios epidemiológicos, populacionais e de rede física instalada.",
         "Lei 8.142/90, Art. 3º",
         "difícil"),

        # =========================================================
        # 3. CONSTITUIÇÃO FEDERAL DE 1988 (ARTS. 196 A 200) (20 questões)
        # =========================================================
        # 51
        ("O Artigo 196 da Constituição Federal de 1988 estabelece que a saúde é:",
         "Direito de todos e dever do Estado, garantido mediante políticas sociais e econômicas que visem à redução do risco de doença e de outros agravos e ao acesso universal e igualitário às ações e serviços para sua promoção, proteção e recuperação.",
         "Um benefício opcional concedido unicamente a quem contribui com a previdência social há mais de 30 anos.",
         "Uma mercadoria comercial sujeita unicamente às leis da oferta e da procura de mercado livre.",
         "Responsabilidade exclusiva do indivíduo, não possuindo o Estado qualquer obrigação sanitária.",
         "Direito restrito a crianças e idosos com renda familiar comprovada inferior a meio salário mínimo.",
         "A",
         "O Art. 196 da CF/88 é a cláusula pétrea doutrinária do SUS: saúde como direito de todos e dever do Estado, com acesso universal e igualitário.",
         "CF/88, Art. 196",
         "fácil"),
        # 52
        ("Nos termos do Art. 197 da Constituição Federal, as ações e serviços de saúde são considerados:",
         "De relevância pública, cabendo ao Poder Público dispor, nos termos da lei, sobre sua regulamentação, fiscalização e controle.",
         "De interesse estritamente privado, sem qualquer direito de intervenção do poder estatal.",
         "Atividades clandestinas toleradas excepcionalmente em períodos de guerra civil.",
         "Exclusivas de organizações não governamentais sediadas no exterior.",
         "Isentas de qualquer fiscalização sanitária ou controle epidemiológico.",
         "A",
         "O Art. 197 da CF/88 define as ações e serviços de saúde como de relevância pública, sujeitos à regulação, fiscalização e controle estatais.",
         "CF/88, Art. 197",
         "fácil"),
        # 53
        ("A execução das ações e serviços de saúde, conforme previsto no Art. 197 da Constituição Federal, deve ser feita:",
         "Diretamente pelo Poder Público ou através de terceiros e, também, por pessoa física ou jurídica de direito privado.",
         "Exclusivamente por hospitais militares das forças armadas da União.",
         "Apenas por médicos estrangeiros sem diploma validado no território nacional.",
         "Unicamente por seguradoras multinacionais de previdência complementar.",
         "Sem qualquer tipo de contrato ou termo de compromisso público.",
         "A",
         "A execução dos serviços de saúde pode ser direta (pelo próprio Estado) ou indireta (através de terceiros e rede privada complementar).",
         "CF/88, Art. 197",
         "média"),
        # 54
        ("O Art. 198 da CF/88 determina que as ações e serviços públicos de saúde integram uma rede regionalizada e hierarquizada e constituem um sistema único, organizado segundo as seguintes DIRETRIZES:",
         "Descentralização, com direção única em cada esfera de governo; Atendimento integral, com prioridade para as atividades preventivas, sem prejuízo dos serviços assistenciais; e Participação da comunidade.",
         "Centralização no Ministério da Saúde, foco no atendimento curativo hospitalar e exclusão da sociedade civil.",
         "Privatização progressiva dos hospitais, copagamento de consultas e militarização da vigilância.",
         "Regionalização sem conexão federativa, atendimento apenas terciário e direção compartilhada por comissões anônimas.",
         "Eliminação das unidades básicas de saúde em favor de policlínicas privadas multinacionais.",
         "A",
         "As três diretrizes constitucionais expressas no Art. 198 da CF/88 são: Descentralização, Atendimento Integral (com prioridade preventiva) e Participação da Comunidade.",
         "CF/88, Art. 198",
         "fácil"),
        # 55
        ("Na diretriz constitucional do ATENDIMENTO INTEGRAL (Art. 198, II da CF/88), a Constituição dá expressa prioridade para:",
         "As atividades preventivas, sem prejuízo dos serviços assistenciais.",
         "As cirurgias plásticas meramente estéticas para celebridades.",
         "A distribuição de remédios importados de alto custo sem prescrição médica.",
         "O atendimento nos leitos de hotelaria cinco estrelas dos hospitais privados.",
         "A realização de exames sofisticados de ressonância magnética para qualquer queixa clínica.",
         "A",
         "O Art. 198, II da CF/88 estipula atendimento integral 'com prioridade para as atividades preventivas, sem prejuízo dos serviços assistenciais'.",
         "CF/88, Art. 198, II",
         "fácil"),
        # 56
        ("A Emenda Constitucional nº 29/2000 (regulamentada pela Lei Complementar nº 141/2012) vinculou recursos orçamentários mínimos obrigatórios para o financiamento da saúde. Os percentuais mínimos da receita corrente de impostos a serem aplicados pelos ESTADOS e pelos MUNICÍPIOS são, respectivamente:",
         "12% para os Estados e 15% para os Municípios.",
         "5% para os Estados e 5% para os Municípios.",
         "25% para os Estados e 35% para os Municípios.",
         "50% para os Estados e 10% para os Municípios.",
         "Não há qualquer limite mínimo percentual na legislação brasileira.",
         "A",
         "Pela LC 141/2012 e CF/88 Art. 198, § 2º, os Estados devem aplicar no mínimo 12% e os Municípios no mínimo 15% de suas receitas de impostos em ações e serviços públicos de saúde.",
         "CF/88, Art. 198, § 2º e LC 141/2012",
         "fácil"),
        # 57
        ("Segundo o Art. 199 da Constituição Federal de 1988, a assistência à saúde:",
         "É livre à iniciativa privada.",
         "É monopólio exclusivo do Estado, sendo proibida a existência de clínicas particulares no Brasil.",
         "Só pode ser prestada por empresas estrangeiras com capital aberto na Europa.",
         "Deve ser cobrada compulsoriamente de todos os cidadãos em folha de pagamento salarial.",
         "É proibida a médicos com menos de 20 anos de formados.",
         "A",
         "O caput do Art. 199 da CF/88 consagra que a assistência à saúde é livre à iniciativa privada no território nacional.",
         "CF/88, Art. 199",
         "fácil"),
        # 58
        ("As instituições privadas que participam de forma complementar do SUS, nos termos do Art. 199, § 1º da CF/88, o fazem segundo as diretrizes deste, mediante:",
         "Contrato de direito público ou convênio, tendo preferência as entidades filantrópicas e as sem fins lucrativos.",
         "Acordo verbal informal firmado com o diretor administrativo do hospital.",
         "Compra em bolsa de valores de cotas de participação hospitalar.",
         "Leilão de leitos no mercado financeiro especulativo.",
         "Troca de favores eleitorais registrada em cartório de notas comum.",
         "A",
         "A participação privada no SUS exige formalização por contrato de direito público ou convênio, com preferência explícita a entidades filantrópicas e sem fins lucrativos.",
         "CF/88, Art. 199, § 1º",
         "fácil"),
        # 59
        ("O § 2º do Art. 199 da Constituição Federal veda expressamente:",
         "A destinação de recursos públicos para auxílios ou subvenções às instituições privadas com fins lucrativos.",
         "A compra de insumos hospitalares de fabricantes nacionais.",
         "O pagamento de salários a técnicos de enfermagem e radiologia do SUS.",
         "O atendimento médico a pacientes portadores de doenças infectocontagiosas.",
         "A realização de pesquisas científicas em universidades públicas estaduais.",
         "A",
         "É expressamente vedada na CF/88 a destinação de verbas públicas para subvenção ou auxílio a empresas privadas de saúde com finalidade lucrativa.",
         "CF/88, Art. 199, § 2º",
         "fácil"),
        # 60
        ("Com relação à comercialização de órgãos, tecidos e substâncias humanas, o Art. 199, § 4º da Constituição Federal determina taxativamente que:",
         "A lei disporá sobre as condições e os requisitos que facilitem a remoção de órgãos, tecidos e substâncias humanas para fins de transplante, pesquisa e tratamento, sendo vedado todo tipo de comercialização.",
         "Qualquer cidadão pode vender um de seus rins no mercado livre para quitar dívidas financeiras.",
         "Os hospitais privados podem exportar bolsas de sangue humano para obter lucro em moeda estrangeira.",
         "A doação de sangue e órgãos deve ser sempre remunerada em dinheiro vivo pelo SUS.",
         "A comercialização de córneas humanas é permitida em leilões promovidos pela internet.",
         "A",
         "O Art. 199, § 4º veda taxativamente todo tipo de comercialização de órgãos, tecidos e substâncias humanas, bem como a coleta e processamento comercial de sangue.",
         "CF/88, Art. 199, § 4º",
         "fácil"),
        # 61
        ("O Artigo 200 da Constituição Federal elenca as competências expressas do Sistema Único de Saúde (SUS). Dentre elas, inclui-se a de executar as ações de vigilância sanitária e epidemiológica, bem como as de:",
         "Saúde do trabalhador.",
         "Segurança pública militar de fronteiras marítimas.",
         "Controle de tráfego aéreo de jatos comerciais.",
         "Exploração de jazidas minerais de petróleo e gás natural.",
         "Construção de barragens de hidrelétricas no leito dos rios.",
         "A",
         "O Art. 200, II da CF/88 confere ao SUS a competência expressa para executar as ações de saúde do trabalhador, ao lado das vigilâncias epidemiológica e sanitária.",
         "CF/88, Art. 200, II",
         "fácil"),
        # 62
        ("Qual é a competência do SUS estabelecida no inciso VIII do Art. 200 da Constituição Federal de 1988?",
         "Colaborar na proteção do meio ambiente, nele compreendido o do trabalho.",
         "Prender infratores ambientais em flagrante delito nas florestas nacionais.",
         "Construir navios cargueiros para transporte de madeira de reflorestamento.",
         "Explorar minas de carvão mineral para geração de eletricidade termoelétrica.",
         "Isentar indústrias poluidoras do pagamento de multas de licenciamento.",
         "A",
         "O Art. 200, VIII da CF/88 consagra a competência do SUS de colaborar na proteção do meio ambiente, 'nele compreendido o do trabalho' (meio ambiente laboral).",
         "CF/88, Art. 200, VIII",
         "fácil"),
        # 63
        ("No que se refere à formação de pessoal para o setor de saúde, o Art. 200, III da CF/88 estabelece como competência do SUS:",
         "Ordenar a formação de recursos humanos na área de saúde.",
         "Cobrar anuidades escolares em universidades federais de medicina.",
         "Impedir a graduação de enfermeiros em faculdades comunitárias.",
         "Exigir que todos os estudantes de farmácia trabalhem de graça por 10 anos.",
         "Proibir o estágio acadêmico em hospitais públicos estaduais.",
         "A",
         "O SUS tem a incumbência constitucional de ordenar a formação de recursos humanos em saúde (Art. 200, III), orientando currículos e residências para as necessidades do sistema.",
         "CF/88, Art. 200, III",
         "média"),
        # 64
        ("A competência de 'controlar e fiscalizar procedimentos, produtos e substâncias de interesse para a saúde e participar da produção de medicamentos, equipamentos, imunobiológicos, hemoderivados e outros insumos' (Art. 200, I da CF/88) fundamenta a criação de qual agência reguladora federal?",
         "ANVISA (Agência Nacional de Vigilância Sanitária).",
         "ANATEL (Agência Nacional de Telecomunicações).",
         "ANP (Agência Nacional do Petróleo).",
         "ANTT (Agência Nacional de Transportes Terrestres).",
         "ANEEL (Agência Nacional de Energia Elétrica).",
         "A",
         "A Anvisa foi criada com base nas competências constitucionais do SUS de controle e fiscalização de medicamentos, alimentos, cosméticos, saneantes e insumos terapêuticos.",
         "CF/88, Art. 200, I e Lei 9.782/1999",
         "média"),
        # 65
        ("Sobre a participação do SUS na formulação da política e na execução das ações de SANEAMENTO BÁSICO (Art. 200, IV da CF/88):",
         "O SUS participa ativamente da formulação da política de saneamento devido à íntima relação entre abastecimento de água, esgotamento e índices de morbimortalidade na população.",
         "O SUS constrói sozinho todas as redes de esgoto sem auxílio de companhias de engenharia.",
         "A competência é meramente decorativa, sem qualquer efeito na saúde pública.",
         "O SUS é proibido de emitir pareceres sobre qualidade da água potável distribuída.",
         "As companhias de saneamento são subordinadas diretamente aos chefes de enfermagem dos postos.",
         "A",
         "O saneamento básico é fator determinante da saúde coletiva; por isso, a CF/88 incluiu a participação do SUS na formulação de suas políticas e ações (Art. 200, IV).",
         "CF/88, Art. 200, IV",
         "fácil"),
        # 66
        ("O Art. 200, VI da CF/88 atribui expressamente ao SUS a competência de:",
         "Fiscalizar e inspecionar alimentos, compreendido o controle de seu teor nutricional, bem como bebidas e águas para consumo humano.",
         "Tabelar os preços de carnes e grãos nos supermercados privados de todo o país.",
         "Determinar a quantidade de açúcar que cada cidadão tem o direito de comprar.",
         "Proibir o consumo de feijão e arroz por indivíduos com excesso de peso corporal.",
         "Distribuir marmitas prontas gratuitamente em todas as esquinas das capitais.",
         "A",
         "A vigilância sanitária de alimentos, água para consumo humano e bebidas é competência sanitária expressa do SUS prevista no Art. 200, VI da CF/88.",
         "CF/88, Art. 200, VI",
         "fácil"),
        # 67
        ("O controle e a fiscalização da produção, transporte, guarda e utilização de substâncias e produtos psicoativos, tóxicos e radioativos (Art. 200, VII da CF/88) pelo SUS garante:",
         "A proteção da saúde dos trabalhadores que manipulam radiisótopos e produtos perigosos, assim como da população e do meio ambiente contra contaminações tóxicas e nucleares.",
         "A autorização livre para qualquer pessoa transportar cilindros de gás tóxico em ônibus urbanos.",
         "A isenção fiscal de indústrias químicas que operam sem licenciamento ambiental.",
         "A dispensa de dosímetros para técnicos que operam fontes de radiação ionizante.",
         "A venda indiscriminada de medicamentos controlados sem retenção de receita médica.",
         "A",
         "O controle sobre psicoativos, tóxicos e radioativos visa evitar contaminação ambiental, desvios e exposição perigosa a trabalhadores e comunidade.",
         "CF/88, Art. 200, VII",
         "média"),
        # 68
        ("A doutrina constitucional brasileira reconhece que a saúde no Art. 196 da CF/88 possui eficácia jurídica plena e aplicabilidade direta, significando que:",
         "O cidadão pode exigir judicialmente do Estado prestações de saúde indispensáveis à sua sobrevivência e dignidade quando houver omissão estatal injustificada.",
         "O Estado nunca pode ser acionado na justiça para fornecer nenhum tratamento médico.",
         "A saúde é uma mera promessa poética da constituição sem valor legal cogente.",
         "O Poder Judiciário está proibido de julgar ações que envolvam fornecimento de leitos hospitalares.",
         "A responsabilidade pelo custeio hospitalar é exclusivamente de bancos estrangeiros.",
         "A",
         "O STF já pacificou o entendimento de que a saúde é direito subjetivo público de aplicabilidade imediata e dever inafastável do Estado em todas as esferas federativas.",
         "Jurisprudência do STF e CF/88 Art. 196",
         "média"),
        # 69
        ("A respeito da SEGURIDADE SOCIAL na Constituição Federal (Art. 194), a saúde integra um tripé protetivo universal e solidário juntamente com:",
         "A Previdência Social e a Assistência Social.",
         "A Segurança Pública e o Sistema Penitenciário.",
         "A Defesa Nacional e as Relações Exteriores.",
         "O Transporte Rodoviário e a Indústria Naval.",
         "O Sistema Tributário e a Dívida Pública Mobiliária.",
         "A",
         "A Seguridade Social compreende um conjunto integrado de ações de iniciativa dos Poderes Públicos e da sociedade, destinadas a assegurar os direitos relativos à saúde, à previdência e à assistência social (Art. 194 da CF/88).",
         "CF/88, Art. 194",
         "fácil"),
        # 70
        ("Qual a diferença fundamental na Seguridade Social entre a SAÚDE e a PREVIDÊNCIA SOCIAL no texto constitucional brasileiro?",
         "A saúde é universal (acesso de todos independentemente de contribuição), enquanto a previdência social tem caráter contributivo e filiação obrigatória.",
         "A saúde exige contribuição financeira prévia de 35 anos, enquanto a previdência atende a todos de graça.",
         "A saúde é gerida exclusivamente por bancos privados, enquanto a previdência é filantrópica.",
         "A previdência social fornece remédios e cirurgias de alta complexidade em hospitais.",
         "Não há nenhuma diferença, ambas exigem exatamente os mesmos requisitos de carência contributiva.",
         "A",
         "A saúde é direito de todos (universal e não contributiva); a previdência é contributiva e atende apenas aos seus segurados inscritos e dependentes.",
         "CF/88, Art. 196 e Art. 201",
         "fácil"),

        # =========================================================
        # 4. POLÍTICA NACIONAL DE SEGURANÇA E SAÚDE NO TRABALHO (PNSST - DECRETO 7.602/2011) (10 questões)
        # =========================================================
        # 71
        ("A Política Nacional de Segurança e Saúde no Trabalho (PNSST), instituída pelo Decreto Presidencial nº 7.602/2011, tem por OBJETIVO geral:",
         "A promoção da saúde e a melhoria da qualidade de vida do trabalhador e a prevenção de acidentes e de danos à saúde advindos, relacionados ao trabalho ou que ocorram no curso dele, por meio da eliminação ou redução dos riscos nos ambientes de trabalho.",
         "O aumento das alíquotas do imposto de renda incidente sobre os salários operários.",
         "A substituição gradativa de todos os trabalhadores humanos por robôs industriais em 5 anos.",
         "A extinção definitiva de todas as Normas Regulamentadoras do Ministério do Trabalho.",
         "A autorização expressa para indústrias operarem sem laudos de insalubridade e periculosidade.",
         "A",
         "O Art. 2º do Decreto 7.602/2011 define como objetivo da PNSST promover a saúde e qualidade de vida e prevenir acidentes e danos no trabalho pela eliminação ou controle de riscos.",
         "Decreto 7.602/2011, Art. 2º",
         "fácil"),
        # 72
        ("Dentre os PRINCÍPIOS basilares da Política Nacional de Segurança e Saúde no Trabalho (Art. 3º do Decreto nº 7.602/2011), inclui-se expressamente:",
         "A precedência das ações de prevenção sobre as de assistência, reabilitação e reparação.",
         "A prioridade da indenização pecuniária post-mortem sobre a prevenção de acidentes.",
         "A cobrança de taxa dos trabalhadores para inspecionar os postos de trabalho perigosos.",
         "A dispensa do diálogo social entre patrões e empregados nas negociações coletivas.",
         "A culpabilização individual da vítima em caso de lesão por maquinário sem proteção.",
         "A",
         "O princípio da precedência da prevenção estabelece que evitar o acidente é prioridade absoluta frente à assistência médica posterior ou indenização reparatória.",
         "Decreto 7.602/2011, Art. 3º, IV",
         "média"),
        # 73
        ("A implementação da PNSST é de responsabilidade compartilhada e articulada no âmbito do governo federal entre os seguintes Ministérios:",
         "Ministério do Trabalho e Emprego, Ministério da Previdência Social e Ministério da Saúde.",
         "Ministério da Agricultura, Ministério das Minas e Energia e Ministério da Pesca.",
         "Ministério do Turismo, Ministério da Cultura e Ministério do Esporte.",
         "Ministério da Defesa, Ministério da Fazenda e Banco Central do Brasil.",
         "Ministério das Comunicações, Ministério dos Transportes e ANATEL.",
         "A",
         "A PNSST articula a gestão tripartite de SST entre a área do Trabalho (fiscalização/NRs), da Previdência (benefícios/CAT/FAP) e da Saúde (vigilância/SUS).",
         "Decreto 7.602/2011, Art. 5º",
         "fácil"),
        # 74
        ("A universalidade como princípio da PNSST (Decreto nº 7.602/2011, Art. 3º, I) assegura que as diretrizes e ações de segurança e saúde no trabalho devem alcançar:",
         "Todos os trabalhadores brasileiros, independentemente de sua vinculação empregatícia (celetistas, estatutários públicos, autônomos, cooperados, avulsos ou rurais).",
         "Apenas os trabalhadores com carteira assinada em multinacionais petroquímicas.",
         "Exclusivamente servidores públicos federais com estabilidade funcional.",
         "Apenas estagiários de cursos técnicos em segurança do trabalho.",
         "Trabalhadores que recebem remuneração salarial acima de 20 salários mínimos.",
         "A",
         "O princípio da universalidade garante a inclusão de todos os trabalhadores no sistema de proteção e promoção da saúde ocupacional.",
         "Decreto 7.602/2011, Art. 3º, I",
         "fácil"),
        # 75
        ("O Comitê Tripartite de Saúde e Segurança no Trabalho (CTSST), instituído para acompanhar a implementação e execução da PNSST, possui composição formada por:",
         "Representantes do governo, dos trabalhadores e dos empregadores, respeitando o princípio do diálogo social tripartite da OIT.",
         "Apenas auditores fiscais da Receita Federal e juízes do trabalho.",
         "Exclusivamente empresários donos de hospitais e planos de saúde privados.",
         "Apenas deputados federais e senadores da bancada governista.",
         "Representantes nomeados unilateralmente pelo presidente de bancos comerciais.",
         "A",
         "O CTSST obedece à estrutura tripartite (governo, trabalhadores e empregadores), harmonizando políticas e o Plano Nacional de Segurança e Saúde no Trabalho (PLANSAT).",
         "Decreto 7.602/2011, Art. 9º",
         "fácil"),
        # 76
        ("Dentre as diretrizes estratégicas da PNSST (Art. 4º do Decreto nº 7.602/2011), destaca-se a 'harmonização das normas e articulação das ações de promoção, proteção, prevenção, assistência, reabilitação e reparação da saúde do trabalhador', o que visa:",
         "Eliminar contradições e sobreposições normativas entre os Ministérios do Trabalho, Saúde e Previdência, integrando dados e fluxos de fiscalização e vigilância.",
         "Permitir que as empresas criem suas próprias leis sem intervenção do Estado.",
         "Acabar com a obrigatoriedade da emissão de Comunicação de Acidente de Trabalho (CAT).",
         "Isentar hospitais públicos de cumprirem a NR-32 e as normas da Anvisa.",
         "Aumentar a burocracia documental para dificultar a aposentadoria dos trabalhadores.",
         "A",
         "A harmonização busca a coerência regulatória e a interoperabilidade de sistemas de informação em SST entre Trabalho, Saúde e Previdência (ex: eSocial).",
         "Decreto 7.602/2011, Art. 4º, II",
         "média"),
        # 77
        ("No âmbito da PNSST, a estruturação de uma rede integrada de informações em saúde e segurança no trabalho tem por finalidade técnica:",
         "Garantir a coleta, consolidação e análise epidemiológica contínua de dados de acidentes, doenças e exposições ocupacionais para orientar políticas públicas preventivas.",
         "Vender o histórico médico dos trabalhadores para empresas de telemarketing comercial.",
         "Divulgar a renda salarial de todos os técnicos de segurança na internet.",
         "Impedir que trabalhadores lesionados tenham acesso a seus prontuários médicos.",
         "Substituir o censo demográfico oficial do IBGE a cada década.",
         "A",
         "A integração de sistemas de informação possibilita o monitoramento epidemiológico dos agravos à saúde do trabalhador e o planejamento de ações fiscais e educativas.",
         "Decreto 7.602/2011, Art. 4º, IV",
         "média"),
        # 78
        ("A respeito da capacitação continuada em segurança e saúde no trabalho preconizada na PNSST:",
         "Deve abranger gestores, empregadores, trabalhadores, membros de CIPA e profissionais do SESMT, fomentando a cultura prevencionista em todos os níveis.",
         "É permitida apenas uma única vez na vida escolar do cidadão durante o ensino infantil.",
         "É restrita a treinamentos teóricos de 10 minutos por correspondência postal.",
         "Fica proibida para empregados que trabalhem em serviços de saúde hospitalares.",
         "Deve ser paga com desconto compulsório de 50% no décimo terceiro salário dos funcionários.",
         "A",
         "A educação permanente e a formação prevencionista dos atores sociais é diretriz central da PNSST para consolidar ambientes de trabalho seguros e saudáveis.",
         "Decreto 7.602/2011, Art. 4º, V",
         "fácil"),
        # 79
        ("A PNSST preconiza a adoção de medidas especiais de segurança e saúde no trabalho para grupos e atividades com maior vulnerabilidade. Em hospitais e serviços de saúde como a FHCGV, isso se traduz na atenção prioritária aos riscos:",
         "Biológicos (patógenos sanguíneos e respiratórios), perfurocortantes, químicos (quimioterápicos) e cargas ergonômicas da movimentação de pacientes.",
         "De colisão de trens de carga nos corredores internos das enfermarias.",
         "De desabamento de minas subterrâneas de extração de carvão mineral.",
         "De descompressão hiperbárica em mergulhos profundos em alto-mar.",
         "De ataque de animais ferozes carnívoros selvagens nos leitos de UTI.",
         "A",
         "O trabalho em saúde apresenta perfil de vulnerabilidade ocupacional específico com riscos biológicos graves, perfurantes, químicos perigosos e esforço biomecânico intenso.",
         "PNSST e Diretrizes Ocupacionais em Saúde",
         "fácil"),
        # 80
        ("Qual é o papel do Sistema Único de Saúde (SUS) na execução da PNSST no estado do Pará e no contexto da FHCGV?",
         "Atuar na vigilância em saúde do trabalhador (VISAT), no diagnóstico de doenças ocupacionais, na notificação no SINAN, na assistência e reabilitação física e na promoção da biossegurança hospitalar.",
         "Cobrar multas trabalhistas para abastecer o caixa particular da diretoria do hospital.",
         "Revogar as leis trabalhistas do estado do Pará para atrair investimentos estrangeiros.",
         "Proibir os técnicos de segurança do trabalho de realizarem inspeções nos postos de saúde.",
         "Substituir o Ministério Público do Trabalho nos inquéritos civis de fraudes fiscais.",
         "A",
         "O SUS é executor direto das ações de vigilância sanitária, epidemiológica e da saúde do trabalhador, atuando na prevenção, diagnóstico e notificação dos agravos ocupacionais.",
         "Decreto 7.602/2011 e Lei 8.080/90",
         "média")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "Legislação SUS",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_sus_questions()
    print(f"Legislação SUS questions generated: {len(q)}")
