# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-15: Atividades e Operações Insalubres (40 questões)
- Anexo 14 (agentes biológicos): 25 questões
- Graus de insalubridade: 10 questões
- EPI e elisão da insalubridade: 5 questões
"""

def get_nr15_questions():
    items = [
        # =========================================================
        # 1. ANEXO 14 - AGENTES BIOLÓGICOS (25 questões)
        # =========================================================
        # 1
        ("A avaliação da insalubridade por agentes biológicos prevista no Anexo nº 14 da NR-15 caracteriza-se por ser:",
         "Eminentemente qualitativa, mediante inspeção realizada no local de trabalho, sem estabelecimento de limites de tolerância numéricos.",
         "Exclusivamente quantitativa, exigindo contagem diária de bactérias por metro cúbico de ar com bomba gravimétrica.",
         "Calculada através de média aritmética de decibéis sonoros do ambiente hospitalar.",
         "Dispensada de laudo pericial, bastando a autodeclaração do funcionário no sindicato.",
         "Realizada por pesagem em balança de precisão dos resíduos biológicos do hospital.",
         "A",
         "A avaliação de risco biológico no Anexo 14 da NR-15 é qualitativa, baseada na análise das atividades, funções e locais com potencial de contato com agentes biológicos.",
         "NR-15, Anexo 14",
         "fácil"),
        # 2
        ("De acordo com o Anexo nº 14 da NR-15, o trabalho ou operações em contato permanente com 'pacientes em isolamento por doenças infectocontagiosas, bem como objetos de seu uso, não previamente esterilizados' assegura o adicional de insalubridade em grau:",
         "Máximo (40%).",
         "Médio (20%).",
         "Mínimo (10%).",
         "Zero (0%), não sendo considerado insalubre.",
         "Variável entre 1% e 5% a critério do diretor.",
         "A",
         "O Anexo 14 da NR-15 enquadra o contato permanente com pacientes em isolamento por doenças infectocontagiosas e objetos não esterilizados em grau MÁXIMO (40%).",
         "NR-15, Anexo 14",
         "fácil"),
        # 3
        ("Em relação aos profissionais de enfermagem e médicos que atuam no atendimento e internação geral de hospitais, enfermarias e ambulatórios (sem isolamento específico), o Anexo 14 da NR-15 estabelece insalubridade de grau:",
         "Médio (20%).",
         "Máximo (40%).",
         "Mínimo (10%).",
         "Integral (100%).",
         "Não há previsão de insalubridade para área hospitalar geral.",
         "A",
         "Trabalhos em contato permanente com pacientes ou material infectocontagiante em hospitais, ambulatórios e enfermarias gerais ensejam grau MÉDIO (20%).",
         "NR-15, Anexo 14",
         "fácil"),
        # 4
        ("O Anexo nº 14 da NR-15 assegura o adicional de insalubridade de GRAU MÁXIMO (40%) para o contato permanente com:",
         "Esgotos (galerias e fossas) e lixo urbano (coleta e industrialização).",
         "Papéis e correspondências administrativas de escritório de advocacia.",
         "Flores ornamentais em jardins públicos municipais.",
         "Computadores novos em sala de informática escolar.",
         "Frutas frescas comercializadas em feiras livres.",
         "A",
         "O Anexo 14 enquadra expressamente no grau máximo o contato com esgotos (galerias e fossas) e lixo urbano (coleta e industrialização).",
         "NR-15, Anexo 14",
         "fácil"),
        # 5
        ("Segundo o entendimento consagrado no item II da Súmula nº 448 do Tribunal Superior do Trabalho (TST):",
         "A higienização de instalações sanitárias de uso público ou coletivo de grande circulação, e a respectiva coleta de lixo, enseja a aplicação do Anexo 14 da NR-15 (lixo urbano), conferindo o adicional de insalubridade em grau máximo.",
         "Toda limpeza de banheiro residencial familiar gera adicional de insalubridade de 40%.",
         "A coleta de lixo em escritórios com 2 funcionários dá direito a grau máximo de insalubridade.",
         "Nenhum tipo de limpeza de sanitários pode ser considerado insalubre pela justiça.",
         "O lixo de banheiros hospitalares é considerado resíduo comum reciclável sem riscos.",
         "A",
         "A Súmula 448, II do TST equipara a limpeza de banheiros de grande circulação pública/coletiva à coleta de lixo urbano, gerando insalubridade em grau máximo (40%).",
         "Súmula 448, II do TST",
         "fácil"),
        # 6
        ("Por outro lado, a limpeza de banheiros em escritórios administrativos com poucas pessoas e a limpeza doméstica residencial, conforme a Súmula 448 do TST:",
         "Não enseja o pagamento de adicional de insalubridade, por não se equiparar à coleta de lixo urbano.",
         "Gera adicional de insalubridade de 40% cumulado com adicional de periculosidade de 30%.",
         "Obriga o patrão a pagar o triplo do salário mínimo em dinheiro todo mês.",
         "É considerada atividade proibida pelo Ministério Público do Trabalho.",
         "Exige o uso de roupa pressurizada de astronauta pela trabalhadora.",
         "A",
         "A Súmula 448 do TST pacifica que a limpeza em residências e escritórios não gera adicional de insalubridade, restringindo o direito a banheiros de grande circulação pública.",
         "Súmula 448, II do TST",
         "fácil"),
        # 7
        ("Os trabalhadores da equipe de limpeza e higienização hospitalar da FHCGV que recolhem os sacos de lixo biológico (infectante) dos leitos, enfermarias e UTIs:",
         "Têm direito ao adicional de insalubridade em grau máximo (40%), tendo em vista o manuseio direto e contínuo de lixo hospitalar com potencial infectocontagiante elevado.",
         "Não têm direito a nenhum adicional salarial por realizarem serviço terceirizado.",
         "Têm direito apenas a um adicional de 5% caso usem uniformes de cor branca.",
         "Recebem apenas adicional noturno mesmo trabalhando às dez horas da manhã.",
         "Têm direito apenas a vale-transporte dobrado em dias de chuva torrencial.",
         "A",
         "O manuseio e coleta de lixo hospitalar infectante em ambientes hospitalares é pacificado pela jurisprudência do TST como ensejador de insalubridade em grau máximo.",
         "Jurisprudência Consolidada TST e NR-15",
         "média"),
        # 8
        ("No que concerne aos laboratórios de análises clínicas e histopatologia, o Anexo 14 da NR-15 prevê insalubridade em grau MÉDIO restrita a qual categoria de trabalhadores?",
         "Unicamente ao pessoal técnico que manipula materiais biológicos infectantes e amostras de pacientes.",
         "Aos recepcionistas que apenas realizam o cadastro de dados pessoais no balcão de entrada.",
         "Aos contadores externos que auditam as notas fiscais em outro endereço comercial.",
         "Aos motoristas que transportam papéis timbrados do laboratório.",
         "Aos diretores acionistas que nunca entram nas áreas técnicas do laboratório.",
         "A",
         "O texto do Anexo 14 diz expressamente: 'Laboratórios de análise clínica e histopatologia (aplica-se tão-só ao pessoal técnico)'.",
         "NR-15, Anexo 14",
         "fácil"),
        # 9
        ("Os técnicos que executam atividades em gabinetes de autópsias, de anatomia e de histoanatomopatologia têm direito, segundo o Anexo 14 da NR-15, ao adicional em grau:",
         "Médio (20%).",
         "Máximo (40%).",
         "Mínimo (10%).",
         "Zero (0%).",
         "Variável de acordo com o peso dos corpos periciados.",
         "A",
         "O Anexo 14 enquadra gabinetes de autópsias, de anatomia e histoanatomopatologia (para o pessoal técnico) no grau MÉDIO (20%).",
         "NR-15, Anexo 14",
         "fácil"),
        # 10
        ("Em cemitérios, a atividade expressamente classificada como insalubre em GRAU MÉDIO (20%) pelo Anexo 14 da NR-15 é:",
         "A exumação de corpos.",
         "O plantio de grama e flores ornamentais nas alamedas do cemitério.",
         "A venda de velas e coroas de flores no portão de entrada.",
         "O atendimento telefônico para agendamento de sepultamentos.",
         "A vigilância noturna da guarita de entrada desarmada.",
         "A",
         "O Anexo 14 inclui especificamente 'exumação de corpos' em cemitérios como atividade insalubre de grau médio (20%).",
         "NR-15, Anexo 14",
         "fácil"),
        # 11
        ("Sobre o conceito de CONTATO PERMANENTE exigido pelo Anexo nº 14 da NR-15 para a caracterização da insalubridade biológica:",
         "Exige que o contato com os agentes biológicos ou pacientes faça parte da rotina habitual e ordinária da função exercida pelo empregado.",
         "Exige que o trabalhador permaneça colado ao paciente 24 horas por dia sem piscar os olhos.",
         "Exclui qualquer trabalhador que tome banho ou troque de luvas durante o expediente.",
         "Significa que o profissional deve dormir dentro da enfermaria todas as noites.",
         "Só se configura se o trabalhador contrair a doença e vier a óbito imediato.",
         "A",
         "Contato permanente no contexto ocupacional é a exposição habitual decorrente das atribuições rotineiras do cargo, e não o contato eventual fortuito.",
         "Doutrina de SST e Jurisprudência Trabalhista",
         "média"),
        # 12
        ("A Súmula nº 47 do TST estabelece que o trabalho executado em condições insalubres em caráter INTERMITENTE:",
         "Não descaracteriza o direito à percepção do respectivo adicional de insalubridade.",
         "Extingue imediatamente o direito ao adicional salarial.",
         "Reduz o adicional para 0,5% do salário mínimo.",
         "Obriga o trabalhador a devolver os salários recebidos nos últimos cinco anos.",
         "Transforma o contrato de trabalho em trabalho voluntário não remunerado.",
         "A",
         "A Súmula 47 do TST é clássica: a intermitência na exposição insalubre não afasta o direito ao pagamento do adicional integral correspondente.",
         "Súmula 47 do TST",
         "fácil"),
        # 13
        ("Um maqueiro da FHCGV transporta diariamente pacientes internados para a realização de cirurgias, exames e transferências entre leitos. Sua atividade:",
         "Enseja o adicional de insalubridade em grau médio (20%), por manter contato permanente com pacientes e materiais em ambiente hospitalar.",
         "Não é insalubre, pois o maqueiro só empurra a estrutura metálica das macas.",
         "É insalubre em grau mínimo de 2% pago em vale-refeição.",
         "Só seria insalubre caso o maqueiro fosse diplomado em medicina cirúrgica.",
         "É isenta de qualquer proteção por se tratar de atividade de hotelaria.",
         "A",
         "O maqueiro hospitalar mantém contato físico e proximidade constante com pacientes e secreções, enquadrando-se no Anexo 14 em grau médio (ou máximo em isolamento).",
         "NR-15, Anexo 14 e Jurisprudência TST",
         "média"),
        # 14
        ("A recepcionista de um hospital que trabalha em guichê de vidro fechado no saguão externo, atendendo unicamente ao público para preenchimento de fichas e triagem administrativa sem contato físico com pacientes:",
         "Não se enquadra na insalubridade do Anexo 14, pois o benefício aplica-se exclusivamente ao pessoal que tem contato com pacientes ou manuseia objetos de seu uso não esterilizados.",
         "Tem direito automático a 40% de insalubridade pelo simples fato de o prédio ser um hospital.",
         "Tem direito a adicional de periculosidade de 30% por risco de contágio aéreo geral.",
         "Deve receber o triplo do salário mínimo como indenização por estresse visual.",
         "É considerada cirurgiã geral para todos os efeitos previdenciários e trabalhistas.",
         "A",
         "O Anexo 14 restringe a insalubridade ao pessoal que presta cuidados diretos ou manuseia materiais infectados; pessoal puramente administrativo não recebe insalubridade.",
         "NR-15, Anexo 14",
         "média"),
        # 15
        ("Em relação à Central de Material e Esterilização (CME), os técnicos que trabalham no setor de EXPURGO lavando e descontaminando instrumentais cirúrgicos com sangue e secreções:",
         "Têm direito ao adicional de insalubridade, decorrente do contato habitual com objetos de uso de pacientes com material biológico infectocontagiante não previamente esterilizado.",
         "Estão isentos de insalubridade porque os materiais serão esterilizados depois.",
         "Perdem o direito ao adicional se usarem avental de borracha e luvas de cano longo.",
         "Têm direito a insalubridade apenas nos dias em que cortarem as próprias mãos.",
         "Devem pagar uma taxa de higienização ao hospital para desempenhar o serviço.",
         "A",
         "O manuseio de objetos e instrumentais cirúrgicos sujos de sangue antes da esterilização amolda-se perfeitamente às hipóteses de insalubridade do Anexo 14.",
         "NR-15, Anexo 14",
         "fácil"),
        # 16
        ("O contato com sangue e hemoderivados em bancos de sangue e hemonúcleos durante a triagem e processamento laboratorial de bolsas de sangue:",
         "Caracteriza atividade insalubre em grau médio pelo manuseio de material biológico humano potencialmente infectado (vírus de hepatites, HIV, etc.).",
         "É considerado totalmente livre de risco biológico pelas normas do trabalho.",
         "Enseja grau máximo exclusivamente se o doador de sangue for portador de rinite alérgica.",
         "Só gera direito a adicional se a bolsa de sangue romper e espirrar nos olhos.",
         "É vedado a servidores públicos estaduais estatutários da administração direta.",
         "A",
         "O processamento de sangue e seus componentes é considerado manuseio de material biológico humano com potencial infeccioso no Anexo 14.",
         "NR-15, Anexo 14",
         "média"),
        # 17
        ("Trabalhadores da lavanderia hospitalar que atuam na chamada 'ÁREA SUJA', realizando a recepção, triagem e pesagem de lençóis, fronhas e campos cirúrgicos com fezes e sangue:",
         "Têm direito ao adicional de insalubridade pelo contato permanente com materiais infectados não previamente desinfetados.",
         "Não têm direito porque os lençóis serão limpos pelas máquinas automáticas.",
         "Recebem apenas adicional de penosidade de 5% sobre a cesta básica.",
         "Ficam proibidos de receber qualquer tipo de EPI pela chefia do setor.",
         "Devem lavar as roupas hospitalares em suas próprias residências particulares.",
         "A",
         "A separação e triagem de roupa suja hospitalar na área contaminada expõe o trabalhador a sangue, fezes e fluidos, caracterizando insalubridade pelo Anexo 14.",
         "NR-15, Anexo 14",
         "fácil"),
        # 18
        ("Se a unidade hospitalar da FHCGV abrigar uma ala de isolamento para pacientes com Tuberculose multirresistente ou Meningite meningocócica, os enfermeiros e técnicos designados para o isolamento:",
         "Fazem jus ao adicional de insalubridade em grau MÁXIMO (40%), por estarem em contato permanente com pacientes em isolamento por doenças infectocontagiosas.",
         "Fazem jus apenas a grau mínimo de 10% por terem máscaras PFF2 disponíveis.",
         "Perdem qualquer adicional salarial por determinação da diretoria clínica.",
         "Têm seus contratos de trabalho rescindidos sumariamente pela CLT.",
         "Recebem apenas um dia de folga no aniversário de contratação da empresa.",
         "A",
         "O contato permanente com pacientes em isolamento por doenças infectocontagiosas enseja grau MÁXIMO (40%) de acordo com o texto expresso do Anexo 14.",
         "NR-15, Anexo 14",
         "fácil"),
        # 19
        ("Em relação aos trabalhadores da odontologia hospitalar que realizam procedimentos cirúrgicos bucomaxilofaciais com aerossóis de saliva e sangue de pacientes:",
         "Estão expostos a agentes biológicos infectocontagiantes em ambiente de cuidados à saúde humana, fazendo jus à insalubridade em grau médio (20%).",
         "Não têm direito a adicional porque dentes humanos são estruturas inanimadas.",
         "Recebem grau máximo apenas se o paciente for menor de 12 anos.",
         "Ficam dispensados de utilizar óculos e máscaras de proteção facial.",
         "Recebem insalubridade apenas caso o motorzinho de rotação quebre na boca.",
         "A",
         "Os cirurgiões-dentistas e auxiliares de saúde bucal mantêm contato com sangue e saliva em procedimentos, enquadrando-se em grau médio no Anexo 14.",
         "NR-15, Anexo 14",
         "fácil"),
        # 20
        ("A atividade de coleta domiciliar de lixo urbano nas ruas das cidades é enquadrada no Anexo 14 em grau:",
         "Máximo (40%).",
         "Médio (20%).",
         "Mínimo (10%).",
         "Zero (0%).",
         "Percentual negociado diariamente com os motoristas dos caminhões.",
         "A",
         "A coleta de lixo urbano é classificada literalmente como atividade insalubre de grau MÁXIMO (40%) no Anexo 14 da NR-15.",
         "NR-15, Anexo 14",
         "fácil"),
        # 21
        ("O contato com animais portadores de doenças infectocontagiosas (como raiva, mormo ou brucelose) em hospitais veterinários ou matadouros confere insalubridade em grau:",
         "Máximo (40%).",
         "Médio (20%).",
         "Mínimo (10%).",
         "Zero (0%).",
         "Apenas direito a ração animal gratuita no almoço.",
         "A",
         "Animais portadores de doenças infectocontagiosas e suas vísceras/dejeções geram insalubridade em grau MÁXIMO (40%) pelo Anexo 14.",
         "NR-15, Anexo 14",
         "média"),
        # 22
        ("Qual a diferença de enquadramento no Anexo 14 da NR-15 entre o contato com animais comuns em estábulos e o contato com animais portadores de doenças infectocontagiosas?",
         "Estábulos e cavalariças gerais geram grau MÉDIO (20%), enquanto animais comprovadamente portadores de doenças infectocontagiosas geram grau MÁXIMO (40%).",
         "Não há nenhuma diferença, ambos não dão direito a adicional de insalubridade.",
         "Animais em estábulos dão grau máximo e animais doentes dão grau mínimo.",
         "Ambos dão direito exclusivamente ao adicional de periculosidade de 30%.",
         "O trabalho em estábulos é considerado proibido para maiores de 18 anos.",
         "A",
         "O Anexo 14 separa estábulos e cavalariças comuns (grau médio 20%) de animais portadores de doenças infectocontagiosas (grau máximo 40%).",
         "NR-15, Anexo 14",
         "média"),
        # 23
        ("A caracterização da insalubridade por agente biológico exige que o trabalhador tenha sofrido contaminação ou adoecido previamente?",
         "Não, a insalubridade decorre do risco potencial objetivo de exposição durante a execução das tarefas, independentemente da ocorrência de contaminação efetiva do empregado.",
         "Sim, o trabalhador só passa a receber insalubridade após testar positivo para HIV ou Hepatite.",
         "Sim, exige internação prévia de pelo menos 60 dias em coma hospitalar.",
         "Apenas se o trabalhador processar criminalmente o paciente atendido.",
         "Sim, o pagamento é retroativo apenas aos meses em que o funcionário teve febre.",
         "A",
         "O adicional de insalubridade remunera a exposição ambiental deletéria ao risco, não sendo indenização securitária por doença já manifestada.",
         "Direito do Trabalho e NR-15",
         "fácil"),
        # 24
        ("Aos trabalhadores que atuam em farmácias hospitalares dispensando caixas lacradas de medicamentos manufaturados aos andares sem contato com pacientes ou fluidos:",
         "Geralmente não é devido o adicional de insalubridade biológica, pois embalagens secundárias fechadas não transmitem agentes infecciosos aos operadores.",
         "É devido adicional de 40% porque remédios contêm produtos químicos medicinais.",
         "É devido adicional de periculosidade de 50% por risco de choque elétrico nas caixas.",
         "É proibido qualquer contato com caixas de papelão sem luvas de malha de aço.",
         "Devem receber o dobro do salário base por realizarem esforço de leitura de bulas.",
         "A",
         "O manuseio de caixas e embalagens íntegras de medicamentos em farmácia hospitalar não configura contato direto com pacientes nem material infectocontagiante.",
         "Jurisprudência TST e Laudos Periciais",
         "média"),
        # 25
        ("Na perícia trabalhista de insalubridade na FHCGV, a análise do perito judicial deve contemplar:",
         "A verificação das rotinas reais de trabalho, setores acessados, contato com pacientes e materiais, ficha de entrega de EPIs com CA e medidas de engenharia adotadas.",
         "Apenas o depoimento pessoal do presidente da associação dos moradores do bairro.",
         "A conferência da marca da tinta utilizada na pintura dos tetos do hospital.",
         "Apenas a contagem do número de lâmpadas incandescentes no estacionamento.",
         "O sorteio de moedas para decidir se o trabalhador ganha ou perde a ação judicial.",
         "A",
         "A perícia técnica analisa faticamente as condições ambientais, atribuições reais, tempo e frequência de exposição e eficácia protetiva dos EPIs fornecidos.",
         "CLT Art. 195 e CPC",
         "fácil"),

        # =========================================================
        # 2. GRAUS DE INSALUBRIDADE (10 questões)
        # =========================================================
        # 26
        ("O Artigo 192 da Consolidação das Leis do Trabalho (CLT) e a NR-15 fixam os adicionais de insalubridade para os graus MÁXIMO, MÉDIO e MÍNIMO nos seguintes percentuais, respectivamente:",
         "40%, 20% e 10%.",
         "50%, 30% e 10%.",
         "30%, 20% e 10%.",
         "100%, 50% e 25%.",
         "20%, 10% e 5%.",
         "A",
         "A CLT (Art. 192) e a NR-15 estipulam claramente os adicionais: 40% (grau máximo), 20% (grau médio) e 10% (grau mínimo).",
         "CLT Art. 192 e NR-15, item 15.2",
         "fácil"),
        # 27
        ("Salvo disposição expressa em convenção coletiva ou legislação estatutária específica mais favorável, a base de cálculo padrão do adicional de insalubridade na CLT é o:",
         "Salário mínimo da região (conforme Súmula Vinculante nº 4 do STF até que lei fixe nova base).",
         "Salário total de toda a diretoria executiva da empresa somado.",
         "Valor do faturamento bruto anual da fundação hospitalar.",
         "Piso salarial da categoria dos pilotos de avião de caça militar.",
         "Valor das horas extras realizadas no último dia do ano civil.",
         "A",
         "Conforme entendimento vinculante do STF (Súmula Vinculante 4), a base de cálculo da insalubridade sob a CLT é o salário mínimo, salvo previsão mais benéfica em ACT/CCT.",
         "Súmula Vinculante 4 do STF e CLT Art. 192",
         "fácil"),
        # 28
        ("No caso de incidência de mais de um fator de insalubridade no mesmo posto de trabalho (exemplo: exposição a ruído excessivo de 20% e contato com pacientes de isolamento de 40%):",
         "Será considerado apenas o de grau mais elevado (40%), sendo vedada a percepção cumulativa de adicionais de insalubridade.",
         "Os adicionais serão somados, totalizando 60% de adicional salarial.",
         "Será pago apenas o de menor valor (20%) para gerar economia ao empregador.",
         "O trabalhador perde o direito a ambos os adicionais por incompatibilidade legal.",
         "Os adicionais são multiplicados entre si na folha de pagamento do servidor.",
         "A",
         "O item 15.3 da NR-15 e o Art. 193, § 2º da CLT vedam a cumulação de adicionais de insalubridade, prevalecendo unicamente o de grau mais elevado.",
         "NR-15, item 15.3 e CLT Art. 193, § 2º",
         "fácil"),
        # 29
        ("A caracterização e a classificação da insalubridade e da periculosidade nos locais de trabalho, segundo o Artigo 195 da CLT, devem ser realizadas por meio de perícia a cargo de:",
         "Médico do Trabalho ou Engenheiro de Segurança do Trabalho, devidamente registrados no Ministério do Trabalho.",
         "Qualquer pessoa com mais de 21 anos que saiba ler e escrever fluentemente.",
         "Delegado de polícia civil do município onde a empresa está instalada.",
         "Gerente de vendas de lojas de departamentos comerciais da capital.",
         "Oficial de justiça da vara da família da comarca de Belém.",
         "A",
         "A CLT Art. 195 determina expressamente que a perícia de insalubridade/periculosidade é ato privativo de Médico do Trabalho ou Engenheiro de Segurança do Trabalho.",
         "CLT Art. 195",
         "fácil"),
        # 30
        ("As atividades com exposição ao calor acima dos limites de tolerância sem controle (Anexo nº 3 da NR-15) geram direito ao adicional de insalubridade em grau:",
         "Médio (20%).",
         "Máximo (40%).",
         "Mínimo (10%).",
         "Zero (0%).",
         "Variável conforme a umidade do ar da praia.",
         "A",
         "A exposição ao calor excessivo acima dos limites de IBUTG do Anexo 3 da NR-15 é classificada como atividade insalubre de grau MÉDIO (20%).",
         "NR-15, Anexo 3",
         "fácil"),
        # 31
        ("A exposição ocupacional a radiações ionizantes (como nos setores de radiologia e radioterapia) sem observância dos limites e normas da CNEN, nos termos do Anexo nº 5 da NR-15, confere insalubridade de grau:",
         "Máximo (40%).",
         "Médio (20%).",
         "Mínimo (10%).",
         "Dispensada se o trabalhador tomar sol de manhã.",
         "Variável de acordo com a voltagem da rede elétrica.",
         "A",
         "O Anexo 5 da NR-15 estabelece adicional de insalubridade em grau MÁXIMO (40%) para operações com radiações ionizantes.",
         "NR-15, Anexo 5",
         "fácil"),
        # 32
        ("As radiações não-ionizantes (como micro-ondas, laser e ultravioleta gerados em processos de solda ou desinfecção) previstas no Anexo nº 7 da NR-15 geram adicional de insalubridade de grau:",
         "Médio (20%).",
         "Máximo (40%).",
         "Mínimo (10%).",
         "Zero (0%).",
         "Cinquenta por cento (50%).",
         "A",
         "As operações que exponham os trabalhadores a radiações não-ionizantes sem proteção adequada asseguram adicional de grau MÉDIO (20%).",
         "NR-15, Anexo 7",
         "fácil"),
        # 33
        ("A exposição a níveis de ruído contínuo ou intermitente acima dos limites de tolerância do Anexo nº 1 da NR-15 (acima de 85 dB(A) para 8 horas) sem proteção confere insalubridade de grau:",
         "Médio (20%).",
         "Máximo (40%).",
         "Mínimo (10%).",
         "Integral (100%).",
         "Depende da preferência musical dos empregados.",
         "A",
         "O ruído acima dos limites de tolerância sem atenuação eficaz do protetor auricular enseja adicional de insalubridade em grau MÉDIO (20%).",
         "NR-15, Anexo 1",
         "fácil"),
        # 34
        ("O direito do empregado ao adicional de insalubridade ou de periculosidade cessa quando:",
         "Ocorrer a eliminação do risco à sua saúde ou integridade física, nos termos da CLT e das Normas Regulamentadoras.",
         "O empregado completar 10 anos ininterruptos no mesmo cargo na empresa.",
         "O trabalhador casar ou tiver o seu primeiro filho registrado em cartório.",
         "O hospital mudar de nome fantasia em anúncio publicitário comercial.",
         "O sindicato dos trabalhadores entrar em recesso durante o mês de julho.",
         "A",
         "Conforme o Art. 194 da CLT, o direito ao adicional cessa com a eliminação do risco que gerou sua concessão (por engenharia ou proteção efetiva).",
         "CLT Art. 194 e NR-15, item 15.4",
         "fácil"),
        # 35
        ("Se a empresa deixar de pagar o adicional de insalubridade devido a um trabalhador durante vários anos de contrato, o trabalhador pode pleitear judicialmente as diferenças salariais:",
         "Respeitada a prescrição quinquenal (últimos 5 anos de contrato) na Justiça do Trabalho.",
         "Apenas dos últimos 30 dias de salário vencido.",
         "De todos os meses trabalhados desde o ano de 1900 sem limites de prescrição.",
         "Apenas se o trabalhador nunca tiver faltado um dia sequer ao trabalho.",
         "Exclusivamente se o perito for parente próximo do reclamante.",
         "A",
         "As verbas trabalhistas prescrevem em 5 anos até o limite de 2 anos após a extinção do contrato de trabalho (CF/88 Art. 7º, XXIX).",
         "CF/88, Art. 7º, XXIX e CLT Art. 11",
         "fácil"),

        # =========================================================
        # 3. EPI E ELISÃO DA INSALUBRIDADE (5 questões)
        # =========================================================
        # 36
        ("A Súmula nº 80 do Tribunal Superior do Trabalho (TST) dispõe expressamente que a eliminação da insalubridade mediante fornecimento de aparelhos protetores aprovados pelo órgão competente:",
         "Exclui a percepção do respectivo adicional de insalubridade.",
         "Obriga a empresa a pagar o dobro do adicional de insalubridade.",
         "Transforma a insalubridade em adicional de periculosidade automático.",
         "Não tem nenhum efeito jurídico perante os tribunais do trabalho.",
         "Exige que o empregado trabalhe 16 horas por dia aos sábados e domingos.",
         "A",
         "A Súmula 80 do TST prevê que a eliminação eficaz da insalubridade pelo uso de protetores com CA válido afasta a obrigatoriedade do pagamento do adicional.",
         "Súmula 80 do TST",
         "fácil"),
        # 37
        ("Entretanto, a Súmula nº 289 do TST complementa o entendimento sobre a neutralização da insalubridade, fixando que:",
         "O simples fornecimento do aparelho de proteção pelo empregador não o exime do pagamento do adicional de insalubridade, cabendo-lhe tomar as medidas que conduzam à diminuição ou eliminação da nocividade, entre as quais as relativas ao uso efetivo do equipamento pelo empregado.",
         "Basta a empresa comprar os protetores e deixá-los trancados no armário do SESMT.",
         "A responsabilidade de fiscalizar o uso do EPI é unicamente da polícia militar estadual.",
         "O empregado pode usar ou não o EPI conforme seu gosto e mesmo assim afastar o adicional.",
         "A entrega do EPI isenta a empresa de realizar exames médicos ocupacionais do PCMSO.",
         "A",
         "A Súmula 289 do TST impõe a obrigação patronal de fiscalizar, exigir o uso efetivo, fornecer treinamento e repor o EPI para que se configure a efetiva elisão da insalubridade.",
         "Súmula 289 do TST",
         "fácil"),
        # 38
        ("A neutralização ou eliminação da insalubridade por meio de EPI nos termos do item 15.4.1 da NR-15 exige obrigatoriamente:",
         "O fornecimento gratuito de EPI com Certificado de Aprovação (CA) válido, compatível com o risco, treinamento adequado para o uso, fiscalização contínua e higienização/manutenção periódica.",
         "Apenas uma declaração verbal do trabalhador afirmando que não se incomoda com o agente agressivo.",
         "O desconto do valor das luvas no vale-alimentação do funcionário todo mês.",
         "O uso de EPIs importados comprados sem registro no Ministério do Trabalho e Emprego.",
         "A dispensa do uso do equipamento caso o ambiente esteja muito quente.",
         "A",
         "A eficácia do EPI para elisão de insalubridade depende do CA válido, especificação correta, higienização, treinamento e comprovação documental do fornecimento e fiscalização.",
         "NR-15, item 15.4.1 e NR-06",
         "média"),
        # 39
        ("Em relação aos agentes biológicos do Anexo nº 14 da NR-15 (como em áreas de isolamento de doenças infectocontagiosas graves), qual é o entendimento pericial e jurisprudencial predominante sobre a elisão da insalubridade de GRAU MÁXIMO pelo uso de luvas e máscaras?",
         "Geralmente não elide a insalubridade de grau máximo, tendo em vista a alta virulência e patogenicidade dos agentes, a possibilidade de aerolização e a suscetibilidade a acidentes ou falhas na paramentação/desparamentação.",
         "Elide completamente a insalubridade se o trabalhador usar uma máscara de pano feita em casa.",
         "Basta borrifar álcool líquido nas mãos uma vez por mês para afastar qualquer insalubridade biológica.",
         "O uso de luvas de borracha transforma o hospital em ambiente 100% esterilizado e seguro.",
         "A insalubridade é automaticamente cancelada se o funcionário tomar um copo de leite.",
         "A",
         "Em pacientes de isolamento infectocontagioso grave (grau máximo), o risco de falha de vedação ou contaminação na retirada dos EPIs mantém a caracterização da insalubridade.",
         "Jurisprudência Trabalhista TST e Perícias Judiciais",
         "média"),
        # 40
        ("Para comprovar juridicamente que um protetor auricular do tipo concha atenuou o ruído ambiente de 92 dB(A) para patamares inferiores a 85 dB(A) (eliminando a insalubridade):",
         "A empresa deve demonstrar o Nível de Redução de Ruído Subject Fit (NRRsf) do EPI com CA válido, ficha de entrega assinada pelo empregado e comprovação de treinamento e substituição periódica.",
         "Apenas perguntar ao trabalhador se ele escutou os cochichos dos colegas na hora do café.",
         "Medir a altura do trabalhador e o tamanho das suas orelhas externas com régua de plástico.",
         "Apresentar uma foto do funcionário sorrindo com o protetor colocado na cabeça.",
         "Comprovar que o trabalhador nunca assistiu a shows musicais em sua vida particular.",
         "A",
         "A elisão de ruído requer cálculo pericial da atenuação pelo NRRsf do CA, documentação de entrega (ficha de EPI), fiscalização e higienização/troca regular.",
         "Higiene Ocupacional Fundacentro e NR-15",
         "média")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-15",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr15_questions()
    print(f"NR-15 questions generated: {len(q)}")
