# -*- coding: utf-8 -*-
"""
Gerador de Questões de Legislação Previdenciária (30 questões)
- CAT (Comunicação de Acidente de Trabalho): 15 questões
- Estabilidade Provisória Acidentária (Art. 118 Lei 8.213/91): 10 questões
- PPP e LTCAT: 5 questões
"""

def get_previdenciaria_questions():
    items = [
        # =========================================================
        # 1. CAT - COMUNICAÇÃO DE ACIDENTE DE TRABALHO (15 questões)
        # =========================================================
        # 1
        ("Nos termos do Artigo 22 da Lei Federal nº 8.213/1991, a empresa deverá comunicar o acidente do trabalho à Previdência Social até:",
         "O primeiro dia útil seguinte ao da ocorrência e, em caso de morte, de imediato, à autoridade competente, sob pena de multa.",
         "O prazo improrrogável de trinta dias úteis a contar do mês seguinte.",
         "O término do contrato de trabalho do acidentado.",
         "A homologação rescisória no sindicato da categoria.",
         "O momento em que o acidentado completar 65 anos de idade.",
         "A",
         "O Art. 22 da Lei 8.213/91 estipula o prazo: até o 1º dia útil seguinte ao acidente e, havendo óbito, de imediato, sob pena de multa prevista no Art. 286 do RPS.",
         "Lei 8.213/1991, Art. 22",
         "fácil"),
        # 2
        ("Em caso de acidente de trabalho que resulte na MORTE imediata do trabalhador, a comunicação à autoridade competente deve ser realizada:",
         "De imediato.",
         "Em até 30 dias após o sepultamento.",
         "No final do ano fiscal durante a assembleia de prestação de contas.",
         "Apenas após o trânsito em julgado de ação indenizatória na Justiça Federal.",
         "Em até 6 meses mediante publicação em jornal de grande circulação.",
         "A",
         "A redação da Lei 8.213/91, Art. 22, é taxativa: '... e, em caso de morte, de imediato'.",
         "Lei 8.213/1991, Art. 22",
         "fácil"),
        # 3
        ("Caso a empresa ou a fundação hospitalar NÃO emita a CAT no prazo legal, quem são os legitimados concorrentes que podem formalizá-la perante a Previdência Social?",
         "O próprio acidentado, seus dependentes, a entidade sindical competente, o médico que o assistiu ou qualquer autoridade pública.",
         "Apenas o presidente da república por decreto privativo.",
         "Exclusivamente o perito contador judicial de falências.",
         "Apenas o vizinho de residência mais idoso do trabalhador.",
         "Ninguém mais pode emitir a CAT, perecendo o direito para sempre.",
         "A",
         "O § 2º do Art. 22 da Lei 8.213/91 confere legitimidade subsidiária ao próprio acidentado, dependentes, sindicato, médico assistente ou qualquer autoridade pública.",
         "Lei 8.213/1991, Art. 22, § 2º",
         "fácil"),
        # 4
        ("A emissão subsidiária da CAT por terceiros legitimados (como o sindicato ou o próprio empregado):",
         "Não exime a empresa da aplicação da multa legal por descumprimento de prazo.",
         "Perdoa automaticamente a empresa de todas as sanções administrativas.",
         "Transfere a obrigação do pagamento de salários para o sindicato emitente.",
         "Obriga o médico assistente a pagar indenização civil ao hospital.",
         "Cancela o contrato de trabalho por justa causa do acidentado.",
         "A",
         "O § 3º do Art. 22 da Lei 8.213/91 estabelece que a emissão da CAT por terceiros não desonera o empregador da multa pelo atraso na comunicação obrigatória.",
         "Lei 8.213/1991, Art. 22, § 3º",
         "fácil"),
        # 5
        ("Se um técnico de enfermagem sofrer um ferimento por picada de agulha com sangue contaminado na FHCGV, mas a lesão física for superficial e NÃO resultar em afastamento do trabalho:",
         "A CAT deve ser emitida obrigatoriamente, pois a comunicação independe da existência de afastamento das atividades laborais.",
         "A CAT é dispensada, pois só se emite comunicação de acidente se houver amputação de membros.",
         "A CAT só deve ser emitida caso o trabalhador venha a falecer.",
         "A fundação deve manter a ocorrência em segredo para não prejudicar suas estatísticas.",
         "O técnico deve ser suspenso por 5 dias para cicatrização do ferimento.",
         "A",
         "O acidente de trabalho exige registro e emissão de CAT mesmo que não haja incapacidade temporária (sem afastamento), para acompanhamento profilático e legal.",
         "Art. 22 da Lei 8.213/91 e Manual da CAT",
         "fácil"),
        # 6
        ("Quais são os três tipos de Comunicação de Acidente de Trabalho (CAT) previstos na regulamentação previdenciária?",
         "CAT Inicial, CAT de Reabertura e CAT de Comunicação de Óbito.",
         "CAT Pequena, CAT Média e CAT Grande.",
         "CAT Simples, CAT Dobrada e CAT Tripla.",
         "CAT Provisória, CAT Temporária e CAT Definitiva.",
         "CAT Matutina, CAT Vespertina e CAT Noturna.",
         "A",
         "Os tipos oficiais de CAT são: Inicial (ocorrência inicial ou doença), Reabertura (reinício de tratamento ou agravamento) e Óbito (morte decorrente do acidente inicial).",
         "Instrução Normativa INSS e Manual do eSocial",
         "fácil"),
        # 7
        ("A CAT de REABERTURA deve ser emitida quando:",
         "Houver reinício de tratamento médico ou agravamento de lesão decorrente de acidente de trabalho ou doença ocupacional anteriormente comunicada.",
         "A empresa desejar anular o acidente registrado há três anos.",
         "O trabalhador for admitido em um segundo emprego na iniciativa privada.",
         "O empregador trocar a razão social do estabelecimento comercial.",
         "O sindicato dos trabalhadores eleger uma nova diretoria.",
         "A",
         "A CAT de reabertura aplica-se quando um acidente ou doença já comunicado anteriormente volta a demandar assistência médica ou gera nova incapacidade por recidiva/agravamento.",
         "IN INSS nº 128/2022",
         "fácil"),
        # 8
        ("O acidente sofrido pelo trabalhador no percurso da sua residência para o local de trabalho ou deste para aquela, qualquer que seja o meio de locomoção (acidente de trajeto):",
         "É equiparado a acidente do trabalho para todos os efeitos previdenciários nos termos do Artigo 21, inciso IV, alínea 'd' da Lei nº 8.213/1991.",
         "É considerado desvio de conduta e falta grave disciplinar do funcionário.",
         "Não tem qualquer relação com o trabalho, devendo ser registrado como crime de trânsito comum.",
         "Só se equipara ao trabalho caso o trabalhador utilize bicicleta da própria empresa.",
         "Perdeu a cobertura previdenciária em todo o território nacional de forma definitiva.",
         "A",
         "O Art. 21, IV, 'd' da Lei 8.213/91 equipara o acidente de trajeto ao acidente de trabalho, assegurando todos os direitos previdenciários e acidentários ao segurado.",
         "Lei 8.213/1991, Art. 21, IV, 'd'",
         "fácil"),
        # 9
        ("A doença profissional (ergopatia) e a doença do trabalho (mesopatia) são legalmente equiparadas ao acidente de trabalho pelo Artigo 20 da Lei nº 8.213/1991. Para fins de marco temporal de emissão da CAT na doença ocupacional, considera-se dia do acidente:",
         "A data do início da incapacidade laborativa para o exercício da atividade habitual, ou o dia da segregação compulsória, ou o dia em que for realizado o diagnóstico médico.",
         "O primeiro dia de vida do empregado registrado na certidão de nascimento.",
         "O dia em que a empresa foi fundada na Junta Comercial do Estado.",
         "O dia do término do período de experiência de 90 dias.",
         "A data do último recesso de final de ano do hospital.",
         "A",
         "Conforme o Art. 23 da Lei 8.213/91, considera-se como dia do acidente na doença ocupacional a data do início da incapacidade ou o dia da realização do diagnóstico conclusivo.",
         "Lei 8.213/1991, Art. 23",
         "média"),
        # 10
        ("Atualmente, o canal eletrônico oficial pelo qual as empresas privadas e órgãos públicos contratantes pelo regime celetista devem enviar a CAT ao ambiente nacional do governo federal é:",
         "O evento S-2210 (Comunicação de Acidente de Trabalho) do Sistema de Escrituração Digital das Obrigações Fiscais, Previdenciárias e Trabalhistas (eSocial).",
         "Uma carta manuscrita enviada por pombo-correio aos cuidados da agência central.",
         "Um anúncio nos classificados de jornal impresso de domingo.",
         "Uma mensagem de áudio enviada para a rádio comunitária do município.",
         "Um fax impresso enviado para o Ministério da Agricultura.",
         "A",
         "A CAT é transmitida digitalmente pelo evento S-2210 do eSocial, unificando a recepção da informação pelo Ministério do Trabalho, Receita Federal e Previdência Social.",
         "Manual do eSocial e Portaria Conjunta MTP/RFB",
         "fácil"),
        # 11
        ("Qual a importância jurídica da comprovação do NEXO TÉCNICO EPIDEMIOLÓGICO PREVIDENCIÁRIO (NTEP) entre a atividade econômica da FHCGV (CNAE de atividades hospitalares) e as doenças osteomusculares e infecciosas (CID-10)?",
         "Estabelece a presunção legal relativa de que a doença é decorrente do trabalho, convertendo o benefício para a modalidade acidentária (B91), cabendo à empresa o ônus de produzir prova em contrário.",
         "Impede que qualquer médico conceda atestado de repouso aos trabalhadores.",
         "Obriga o INSS a demitir todos os servidores da perícia médica federal.",
         "Isenta o hospital do pagamento de FGTS dos empregados sadios.",
         "Determina que todos os doentes sejam multados pelo Ministério da Fazenda.",
         "A",
         "O NTEP (Art. 21-A da Lei 8.213/91) cruza o CNAE da empresa com a CID da patologia; havendo correlação estatística, presume-se o nexo ocupacional, cabendo contraprova à organização.",
         "Lei 8.213/1991, Art. 21-A",
         "média"),
        # 12
        ("Não são consideradas como doença do trabalho pela Lei nº 8.213/1991 (Art. 20, § 1º):",
         "A doença degenerativa, a inerente a grupo de faixa etária e a que não produza incapacidade laborativa.",
         "A febre tifóide e a tuberculose contraídas em ambiente de internação de infectologia.",
         "A tendinite do manguito rotador decorrente de movimentação excessiva de cargas pesadas.",
         "A síndrome do túnel do carpo decorrente de digitação contínua sem pausas ergonômicas.",
         "A hepatite B transmitida por perfuração com agulha cirúrgica no centro obstétrico.",
         "A",
         "O Art. 20, § 1º da Lei 8.213/91 exclui do conceito de doença do trabalho: degenerativas, etárias, as sem incapacidade e as endêmicas (salvo comprovação de exposição direta).",
         "Lei 8.213/1991, Art. 20, § 1º",
         "fácil"),
        # 13
        ("Em relação à doença endêmica (como Malária ou Dengue), ela pode ser considerada doença do trabalho pelo INSS?",
         "Geralmente não, SALVO comprovação de que é resultante de exposição ou contato direto determinado pela natureza do trabalho exercido (Art. 20, § 1º, 'd' da Lei 8.213/91).",
         "Sim, qualquer gripe ou resfriado comum é automaticamente doença do trabalho.",
         "Nunca, sob nenhuma circunstância, mesmo para pesquisadores picados em laboratório.",
         "Apenas se o mosquito transmissor tiver sido contratado com carteira assinada pela empresa.",
         "Apenas se a cidade inteira estiver de quarentena nacional.",
         "A",
         "A doença endêmica só se equipara a doença do trabalho se comprovado que o trabalhador se expôs ao vetor/patógeno em razão exclusiva de sua atividade ocupacional.",
         "Lei 8.213/1991, Art. 20, § 1º, alínea 'd'",
         "média"),
        # 14
        ("Durante os primeiros 15 dias consecutivos de afastamento decorrente de acidente de trabalho ou doença ocupacional, o pagamento da remuneração integral do trabalhador celetista é de responsabilidade:",
         "Da empresa empregadora.",
         "Do INSS mediante pagamento direto no balcão da agência.",
         "Do sindicato da categoria através de doações voluntárias.",
         "Do Fundo de Amparo ao Trabalhador (FAT).",
         "Da Organização das Nações Unidas (ONU).",
         "A",
         "A empresa responde pelo pagamento integral do salário durante os primeiros 15 dias de afastamento (Art. 60, § 3º da Lei 8.213/91); o INSS assume a partir do 16º dia.",
         "Lei 8.213/1991, Art. 60, § 3º",
         "fácil"),
        # 15
        ("Se a empresa deixar de recolher o Fundo de Garantia do Tempo de Serviço (FGTS) durante o período em que o trabalhador acidentado estiver recebendo auxílio por incapacidade temporária ACIDENTÁRIO (B91) do INSS:",
         "A empresa descumpre obrigação legal, pois o Art. 15, § 5º da Lei nº 8.036/1990 torna OBRIGATÓRIO o depósito mensal do FGTS nos casos de afastamento por acidente de trabalho ou doença ocupacional.",
         "A conduta é legalmente correta, pois trabalhador afastado nunca tem depósito de FGTS.",
         "A empresa recebe desconto nos tributos estaduais do ICMS.",
         "O trabalhador deve devolver todo o saldo do FGTS já acumulado.",
         "O contrato de trabalho é considerado automaticamente extinto.",
         "A",
         "Diferente do auxílio-doença comum (B31), no afastamento acidentário (B91) a empresa continua obrigada a depositar o FGTS mensalmente durante todo o período de afastamento.",
         "Lei 8.036/1990, Art. 15, § 5º",
         "média"),

        # =========================================================
        # 2. ESTABILIDADE PROVISÓRIA ACIDENTÁRIA (10 questões)
        # =========================================================
        # 16
        ("O Artigo 118 da Lei Federal nº 8.213/1991 assegura ao trabalhador que sofreu acidente do trabalho a garantia provisória de emprego pelo prazo mínimo de:",
         "Doze meses após a cessação do benefício por incapacidade acidentário (antigo auxílio-doença acidentário).",
         "Seis meses a contar do dia em que ocorreu a queda no local de trabalho.",
         "Cinco anos a partir da data de admissão na empresa.",
         "Trinta dias contados da entrega da ficha de EPI.",
         "Duas semanas após a realização do exame periódico anual.",
         "A",
         "O Art. 118 da Lei 8.213/91 concede estabilidade de 12 meses, contados a partir da cessação do benefício acidentário concedido pelo INSS.",
         "Lei 8.213/1991, Art. 118",
         "fácil"),
        # 17
        ("De acordo com a Súmula nº 378, item II, do Tribunal Superior do Trabalho (TST), são pressupostos cumulativos para a concessão da estabilidade acidentária do Artigo 118 da Lei nº 8.213/1991:",
         "O afastamento do trabalho por prazo superior a 15 dias e a consequente percepção do auxílio por incapacidade temporária acidentário (código B91), salvo se constatada, após a despedida, doença profissional que guarde relação de causalidade com o trabalho.",
         "Apenas o recebimento de qualquer tipo de atestado de 1 dia assinado por dentista.",
         "A filiação partidária a grêmios estudantis e sindicatos por mais de 5 anos.",
         "O trabalho em horário noturno por pelo menos 3 meses contínuos.",
         "A assinatura de duas advertências disciplinares pelo encarregado do setor.",
         "A",
         "A Súmula 378, II do TST fixa a regra geral: afastamento > 15 dias + percepção do benefício B91 (ou comprovação posterior de doença profissional com nexo de causalidade).",
         "Súmula 378, II do TST",
         "fácil"),
        # 18
        ("Um técnico de enfermagem da FHCGV sofreu entorse de tornozelo no trabalho e ficou afastado por 8 DIAS com atestado médico, retornando logo em seguida às suas funções normais. Nesse caso:",
         "Ele NÃO adquire a estabilidade provisória do Art. 118 da Lei 8.213/91, pois o afastamento foi inferior a 15 dias e não houve concessão de benefício acidentário pelo INSS.",
         "Ele adquire 5 anos de estabilidade absoluta e vitalícia no serviço público.",
         "A empresa fica proibida de alterar o horário de seu almoço por 2 anos.",
         "O empregado deve ser promovido a diretor administrativo imediatamente.",
         "Ele tem direito a uma indenização equivalente a 100 salários mínimos.",
         "A",
         "Afastamentos de até 15 dias pagos pelo empregador sem ingresso no INSS e sem benefício B91 não geram a garantia de emprego de 12 meses do Art. 118 da Lei 8.213/91.",
         "Súmula 378, II do TST",
         "fácil"),
        # 19
        ("Segundo o item III da Súmula nº 378 do TST, o empregado submetido a CONTRATO DE TRABALHO POR TEMPO DETERMINADO (inclusive contrato de experiência):",
         "Gosa da garantia provisória de emprego decorrente de acidente de trabalho prevista no Artigo 118 da Lei nº 8.213/1991.",
         "Não tem direito a estabilidade sob nenhuma hipótese por ser contrato temporário.",
         "Perde imediatamente o direito a receber atendimento médico de urgência.",
         "Pode ser dispensado sumariamente sem receber sequer os dias trabalhados.",
         "Tem seu contrato transformado em prestação de serviços voluntários gratuitos.",
         "A",
         "A Súmula 378, III do TST estendeu expressamente a estabilidade acidentária aos contratos a prazo determinado, inclusive ao contrato de experiência.",
         "Súmula 378, III do TST",
         "fácil"),
        # 20
        ("Se a empresa dispensar SEM JUSTA CAUSA um trabalhador que esteja no gozo do período de estabilidade provisória acidentária de 12 meses:",
         "A dispensa é nula, tendo o trabalhador direito à REINTEGRAÇÃO ao emprego ou, caso desaconselhável ou exaurido o período estabilitário, à INDENIZAÇÃO substitutiva correspondente aos salários e vantagens de todo o período (Súmula 396 do TST).",
         "A dispensa é válida e a empresa não precisa pagar nenhuma indenização ao operário.",
         "O trabalhador deve pagar uma multa de R$ 10.000,00 à Justiça do Trabalho.",
         "O trabalhador é obrigado a trabalhar de graça por 1 ano para compensar o patrão.",
         "O Ministério do Trabalho cancela o CPF do trabalhador dispensado.",
         "A",
         "A dispensa arbitrária no período estabilitário impõe a reintegração com pagamento dos salários vencidos ou a conversão em indenização pecuniária substitutiva integral.",
         "Súmula 396 do TST e Art. 118 Lei 8.213/91",
         "fácil"),
        # 21
        ("Durante o período de 12 meses de estabilidade acidentária, o empregado acidentado pode ser demitido por JUSTA CAUSA?",
         "Sim, a estabilidade acidentária veda a dispensa imotivada (sem justa causa), mas não impede a dispensa por justa causa caso o empregado cometa falta grave prevista no Artigo 482 da CLT.",
         "Não, o empregado com estabilidade adquire imunidade absoluta e não pode ser punido nem mesmo se praticar furtos ou agressões físicas no local de trabalho.",
         "Apenas se o presidente da fundação hospitalar for autorizado pela CIPA.",
         "Apenas se o trabalhador concordar por escrito em ser demitido.",
         "Não, justa causa é terminantemente proibida na CLT brasileira.",
         "A",
         "A garantia provisória obsta a rescisão unilateral sem motivo; o cometimento de falta grave tipificada no Art. 482 da CLT autoriza a rescisão motivada (justa causa).",
         "CLT Art. 482 e Doutrina Trabalhista",
         "fácil"),
        # 22
        ("Qual é a diferença fundamental entre o benefício de código B31 (Auxílio por Incapacidade Temporária Previdenciário comum) e o código B91 (Auxílio por Incapacidade Temporária Acidentário)?",
         "O B91 decorre de acidente de trabalho ou doença ocupacional, gerando direito à estabilidade provisória de 12 meses e continuidade dos depósitos do FGTS; o B31 decorre de doença/acidente comum sem relação com o trabalho, não gerando estabilidade nem depósito de FGTS.",
         "Não existe nenhuma diferença, os dois códigos foram criados por acaso.",
         "O B31 é pago pelo governo e o B91 é pago pelo sindicato dos metalúrgicos.",
         "O B91 exige que o trabalhador tenha mais de 80 anos de idade.",
         "O B31 é destinado exclusivamente a cidadãos estrangeiros sem visto.",
         "A",
         "O benefício acidentário (B91) confere garantias materiais substanciais: estabilidade acidentária de 1 ano após a alta e recolhimento patronal do FGTS durante o afastamento.",
         "Lei 8.213/1991 e Lei 8.036/1990",
         "fácil"),
        # 23
        ("Se o trabalhador for demitido sem justa causa e, meses após a demissão, for constatada mediante perícia judicial a existência de doença ocupacional adquirida durante o contrato:",
         "Ele terá reconhecido o direito à estabilidade acidentária (Súmula 378, II, parte final, do TST), fazendo jus à indenização do período de garantia de emprego.",
         "Ele perde qualquer direito porque a perícia ocorreu após o término do vínculo de emprego.",
         "O juiz deve condenar o trabalhador por litigância de má-fé.",
         "A empresa fica isenta de qualquer responsabilidade civil ou trabalhista.",
         "O laudo médico pericial é nulo se não for assinado pelo dono da empresa.",
         "A",
         "A parte final da Súmula 378, II do TST protege o empregado dispensado doente: o nexo causal comprovado após a rescisão convalida o direito à garantia estabilitária acidentária.",
         "Súmula 378, II do TST",
         "média"),
        # 24
        ("Caso o prazo de 12 meses da estabilidade acidentária já tenha decorrido integralmente no momento em que for proferida a sentença trabalhista:",
         "A reintegração não é mais cabível, sendo devida ao empregado unicamente a indenização substitutiva correspondente aos salários e reflexos do período estabilitário vencido (Súmula 396, I, do TST).",
         "O trabalhador perde o direito a receber qualquer indenização em dinheiro.",
         "O empregador é obrigado a contratar o filho mais velho do reclamante.",
         "O juiz deve fechar o hospital e mandar prender todos os gerentes.",
         "O período de estabilidade é renovado automaticamente por mais 10 anos.",
         "A",
         "Conforme a Súmula 396, I do TST, exaurido o período estabilitário, são devidos ao empregado apenas os salários do período compreendido entre a data da despedida e o final da estabilidade.",
         "Súmula 396, I do TST",
         "fácil"),
        # 25
        ("A renúncia expressa do trabalhador ao direito da estabilidade provisória acidentária em documento assinado sob coação patronal no departamento de recursos humanos:",
         "É absolutamente nula de pleno direito, em virtude do princípio trabalhista da irrenunciabilidade de direitos e do Artigo 9º da CLT.",
         "É plenamente válida e irrevogável perante o Poder Judiciário.",
         "Garante à empresa um prêmio financeiro de produtividade jurídica.",
         "Faz com que o trabalhador perca a sua carteira de identidade civil.",
         "Exige apenas o reconhecimento de firma em cartório para convalidar o ato.",
         "A",
         "Normas de saúde e segurança e estabilidade acidentária são de ordem pública (Art. 9º da CLT e Art. 118 da Lei 8.213/91), sendo nula qualquer renúncia forçada de direitos.",
         "CLT Art. 9º e Princípios do Direito do Trabalho",
         "fácil"),

        # =========================================================
        # 3. PPP E LTCAT (5 questões)
        # =========================================================
        # 26
        ("O Laudo Técnico das Condições Ambientais do Trabalho (LTCAT), previsto no Artigo 58 da Lei Federal nº 8.213/1991, é o documento técnico privativo elaborado por:",
         "Médico do Trabalho ou Engenheiro de Segurança do Trabalho, nos termos da legislação trabalhista e previdenciária.",
         "Qualquer funcionário do setor financeiro ou contábil do hospital.",
         "Técnico em contabilidade recém-formado no ensino médio.",
         "Comissão de pacientes voluntários internados na fundação.",
         "Advogado particular sem registro em conselho de engenharia ou medicina.",
         "A",
         "O Art. 58, § 1º da Lei 8.213/91 é taxativo: o LTCAT é emitido exclusivamente por Médico do Trabalho ou Engenheiro de Segurança do Trabalho habilitados.",
         "Lei 8.213/1991, Art. 58, § 1º",
         "fácil"),
        # 27
        ("O LTCAT tem como finalidade primordial perante a Previdência Social (INSS):",
         "Comprovar a efetiva exposição habitual e permanente do trabalhador a agentes nocivos químicos, físicos, biológicos ou associação de agentes para fins de concessão de APOSENTADORIA ESPECIAL.",
         "Calcular a alíquota do Imposto Predial e Territorial Urbano da prefeitura.",
         "Determinar a escala de férias de verão dos médicos diretores.",
         "Definir a marca de ar condicionado que deve ser comprada pelo almoxarifado.",
         "Autorizar a demolição de prédios tombados pelo patrimônio histórico.",
         "A",
         "O LTCAT é o laudo estritamente previdenciário que embasa a caracterização da nocividade ambiental para a concessão da Aposentadoria Especial (Art. 57 e 58 da Lei 8.213/91).",
         "Lei 8.213/1991, Art. 58",
         "fácil"),
        # 28
        ("O Perfil Profissiográfico Previdenciário (PPP) é o documento histórico-laboral individual que deve ser emitido pelo empregador contendo:",
         "Dados administrativos da empresa e do trabalhador, descrição das atividades desempenhadas, registros ambientais de exposição a agentes nocivos e monitoração biológica (PCMSO).",
         "A lista de todos os filmes cinematográficos assistidos pelo trabalhador nos fins de semana.",
         "O comprovante de votação em eleições municipais dos últimos 30 anos.",
         "O valor do limite do cartão de crédito particular do empregado.",
         "A árvore genealógica de todos os antepassados do trabalhador desde o século XIX.",
         "A",
         "O PPP compila o histórico funcional, os fatores de risco ambiental do LTCAT, a eficácia do EPI e os exames do PCMSO ao longo de todo o contrato de trabalho.",
         "IN INSS nº 128/2022 e Lei 8.213/1991",
         "fácil"),
        # 29
        ("A partir de 1º de janeiro de 2023, o Perfil Profissiográfico Previdenciário (PPP) passou a ser emitido obrigatoriamente em qual formato para todos os trabalhadores segurados?",
         "Exclusivamente em formato ELETRÔNICO (PPP Digital), emitido pelo INSS com base nos dados dos eventos de SST enviados pelas empresas ao eSocial (S-2220 e S-2240).",
         "Em pergaminho de couro de cabra manuscrito com pena e tinta nanquim.",
         "Em folhas de papelão grosso dobradas guardadas em caixas de sapatos.",
         "Em placas de alumínio gravadas a laser para afixação na porta de entrada.",
         "O PPP foi totalmente extinto e proibido no Brasil desde 2023.",
         "A",
         "A Portaria MTP nº 313/2021 instituiu o PPP Eletrônico obrigatório a partir de 01/01/2023, consultável pelo trabalhador através do aplicativo Meu INSS alimentado pelo eSocial.",
         "Portaria MTP nº 313/2021 e IN INSS nº 128/2022",
         "fácil"),
        # 30
        ("Qual é a obrigação legal da FHCGV quanto ao fornecimento do PPP ao trabalhador no momento da rescisão do contrato de trabalho?",
         "A organização deve disponibilizar ou fornecer cópia autêntica do PPP ao trabalhador no momento da rescisão do contrato, sob pena de infração e multa da legislação previdenciária.",
         "A fundação é expressamente proibida de deixar o trabalhador ver o conteúdo do PPP.",
         "O PPP só pode ser entregue aos herdeiros após o falecimento do trabalhador.",
         "A entrega do documento está condicionada ao pagamento de taxa de R$ 500,00 pelo servidor.",
         "O PPP deve ser destruído na trituradora de papel na frente do trabalhador demitido.",
         "A",
         "O Art. 58, § 4º da Lei 8.213/91 impõe à empresa o dever de fornecer cópia autêntica do PPP ao trabalhador por ocasião da rescisão contratual ou quando solicitado para fins previdenciários.",
         "Lei 8.213/1991, Art. 58, § 4º",
         "fácil")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "Legislação Previdenciária",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_previdenciaria_questions()
    print(f"Legislação Previdenciária questions generated: {len(q)}")
