# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-07: PCMSO (40 questões)
- Exames médicos: 20 questões
- ASO: 10 questões
- Periodicidade: 10 questões
"""

def get_nr07_questions():
    items = [
        # =========================================================
        # 1. EXAMES MÉDICOS (20 questões)
        # =========================================================
        # 1
        ("O Programa de Controle Médico de Saúde Ocupacional (PCMSO), disciplinado pela NR-07, compreende obrigatoriamente a realização de quais exames médicos?",
         "Admissional, periódico, de retorno ao trabalho, de mudança de riscos ocupacionais e demissional.",
         "Apenas o exame admissional no primeiro dia e o demissional no último dia.",
         "Apenas exames de sangue para detecção de anemia em doadores voluntários.",
         "Exame pré-nupcial, exame de direção veicular e teste de aptidão física militar.",
         "Consultas pediátricas para filhos dos funcionários menores de cinco anos.",
         "A",
         "O item 7.5.6 da NR-07 estabelece os 5 exames médicos ocupacionais obrigatórios: admissional, periódico, retorno ao trabalho, mudança de riscos e demissional.",
         "NR-07, item 7.5.6",
         "fácil"),
        # 2
        ("O exame médico ADMISSIONAL deve ser realizado obrigatoriamente:",
         "Antes que o trabalhador assuma as suas atividades na instituição.",
         "No prazo de até 30 dias após o início do trabalho em ambiente cirúrgico.",
         "Apenas após o término do período de experiência de 90 dias.",
         "No primeiro dia útil após o recebimento do primeiro salário mensal.",
         "Exclusivamente se o empregado apresentar queixas clínicas na entrevista de RH.",
         "A",
         "Conforme o subitem 7.5.7 da NR-07, o exame admissional deve ser realizado antes que o trabalhador assuma suas atividades.",
         "NR-07, item 7.5.7",
         "fácil"),
        # 3
        ("O exame médico de RETORNO AO TRABALHO deve ser realizado obrigatoriamente no primeiro dia da volta ao trabalho de trabalhador ausente por período:",
         "Igual ou superior a 30 dias por motivo de doença ou acidente, de natureza ocupacional ou não.",
         "Superior a 5 dias decorrentes de gripe comum ou virose intestinal passageira.",
         "De 24 horas por motivo de doação voluntária de sangue comprovada.",
         "Superior a 3 dias por motivo de casamento civil ou falecimento de parente.",
         "De 10 dias de férias regulamentares anuais remuneradas.",
         "A",
         "O subitem 7.5.9 da NR-07 determina que o exame de retorno ao trabalho seja feito no 1º dia de volta após afastamento igual ou superior a 30 dias por doença/acidente.",
         "NR-07, item 7.5.9",
         "fácil"),
        # 4
        ("No caso de retorno ao trabalho de trabalhadora após o término da licença-maternidade, a realização do exame de retorno ao trabalho:",
         "Deve ser realizada se a trabalhadora esteve afastada por período igual ou superior a 30 dias, avaliando sua aptidão física e psíquica para a reassunção de suas atividades.",
         "É expressamente proibida pela Constituição Federal para não constranger a mãe.",
         "Deve ser realizada exclusivamente pelo médico obstetra particular sem ASO.",
         "Fica dispensada para sempre se o parto tiver sido natural sem complicações.",
         "Deve ser substituída por uma declaração da avó da criança atestando saúde.",
         "A",
         "O afastamento por parto/maternidade superior a 30 dias enseja o exame de retorno ao trabalho no 1º dia de retorno para avaliar condições clínicas frente às tarefas.",
         "NR-07, item 7.5.9",
         "média"),
        # 5
        ("O exame médico de MUDANÇA DE RISCOS OCUPACIONAIS deve, obrigatoriamente, ser realizado:",
         "Antes da data da mudança efetiva de setor ou atividade, sempre que houver alteração nos riscos aos quais o trabalhador estava exposto.",
         "Seis meses após o trabalhador já estar desempenhando a nova função com riscos maiores.",
         "Apenas se o trabalhador reclamar formalmente com o sindicato de sua categoria.",
         "Apenas quando houver redução do salário base do empregado.",
         "No momento de sua aposentadoria especial definitiva pelo INSS.",
         "A",
         "O subitem 7.5.10 da NR-07 exige que o exame de mudança de riscos seja realizado ANTES da alteração de atividade, assegurando que o trabalhador está apto ao novo risco.",
         "NR-07, item 7.5.10",
         "fácil"),
        # 6
        ("O exame médico DEMISSIONAL deve ser realizado no prazo de até:",
         "Dez dias contados do término do contrato de trabalho.",
         "Trinta dias antes do trabalhador comunicar que deseja pedir demissão.",
         "Seis meses após o desligamento e a homologação rescisória.",
         "Vinte e quatro horas antes do aviso prévio se iniciar.",
         "Um ano após a rescisão com pagamento de juros pelo empregador.",
         "A",
         "O subitem 7.5.11 da NR-07 prevê que o exame demissional deve ser realizado em até 10 dias contados do término do contrato.",
         "NR-07, item 7.5.11",
         "fácil"),
        # 7
        ("Em relação ao exame demissional, a NR-07 prevê que ele pode ser DISPENSADO caso o último exame médico ocupacional tenha sido realizado há menos de:",
         "135 dias para estabelecimentos de graus de risco 1 e 2, ou 90 dias para estabelecimentos de graus de risco 3 e 4.",
         "30 dias para qualquer grau de risco em todo o território nacional.",
         "365 dias para hospitais gerais e prontos-socorros estaduais.",
         "730 dias para servidores concursados da área de saúde pública.",
         "15 dias exclusivamente para empresas prestadoras de vigilância armada.",
         "A",
         "O subitem 7.5.11 da NR-07 dispensa o demissional se o último exame tiver ocorrido há menos de 135 dias (graus 1 e 2) ou 90 dias (graus 3 e 4), salvo extensão por negociação.",
         "NR-07, item 7.5.11",
         "média"),
        # 8
        ("Na Fundação Hospital de Clínicas Gaspar Vianna (FHCGV), enquadrada em grau de risco 3 pelo Quadro I da NR-04, a dispensa do exame demissional só ocorreria se o último exame tivesse sido feito há menos de:",
         "90 dias.",
         "135 dias.",
         "180 dias.",
         "365 dias.",
         "30 dias.",
         "A",
         "Para estabelecimentos de grau de risco 3 (como hospitais), o prazo de aproveitamento do último exame para dispensa do demissional é de 90 dias.",
         "NR-07, item 7.5.11 e NR-04",
         "fácil"),
        # 9
        ("Os exames médicos complementares laboratoriais e gráficos do PCMSO devem ser definidos pelo médico do trabalho responsável com base em:",
         "Riscos ocupacionais identificados e classificados no PGR da empresa e no estado da arte médico-científico.",
         "Sorteio aleatório de nomes em conferências municipais de saúde.",
         "Cotas comerciais de exames estipuladas por laboratórios particulares conveniados.",
         "Idade do prédio onde o hospital está localizado geograficamente.",
         "Vontade subjetiva do trabalhador sem qualquer nexo com a sua função.",
         "A",
         "Os exames complementares do PCMSO são estritamente orientados pelo perfil de riscos ocupacionais levantados no Inventário de Riscos do PGR (NR-07, item 7.5.1).",
         "NR-07, item 7.5.1",
         "fácil"),
        # 10
        ("Para os profissionais que trabalham expostos a fontes de radiação ionizante nos serviços de diagnóstico por imagem da FHCGV, o PCMSO deve incluir periodicamente:",
         "Hemograma completo com contagem de plaquetas para monitoramento do sistema hematopoiético.",
         "Teste de esteira ergométrica com esforço máximo a cada 15 dias.",
         "Audiometria vocal de alta frequência em cabine hiperbárica.",
         "Exame de densitometria óssea dos membros inferiores mensalmente.",
         "Dosagem de ácido úrico no suor das axilas do trabalhador.",
         "A",
         "O monitoramento médico da exposição a radiações ionizantes inclui hemograma com contagem de plaquetas na admissão e nos periódicos (NR-07 e normas da CNEN).",
         "NR-07 e CNEN NN 3.01",
         "média"),
        # 11
        ("O monitoramento da exposição ocupacional ao ruído contínuo ou intermitente no PCMSO exige a realização de exames audiométricos. A audiometria de referência deve ser realizada:",
         "No exame admissional, com repouso auditivo prévio de pelo menos 14 horas.",
         "Exclusivamente durante a realização de uma cirurgia com serra óssea ligada.",
         "Após o término da jornada de trabalho sem nenhum repouso sonoro.",
         "Apenas após o trabalhador completar 60 anos de idade na empresa.",
         "Dentro do veículo de transporte coletivo a caminho do trabalho.",
         "A",
         "O Anexo II da NR-07 exige repouso auditivo de no mínimo 14 horas antes do exame audiométrico para evitar que a fadiga auditiva temporária falseie o limiar auditivo.",
         "NR-07, Anexo II",
         "fácil"),
        # 12
        ("A guarda dos prontuários médicos ocupacionais de todos os trabalhadores atendidos no PCMSO é responsabilidade do médico do trabalho, devendo ser mantidos arquivados por no mínimo:",
         "Vinte anos após o desligamento do trabalhador da instituição.",
         "Cinco anos contados da data de admissão no cargo público.",
         "Dois anos após o encerramento do contrato de estágio probatório.",
         "Seis meses a contar da data de emissão do último ASO.",
         "Cinquenta anos antes do nascimento do empregado.",
         "A",
         "O prontuário clínico individual deve ser mantido sob a guarda do médico responsável pelo PCMSO por no mínimo 20 anos após o desligamento do empregado (NR-07, item 7.6.1.1).",
         "NR-07, item 7.6.1.1",
         "fácil"),
        # 13
        ("Em caso de substituição do médico do trabalho responsável pelo PCMSO da FHCGV, os prontuários médicos dos trabalhadores devem:",
         "Ser formalmente transferidos para o novo médico responsável pelo programa, sob termo de guarda e estrito sigilo ético-profissional.",
         "Ser incinerados no pátio interno do hospital para não revelar segredos dos pacientes.",
         "Ser entregues aos gerentes do departamento de recursos humanos da fundação.",
         "Ser vendidos para empresas seguradoras de saúde para quitação de despesas.",
         "Ser abandonados no arquivo morto sem nenhum responsável técnico legal.",
         "A",
         "Havendo troca do médico do trabalho responsável, os prontuários devem ser repassados diretamente ao médico sucessor sob sigilo profissional (NR-07, subitem 7.6.1.2).",
         "NR-07, item 7.6.1.2",
         "fácil"),
        # 14
        ("O documento médico anual elaborado pelo médico do trabalho responsável pelo PCMSO que apresenta o panorama da saúde dos trabalhadores da organização é denominado:",
         "Relatório Analítico do PCMSO.",
         "Atestado de Antecedentes Criminais.",
         "Declaração de Ajuste Anual de Imposto de Renda.",
         "Guia de Recolhimento da Previdência Social.",
         "Certificado de Conclusão de Ensino Fundamental.",
         "A",
         "O Relatório Analítico do PCMSO (antigo relatório anual) detalha estatísticas de exames, prevalência de agravos, absenteísmo e recomendações preventivas para o PGR.",
         "NR-07, item 7.6.2",
         "fácil"),
        # 15
        ("O Relatório Analítico do PCMSO deve ser apresentado e discutido anualmente com:",
         "A CIPA (Comissão Interna de Prevenção de Acidentes e Assédio) e gestores do SESMT, sendo suas conclusões anexadas e consideradas no PGR.",
         "Apenas a empresa fornecedora de refeições do refeitório central.",
         "O juiz da vara da infância e da juventude da comarca da capital.",
         "A embaixada de países estrangeiros com representação consular no estado.",
         "Os pacientes internados nos leitos da enfermaria ortopédica.",
         "A",
         "A NR-07 (item 7.6.3) determina que o médico do trabalho apresente e discuta o Relatório Analítico na CIPA para subsidiar o plano de ação preventiva do PGR.",
         "NR-07, item 7.6.3 e NR-05",
         "média"),
        # 16
        ("Quando um exame complementar de monitoramento biológico indicar alteração clínica com significado clínico e nexo causal ocupacional confirmado pelo médico do trabalho:",
         "O médico deve emitir o ASO de inapto se necessário, afastar o trabalhador da exposição, emitir a CAT, encaminhar à perícia médica do INSS e orientar a revisão do PGR.",
         "O médico deve alterar o resultado laboratorial para evitar multas trabalhistas para a diretoria.",
         "O hospital deve demitir imediatamente o trabalhador sem pagar as verbas rescisórias devidas.",
         "O médico deve receitar calmantes e manter o trabalhador no mesmo posto com o dobro de horas.",
         "O SESMT deve ignorar o caso e proibir que a CIPA tenha acesso às informações.",
         "A",
         "A confirmação de agravo ocupacional exige condutas clínicas imediatas: emissão de CAT, afastamento se indicado, suporte médico e comunicação ao SESMT para revisar o PGR.",
         "NR-07, item 7.5.19 e Diretrizes de Medicina do Trabalho",
         "média"),
        # 17
        ("Nos termos da NR-07 e do Código de Ética Médica, o médico do trabalho pode revelar à gerência administrativa de RH o resultado específico dos exames laboratoriais de um trabalhador?",
         "Não, os resultados laboratoriais e diagnósticos são protegidos pelo sigilo médico, informando-se à empresa apenas a conclusão de 'Apto' ou 'Inapto' no ASO.",
         "Sim, a empresa tem o direito de afixar os exames de fezes e sangue no mural público do corredor.",
         "Sim, os exames médicos de todos os funcionários devem ser postados nas redes sociais da empresa.",
         "Apenas se o trabalhador for aprovado em concurso público estadual.",
         "Sim, desde que o chefe imediato pague uma taxa de consulta particular ao médico.",
         "A",
         "O sigilo médico é inviolável (Art. 73 do Código de Ética Médica e NR-07); a empresa só recebe a aptidão ou inaptidão ocupacional, sem acesso ao diagnóstico clínico.",
         "Código de Ética Médica e NR-07",
         "fácil"),
        # 18
        ("Caso o trabalhador seja considerado temporariamente INAPTO em um exame periódico decorrente de lesão osteomuscular por esforço repetitivo (LER/DORT):",
         "O médico deve registrar a inaptidão para a função, encaminhá-lo para tratamento especializado e, se o afastamento for superior a 15 dias, ao INSS, notificando a CAT.",
         "O trabalhador deve ser preso no almoxarifado até que cure a inflamação dos tendões.",
         "A empresa pode rebaixar seu salário para o piso regional de servente de obras.",
         "O trabalhador perde automaticamente a sua carteira de trabalho e previdência social.",
         "O empregador pode confiscar todos os bens pessoais do trabalhador no estado.",
         "A",
         "A inaptidão temporária enseja cuidados terapêuticos, readequação funcional e proteção previdenciária mediante encaminhamento e abertura de CAT pelo empregador.",
         "NR-07 e Lei 8.213/91",
         "média"),
        # 19
        ("A realização de testes de gravidez (beta-HCG) ou exames de esterilização como condição prévia para admissão ou manutenção do emprego de mulheres:",
         "É expressamente proibida pela Lei Federal nº 9.029/1995 e pela NR-07, configurando prática discriminatória e crime punível com detenção.",
         "É obrigatória em todos os hospitais públicos do território brasileiro.",
         "Pode ser exigida caso a trabalhadora vá atuar na copa do refeitório de funcionários.",
         "É facultativa a critério exclusivo de qualquer técnico de segurança de plantão.",
         "Deve ser realizada publicamente na frente de todos os candidatos concorrentes.",
         "A",
         "A Lei 9.029/95 e a NR-07 proíbem terminantemente a exigência de teste de gravidez e esterilização na admissão e na relação de emprego, tipificando como crime.",
         "Lei 9.029/1995 e NR-07",
         "fácil"),
        # 20
        ("A exigência de teste toxicológico ou sorologia de HIV na admissão de trabalhadores da saúde sem qualquer justificativa epidemiológica e sem consentimento:",
         "Viola a dignidade da pessoa humana, a intimidade, as diretrizes da OIT e as resoluções do Conselho Federal de Medicina (CFM), sendo prática discriminatória ilícita.",
         "É recomendada formalmente pela Organização Mundial da Saúde para todas as profissões.",
         "É permitida desde que o hospital desconte o valor do exame no salário do candidato.",
         "Pode ser aplicada apenas aos candidatos do sexo masculino acima de 40 anos.",
         "É indispensável para a emissão de crachá de identificação funcional.",
         "A",
         "A testagem discriminatória para HIV/drogas sem embasamento legal específico é vedada pelo CFM (Resolução 1.665/2003) e jurisprudência pacífica do TST.",
         "Resolução CFM 1.665/2003 e TST Súmula 443",
         "média"),

        # =========================================================
        # 2. ATESTADO DE SAÚDE OCUPACIONAL - ASO (10 questões)
        # =========================================================
        # 21
        ("Para cada exame clínico ocupacional realizado (admissional, periódico, retorno, mudança de risco e demissional), o médico deve emitir obrigatoriamente:",
         "O Atestado de Saúde Ocupacional (ASO).",
         "A Certidão de Quitação Eleitoral Municipal.",
         "A Nota Promissória de Caução de Contrato.",
         "O Certificado de Registro de Veículo Automotor.",
         "A Guia de Arrecadação de Tributos Estaduais.",
         "A",
         "O subitem 7.5.19 da NR-07 determina que, para cada exame clínico ocupacional realizado, o médico deve emitir o correspondente Atestado de Saúde Ocupacional (ASO).",
         "NR-07, item 7.5.19",
         "fácil"),
        # 22
        ("O ASO deve ser emitido em quantas vias e qual a destinação obrigatória da segunda via?",
         "No mínimo em duas vias, devendo a primeira via ficar arquivada no local de trabalho (sob guarda da empresa) e a segunda via ser entregue obrigatoriamente ao trabalhador mediante recibo.",
         "Em uma via única que deve ser afixada na porta do banheiro do hospital.",
         "Em dez vias coloridas enviadas para a imprensa local da cidade de Belém.",
         "Em três vias manuscritas guardadas exclusivamente no cofre do médico particular.",
         "O ASO não pode ser entregue ao empregado sob nenhuma hipótese legal.",
         "A",
         "A 1ª via fica com a organização e a 2ª via é fornecida obrigatoriamente ao empregado contra recibo assinado ou disponibilizada em meio eletrônico (NR-07, subitem 7.5.19.1).",
         "NR-07, item 7.5.19.1",
         "fácil"),
        # 23
        ("Dentre os dados obrigatórios que devem constar no corpo do ASO, de acordo com o subitem 7.5.19 da NR-07, inclui-se:",
         "Razão social e CNPJ da empresa, nome completo e CPF do trabalhador, descrição da função e riscos ocupacionais do PGR (ou sua ausência).",
         "O número do título de eleitor com a indicação de quem o servidor votou na última eleição.",
         "A renda familiar mensal per capita de todos os parentes do empregado.",
         "A raça do animal de estimação de estimação do trabalhador.",
         "A marca de celular e o modelo de automóvel do funcionário.",
         "A",
         "O ASO deve identificar detalhadamente a empresa, o trabalhador, o cargo, os riscos ocupacionais avaliados no PGR e a indicação dos exames realizados.",
         "NR-07, item 7.5.19",
         "fácil"),
        # 24
        ("No que concerne aos EXAMES COMPLEMENTARES realizados pelo trabalhador, o ASO deve informar:",
         "A indicação dos exames complementares realizados e as respectivas datas de realização, sendo PROIBIDO registrar seus resultados e laudos numéricos por sigilo médico.",
         "O laudo detalhado e a transcrição completa de todos os resultados laboratoriais no corpo do ASO.",
         "Apenas o preço pago pela empresa por cada hemograma realizado.",
         "A assinatura de todos os colegas de quarto que presenciaram a coleta de sangue.",
         "A taxa de colesterol total escrita em letras vermelhas gigantescas.",
         "A",
         "A NR-07 é categórica: o ASO informa quais exames foram realizados e suas datas, preservando o sigilo dos resultados numéricos que ficam guardados no prontuário.",
         "NR-07, subitem 7.5.19, alínea 'd'",
         "média"),
        # 25
        ("A conclusão médica quanto à aptidão no ASO deve ser expressa tecnicamente como:",
         "'Apto' ou 'Inapto' para a função específica que o trabalhador vai exercer, exerce ou exerceu.",
         "'Excelente', 'Regular' ou 'Péssimo' segundo a simpatia do trabalhador.",
         "'Magro', 'Normal' ou 'Gordo' com base na pesagem de balança.",
         "'Simpático' ou 'Antipático' após entrevista de 5 minutos.",
         "'Aprovado com louvor' ou 'Reprovado sem direito a recurso'.",
         "A",
         "A conclusão ocupacional é binária e funcional: apto ou inapto para a atividade laborativa e os riscos inerentes daquele cargo na organização.",
         "NR-07, subitem 7.5.19, alínea 'e'",
         "fácil"),
        # 26
        ("É lícito e ético ao médico examinador fazer constar o Código Internacional de Doenças (CID-10) no Atestado de Saúde Ocupacional (ASO) entregue à empresa?",
         "Não, é vedada a inclusão de código de CID no ASO por constituir violação ao sigilo médico e à intimidade do trabalhador, salvo autorização expressa em situações legais estritas.",
         "Sim, o CID deve ser carimbado em tamanho grande na capa da carteira de trabalho do empregado.",
         "Sim, a empresa pode exigir o CID de todos os empregados para filtrar candidatos doentes.",
         "Apenas se o trabalhador tiver renda superior a 10 salários mínimos.",
         "Sim, o CID é obrigatório pela NR-07 em todas as vias do ASO.",
         "A",
         "O Código de Ética Médica e a NR-07 vedam a inclusão do CID no ASO funcional disponibilizado ao setor administrativo da empresa para preservar o sigilo diagnóstico.",
         "Resolução CFM 1.810/2007 e NR-07",
         "fácil"),
        # 27
        ("O ASO deve conter a identificação profissional com assinatura e carimbo com CRM de quem?",
         "Do médico examinador e o nome e CRM do médico do trabalho responsável pelo PCMSO.",
         "Apenas do técnico de segurança do trabalho do turno da tarde.",
         "Do diretor administrativo da fundação hospitalar exclusivamente.",
         "Do presidente do sindicato dos enfermeiros do Pará.",
         "Do policial militar que acompanha a portaria do hospital.",
         "A",
         "O ASO exige a identificação formal do médico examinador que realizou o ato clínico e a referência ao médico coordenador/responsável pelo PCMSO.",
         "NR-07, subitem 7.5.19, alíneas 'f' e 'g'",
         "fácil"),
        # 28
        ("Caso o trabalhador apresente uma limitação temporária e o médico considere que ele pode trabalhar sem executar certas atividades de risco (ex: não erguer peso acima de 5 kg por 15 dias):",
         "O médico emite o ASO de 'Apto com restrição' e orienta a chefia sobre as tarefas específicas que devem ser temporariamente suspensas na rotina daquele servidor.",
         "O trabalhador deve ser imediatamente demitido sem direito ao seguro-desemprego.",
         "O médico deve trancar o servidor no quarto de isolamento até a cicatrização do músculo.",
         "O servidor é obrigado a carregar o triplo de peso para fortalecer os ligamentos rompidos.",
         "A chefia pode ignorar a restrição e obrigar o trabalhador a descumprir a recomendação médica.",
         "A",
         "A emissão de aptidão com restrições temporárias resguarda a saúde do trabalhador, permitindo sua readaptação ou remanejamento transitório de tarefas incompatíveis.",
         "Diretrizes do CFM e NR-07",
         "média"),
        # 29
        ("A recusa do empregador em fornecer a segunda via do ASO ao trabalhador admitido ou examinado constitui:",
         "Infração expressa à NR-07, passível de notificação e autuação pelos Auditores Fiscais do Trabalho durante fiscalização.",
         "Procedimento legalmente recomendado para evitar o vazamento de informações da empresa.",
         "Crime inafiançável com pena de perda de mandato do presidente da república.",
         "Ato normal que não gera nenhuma consequência para a instituição hospitalar.",
         "Motivo para cancelamento automático do registro hospitalar na Anvisa.",
         "A",
         "A não entrega da 2ª via do ASO é infração às normas de segurança e medicina do trabalho fiscalizadas pelo Ministério do Trabalho e Emprego.",
         "NR-07 e NR-28",
         "fácil"),
        # 30
        ("A disponibilização do ASO em formato digital/eletrônico para o empregado é permitida pela legislação trabalhista atual?",
         "Sim, desde que seja garantido o acesso fácil ao trabalhador, a integridade do arquivo e a certificação digital com assinatura eletrônica válida (ICP-Brasil).",
         "Não, documentos médicos digitais são terminantemente proibidos no Brasil.",
         "Apenas se o trabalhador imprimir o documento em papel fotográfico brilhante.",
         "Apenas para funcionários que trabalham na área de tecnologia da informação.",
         "Sim, mas o documento eletrônico só tem validade se for lido em voz alta em audiência pública.",
         "A",
         "A Portaria MTP 671/2021 e a NR-01 autorizam a emissão e guarda de documentos em formato digital, desde que atendidos os requisitos de segurança e assinatura digital.",
         "Portaria MTP 671/2021 e NR-01",
         "fácil"),

        # =========================================================
        # 3. PERIODICIDADE DOS EXAMES (10 questões)
        # =========================================================
        # 31
        ("Qual é a periodicidade padrão estabelecida pelo subitem 7.5.8 da NR-07 para o exame clínico periódico de trabalhadores expostos a riscos ocupacionais identificados e classificados no PGR?",
         "Anual.",
         "A cada cinco anos.",
         "A cada seis meses para qualquer trabalhador da fábrica.",
         "Bienal (a cada dois anos) sem exceções.",
         "Decenal (a cada dez anos de serviço).",
         "A",
         "Para trabalhadores expostos a riscos ocupacionais classificados no PGR (e para portadores de doenças crônicas que aumentem a susceptibilidade), a periodicidade é anual.",
         "NR-07, subitem 7.5.8, alínea 'a'",
         "fácil"),
        # 32
        ("Para os trabalhadores que NÃO estejam expostos a riscos ocupacionais identificados e classificados no PGR (como servidores administrativos em escritórios comuns sem agentes nocivos):",
         "O exame clínico periódico deve ser realizado bienalmente (a cada dois anos).",
         "O exame clínico periódico deve ser feito diariamente antes do expediente matutino.",
         "Fica proibida para sempre a realização de qualquer exame periódico de saúde.",
         "O exame periódico deve ser realizado apenas aos 70 anos de idade.",
         "O trabalhador deve pagar consulta particular a cada três meses.",
         "A",
         "Para trabalhadores não expostos a riscos ocupacionais no PGR, o exame clínico periódico deve ser realizado a cada dois anos (bienal) (NR-07, item 7.5.8, alínea 'b').",
         "NR-07, subitem 7.5.8, alínea 'b'",
         "fácil"),
        # 33
        ("Em relação aos profissionais de saúde da FHCGV que mantêm contato direto diário com pacientes e materiais biológicos potencialmente infectantes, o exame periódico deve ser:",
         "Anual, devido à classificação e exposição ao risco biológico constante no PGR.",
         "Bienal, pois o risco biológico não necessita de monitoramento anual no hospital.",
         "A cada 10 anos, por serem profissionais treinados na faculdade.",
         "Apenas no momento em que ocorrer um acidente com perfurocortante.",
         "Mensal, com internação compulsória de 48 horas a cada exame.",
         "A",
         "Havendo exposição a riscos ocupacionais classificados no PGR (como o risco biológico em serviços hospitalares), o exame clínico deve ser realizado anualmente.",
         "NR-07, item 7.5.8 e NR-32",
         "fácil"),
        # 34
        ("A periodicidade dos exames complementares de controle médico previstos nos Quadros 1 e 2 da NR-07 pode ser reduzida (aumentando a frequência) pelo médico do trabalho?",
         "Sim, a critério técnico fundamentado do médico responsável pelo PCMSO, ou por exigência de Norma Regulamentadora específica ou recomendação da CIB/CIT.",
         "Não, a NR-07 proíbe expressamente qualquer médico de solicitar exames em prazos menores.",
         "Apenas se o técnico de segurança do trabalho autorizar por escrito em cartório.",
         "Apenas se o trabalhador pagar os exames adicionais com seu próprio salário.",
         "Sim, mas exige autorização prévia por decreto do governador do estado.",
         "A",
         "O médico do trabalho possui autonomia técnica para antecipar exames e reduzir intervalos quando houver suspeita de agravo ou agravamento de exposições.",
         "NR-07, item 7.5.15",
         "média"),
        # 35
        ("No monitoramento auditivo de trabalhadores expostos a níveis de ruído elevados, o primeiro exame audiométrico periódico deve ser realizado:",
         "Seis meses após o exame admissional, e anualmente a partir de então.",
         "Cinco anos após a admissão do empregado.",
         "A cada 30 dias durante toda a vigência do contrato.",
         "Apenas no exame demissional ao se aposentar.",
         "Exclusivamente durante os feriados de carnaval.",
         "A",
         "O Anexo II da NR-07 prevê que a 1ª audiometria periódica seja feita aos 6 meses após o admissional e, posteriormente, com periodicidade anual.",
         "NR-07, Anexo II",
         "fácil"),
        # 36
        ("Para trabalhadores expostos a poeiras minerais com risco de pneumoconioses (como sílica ou asbesto), as radiografias de tórax preconizadas no PCMSO devem ser interpretadas de acordo com:",
         "O padrão e a classificação radiológica internacional da OIT (Organização Internacional do Trabalho).",
         "Apenas a opinião estética do técnico que operou o aparelho de raio-X.",
         "A quantidade de manchas escuras visíveis a olho nu contra a luz solar da janela.",
         "O peso da folha de filme radiográfico em balança analítica.",
         "A data de validade da tinta química de revelação do filme fotográfico.",
         "A",
         "As radiografias de tórax para pneumoconioses exigem leitura técnica padronizada conforme a Classificação Radiológica de Pneumoconioses da OIT por leitor certificado.",
         "NR-07, Anexo de Poeiras e Diretrizes OIT",
         "média"),
        # 37
        ("Trabalhadores portadores de condições clínicas crônicas (como hipertensão arterial descompensada, diabetes ou cardiopatias) expostos a condições extremas devem ter sua periodicidade de exame:",
         "Adequada e individualizada pelo médico do trabalho, podendo ser semestral ou inferior, conforme o controle clínico e os riscos da função.",
         "Prorrogada para a cada 15 anos para não gerar estresse emocional.",
         "Ignorada pelo PCMSO, pois doenças crônicas não têm relação com medicina do trabalho.",
         "Substituída por uma carta de compromisso assinada pelos familiares.",
         "Condicionada à perda imediata do plano de saúde hospitalar.",
         "A",
         "A vigilância de trabalhadores com maior susceptibilidade permite intervalos mais curtos a critério do médico para prevenção de descompensações e acidentes.",
         "NR-07, subitem 7.5.8",
         "média"),
        # 38
        ("Se um trabalhador ficar afastado da FHCGV por 45 dias em razão de cirurgia ortopédica decorrente de queda em jogo de futebol no final de semana:",
         "Ele é obrigado a realizar o exame de retorno ao trabalho no primeiro dia de sua volta, pois o afastamento por motivo de saúde foi superior a 30 dias.",
         "Ele fica dispensado de exame de retorno por se tratar de acidente extralaboral de lazer.",
         "Ele deve ser demitido por justa causa por praticar esportes nos dias de folga.",
         "Ele só precisa fazer exame se voltar a sentir dores nos membros após 6 meses.",
         "O exame de retorno só é exigido caso ele tenha fraturado o crânio.",
         "A",
         "O exame de retorno ao trabalho independe de o afastamento ter tido origem ocupacional ou comum; afastou-se por doença/acidente por 30 dias ou mais, o exame é obrigatório.",
         "NR-07, subitem 7.5.9",
         "fácil"),
        # 39
        ("Caso um servidor da FHCGV mude de setor de trabalho, saindo do arquivo administrativo (sem riscos ambientais) para o setor de expurgo da CME (com risco biológico e químico):",
         "O exame médico de mudança de riscos ocupacionais deve ser realizado OBRIGATORIAMENTE antes do início de suas novas funções na CME.",
         "O exame de mudança de função pode ser feito 1 ano após a transferência já consumada.",
         "O exame é desnecessário, pois ambos os setores pertencem ao mesmo hospital.",
         "Apenas o chefe do setor de expurgo precisa assinar uma folha de autorização verbal.",
         "O trabalhador deve assinar termo abrindo mão de qualquer proteção à sua saúde.",
         "A",
         "A transferência para atividade com riscos novos/maiores exige exame prévio para assegurar que o profissional está apto a lidar com os agentes químicos e biológicos da CME.",
         "NR-07, subitem 7.5.10",
         "fácil"),
        # 40
        ("Qual é a consequência administrativa para a fundação hospitalar se os exames periódicos dos trabalhadores forem mantidos vencidos e atrasados por desídia da gestão?",
         "A fundação comete infração à NR-07 e à CLT, sujeitando-se a multas aplicadas pela Auditoria Fiscal do Trabalho, além de responsabilização em ações civis públicas movidas pelo MPT.",
         "O Ministério do Trabalho concederá uma medalha de honra ao mérito por economia orçamentária.",
         "Os funcionários serão proibidos de se alimentar no refeitório durante o almoço.",
         "O hospital recebe autorização especial para dobrar o preço das consultas particulares.",
         "Todos os leitos hospitalares são transferidos para o setor privado sem indenização.",
         "A",
         "Manter exames ocupacionais vencidos viola o Art. 168 da CLT e a NR-07, sujeitando o empregador às penalidades da NR-28 e ações do Ministério Público do Trabalho.",
         "CLT Art. 168, NR-07 e NR-28",
         "fácil")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-07",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr07_questions()
    print(f"NR-07 questions generated: {len(q)}")
