# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-01: GRO e PGR (50 questões)
- Inventário de riscos: 20 questões
- Plano de ação: 15 questões
- Direito de recusa: 10 questões
- eSocial (S-2210, S-2220, S-2240): 5 questões
"""

def get_nr01_questions():
    items = [
        # =========================================================
        # 1. INVENTÁRIO DE RISCOS (20 questões)
        # =========================================================
        # 1
        ("O Programa de Gerenciamento de Riscos (PGR), instituído pela nova redação da NR-01, deve ser composto no mínimo por dois documentos estruturais essenciais:",
         "O Inventário de Riscos Ocupacionais e o Plano de Ação.",
         "O Livro de Ponto Eletrônico e o Recibo de Férias.",
         "A Ficha Cadastral dos Clientes e o Balanço Contábil.",
         "A Apólice de Seguro de Automóveis e a Guia de IPTU.",
         "O Manual de Boas Maneiras e o Cardápio do Refeitório.",
         "A",
         "Conforme o subitem 1.5.3.1 da NR-01, o PGR deve conter, no mínimo, o Inventário de Riscos e o Plano de Ação.",
         "NR-01, item 1.5.3.1",
         "fácil"),
        # 2
        ("No Inventário de Riscos Ocupacionais do PGR da FHCGV, a caracterização dos processos e ambientes de trabalho deve conter:",
         "A descrição detalhada das atividades executadas, os perigos identificados, as possíveis lesões ou agravos à saúde e as fontes geradoras.",
         "Apenas o valor venal do prédio e o imposto predial territorial urbano pago.",
         "A marca comercial dos computadores utilizados na administração.",
         "A lista de compras do supermercado para a diretoria executiva.",
         "O organograma político dos deputados estaduais da região metropolitana.",
         "A",
         "O item 1.5.7.3.2 da NR-01 exige no inventário a caracterização dos processos, perigos, fontes, possíveis lesões e trabalhadores expostos.",
         "NR-01, item 1.5.7.3.2",
         "fácil"),
        # 3
        ("A avaliação dos riscos ocupacionais no âmbito da NR-01 baseia-se na combinação de dois parâmetros fundamentais:",
         "A severidade das possíveis lesões ou agravos à saúde e a probabilidade de sua ocorrência.",
         "O peso corporal do empregado e a sua idade cronológica.",
         "A cor do capacete e a distância do hospital até a capital do estado.",
         "A taxa de inflação acumulada e o valor do dólar comercial.",
         "O número de faltas não justificadas e a altura do teto do almoxarifado.",
         "A",
         "A NR-01 (subitem 1.5.4.4.2) determina que o nível de risco ocupacional deve ser determinado pela combinação da severidade com a probabilidade de ocorrência.",
         "NR-01, item 1.5.4.4.2",
         "fácil"),
        # 4
        ("A estimativa da SEVERIDADE das lesões na matriz de riscos da NR-01 deve levar em consideração:",
         "A magnitude da consequência do evento perigoso, o número de trabalhadores potencialmente afetados e se o dano é reversível, incapacitante ou fatal.",
         "Apenas o custo financeiro para a reposição de uma lâmpada fluorescente queimada.",
         "A escolaridade dos técnicos de segurança do trabalho do setor.",
         "A distância percorrida pelo ônibus do transporte público até o hospital.",
         "A marca dos jalecos distribuídos pela diretoria aos servidores.",
         "A",
         "A severidade avalia o impacto físico e a gravidade dos danos à saúde (reversibilidade, sequelas, mortes e abrangência de pessoas atingidas).",
         "NR-01, item 1.5.4.4.3",
         "média"),
        # 5
        ("Na estimativa da PROBABILIDADE de ocorrência de uma lesão ou agravo à saúde, a organização deve considerar:",
         "As exigências da atividade de trabalho, os dados de acidentes e agravos anteriores, o perfil de exposição e a eficácia das medidas de prevenção existentes.",
         "Apenas a opinião individual de um único estagiário recém-admitido.",
         "As previsões astrológicas publicadas nos jornais diários.",
         "A temperatura máxima da água da piscina do clube dos funcionários.",
         "A velocidade média do vento na praia de Salinas.",
         "A",
         "A probabilidade leva em conta a frequência de exposição, a adequação e eficácia das barreiras preventivas e o histórico de acidentalidade da empresa.",
         "NR-01, item 1.5.4.4.4",
         "média"),
        # 6
        ("O agrupamento de trabalhadores que desempenham atividades semelhantes, expostos aos mesmos perigos e sob idênticas condições ambientais é denominado tecnicamente no PGR de:",
         "Grupo Homogêneo de Exposição (GHE) ou Grupo Similar de Exposição (GSE).",
         "Turma de recreação laboral vespertina.",
         "Bloco carnavalesco hospitalar integrado.",
         "Comissão de sindicância disciplinar colegiada.",
         "Pelotão de infantaria civil hospitalar.",
         "A",
         "O Grupo Homogêneo de Exposição (GHE) reúne trabalhadores submetidos aos mesmos fatores de risco com perfil de exposição equivalente para fins de avaliação e monitoramento.",
         "NR-01, Fundacentro e Higiene Ocupacional",
         "fácil"),
        # 7
        ("A avaliação de riscos no PGR da FHCGV deve ser revista obrigatoriamente a cada:",
         "Dois anos, ou no prazo de até três anos para organizações que possuam certificações em sistema de gestão de SST.",
         "Trinta dias para todos os estabelecimentos comerciais do país.",
         "Dez anos para hospitais com mais de duzentos leitos ativos.",
         "Vinte e cinco anos sem possibilidade de atualização intermediária.",
         "Seis meses, exclusivamente se a empresa não tiver faturamento financeiro.",
         "A",
         "O item 1.5.4.4.6 da NR-01 estabelece a revisão da avaliação a cada 2 anos, ou a cada 3 anos para organizações certificadas em sistemas de gestão de SST (ex: ISO 45001).",
         "NR-01, item 1.5.4.4.6",
         "fácil"),
        # 8
        ("Além do prazo ordinário de revisão (2 ou 3 anos), a avaliação de riscos deve ser IMEDIATAMENTE revista pela organização quando:",
         "Após a ocorrência de acidentes ou doenças relacionadas ao trabalho graves, quando houver modificação nas tecnologias, processos ou quando identificadas inadequações nas medidas preventivas.",
         "O preço do combustível subir na primeira quinzena do mês.",
         "Um funcionário solicitar empréstimo consignado na folha de pagamento.",
         "Houver mudança no fornecedor de copos plásticos descartáveis do refeitório.",
         "O hospital comemorar aniversário de fundação com bolo festivo.",
         "A",
         "A NR-01 (subitem 1.5.4.4.6.1) lista situações que disparam a revisão obrigatória do inventário: acidentes, doenças graves, novas leis, mudanças de processos ou falhas de controle.",
         "NR-01, item 1.5.4.4.6.1",
         "média"),
        # 9
        ("O histórico das atualizações e revisões dos documentos integrantes do PGR deve ser mantido disponível pela organização por um período mínimo de:",
         "Vinte anos, à disposição dos trabalhadores e da fiscalização.",
         "Três meses após a homologação das atas pelo sindicato.",
         "Um ano para descarte e incineração anual compulsória.",
         "Cinco dias úteis após a inspeção do corpo de bombeiros.",
         "Cinquenta anos em arquivo subterrâneo de chumbo.",
         "A",
         "Os documentos do PGR devem ser mantidos arquivados e disponíveis por, no mínimo, 20 anos (NR-01, subitem 1.5.7.4.1).",
         "NR-01, item 1.5.7.4.1",
         "fácil"),
        # 10
        ("Em relação à identificação de perigos no inventário da FHCGV, a etapa preliminar de levantamento de perigos deve incluir:",
         "A consulta aos trabalhadores, a análise das condições de trabalho e a análise de dados epidemiológicos do PCMSO sobre acidentes e adoecimentos prévios.",
         "Apenas a medição de ruído com celular comum nas garagens do hospital.",
         "A aplicação de punições disciplinares a quem relatar queixas ergonômicas.",
         "A dispensa de análise de riscos químicos na manipulação de quimioterápicos.",
         "A assinatura de declaração padrão de que o ambiente de trabalho é 100% perfeito.",
         "A",
         "O levantamento de perigos envolve escuta dos trabalhadores, observação das rotinas reais de trabalho e articulação com os relatórios médicos do PCMSO.",
         "NR-01, item 1.5.4.3",
         "média"),
        # 11
        ("Quando a avaliação preliminar indicar que um risco ocupacional é classificado como 'INTOLERÁVEL' ou 'CRÍTICO' na matriz de risco da FHCGV:",
         "O trabalho não deve ser iniciado ou continuado até que o risco tenha sido reduzido a níveis aceitáveis por medidas de controle urgentes.",
         "O empregador deve pagar um adicional indenizatório de R$ 50,00 e manter o trabalhador no local desprotegido.",
         "O trabalhador deve trabalhar com os olhos vendados para não sentir medo do perigo.",
         "A atividade deve continuar normalmente sem nenhuma alteração no processo.",
         "O técnico de segurança deve apagar o registro da matriz para evitar autuações.",
         "A",
         "Riscos intoleráveis exigem paralisação imediata ou medidas emergenciais que reduzam o nível de risco antes de qualquer operação continuada.",
         "NR-01 e Diretrizes de Gerenciamento de Riscos",
         "fácil"),
        # 12
        ("Qual a relação obrigatória exigida pela NR-01 e NR-07 entre o Inventário de Riscos do PGR e o Programa de Controle Médico de Saúde Ocupacional (PCMSO)?",
         "O PCMSO deve ser planejado e implantado com base nos riscos identificados no Inventário de Riscos do PGR, e os dados de saúde do PCMSO devem retroalimentar a avaliação de riscos do PGR.",
         "Não há nenhuma conexão entre eles, pois o PGR cuida apenas de incêndios e o PCMSO de receitas médicas.",
         "O médico do trabalho é proibido por sigilo de ler qualquer documento elaborado pelo SESMT.",
         "O PGR só pode ser iniciado 5 anos após o término do PCMSO.",
         "O inventário de riscos substitui integralmente a necessidade de realizar exames médicos admissionais.",
         "A",
         "Existe integração e retroalimentação direta: o PGR subsidia os exames do PCMSO e a vigilância médica alerta o PGR sobre o surgimento ou agravamento de doenças.",
         "NR-01, item 1.5.5.1 e NR-07, item 7.3.2",
         "média"),
        # 13
        ("Em relação à avaliação de riscos em empresas prestadoras de serviços terceirizadas que atuam dentro da FHCGV (como limpeza, segurança e manutenção predial):",
         "A contratante (FHCGV) e as contratadas devem articular suas ações de prevenção, fornecendo informações recíprocas sobre os perigos e integrando os inventários de risco nos ambientes compartilhados.",
         "A FHCGV não tem nenhuma obrigação em relação aos terceirizados, que respondem isoladamente por tudo.",
         "Os trabalhadores terceirizados são proibidos de usar os banheiros e bebedouros do hospital.",
         "O PGR da contratante revoga automaticamente a personalidade jurídica da empresa terceirizada.",
         "A terceirizada não precisa ter PGR se o seu contrato for inferior a 12 meses.",
         "A",
         "A NR-01 (subitem 1.5.8) estabelece obrigações conjuntas e cooperação entre contratante e contratadas para gestão integrada dos riscos no estabelecimento comum.",
         "NR-01, item 1.5.8",
         "média"),
        # 14
        ("A avaliação quantitativa das exposições ocupacionais no PGR deve ser realizada quando:",
         "Necessária para comprovar o controle da exposição ou a inexistência de riscos, confirmar a eficácia das medidas de prevenção ou dimensionar medidas de proteção coletiva.",
         "Apenas para cumprir exigência de contabilidade de custos de materiais de escritório.",
         "Sempre que o técnico de segurança desejar utilizar um aparelho digital novo.",
         "Apenas após a morte de pelo menos cinco servidores no mesmo setor.",
         "Ouvir-se um ruído de folhas secas ao vento no estacionamento do hospital.",
         "A",
         "A avaliação quantitativa mede concentrações químicas ou intensidades físicas para verificar conformidade com limites de tolerância e níveis de ação.",
         "NR-01, item 1.5.4.4.5 e NR-09",
         "média"),
        # 15
        ("Na matriz de classificação de riscos ocupacionais, um risco classificado como 'TRIVIAL' ou 'DESPREZÍVEL' geralmente requer:",
         "Nenhuma medida de controle adicional além da manutenção dos procedimentos de rotina existentes e monitoramento periódico de que a condição se mantém.",
         "A evacuação imediata do quarteirão com apoio da defesa civil municipal.",
         "A interdição completa do bloco cirúrgico por tempo indeterminado.",
         "A substituição de todos os médicos por robôs automatizados de cirurgia.",
         "O pagamento compulsório de adicional de periculosidade de 30% aos funcionários.",
         "A",
         "Riscos triviais ou aceitáveis não exigem ações corretivas emergenciais adicionais, exigindo apenas a manutenção das boas práticas operacionais.",
         "NR-01 e Metodologia de Análise de Riscos",
         "fácil"),
        # 16
        ("O processo de Identificação de Perigos no PGR deve ser contínuo e contemplar, conforme o subitem 1.5.4.3.1 da NR-01:",
         "Os perigos externos previsíveis que possam afetar a segurança e a saúde no trabalho da organização.",
         "Apenas os perigos originados exclusivamente dentro das gavetas trancadas da gerência.",
         "Apenas acidentes já julgados pelo Superior Tribunal de Justiça com trânsito em julgado.",
         "Apenas danos causados por quedas de meteoritos na região metropolitana de Belém.",
         "Exclusivamente brigas familiares de funcionários ocorridas aos domingos em suas casas.",
         "A",
         "A NR-01 inovou ao exigir a identificação de perigos externos previsíveis relacionados ao trabalho (ex: violência urbana, inundações, trânsito nos trajetos de trabalho).",
         "NR-01, item 1.5.4.3.1",
         "média"),
        # 17
        ("No PGR hospitalar da FHCGV, a classificação do risco biológico em uma enfermaria de clínica médica deve considerar:",
         "A virulência dos patógenos, as vias de transmissão, a endemicidade regional, a frequência do contato assistencial e a imunização/EPIs dos servidores.",
         "Apenas o custo financeiro das diárias de internação cobradas dos planos particulares.",
         "A idade do prédio e a cor da pintura externa da fachada do hospital.",
         "O cardápio da lanchonete localizada na calçada em frente ao hospital.",
         "O número de vagas de automóveis no estacionamento da diretoria.",
         "A",
         "O inventário de riscos biológicos articula o perigo intrínseco do agente patogênico com a exposição real dos trabalhadores no ambiente clínico.",
         "NR-01 e NR-32",
         "média"),
        # 18
        ("A Microempresa (ME) e a Empresa de Pequeno Porte (EPP) com graus de risco 1 e 2 que declararem que não possuem riscos físicos, químicos e biológicos em sua atividade:",
         "Estão dispensadas da elaboração do PGR, de acordo com o subitem 1.8.4 da NR-01.",
         "São obrigadas a contratar três engenheiros de segurança do trabalho em tempo integral.",
         "Ficam proibidas de contratar funcionários celetistas por tempo indeterminado.",
         "Devem pagar uma multa mensal de 10 salários mínimos ao Ministério do Trabalho.",
         "Estão isentas de cumprir qualquer norma de ergonomia e segurança de máquinas.",
         "A",
         "A NR-01 prevê tratamento diferenciado para ME e EPP graus de risco 1 e 2 que declarem inexistência de riscos físicos, químicos e biológicos, dispensando o PGR.",
         "NR-01, item 1.8.4",
         "fácil"),
        # 19
        ("A dispensa da elaboração do PGR para uma ME ou EPP isenta a empresa de cumprir as demais Normas Regulamentadoras de SST aplicáveis à sua atividade?",
         "Não, a dispensa do PGR não desobriga a empresa do cumprimento das demais exigências normativas de segurança e saúde no trabalho (ex: NR-06, NR-17).",
         "Sim, a empresa fica autorizada a ignorar todas as leis de segurança do trabalho do Brasil.",
         "Sim, a empresa pode deixar de fornecer EPIs e treinamento aos seus trabalhadores.",
         "Sim, a empresa fica dispensada do pagamento de salários e encargos trabalhistas.",
         "Não, exceto se a empresa doar 50% de seu lucro anual para o sindicato patronal.",
         "A",
         "O subitem 1.8.6 da NR-01 é taxativo: a dispensa da obrigação do PGR não alcança nem desobriga a organização do cumprimento das demais NRs aplicáveis.",
         "NR-01, item 1.8.6",
         "fácil"),
        # 20
        ("Qual é o papel da CIPA (Comissão Interna de Prevenção de Acidentes e Assédio) na elaboração e acompanhamento do Inventário de Riscos do PGR?",
         "A CIPA deve ser ouvida e participar da identificação dos perigos e percepção dos riscos nos locais de trabalho, colaborando no desenvolvimento do inventário.",
         "A CIPA tem poder para proibir o médico do trabalho de examinar os funcionários.",
         "A CIPA é terminantemente proibida de tomar conhecimento dos riscos avaliados no PGR.",
         "A CIPA deve assumir a responsabilidade penal e civil pelo laudo de engenharia emitido.",
         "A CIPA atua exclusivamente como órgão de cobrança financeira das mensalidades sindicais.",
         "A",
         "A NR-01 e a NR-05 determinam que a organização deve ouvir a CIPA e os trabalhadores na identificação de perigos e na avaliação dos riscos ocupacionais.",
         "NR-01, item 1.5.3.3 e NR-05",
         "média"),

        # =========================================================
        # 2. PLANO DE AÇÃO (15 questões)
        # =========================================================
        # 21
        ("O PLANO DE AÇÃO do PGR, conforme estabelecido no subitem 1.5.5.2 da NR-01, deve definir com clareza:",
         "As medidas de prevenção a serem introduzidas, aprimoradas ou mantidas, com cronograma de execução, formas de acompanhamento e responsáveis pela implementação.",
         "Apenas o valor das diárias de viagens dos diretores em congressos internacionais.",
         "A lista dos funcionários que serão demitidos por justa causa nos próximos 3 anos.",
         "A escala de férias de verão dos servidores que já possuem mais de 60 anos.",
         "O cardápio da confraternização de final de ano dos empregados da fundação.",
         "A",
         "O Plano de Ação é o instrumento executivo do PGR que estabelece 'o que fazer, quem faz, quando faz e como se mede a eficácia' das medidas preventivas.",
         "NR-01, item 1.5.5.2",
         "fácil"),
        # 22
        ("A NR-01 estabelece uma ORDEM DE PRIORIDADE obrigatória para a adoção das medidas de prevenção nos locais de trabalho (item 1.4.1). Essa hierarquia determina que:",
         "Primeiro deve-se eliminar os fatores de risco; em segundo lugar, minimizar e controlar na fonte com EPC; em terceiro, adotar medidas administrativas; e, por último, o uso de EPI.",
         "Primeiro deve-se distribuir EPIs descartáveis baratos para toda a fábrica e ignorar a fonte.",
         "A proteção individual (EPI) tem prioridade absoluta sobre qualquer medida coletiva ou de engenharia.",
         "As medidas administrativas de redução de salário devem preceder as medidas técnicas de segurança.",
         "A empresa é livre para escolher qualquer medida aleatoriamente sem seguir hierarquia de controle.",
         "A",
         "A hierarquia de controle de riscos é clássica: 1º Eliminação -> 2º Substituição/EPC -> 3º Medidas Administrativas -> 4º EPI.",
         "NR-01, item 1.4.1",
         "fácil"),
        # 23
        ("A implantação de Medidas de Proteção Coletiva (EPC), como sistemas de exaustão localizada na capela de quimioterápicos da FHCGV, é prioritária em relação ao EPI porque:",
         "Protege a coletividade de trabalhadores no ambiente, não depende exclusivamente do comportamento individual contínuo e atua diretamente na contenção do perigo na fonte.",
         "Custa menos dinheiro para a empresa do que comprar máscaras cirúrgicas descartáveis.",
         "Elimina a necessidade de qualquer treinamento dos operadores do setor.",
         "Isenta o hospital de realizar manutenção periódica nos filtros e motores.",
         "Permite que os técnicos trabalhem desprovidos de roupas e calçados.",
         "A",
         "O EPC protege múltiplos trabalhadores simultaneamente e controla o agente na origem ou na trajetória, minimizando a dependência de atos individuais.",
         "Higiene Ocupacional e NR-01",
         "fácil"),
        # 24
        ("O uso de Equipamento de Proteção Individual (EPI) deve ser adotado no Plano de Ação do PGR nas seguintes situações, EXCETO:",
         "Quando as medidas de proteção coletiva forem inviáveis tecnicamente ou não oferecerem completa proteção contra os riscos.",
         "Enquanto as medidas de proteção coletiva estiverem sendo implantadas (em caráter transitório).",
         "Para atender a situações de emergência.",
         "Como medida primária prioritária, em substituição perpétua ao conserto de máquinas com peças perigosas expostas.",
         "Em complementação às medidas de engenharia já instaladas que não anulem 100% da exposição.",
         "D",
         "O EPI nunca deve ser a primeira opção de comodidade para evitar a instalação de proteções coletivas necessárias; ele é a última barreira defensiva.",
         "NR-01, item 1.4.1 e NR-06",
         "média"),
        # 25
        ("O acompanhamento da eficácia das medidas de prevenção previstas no Plano de Ação deve ser realizado pelo SESMT através de:",
         "Inspeções periódicas nos locais de trabalho, monitoramento das avaliações ambientais, auditorias internas e cruzamento com os indicadores epidemiológicos do PCMSO.",
         "Consultas a videntes e previsões de cartas de tarô na sala de enfermagem.",
         "Reuniões informais de cafezinho sem ata nem registro de deliberações técnicas.",
         "Leitura dos horóscopos dos servidores aniversariantes do mês.",
         "Pesquisa de popularidade nas redes sociais da internet.",
         "A",
         "Aferir eficácia exige medições, auditorias em campo e monitoramento dos indicadores de saúde para certificar se as barreiras realmente controlaram o risco.",
         "NR-01, item 1.5.5.3",
         "média"),
        # 26
        ("Se durante o acompanhamento da eficácia for constatado que uma medida preventiva adotada (ex: um novo dispositivo de segurança em agulha) não produziu o efeito esperado:",
         "O Plano de Ação deve ser imediatamente revisto, corrigindo-se a falha, substituindo-se o modelo ou aprimorando-se o treinamento dos trabalhadores.",
         "A empresa deve arquivar o PGR e proibir a realização de novas inspeções no setor.",
         "O trabalhador que sofreu o acidente deve ser obrigado a pagar o valor do dispositivo.",
         "O SESMT deve culpar o fabricante e não tomar nenhuma atitude corretiva no hospital.",
         "A comissão deve aguardar 10 anos até a próxima revisão formal do plano.",
         "A",
         "O PGR é um ciclo dinâmico contínuo (PDCA); constatada a ineficácia da medida, o plano deve ser ajustado e aprimorado imediatamente.",
         "NR-01, item 1.5.5.3.3",
         "fácil"),
        # 27
        ("Dentre as medidas administrativas de prevenção que podem ser incluídas no Plano de Ação do PGR para setores com alta carga biomecânica ou estresse na FHCGV, cita-se:",
         "A instituição de pausas regulares de descanso durante a jornada de trabalho, alternância de tarefas (rodízio) e adequação dos procedimentos operacionais padrão.",
         "O aumento da jornada diária de trabalho de 12 para 18 horas ininterruptas.",
         "A proibição do consumo de água potável durante todo o plantão de serviço.",
         "A eliminação do direito ao descanso semanal remunerado dos servidores.",
         "A instalação de câmeras espiãs secretas nos banheiros e vestiários masculinos e femininos.",
         "A",
         "Medidas administrativas e organizacionais incluem redução do tempo de exposição, pausas programadas, rodízio de postos e melhoria ergonômica de processos.",
         "NR-01 e NR-17",
         "fácil"),
        # 28
        ("O cronograma de execução das ações do PGR na FHCGV deve estabelecer:",
         "Prazos claros e datas-limite para a conclusão de cada etapa, permitindo o controle de metas de curto, médio e longo prazo.",
         "Prazos genéricos indefinidos como 'quando for possível financeiramente'.",
         "Datas fixadas exclusivamente no passado para simular cumprimento de metas.",
         "Prazos superiores a 50 anos para todas as medidas que exijam compra de materiais.",
         "Apenas o horário de entrada e saída do diretor-presidente da fundação hospitalar.",
         "A",
         "O cronograma deve conter metas cronológicas objetivas (datas ou períodos determinados) para possibilitar a cobrança e auditoria de cumprimento.",
         "NR-01, item 1.5.5.2.2",
         "fácil"),
        # 29
        ("A definição de responsáveis no Plano de Ação do PGR tem como finalidade técnica e gerencial:",
         "Assegurar a prestação de contas (accountability), atribuindo a setores ou gestores específicos a competência e autoridade para viabilizar as ações planejadas.",
         "Identificar quem deverá ser processado criminalmente caso chova no telhado do hospital.",
         "Transferir a responsabilidade da empresa para estagiários voluntários sem remuneração.",
         "Permitir que o diretor do hospital fique livre de quaisquer obrigações legais de gestão.",
         "Criar um sorteio mensal de culpados por acidentes de trabalho nas enfermarias.",
         "A",
         "Identificar formalmente os responsáveis por cada ação garante que as medidas tenham execução garantida e acompanhada pelos escalões administrativos competentes.",
         "NR-01, item 1.5.5.2",
         "média"),
        # 30
        ("Em relação à capacitação e treinamento dos trabalhadores previstos no Plano de Ação do PGR:",
         "Os treinamentos devem ser realizados durante a jornada normal de trabalho, sem ônus para o trabalhador, abordando os perigos e as medidas preventivas adotadas.",
         "Os cursos devem ser realizados nos finais de semana de folga do servidor sem pagamento de hora extra.",
         "O empregado deve pagar uma taxa de matrícula de R$ 300,00 por módulo de treinamento da NR.",
         "Os treinamentos são dispensados se o servidor possuir carteira de habilitação categoria B.",
         "O hospital pode realizar o treinamento através de um folheto colocado debaixo da porta do quarto.",
         "A",
         "A NR-01 (subitem 1.7.1) estipula que a capacitação é custeada pelo empregador e realizada obrigatoriamente dentro da jornada normal de trabalho.",
         "NR-01, item 1.7.1",
         "fácil"),
        # 31
        ("O Anexo II da NR-01 estabelece as diretrizes e requisitos para a realização de treinamentos de SST na modalidade a distância (EAD) ou semipresencial, exigindo:",
         "Projeto pedagógico estruturado, ambiente virtual com controle de acesso, tutoria qualificada e cumprimento de atividades práticas presenciais quando exigidas pela respectiva NR.",
         "Apenas o envio de mensagens de texto curtas em aplicativos de bate-papo informal.",
         "A dispensa de qualquer tipo de avaliação final de aprendizagem do aluno.",
         "Que o curso seja assistido unicamente na residência do trabalhador durante a madrugada.",
         "A gravação de vídeos amadores sem responsabilidade técnica de profissional habilitado.",
         "A",
         "O Anexo II da NR-01 regulamenta o EAD em SST com critérios rigorosos de projeto pedagógico, validação de presença e obrigatoriedade de práticas presenciais.",
         "NR-01, Anexo II",
         "média"),
        # 32
        ("Qual a periodicidade com que o empregador deve realizar o treinamento periódico (reciclagem) dos trabalhadores em relação aos riscos do PGR?",
         "Conforme o prazo estabelecido na Norma Regulamentadora específica de cada tema ou sempre que houver modificação de processos e reavaliação de riscos.",
         "Apenas uma vez a cada 30 anos de serviço público ininterrupto.",
         "Diariamente por 8 horas consecutivas antes de iniciar o atendimento médico.",
         "Apenas após o servidor sofrer uma amputação traumática no trabalho.",
         "Nunca, pois o diploma de ensino médio supre qualquer treinamento em SST.",
         "A",
         "A periodicidade dos treinamentos periódicos obedece às NRs específicas ou aos prazos fixados no próprio PGR da organização.",
         "NR-01, item 1.7.3",
         "fácil"),
        # 33
        ("Em caso de acidente de trabalho com óbito ou lesão grave que exija internação na FHCGV, qual ação IMEDIATA deve ser incluída no Plano de Ação pelo SESMT?",
         "Análise profunda do acidente com investigação das causas imediatas e subjacentes, adotando-se medidas de contenção para evitar a repetição imediata do evento.",
         "A demolição sumária de todas as paredes do setor onde ocorreu o acidente.",
         "O pagamento em dinheiro vivo aos colegas de quarto para que não testemunhem na delegacia.",
         "A alteração imediata da data do laudo pericial para forjar cumprimento de normas.",
         "O arquivamento confidencial do prontuário por ordem verbal do diretor.",
         "A",
         "A análise de acidentes graves é obrigatória e deve gerar medidas imediatas de correção incluídas no plano de ação para mitigar a vulnerabilidade do sistema.",
         "NR-01, item 1.5.5.5",
         "fácil"),
        # 34
        ("A articulação do Plano de Ação do PGR com a preparação para emergências hospitalares (incêndios, vazamento de oxigênio, catástrofes externas) exige que a fundação disponha de:",
         "Plano de Emergência com procedimentos de evacuação, alarme, combate a princípios de incêndio, primeiros socorros e realização de simulados periódicos.",
         "Apenas uma buzina manual guardada na gaveta trancada da sala da diretoria.",
         "Uma caixa de fósforos e uma vela de cera de abelha em cada corredor.",
         "A dispensa de extintores de incêndio para reduzir o peso estrutural das paredes.",
         "A evacuação de pacientes exclusivamente pelas janelas do décimo andar com cordas de varal.",
         "A",
         "O subitem 1.5.6 da NR-01 exige Plano de Resposta a Emergências com rotas de fuga, sinalização, brigadas e exercícios simulados periódicos compatíveis com a atividade.",
         "NR-01, item 1.5.6 e NR-23",
         "fácil"),
        # 35
        ("Na gestão da segurança, o conceito de 'Melhoria Contínua' (Ciclo PDCA) incorporado pela NR-01 ao GRO significa que o gerenciamento de riscos:",
         "É um processo contínuo e dinâmico de planejamento (Plan), execução (Do), checagem (Check) e ação corretiva/aprimoramento (Act).",
         "Termina definitivamente no momento em que a primeira via do PGR é impressa em papel.",
         "É uma atividade burocrática destinada unicamente a ser arquivada para fiscais do trabalho.",
         "Deve ser realizado uma única vez na história da fundação hospitalar sem mudanças.",
         "Permite que os riscos aumentem anualmente sem intervenção técnica do SESMT.",
         "A",
         "O GRO baseia-se no ciclo PDCA de melhoria contínua dos desempenhos em segurança e saúde no trabalho.",
         "NR-01, item 1.5.3.4",
         "fácil"),

        # =========================================================
        # 3. DIREITO DE RECUSA (10 questões)
        # =========================================================
        # 36
        ("O subitem 1.4.3 da NR-01 consagra expressamente o 'Direito de Recusa' ao trabalhador, assegurando que este poderá interromper suas atividades quando:",
         "Constatar uma situação de trabalho onde, a seu ver, por motivos razoáveis, envolva um risco grave e iminente para a sua vida e saúde.",
         "Não estiver com vontade de trabalhar em uma tarde chuvosa de sexta-feira.",
         "Discordar da cor da parede da sala onde seu computador de mesa está instalado.",
         "Quiser assistir a uma partida de futebol transmitida pela televisão comercial.",
         "O hospital não fornecer lanche da tarde com sobremesa de chocolate importado.",
         "A",
         "O item 1.4.3 da NR-01 garante que o trabalhador interrompa a atividade diante de situação com motivos razoáveis de risco grave e iminente à sua integridade.",
         "NR-01, item 1.4.3",
         "fácil"),
        # 37
        ("Ao exercer legitimamente o direito de recusa diante de um risco grave e iminente na FHCGV, o trabalhador deve OBRIGATORIAMENTE:",
         "Comunicar imediatamente a situação de risco ao seu superior hierárquico.",
         "Abandonar o hospital e viajar para outro estado da federação sem avisar ninguém.",
         "Quebrar os equipamentos do posto de trabalho para impedir que outros trabalhem.",
         "Publicar calúnias e ofensas pessoais aos diretores nas redes sociais.",
         "Incendiar o quadro de distribuição elétrica do setor com álcool.",
         "A",
         "O trabalhador deve comunicar imediatamente ao superior hierárquico o motivo da interrupção para avaliação e adoção de medidas corretivas (NR-01, item 1.4.3).",
         "NR-01, item 1.4.3",
         "fácil"),
        # 38
        ("Após a comunicação do trabalhador sobre a existência de risco grave e iminente, qual é a obrigação legal do empregador perante a situação?",
         "Não exigir o retorno dos trabalhadores à atividade até que sejam adotadas medidas corretivas ou a situação de grave e iminente risco seja eliminada.",
         "Obrigar o trabalhador a retornar imediatamente à tarefa sob mira de armas de fogo.",
         "Suspender os salários de todos os funcionários do setor pelo prazo de um ano.",
         "Demiti-lo sumariamente por justa causa no mesmo instante da comunicação.",
         "Determinar que um estagiário sem treinamento assuma a mesma tarefa perigosa.",
         "A",
         "O empregador não pode exigir o retorno à atividade enquanto perdurar a situação de risco grave e iminente e não forem aplicadas medidas de segurança.",
         "NR-01, item 1.4.3.1",
         "fácil"),
        # 39
        ("O trabalhador que interrompe suas atividades com base no legítimo exercício do direito de recusa da NR-01:",
         "Não poderá sofrer qualquer tipo de represália disciplinar, punição ou prejuízo injustificado em sua remuneração e situação funcional.",
         "Deve ser colocado em isolamento solitário no subsolo do hospital por 10 dias.",
         "Perde o direito à aposentadoria e ao plano de previdência social.",
         "Deve pagar uma multa de 50 salários mínimos ao Fundo de Amparo ao Trabalhador.",
         "Fica impedido de votar nas eleições municipais do seu domicílio eleitoral.",
         "A",
         "A legislação protege o trabalhador contra represálias ou prejuízos advindos do exercício de boa-fé do direito de recusa frente a perigos graves.",
         "NR-01, item 1.4.3.2 e Princípios da OIT",
         "fácil"),
        # 40
        ("Considera-se 'RISCO GRAVE E IMINENTE' para fins de interrupção do trabalho ou interdição/embargo pelas autoridades:",
         "Toda condição ou situação de trabalho que possa causar acidente ou doença com lesão grave à integridade física do trabalhador em curto prazo de tempo.",
         "A presença de um grão de poeira no chão de um corredor de concreto externo.",
         "O atraso de 5 minutos na entrega do jornal matutino na portaria central.",
         "A temperatura do ar condicionado estar regulada em 23ºC em vez de 22ºC.",
         "A falta de canetas esferográficas azuis no almoxarifado de papelaria.",
         "A",
         "Risco grave e iminente é aquele que traz probabilidade substancial de morte, amputação ou lesão gravíssima com urgência temporal na ausência de controle.",
         "NR-01 e NR-03",
         "fácil"),
        # 41
        ("Um técnico de enfermagem da UTI recusa-se a realizar a aspiração de vias aéreas de um paciente com tuberculose ativa bacilífera porque o hospital não disponibilizou máscara PFF2/N95. A atitude do profissional:",
         "Configura exercício legítimo do direito de recusa amparado pela NR-01 e NR-32, dado o risco grave e iminente de contaminação por patógeno respiratório grave sem EPI adequado.",
         "Constitui falta funcional gravíssima que justifica a demissão imediata com perda do diploma profissional.",
         "É ilegal, pois o profissional de saúde é obrigado a sacrificar sua vida em qualquer circunstância.",
         "Só seria válida se o técnico comprasse sua própria máscara com seus recursos pessoais.",
         "Configura insubordinação civil sujeita a prisão em flagrante por desacato à autoridade.",
         "A",
         "A falta de respirador PFF2 em procedimento gerador de aerossóis biológicos de alta patogenicidade caracteriza risco grave e iminente, legitimando a interrupção.",
         "NR-01, item 1.4.3 e NR-32",
         "média"),
        # 42
        ("Caso haja divergência entre o trabalhador que interrompeu o trabalho e o superior hierárquico sobre a real existência de risco grave e iminente, deve-se:",
         "Solicitar a intervenção técnica e avaliação do SESMT (ou da CIPA e de profissional legalmente habilitado) para analisar tecnicamente o posto de trabalho.",
         "Decidir a questão em uma briga física entre o chefe e o subordinado.",
         "Prender o trabalhador preventivamente na carceragem da delegacia de polícia.",
         "Ignorar a reclamação e obrigar o trabalhador a assinar uma confissão de culpa.",
         "Realizar uma votação anônima na internet aberta para o público em geral.",
         "A",
         "Diante de dúvidas técnicas, cabe ao SESMT/CIPA inspecionar a área, emitir parecer técnico e determinar os controles necessários para segurança da operação.",
         "NR-01 e Prática de Engenharia de Segurança",
         "fácil"),
        # 43
        ("O direito de recusa aplica-se:",
         "A situações onde, por motivos razoáveis, a vida ou a saúde do trabalhador esteja exposta a perigo grave e iminente sem proteções eficazes.",
         "A qualquer tarefa rotineira que o empregado considere cansativa ou entediante.",
         "À recusa de responder às saudações de 'bom dia' dos colegas de trabalho.",
         "À negativa de registrar o ponto eletrônico na entrada e na saída do expediente.",
         "Exclusivamente a diretores executivos que recebem salários acima de R$ 100.000,00.",
         "A",
         "O direito de recusa não é um salvo-conduto para o descumprimento injustificado de deveres contratuais; vincula-se estritamente à presença de risco grave e iminente de dano à vida/saúde.",
         "NR-01, item 1.4.3",
         "fácil"),
        # 44
        ("A comunicação do direito de recusa pelo empregado e a respectiva avaliação técnica pelo SESMT devem preferencialmente ser:",
         "Registradas por escrito (ou em meio eletrônico rastreável), documentando o perigo apontado, a avaliação técnica realizada e as medidas corretivas implementadas.",
         "Mantidas em segredo absoluto sem nenhum documento para não deixar provas.",
         "Gravadas em fita magnética de áudio e enterradas no quintal do hospital.",
         "Destruídas em triturador de papel em menos de 10 minutos após o fato.",
         "Enviadas em carta anônima sem assinatura para jornais de fofocas locais.",
         "A",
         "O registro documental formal resguarda juridicamente as partes e comprova a atuação técnica do SESMT na eliminação da condição de risco.",
         "Boas Práticas de Gestão de SST e NR-01",
         "média"),
        # 45
        ("Se a empresa mantiver a exigência de trabalho em local com risco grave e iminente sem adotar medidas de controle, descumprindo o direito de recusa, o trabalhador e o sindicato podem:",
         "Acionar a Inspeção do Trabalho (Auditoria Fiscal do Trabalho) e o Ministério Público do Trabalho para fiscalização e eventual interdição do setor com base na NR-03.",
         "Contratar mercenários armados para invadir o hospital e tomar a direção à força.",
         "Incendiar os veículos oficiais da fundação hospitalar no estacionamento.",
         "Declarar o hospital como território independente e separado do Brasil.",
         "Exigir a renúncia de todos os ministros do Supremo Tribunal Federal.",
         "A",
         "Os órgãos de fiscalização do trabalho e o MPT são as instâncias competentes para fiscalizar e promover a interdição de atividades com risco grave e iminente (NR-03/CLT).",
         "CLT Art. 161, NR-03 e NR-01",
         "fácil"),

        # =========================================================
        # 4. ESOCIAL EM SST (S-2210, S-2220, S-2240) (5 questões)
        # =========================================================
        # 46
        ("No sistema eSocial, o evento responsável pelo envio das informações da Comunicação de Acidente de Trabalho (CAT) é o:",
         "Evento S-2210 (Comunicação de Acidente de Trabalho).",
         "Evento S-1000 (Informações do Empregador).",
         "Evento S-1200 (Remuneração de Trabalhador).",
         "Evento S-2299 (Desligamento de Empregado).",
         "Evento S-5001 (Contribuições Sociais).",
         "A",
         "O evento S-2210 é utilizado exclusivamente para registrar e transmitir a Comunicação de Acidente de Trabalho (CAT) à Previdência Social via eSocial.",
         "Manual de Orientação do eSocial (MOS) - Evento S-2210",
         "fácil"),
        # 47
        ("O prazo regulamentar para o envio do evento S-2210 (CAT) no eSocial após a ocorrência de um acidente de trabalho ou diagnóstico de doença ocupacional é:",
         "Até o primeiro dia útil seguinte ao da ocorrência e, em caso de morte, de imediato.",
         "Até o dia 20 do mês subsequente ao do acidente sem qualquer exceção.",
         "Em até 180 dias corridos contados da alta médica hospitalar do funcionário.",
         "Apenas após o encerramento do inquérito policial civil na delegacia de trânsito.",
         "Não existe prazo estipulado, podendo ser enviado a qualquer tempo em 10 anos.",
         "A",
         "O prazo legal do evento S-2210 é idêntico ao da Lei 8.213/91: até o 1º dia útil seguinte e de imediato em caso de óbito do trabalhador.",
         "Lei 8.213/91, Art. 22 e MOS eSocial Evento S-2210",
         "fácil"),
        # 48
        ("O evento S-2220 do eSocial destina-se a informar à plataforma do governo federal os dados relativos ao:",
         "Monitoramento da Saúde do Trabalhador durante todo o vínculo laboral com a empresa, detalhando os exames médicos (admissionais, periódicos, demissionais) e o Atestado de Saúde Ocupacional (ASO).",
         "Extrato de conta corrente bancária individual do trabalhador para cobrança de taxas.",
         "Histórico escolar com notas obtidas no ensino fundamental e médio do servidor.",
         "Registro de infrações de trânsito cometidas pelo trabalhador em veículo particular.",
         "Cardápio de calorias e proteínas consumidas no almoço diário do hospital.",
         "A",
         "O evento S-2220 consolida o monitoramento biológico e clínico do trabalhador (PCMSO), registrando a realização de exames clínicos, complementares e o respectivo ASO.",
         "MOS eSocial - Evento S-2220 e NR-07",
         "fácil"),
        # 49
        ("O evento S-2240 (Condições Ambientais do Trabalho - Fatores de Risco) do eSocial é utilizado para registrar as condições de prestação de serviços do trabalhador e tem por objetivo principal:",
         "Comprovar a exposição a agentes nocivos químicos, físicos e biológicos (ou sua ausência) para fins de concessão de Aposentadoria Especial perante o INSS e emissão do PPP eletrônico.",
         "Tabelar os preços das consultas médicas particulares em clínicas privadas.",
         "Registrar o modelo de ar-condicionado instalado na sala do diretor do hospital.",
         "Calcular a distância em metros da casa do trabalhador até a parada de ônibus.",
         "Substituir o pagamento de salário mensal por cupons de desconto comercial.",
         "A",
         "O S-2240 reflete as informações do LTCAT sobre exposição a agentes nocivos previstos no Anexo IV do Decreto 3.048/99 para alimentar o Perfil Profissiográfico Previdenciário (PPP).",
         "MOS eSocial - Evento S-2240 e Lei 8.213/91",
         "média"),
        # 50
        ("A partir da implantação oficial dos eventos de SST no eSocial, o Perfil Profissiográfico Previdenciário (PPP) passou a ser emitido de forma:",
         "Exclusivamente eletrônica (PPP Eletrônico), gerado automaticamente para o trabalhador a partir das informações transmitidas pela empresa no evento S-2240.",
         "Manuscrita em papel carbono azul entregue em envelope timbrado pelo correio postal.",
         "Dispensada, pois a Previdência Social extinguiu o direito à aposentadoria especial.",
         "Apenas em disquete de computador de 3,5 polegadas entregue no balcão da agência bancária.",
         "Oral, mediante gravação de mensagem de voz no telefone fixo da agência do INSS.",
         "A",
         "Desde 1º de janeiro de 2023, o PPP físico em papel foi substituído pelo PPP Eletrônico alimentado diretamente pelo envio do evento S-2240 no eSocial.",
         "Portaria MTP 313/2021 e Instrução Normativa INSS 128/2022",
         "média")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-01",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr01_questions()
    print(f"NR-01 questions generated: {len(q)}")
