# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-32: Vacinação e EPIs específicos (30 questões)
"""

def get_nr32_vacinacao_epi_questions():
    items = [
        # 1
        ("De acordo com a NR-32 (item 32.2.4.17), a todo trabalhador dos serviços de saúde deve ser fornecido gratuitamente programa de imunização ativa contra:",
         "Apenas febre amarela e malária.",
         "Tétano, difteria, hepatite B e os estabelecidos no PCMSO.",
         "Dengue, zika vírus e febre maculosa exclusivamente.",
         "Apenas gripe comum (influenza) a cada 5 anos.",
         "Raiva humana e peste bubônica em dose única.",
         "B",
         "A NR-32 estabelece no item 32.2.4.17 que deve ser fornecido gratuitamente programa de imunização contra tétano, difteria, hepatite B e os indicados pelo PCMSO.",
         "NR-32, item 32.2.4.17",
         "fácil"),
        # 2
        ("Qual é o exame laboratorial indicado pelo PCMSO para avaliar a resposta imunológica e a soroconversão protetora após a vacinação contra o vírus da Hepatite B?",
         "Pesquisa quantitativa de anticorpos Anti-HBs.",
         "Hemograma completo com contagem de plaquetas.",
         "Velocidade de hemossedimentação (VHS).",
         "Exame parasitológico de fezes pelo método MIF.",
         "Teste de tolerância oral à lactose.",
         "A",
         "O teste de Anti-HBs quantitativo verifica se o trabalhador desenvolveu anticorpos protetores contra a hepatite B (título protetor >= 10 mUI/mL).",
         "NR-32 e Diretrizes do Ministério da Saúde",
         "fácil"),
        # 3
        ("Após a administração do esquema básico completo de vacinação contra a hepatite B (3 doses: 0, 1 e 6 meses), o exame de Anti-HBs deve ser realizado preferencialmente:",
         "Entre 30 e 60 dias após a terceira dose da vacina.",
         "No mesmo dia da primeira dose da vacina.",
         "Exatamente 15 anos após a última dose da vacina.",
         "Apenas se o trabalhador for picado por escorpião.",
         "Durante o exame demissional ao se aposentar.",
         "A",
         "A coleta do Anti-HBs é idealmente realizada entre 1 e 2 meses após o término do esquema vacinal de 3 doses para avaliar a resposta imunológica no pico da produção.",
         "Protocolo de Imunização Ocupacional MS e NR-32",
         "média"),
        # 4
        ("Considera-se imunologicamente protegido (respondedor) contra a Hepatite B o trabalhador cujo título sorológico de Anti-HBs for:",
         "Igual a 0,0 mUI/mL.",
         "Menor que 5 mUI/mL.",
         "Igual ou superior a 10 mUI/mL (≥ 10 mUI/mL).",
         "Exclusivamente acima de 1.000.000 mUI/mL.",
         "Negativo com presença de HBsAg no sangue.",
         "C",
         "Títulos de Anti-HBs iguais ou superiores a 10 mUI/mL conferem imunidade protetora comprovada contra o vírus da hepatite B.",
         "Ministério da Saúde e NR-32",
         "fácil"),
        # 5
        ("Se após o primeiro esquema vacinal completo de 3 doses contra Hepatite B o trabalhador apresentar Anti-HBs menor que 10 mUI/mL (não-respondedor), a conduta médica correta é:",
         "Demiti-lo sumariamente por incapacidade física para o trabalho em saúde.",
         "Revaciná-lo com um segundo esquema completo de 3 doses (0, 1 e 6 meses) ou esquema com doses adicionais e retestar o Anti-HBs após 30 a 60 dias.",
         "Submetê-lo a transfusão total de sangue de doador desconhecido.",
         "Proibir o trabalhador de consumir líquidos por 3 semanas.",
         "Encaminhá-lo imediatamente para cirurgia hepática profilática.",
         "B",
         "Para indivíduos não respondedores ao 1º esquema, recomenda-se um 2º esquema completo de 3 doses e nova testagem de Anti-HBs. Cerca de 50% respondem a esse 2º ciclo.",
         "Protocolos de Imunização MS e NR-32",
         "média"),
        # 6
        ("Se mesmo após a aplicação de dois esquemas vacinais completos (total de 6 doses) contra a hepatite B o trabalhador continuar com Anti-HBs menor que 10 mUI/mL:",
         "Ele é considerado definitivamente 'não respondedor', devendo ser orientado detalhadamente e receber imunoglobulina específica (HBIG) caso venha a sofrer acidente com fonte positiva.",
         "Ele deve tomar mais 20 doses consecutivas da vacina no mesmo braço.",
         "Ele deve ser isolado em quarto de pressão negativa pelo resto da vida profissional.",
         "Ele está proibido por lei federal de exercer qualquer trabalho com carteira assinada.",
         "Ele é considerado milagrosamente imune a todos os vírus conhecidos.",
         "A",
         "O não respondedor após 6 doses não se beneficia de novas doses; ele deve receber orientações de prevenção e indicação de HBIG imediata em caso de acidente de risco.",
         "Diretrizes de Imunização MS e NR-32",
         "difícil"),
        # 7
        ("Em relação à vacina dupla adulto (dT - difteria e tétano) preconizada na NR-32 para trabalhadores de saúde da FHCGV, as doses de reforço devem ser administradas a cada:",
         "1 ano corrido.",
         "10 anos (ou 5 anos em caso de ferimentos graves ou profundos sujos).",
         "25 anos sem exceção.",
         "6 meses durante a estação chuvosa amazônica.",
         "Apenas na admissão sem qualquer necessidade de reforço futuro.",
         "B",
         "O reforço da vacina antitetânica (dT) para adultos imunizados é feito a cada 10 anos, antecipando-se para 5 anos em acidentes com ferimentos de alto risco para tétano.",
         "Programa Nacional de Imunizações (PNI) e NR-32",
         "fácil"),
        # 8
        ("Caso um trabalhador de saúde da FHCGV se recuse formalmente a receber a vacinação obrigatória disponibilizada gratuitamente pelo hospital:",
         "O trabalhador deve ser submetido à vacinação forçada pela brigada de segurança do hospital.",
         "O empregador deve comprovar por documento a recusa formal do trabalhador, após tê-lo esclarecido detalhadamente sobre as vantagens e os riscos de sua decisão.",
         "O trabalhador perde a posse de seu imóvel e todos os bens pessoais no estado do Pará.",
         "O empregador deve fingir que o trabalhador foi vacinado e assinar a carteirinha por ele.",
         "O trabalhador deve pagar multa diária de 20 salários mínimos ao Fundo Nacional de Saúde.",
         "B",
         "Conforme a NR-32 (item 32.2.4.17.4), o empregador deve comprovar a recusa por escrito do trabalhador, guardando a declaração no prontuário após orientação formal sobre os riscos.",
         "NR-32, item 32.2.4.17.4",
         "média"),
        # 9
        ("A guarda do comprovante de vacinação do trabalhador de saúde, de acordo com o subitem 32.2.4.17.2 da NR-32, deve ser:",
         "Mantida exclusivamente nas gavetas da residência do servidor sem acesso pelo hospital.",
         "Registrada e mantida no prontuário clínico individual do trabalhador, ficando à disposição da fiscalização do trabalho e do SESMT.",
         "Publicada no Diário Oficial do Estado do Pará com foto colorida do servidor.",
         "Incinerada ao final de cada ano fiscal junto aos resíduos comuns do hospital.",
         "Guardada na capela ecumênica do hospital em cofre de segurança.",
         "B",
         "A comprovação da vacinação deve constar no prontuário médico ocupacional do trabalhador, atualizada e acessível à auditoria fiscal do trabalho (NR-32, item 32.2.4.17.2).",
         "NR-32, item 32.2.4.17.2",
         "fácil"),
        # 10
        ("Qual vacina, além de dT e Hepatite B, é comumente indicada no PCMSO para prevenção de doenças de transmissão respiratória exantemáticas em profissionais de saúde?",
         "Vacina Tríplice Viral (Sarampo, Caxumba e Rubéola).",
         "Vacina contra Peste Suína Africana.",
         "Vacina contra Cinomose Canina.",
         "Vacina contra Antraz Inalatório.",
         "Vacina contra Brucelose bovina.",
         "A",
         "A vacina tríplice viral (SCR) protege contra sarampo, caxumba e rubéola, sendo altamente recomendada aos trabalhadores de saúde para prevenir surtos hospitalares.",
         "PNI / Ministério da Saúde e NR-32",
         "fácil"),
        # 11
        ("Sobre o fornecimento de Equipamentos de Proteção Individual (EPI) pela Fundação Hospital de Clínicas Gaspar Vianna aos seus empregados:",
         "O fornecimento deve ser gratuito, em perfeito estado de conservação, adequado ao risco da atividade e com Certificado de Aprovação (CA) válido.",
         "O hospital pode cobrar o custo dos EPIs mediante desconto de 15% na folha de pagamento.",
         "O empregado deve adquirir suas próprias máscaras e luvas em farmácias comerciais da cidade.",
         "O hospital pode fornecer EPIs com CA vencido ou cancelado pelo MTE para contenção de despesas.",
         "O fornecimento só é exigido caso o servidor tenha mais de 3 anos de serviços prestados.",
         "A",
         "O empregador é obrigado a fornecer ao empregado, gratuitamente, EPI adequado ao risco, em perfeito estado de funcionamento e com CA emitido pelo órgão competente.",
         "NR-06, item 6.3 e NR-32",
         "fácil"),
        # 12
        ("Qual tipo de luva de procedimento é o MAIS indicado para profissionais que apresentam histórico comprovado de alergia ao látex natural (hipersensibilidade Tipo I mediada por IgE)?",
         "Luvas de borracha nitrílica ou luvas de vinil / neoprene isentas de látex e sem pó.",
         "Luvas de lã cirúrgica esterilizada com formol.",
         "Luvas de látex de espessura tripla com concentração extra de talco lubrificante.",
         "Luvas de malha de aço entrelaçado com fios de cobre.",
         "Luvas de couro de vaqueta para soldador industrial.",
         "A",
         "Trabalhadores alérgicos ao látex devem receber luvas sintéticas alternativas (nitrila, vinil, neoprene), isentas de proteínas do látex e sem talco irritante.",
         "NR-32, item 32.2.4.8 e Protocolos Dermatológicos",
         "fácil"),
        # 13
        ("Em relação ao uso de talco em luvas cirúrgicas e de procedimento em serviços de saúde, a ANVISA e as boas práticas de segurança recomendam:",
         "O uso de luvas isentas de pó/talco (powder-free), reduzindo reações alérgicas, granulomas cirúrgicos e aerossolização de alérgenos proteicos.",
         "O aumento contínuo da quantidade de talco dentro das luvas para absorver suor.",
         "A colocação de farinha de trigo dentro das luvas caso falte talco no hospital.",
         "A aplicação de pó de giz escolar sobre as mãos antes do enluvamento.",
         "O uso obrigatório de talco perfumado com essência de eucalipto.",
         "A",
         "A RDC ANVISA baniu e restringiu o pó absorvível em luvas médicas devido aos riscos de alergia respiratória, dérmica e granulomas pós-operatórios.",
         "RDC ANVISA e NR-32",
         "média"),
        # 14
        ("O equipamento de proteção individual respiratória que possui eficiência mínima de filtração de 94% a 95% para partículas biológicas aerossolizadas é denominado:",
         "Máscara descartável simples de papel celulose.",
         "Respirador purificador de ar semifacial descartável classe PFF2 (ou padrão internacional N95).",
         "Lenço de seda amarrado em torno do nariz e da boca.",
         "Máscara cirúrgica de uso odonto-médico com visor acrílico.",
         "Protetor auricular tipo plug de inserção de silicone.",
         "B",
         "Os respiradores PFF2 (padrão ABNT/MTE) e N95 (padrão NIOSH) filtram no mínimo 94-95% das partículas de até 0,3 micrômetros (aerossóis biológicos).",
         "ABNT NBR 13698, NR-06 e NR-32",
         "fácil"),
        # 15
        ("Qual a diferença funcional fundamental entre a MÁSCARA CIRÚRGICA e o RESPIRADOR PFF2/N95 no ambiente hospitalar?",
         "A máscara cirúrgica protege contra gotículas pesadas (> 5 µm) e protege o paciente contra secreções do profissional, enquanto a PFF2 veda a face e filtra aerossóis microscópicos inalados.",
         "A máscara cirúrgica é estanque e filtra gases anestésicos voláteis, enquanto a PFF2 só serve para poeira de carvão.",
         "A máscara cirúrgica deve ser lavada com cloro diariamente, enquanto a PFF2 é dissolvida em água.",
         "Não existe nenhuma diferença, ambas possuem a mesma capacidade de vedação e filtragem respiratória.",
         "A PFF2 só pode ser utilizada por profissionais portadores de barba longa volumosa.",
         "A",
         "Máscara cirúrgica protege contra gotículas e não tem vedação hermética perimetral; o respirador PFF2/N95 tem vedação facial e filtração contra aerossóis finos inaláveis.",
         "Diretrizes ANVISA e NR-32",
         "média"),
        # 16
        ("A presença de barba, bigode volumoso ou costeletas longas na face de um profissional de saúde afeta diretamente a eficácia do respirador PFF2/N95 porque:",
         "Os pelos impedem o ajuste anatômico e a vedação periférica hermética com a pele, permitindo a passagem de ar contaminado pelas frestas.",
         "Os pelos da barba desintegram quimicamente as fibras sintéticas de polipropileno do filtro.",
         "O respirador não pode ser esticado sobre rostos com pelos faciais sob risco de explosão.",
         "A NR-32 proíbe o uso de barba exclusivamente por razões estéticas institucionais.",
         "Os pelos absorvem toda a umidade do ar, ressecando a garganta do trabalhador.",
         "A",
         "A barba interfere no selamento periférico da peça semifacial contra a pele, quebrando a vedação e anulando o fator de proteção do respirador.",
         "Manual de Proteção Respiratória Fundacentro e NR-06",
         "fácil"),
        # 17
        ("Em relação à reutilização de respiradores PFF2/N95 durante a jornada de trabalho, em quais circunstâncias o respirador deve ser DESCARTADO IMEDIATAMENTE?",
         "Quando for submetido à luz do sol por mais de 5 minutos.",
         "Se estiver sujo de sangue/secreções, úmido, amassado, perfurado, com elásticos frouxos ou com aumento perceptível da resistência respiratória.",
         "Apenas ao término do ano civil fiscal do hospital.",
         "Sempre que o servidor mudar de plantão de dia para a noite.",
         "Apenas se o trabalhador for aprovado em outro concurso público.",
         "B",
         "Danos mecânicos, sujeira visível por fluidos corporais, umidade excessiva ou perda de ajuste e vedação exigem descarte e substituição imediata da PFF2.",
         "Protocolos ANVISA/MTE e NR-32",
         "fácil"),
        # 18
        ("Ao prestar assistência direta a paciente com suspeita de COVID-19 ou Influenza durante procedimento de intubação orotraqueal na UTI, o conjunto de EPIs correto deve incluir:",
         "Apenas luvas de plástico e máscara cirúrgica com janelas abertas.",
         "Gorro descartável, óculos de segurança com vedação lateral (ou protetor facial acrílico), respirador PFF2/N95, avental impermeável de manga longa e luvas de procedimento.",
         "Jaleco de linho sem mangas, chinelos de borracha e máscara de tecido de algodão simples.",
         "Máscara de mergulho com snorkel e bermuda de banho impermeável.",
         "Protetor auditivo circum-auricular (concha) e botas de couro com biqueira de aço.",
         "B",
         "Procedimentos geradores de aerossol de vírus respiratórios graves exigem proteção completa: PFF2/N95, óculos/face shield, capote impermeável, gorro e luvas.",
         "Protocolos de Manejo de Síndromes Respiratórias ANVISA e NR-32",
         "fácil"),
        # 19
        ("A correta sequência padronizada para a RETIRADA (desparamentação) dos EPIs ao sair de um quarto de isolamento hospitalar visa prevenir a autocontaminação e deve iniciar prioritariamente por:",
         "Máscara PFF2 tocando na frente do filtro com as mãos desnudas.",
         "Luvas de procedimento e avental contaminado (as partes mais expostas a patógenos), com imediata higienização das mãos antes de remover a proteção ocular e respiratória.",
         "Retirar primeiramente as botas de borracha no chão do quarto.",
         "Lavar o jaleco dentro da pia do paciente com o profissional ainda vestindo-o.",
         "Sacudir vigorosamente o avental sujo de secreção para arejar as fibras.",
         "B",
         "As luvas e o avental são as peças mais contaminadas externamente e devem ser retiradas primeiro, com técnica sem contato com o corpo, seguida de antissepsia das mãos.",
         "Diretrizes ANVISA e NR-32",
         "média"),
        # 20
        ("Ao retirar o respirador PFF2 / N95 ao final do procedimento no quarto de isolamento, o trabalhador de saúde deve manipulá-lo:",
         "Segurando pelas bordas e pela face externa frontal do filtro com as mãos.",
         "Exclusivamente pelos elásticos posteriores de fixação na cabeça, sem tocar na superfície externa do filtro que esteve exposta ao ar.",
         "Puxando com os dentes para desamarrar as tiras elásticas.",
         "Friccionando a palma da mão sobre o tecido filtrante frontal.",
         "Enrolando o respirador em uma bola com os dedos contaminados.",
         "B",
         "A face externa do respirador é considerada potencialmente contaminada; a retirada deve ser feita exclusivamente puxando os elásticos por trás da cabeça.",
         "Manual de Biossegurança ANVISA e NR-32",
         "fácil"),
        # 21
        ("Sobre o uso de óculos de segurança em serviços de saúde da FHCGV, a NR-32 e normas técnicas estabelecem que:",
         "Devem possuir armação com proteção lateral e superior, boa transparência visual, tratamento antirrisco e antiembaçante, protegendo contra respingos de sangue e fluidos.",
         "Podem ser substituídos por óculos escuros de sol comuns comprados no comércio ambulante.",
         "São obrigatórios apenas para funcionários que não possuem dentes naturais.",
         "Devem ser confeccionados em vidro comum recozido que estilhaça com facilidade.",
         "São dispensados em cirurgias ortopédicas de grande porte com serra elétrica.",
         "A",
         "Óculos de segurança hospitalar devem vedar projeções laterais e respingos de fluidos biológicos ou químicos nos olhos do operador.",
         "NR-06 e NR-32",
         "fácil"),
        # 22
        ("Qual a recomendação para o trabalhador de saúde que utiliza óculos graduados (de grau) corretivos em atividades assistenciais com risco de respingos?",
         "Ele deve trabalhar sem óculos para evitar que os seus óculos particulares quebrem.",
         "Ele deve utilizar óculos de proteção sobrepostos (sobre-óculos) desenhados para encaixar sobre os óculos de grau, ou óculos de segurança com lentes graduadas confeccionadas com CA.",
         "Ele deve colar fita crepe na lente dos seus óculos de grau para vedar os olhos.",
         "Ele está proibido de trabalhar em hospitais por ter deficiência visual leve.",
         "Ele deve utilizar uma lupa de relojoeiro presa ao supercílio direito.",
         "B",
         "Trabalhadores que usam óculos de grau devem receber sobre-óculos de segurança amplos compatíveis ou óculos de segurança graduados com CA oficial.",
         "NR-06 e NR-32",
         "média"),
        # 23
        ("Em relação ao protetor facial acrílico tipo 'face shield', assinale a afirmação correta:",
         "Ele substitui integralmente a necessidade do uso de respirador PFF2 em ambientes com aerossóis.",
         "Ele fornece excelente proteção de barreira mecânica para os olhos e toda a face contra grandes respingos de fluidos, devendo ser utilizado em conjunto com a máscara/respirador apropriado.",
         "Ele é de uso único, devendo ser descartado no lixo comum a cada 15 minutos.",
         "Ele só deve ser higienizado com ácido sulfúrico fumegante após o uso.",
         "Ele impede a respiração humana por vedar a boca e as narinas hermeticamente.",
         "B",
         "O face shield protege os olhos, mucosas e a própria máscara contra respingos diretos de sangue e fluidos, mas não atua como filtro de aerossol sem o respirador associado.",
         "Diretrizes de Biossegurança e NR-32",
         "fácil"),
        # 24
        ("Os aventais ou capotes utilizados para proteção biológica contra sangue e líquidos corporais durante cirurgias e partos devem possuir:",
         "Mangas compridas com punho elástico ou de malha, comprimento abaixo dos joelhos, abertura dorsal e tecido impermeável de alta barreira biológica.",
         "Abertura frontal com botões frouxos e mangas curtas acima do cotovelo.",
         "Tecido de rede furada transparente para facilitar a passagem de ar frio.",
         "Bolsos frontais largos abertos para acumular secreções biológicas.",
         "Gola alta fechada com arame farpado para manter a postura ereta.",
         "A",
         "Aventais cirúrgicos/impermeáveis devem ter mangas longas, punhos ajustados, fechamento dorsal e impermeabilidade contra fluidos corporais sob pressão.",
         "ABNT NBR 16064 e NR-32",
         "fácil"),
        # 25
        ("Sobre o uso de calçados de segurança em serviços de saúde da FHCGV, assinale a alternativa que descreve o calçado OBRIGATÓRIO pela NR-32:",
         "Sandálias de tiras de couro com salto alto fino de 10 cm.",
         "Chinelos de dedo abertos confeccionados em borracha de praia.",
         "Calçado completamente fechado na região superior e posterior (calcanhar), com sola antiderrapante e material impermeável e lavável.",
         "Sapatos de camurça permeável com solado liso encerado.",
         "Chuteiras de futebol com travas de alumínio de 2 cm.",
         "C",
         "A NR-32 exige calçado fechado (protegendo todo o pé contra perfurocortantes e líquidos) e solado antiderrapante para prevenir quedas em pisos úmidos.",
         "NR-32, item 32.2.4.7",
         "fácil"),
        # 26
        ("A respeito do Certificado de Aprovação (CA) dos Equipamentos de Proteção Individual:",
         "O CA é dispensado para equipamentos utilizados em serviços de saúde do SUS.",
         "Todo EPI, seja de fabricação nacional ou importado, só pode ser posto à venda ou utilizado no trabalho com a indicação do Certificado de Aprovação (CA) expedido pelo órgão nacional competente em matéria de segurança do trabalho.",
         "O CA é emitido pelo conselho regional de medicina local de cada município.",
         "A validade do CA precisa ser verificada apenas no dia da demissão do empregado.",
         "O número do CA pode ser inventado livremente pelo técnico de segurança da unidade.",
         "B",
         "A comercialização e o fornecimento de qualquer EPI no Brasil exigem CA válido emitido pelo Ministério do Trabalho e Emprego (CLT Art. 167 e NR-06).",
         "CLT Art. 167 e NR-06, item 6.2",
         "fácil"),
        # 27
        ("Se a validade do Certificado de Aprovação (CA) de um lote de máscaras PFF2 vencer após a compra válida pelo hospital, as máscaras que estão em estoque:",
         "Devem ser incineradas imediatamente por crime sanitário.",
         "Podem ser utilizadas até a data de validade de fabricação estipulada pelo fabricante, desde que tenham sido adquiridas no período em que o CA estava válido.",
         "Podem ser vendidas a preço de custo aos pacientes da recepção.",
         "Exigem a aplicação de uma carimbada manual do diretor para renovar o CA.",
         "Devem ser enviadas para a Suíça para recertificação internacional.",
         "B",
         "Conforme entendimento consolidado do MTE (Nota Técnica), o EPI adquirido com CA válido pode ser utilizado até o término da validade do produto pelo fabricante.",
         "Nota Técnica MTE e NR-06",
         "média"),
        # 28
        ("Qual é a obrigação do trabalhador da FHCGV quanto ao EPI fornecido pela instituição, conforme o subitem 6.6.2 da NR-06?",
         "Utilizar o equipamento apenas para as finalidades a que se destina, responsabilizar-se pela sua guarda e conservação e comunicar ao empregador qualquer alteração que o torne impróprio para uso.",
         "Vender o EPI usado para colegas de outros hospitais para complementar a renda familiar.",
         "Levar o EPI para casa e utilizá-lo na pintura de paredes do seu condomínio.",
         "Recusar o uso do EPI se a cor do plástico não combinar com seu uniforme pessoal.",
         "Modificar a estrutura do EPI com tesoura e maçarico para torná-lo mais largo.",
         "A",
         "O empregado deve usar o EPI fornecido, cuidar de sua conservação e comunicar imediatamente ao SESMT/chefia qualquer dano ou extravio para substituição.",
         "NR-06, item 6.6.2",
         "fácil"),
        # 29
        ("A disponibilização de vestiários adequados para troca de roupa e banho após o plantão na FHCGV é uma exigência que atende à NR-32 e NR-24 com o propósito de:",
         "Garantir que os trabalhadores não levem sujidade e patógenos biológicos hospitalares para fora do ambiente assistencial, protegendo suas famílias e a comunidade.",
         "Servir como ponto de encontro festivo para churrascos de final de semana dos funcionários.",
         "Obrigar os servidores a gastarem a cota de sabonete fornecida pelo Estado.",
         "Substituir o pagamento de insalubridade por fornecimento de água quente.",
         "Possibilitar a cobrança de ingresso aos visitantes da fundação hospitalar.",
         "A",
         "A higiene pessoal e a troca de vestimenta nos vestiários impedem a disseminação de patógenos hospitalares para o ambiente público e domiciliar dos trabalhadores.",
         "NR-32 e NR-24",
         "fácil"),
        # 30
        ("Em relação ao fornecimento de luvas com espessuras e materiais diferenciados na FHCGV:",
         "Todos os setores, desde a cirurgia cardíaca até a jardinagem externa, devem usar a mesma luva cirúrgica estéril de látex ultrafina nº 7.",
         "A especificação do tipo de luva (procedimento, cirúrgica, nitrílica, borracha pesada com cano longo, anticorte) deve ser compatível com a natureza da tarefa e o agente de risco presente.",
         "As luvas devem ser fornecidas em tamanho único extrapequeno para economizar espaço de prateleira.",
         "É expressamente proibido fornecer luvas aos servidores do setor de expurgo da CME.",
         "As luvas devem ser furadas propositalmente nas pontas dos dedos para respirar a pele.",
         "B",
         "A adequação do EPI ao risco e à biometria do trabalhador é preceito fundamental da NR-06 e NR-32 (luvas finas para destreza, grossas impermeáveis para expurgo e limpeza).",
         "NR-06 e NR-32",
         "fácil")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-32",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr32_vacinacao_epi_questions()
    print(f"Vacinação & EPI questions generated: {len(q)}")
