# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-06: Equipamentos de Proteção Individual (30 questões)
- Certificado de Aprovação (CA): 10 questões
- Obrigações do empregador e empregado: 10 questões
- Tipos e classificação de EPIs: 10 questões
"""

def get_nr06_questions():
    items = [
        # =========================================================
        # 1. CERTIFICADO DE APROVAÇÃO - CA (10 questões)
        # =========================================================
        # 1
        ("Conforme o Artigo 167 da CLT e o item 6.2 da NR-06, todo Equipamento de Proteção Individual (EPI), seja de fabricação nacional ou importado:",
         "Só poderá ser posto à venda ou utilizado com a indicação do Certificado de Aprovação (CA) expedido pelo órgão de âmbito nacional competente em matéria de segurança e saúde no trabalho.",
         "Pode ser vendido sem qualquer teste técnico caso o fabricante possua mais de 10 anos de mercado.",
         "Tem seu registro dispensado caso seja doado gratuitamente a hospitais públicos estaduais.",
         "Pode ter seu número de aprovação inventado pelo técnico de segurança do trabalho do hospital.",
         "Depende apenas de uma autorização verbal emitida pela delegacia de polícia civil local.",
         "A",
         "O Art. 167 da CLT e o item 6.2 da NR-06 exigem que todo EPI, nacional ou importado, possua CA válido emitido pelo Ministério do Trabalho e Emprego para venda e uso.",
         "CLT Art. 167 e NR-06, item 6.2",
         "fácil"),
        # 2
        ("Qual é a consequência legal se uma empresa adquirir e fornecer aos seus trabalhadores equipamentos de proteção cujo Certificado de Aprovação (CA) já estava VENCIDO ou CANCELADO na data da compra?",
         "A empresa comete infração às normas de segurança do trabalho, sendo passível de autuação pela Auditoria Fiscal do Trabalho, pois o equipamento não é legalmente considerado EPI válido.",
         "A empresa recebe incentivos fiscais e descontos tributários pelo aproveitamento de estoques antigos.",
         "O equipamento é automaticamente convalidado se o trabalhador assinar um termo de perdão.",
         "O trabalhador perde a posse de sua carteira profissional por 30 dias.",
         "O Ministério do Trabalho passa a pagar o salário do funcionário de forma subsidiária.",
         "A",
         "A aquisição de EPI com CA vencido ou cancelado no ato da compra é infração à NR-06, descaracterizando a proteção legal e gerando penalidades à empresa.",
         "NR-06, item 6.2 e NR-28",
         "fácil"),
        # 3
        ("Se um lote de EPIs (ex: respiradores PFF2 ou botas de segurança) foi adquirido pela FHCGV com CA VÁLIDO na época da compra, mas o CA veio a expirar posteriormente enquanto as peças ainda estavam estocadas no almoxarifado:",
         "Os EPIs podem ser utilizados normalmente até o limite da data de validade de fabricação estabelecida pelo fabricante, desde que conservados adequadamente nas embalagens originais.",
         "Todos os equipamentos estocados devem ser imediatamente destruídos com ácido no pátio.",
         "O almoxarife deve ser preso em flagrante por crime contra a saúde pública.",
         "O hospital é obrigado a fechar as portas e transferir os pacientes para outros estados.",
         "O número do CA deve ser raspado com uma lixa e substituído por uma etiqueta sem número.",
         "A",
         "Segundo o entendimento consolidado da Secretaria de Inspeção do Trabalho (Nota Técnica), o EPI comprado com CA válido pode ser usado até o fim da vida útil/validade do fabricante.",
         "Nota Técnica MTE e NR-06",
         "média"),
        # 4
        ("A gravação indelével que deve constar obrigatoriamente no corpo de todo Equipamento de Proteção Individual comercializado no Brasil compreende:",
         "O nome comercial do fabricante ou do importador, o lote de fabricação e o número do Certificado de Aprovação (CA).",
         "Apenas o preço de venda da mercadoria em reais com desconto de atacado.",
         "A foto colorida do presidente do sindicato dos trabalhadores da indústria.",
         "A relação de nomes de todos os operários que costuraram a peça na fábrica.",
         "Apenas o endereço do sítio de lazer do dono da fábrica fornecedora.",
         "A",
         "O item 6.9.3 da NR-06 exige que o EPI tenha gravado de forma indelével o nome do fabricante/importador, lote e o número do CA emitido pelo MTE.",
         "NR-06, item 6.9.3",
         "fácil"),
        # 5
        ("Caso a gravação do número do CA no corpo do próprio EPI seja tecnicamente inviável devido às dimensões reduzidas ou material da peça (ex: protetores auriculares tipo plug ou luvas cirúrgicas ultrafinas):",
         "A indicação do CA, fabricante e lote deve constar obrigatoriamente na embalagem primária ou secundária do produto.",
         "O equipamento fica expressamente proibido de ser comercializado em qualquer hipótese.",
         "O trabalhador deve tatuar o número do CA no dorso de sua mão esquerda.",
         "O equipamento pode ser vendido anonimamente a granel sem nenhuma etiqueta de rastreio.",
         "O fabricante fica dispensado de realizar ensaios laboratoriais de conformidade técnica.",
         "A",
         "Quando não for viável marcar o próprio produto, a NR-06 autoriza que a identificação e o número do CA constem na embalagem correspondente.",
         "NR-06, subitem 6.9.3.1",
         "média"),
        # 6
        ("Qual é a entidade ou órgão federal responsável no Brasil pela realização de testes, emissão, prorrogação, renovação ou cancelamento do Certificado de Aprovação (CA) de EPIs?",
         "O Ministério do Trabalho e Emprego (por meio de sua Secretaria competente em SST e laboratórios acreditados pelo INMETRO).",
         "O Conselho Federal de Engenharia e Agronomia (CONFEA).",
         "O Instituto Brasileiro de Geografia e Estatística (IBGE).",
         "A Superintendência da Zona Franca de Manaus (SUFRAMA).",
         "A Agência Nacional de Transportes Aquaviários (ANTAQ).",
         "A",
         "A emissão e gestão do Certificado de Aprovação (CA) é competência institucional exclusiva do Ministério do Trabalho e Emprego (MTE).",
         "CLT Art. 167 e NR-06",
         "fácil"),
        # 7
        ("A consulta pública oficial sobre a situação cadastral, validade, normas técnicas de ensaio e laudos laboratoriais de um número de CA pode ser realizada online através:",
         "Do sistema de Consulta de Certificado de Aprovação de EPI (CAEPI) do Ministério do Trabalho e Emprego.",
         "Do aplicativo de mensagens pessoais do ministro da economia.",
         "Do portal de leilões da Receita Federal de mercadorias apreendidas.",
         "Do boletim oficial das Forças Armadas do Brasil.",
         "Da lista telefônica comercial impressa do estado do Pará.",
         "A",
         "O sistema oficial do governo federal (CAEPI) permite a qualquer cidadão, empresa ou perito verificar a validade e especificações do CA de um EPI.",
         "MTE e NR-06",
         "fácil"),
        # 8
        ("A emissão do Certificado de Aprovação (CA) para um respirador do tipo PFF2/N95 no Brasil depende da apresentação prévia de laudos técnicos de ensaios laboratoriais acreditados pelo:",
         "INMETRO (Instituto Nacional de Metrologia, Qualidade e Tecnologia).",
         "Banco Central do Brasil.",
         "Conselho Administrativo de Defesa Econômica (CADE).",
         "Instituto Chico Mendes de Conservação da Biodiversidade (ICMBio).",
         "Departamento Nacional de Infraestrutura de Transportes (DNIT).",
         "A",
         "Os EPIs passam por ensaios de conformidade em laboratórios acreditados e organismos de certificação vinculados ao INMETRO para obter o CA do MTE.",
         "Portaria MTE e NR-06",
         "média"),
        # 9
        ("A alteração proposital das características originais de um EPI (como furar um protetor facial para ventilar ou cortar os dedos de uma luva de vaqueta):",
         "Invalida a proteção técnica certificada pelo CA e transfere a responsabilidade civil e criminal por eventuais acidentes a quem adulterou o equipamento.",
         "É recomendada formalmente pela NR-06 para aumentar o conforto estético do operador.",
         "Gera aumento do nível de atenuação sonora de protetores de ouvido.",
         "Deve ser realizada com maçarico de acetileno a cada 15 dias de uso.",
         "É permitida desde que a empresa pague um adicional de 5% ao funcionário.",
         "A",
         "Modificar o EPI invalida a certificação do CA, anula a garantia do fabricante e quebra a barreira de segurança, expondo o operador a riscos graves.",
         "NR-06 e Doutrina de SST",
         "fácil"),
        # 10
        ("Qual é o prazo máximo de validade geral de um Certificado de Aprovação (CA) concedido pelo Ministério do Trabalho aos fabricantes de EPIs antes de sua renovação periódica?",
         "Geralmente 5 anos, mediante renovação vinculada a novos ensaios laboratoriais ou avaliação de conformidade.",
         "Exatamente 30 dias após a publicação no Diário Oficial.",
         "Vigência perpétua de 100 anos sem necessidade de novos testes.",
         "24 horas, devendo ser renovado diariamente pelo fabricante.",
         "10 anos sem qualquer acompanhamento técnico de qualidade.",
         "A",
         "A validade padrão do Certificado de Aprovação é de até 5 anos, devendo o fabricante requerer a renovação com antecedência mediante comprovação de conformidade.",
         "Portaria MTE e NR-06",
         "média"),

        # =========================================================
        # 2. OBRIGAÇÕES DO EMPREGADOR E DO EMPREGADO (10 questões)
        # =========================================================
        # 11
        ("O subitem 6.5.1 da NR-06 estabelece que cabe ao EMPREGADOR quanto ao EPI, dentre outras, as seguintes obrigações, EXCETO:",
         "Adquirir o EPI adequado ao risco de cada atividade.",
         "Exigir seu uso pelos empregados.",
         "Fornecer ao empregado somente o aprovado pelo órgão nacional competente em SST.",
         "Orientar e treinar o empregado sobre o uso adequado, guarda e conservação.",
         "Cobrar o valor de custo do EPI mediante desconto em folha de pagamento no final do mês.",
         "E",
         "O fornecimento do EPI deve ser GRATUITO (CLT Art. 166 e NR-06, item 6.3). Cobrar ou descontar o valor do EPI é ilegal.",
         "CLT Art. 166 e NR-06, item 6.5.1",
         "fácil"),
        # 12
        ("Em relação à higienização e manutenção periódica dos EPIs reutilizáveis (como aventais de chumbo, óculos de segurança e protetores auriculares tipo concha):",
         "A responsabilidade pela higienização e manutenção é do empregador, podendo ser realizada pelo próprio hospital ou por lavanderia especializada.",
         "A responsabilidade é exclusiva do empregado, que deve levar o avental com sangue para lavar no tanque de sua casa.",
         "O equipamento deve ser jogado fora no rio após cada dia de trabalho.",
         "É expressamente proibido limpar ou lavar qualquer EPI reutilizável.",
         "A manutenção deve ser paga com rifas organizadas entre os pacientes.",
         "A",
         "A NR-06 (subitem 6.5.1, alínea 'e') estipula que cabe ao empregador responsabilizar-se pela higienização e manutenção periódica dos EPIs.",
         "NR-06, item 6.5.1",
         "fácil"),
        # 13
        ("O registro do fornecimento do EPI ao trabalhador pelo empregador (subitem 6.5.1, alínea 'h' da NR-06):",
         "Pode ser feito mediante livros, fichas de controle de EPI físicas assinadas ou sistema eletrônico seguro que comprove a entrega e o número do CA.",
         "É dispensado para hospitais filantrópicos e fundações estaduais.",
         "Deve ser gravado exclusivamente em placas de bronze afixadas na parede externa.",
         "Só tem validade se for registrado em cartório de títulos e documentos da capital toda semana.",
         "Pode ser substituído por uma piscada de olhos em sinal de concordância mútua.",
         "A",
         "O registro de entrega do EPI pode ser feito por ficha de papel com assinatura ou sistema eletrônico rastreável com assinatura biométrica/digital.",
         "NR-06, item 6.5.1, alínea 'h'",
         "fácil"),
        # 14
        ("Quando um EPI for danificado ou extraviado involuntariamente durante a jornada regular de trabalho na FHCGV, a obrigação imediata do empregador é:",
         "Substituí-lo imediatamente sem qualquer cobrança financeira ao trabalhador.",
         "Suspender o trabalhador por 15 dias sem direito a alimentação.",
         "Obrigar o trabalhador a continuar a tarefa sem nenhuma proteção.",
         "Exigir que o servidor faça um empréstimo bancário para comprar outra peça nova.",
         "Demiti-lo sumariamente por depredação dolosa do patrimônio do Estado.",
         "A",
         "Cabe ao empregador 'substituir imediatamente, quando danificado ou extraviado' o EPI, assegurando a continuidade da proteção (NR-06, item 6.5.1, alínea 'd').",
         "NR-06, item 6.5.1, alínea 'd'",
         "fácil"),
        # 15
        ("De acordo com o subitem 6.6.1 da NR-06, cabe ao EMPREGADO quanto ao EPI:",
         "Usar o equipamento fornecido pela organização apenas para a finalidade a que se destina, responsabilizar-se pela sua guarda e conservação e comunicar qualquer alteração que o torne impróprio.",
         "Vender o equipamento excedente para outros hospitais para complementar a renda familiar.",
         "Levar o protetor auditivo para casa e emprestá-lo para seus vizinhos assistirem filmes.",
         "Recusar o uso do EPI caso ele não combine com a cor do sapato particular.",
         "Modificar a estrutura de segurança da bota com faca para deixá-la aberta.",
         "A",
         "As obrigações do empregado são: usar apenas para a finalidade devida, guardar e zelar pela conservação e comunicar ao empregador qualquer defeito ou dano.",
         "NR-06, item 6.6.1",
         "fácil"),
        # 16
        ("Se um técnico de enfermagem recusar-se expressamente e de forma injustificada a utilizar o respirador PFF2 e as luvas de procedimento fornecidos gratuitamente pelo hospital para atendimento em quarto de isolamento:",
         "Sua conduta constitui ato faltoso passível de punição disciplinar pelo empregador (advertência, suspensão e, em caso de reiteração, demissão por justa causa conforme CLT Art. 158).",
         "O técnico tem o direito subjetivo de trabalhar desprotegido caso alegue calor no rosto.",
         "A direção do hospital deve ser presa por desrespeitar a vontade individual do servidor.",
         "O hospital é obrigado a pagar o dobro do salário ao funcionário que recusa o EPI.",
         "O técnico é imediatamente promovido a chefe da Comissão de Controle de Infecção Hospitalar.",
         "A",
         "O Art. 158 da CLT prevê expressamente que a recusa injustificada do empregado em usar o EPI fornecido pela empresa constitui ato faltoso passível de sanções disciplinares.",
         "CLT Art. 158, parágrafo único e NR-06",
         "fácil"),
        # 17
        ("O empregador tem o dever de comunicar ao órgão nacional competente em matéria de segurança e saúde no trabalho (MTE):",
         "Qualquer irregularidade observada no EPI fornecido (como defeitos de fabricação em série ou ineficácia do CA).",
         "A lista de todos os servidores que aniversariam na semana corrente.",
         "A marca de café consumida pelos funcionários no plantão noturno.",
         "O resultado dos jogos do campeonato de futebol do Pará.",
         "O número de vezes que os trabalhadores foram ao banheiro durante o dia.",
         "A",
         "A NR-06 (subitem 6.5.1, alínea 'f') obriga a organização a comunicar ao MTE qualquer irregularidade técnica constatada no EPI fornecido pelos fabricantes.",
         "NR-06, item 6.5.1, alínea 'f'",
         "média"),
        # 18
        ("A orientação e o treinamento do trabalhador sobre o uso adequado, guarda e conservação do EPI devem ser realizados pelo empregador:",
         "No momento da admissão e periodicamente, ou sempre que houver substituição do modelo de EPI ou alteração de riscos.",
         "Apenas após o trabalhador completar 25 anos de serviços prestados.",
         "Exclusivamente durante as férias regulamentares do empregado sem remuneração.",
         "Por meio de uma folha de papel dobrada colocada dentro da caixa do sapato.",
         "Apenas se o trabalhador pagar R$ 50,00 por hora de aula ao técnico de segurança.",
         "A",
         "O treinamento em EPI é dever do empregador e deve ser realizado na admissão e sempre que novos modelos ou riscos exijam instruções específicas de ajuste e conservação.",
         "NR-06, item 6.5.1, alínea 'c'",
         "fácil"),
        # 19
        ("A respeito da seleção e adequação biométrica do EPI ao trabalhador:",
         "O EPI deve ser selecionado considerando o conforto, a eficácia da proteção e as características físicas (tamanho, formato) do trabalhador.",
         "Todos os trabalhadores, do menor porte ao maior peso, devem usar luvas e calçados em tamanho único P.",
         "A estética do equipamento e sua marca comercial são os únicos fatores que determinam a escolha.",
         "O empregador deve sortear os números de botas em uma roleta de bingo.",
         "A empresa só é obrigada a fornecer EPIs que caibam nos membros da diretoria.",
         "A",
         "A NR-06 exige que a seleção do EPI considere a atividade, os riscos, a compatibilidade ergonômica e as medidas antropométricas do usuário.",
         "NR-06, item 6.5.2",
         "fácil"),
        # 20
        ("Qual é a conduta do empregado ao perceber que a sua máscara PFF2 está rasgada na borda elástica logo antes de entrar em uma enfermaria de isolamento biológico?",
         "Comunicar imediatamente a alteração ao superior/SESMT e solicitar a substituição da máscara por outra íntegra antes de iniciar o atendimento.",
         "Entrar na enfermaria desprotegido e prender a respiração durante 40 minutos.",
         "Colocar um pedaço de chiclete mascado para tampar o rasgo da máscara.",
         "Amarrar a máscara com arame farpado apertando as bochechas.",
         "Ignorar o defeito e tossir de propósito sobre o paciente internado.",
         "A",
         "O empregado deve comunicar imediatamente ao empregador qualquer alteração que torne o EPI impróprio para uso (NR-06, item 6.6.1, alínea 'b').",
         "NR-06, item 6.6.1, alínea 'b'",
         "fácil"),

        # =========================================================
        # 3. TIPOS E CLASSIFICAÇÃO DE EPIS (10 questões)
        # =========================================================
        # 21
        ("O equipamento de proteção individual destinado a proteger a cabeça contra impactos de objetos quedados do alto e choques elétricos em obras de manutenção predial é o:",
         "Capacete de segurança (Classe A para impacto geral ou Classe B para impacto e riscos elétricos).",
         "Chapéu de palha de praia com abas largas.",
         "Gorro cirúrgico de tnt impermeável.",
         "Boné esportivo de time de futebol.",
         "Capuz de lã tricotado manualmente.",
         "A",
         "Os capacetes de segurança com CA dividem-se em Classe A (impactos mecânicos) e Classe B (impactos mecânicos e proteção contra choques elétricos de alta tensão).",
         "ABNT NBR 8221 e NR-06, Anexo I",
         "fácil"),
        # 22
        ("Qual é a diferença de indicação entre as luvas cirúrgicas estéreis e as luvas de procedimento não estéreis no contexto hospitalar?",
         "Luvas cirúrgicas são estéreis, usadas para procedimentos invasivos e cirúrgicos que exigem assepsia rigorosa; luvas de procedimento não são estéreis, usadas para contato com mucosas, sangue e fluidos em exames de rotina.",
         "Luvas cirúrgicas são feitas de ferro fundido e luvas de procedimento de papel celulose.",
         "Luvas de procedimento são usadas apenas para lavar pisos de corredores externos.",
         "Não existe nenhuma diferença técnica, o nome muda apenas por razões de marketing comercial.",
         "Luvas cirúrgicas só podem ser calçadas após a meia-noite em dias pares.",
         "A",
         "A esterilidade é a diferença-chave: cirúrgicas protegem o campo operatório asséptico e o cirurgião; as de procedimento protegem o profissional contra contaminação por contato diário.",
         "NR-32 e Protocolos ANVISA",
         "fácil"),
        # 23
        ("Os respiradores purificadores de ar mecânicos são classificados pela norma técnica (ABNT NBR 13698) em três classes de filtros: PFF1, PFF2 e PFF3. A classe PFF2 possui eficiência mínima de filtração de:",
         "94% contra poeiras, névoas e aerossóis biológicos (padrão equivalente ao N95 americano).",
         "10% apenas contra fumaça de cigarro.",
         "50% contra folhas secas que caem de árvores.",
         "99,99% apenas contra o gás hélio inodoro.",
         "100% contra disparos de projéteis de armas de fogo.",
         "A",
         "A peça semifacial filtrante PFF2 filtra no mínimo 94% dos aerossóis de ensaio (0,3 µm), sendo o respirador recomendado em biossegurança contra patógenos aéreos.",
         "ABNT NBR 13698 e NR-06",
         "fácil"),
        # 24
        ("Para a proteção respiratória em ambientes com deficiência de oxigênio (concentração de O2 no ar abaixo de 12,5% em volume), é TERMINANTEMENTE PROIBIDO o uso de:",
         "Respiradores purificadores de ar (com filtros mecânicos ou químicos), devendo-se utilizar obrigatoriamente respiradores de adução de ar (máscara autônoma ou linha de ar comprimido).",
         "Cilindros de ar respirável medicinal comprimido.",
         "Linhas de suprimento contínuo de ar filtrado tipo narguilé hospitalar.",
         "Aparelhos de respiração autônoma de circuito aberto de pressão positiva.",
         "Qualquer equipamento que forneça ar puro comprimido ao operador.",
         "A",
         "Filtros purificadores não geram oxigênio; em atmosferas IPVS com asfixia ou deficiência de oxigênio (< 12,5%), é obrigatório o uso de suprimento de ar (adução de ar).",
         "PPR Fundacentro e NR-06",
         "média"),
        # 25
        ("Em relação à atenuação sonora fornecida por protetores auriculares, o indicador técnico medido em decibéis que indica o nível de redução de ruído obtido em ensaios laboratoriais com usuários treinados é o:",
         "NRRsf (Nível de Redução de Ruído Subject Fit).",
         "IBUTG (Índice de Bulbo Úmido Termômetro de Globo).",
         "PPM (Partes Por Milhão de Mercúrio).",
         "BTU (British Thermal Unit).",
         "pH (Potencial Hidrogeniônico da Água).",
         "A",
         "O NRRsf (Subject Fit) é a métrica brasileira adotada no CA do MTE para indicar a redução sonora real média proporcionada pelo protetor auditivo ao trabalhador.",
         "ANSI S12.6, Fundacentro e NR-06",
         "fácil"),
        # 26
        ("Para a realização de trabalhos em altura (atividades executadas acima de 2,00 m do nível inferior com risco de queda) na manutenção predial do hospital, o EPI de retenção de queda obrigatório é:",
         "O cinturão de segurança tipo paraquedista integrado com dispositivo trava-quedas ou talabarte de segurança.",
         "O cinto de couro abdominal simples do tipo eletricista antigo sem alças nos ombros.",
         "Uma corda de sisal amarrada firmemente em torno do pescoço do trabalhador.",
         "Uma rede de pesca amarrada nas pernas do empregado.",
         "Sapatos com solado de couro liso encerado sem travas.",
         "A",
         "A NR-35 e a NR-06 proíbem o cinto abdominal para retenção de queda, exigindo o cinturão tipo paraquedista conectado a talabarte com absorvedor de energia ou trava-quedas.",
         "NR-35 e NR-06, Anexo I",
         "fácil"),
        # 27
        ("As luvas confeccionadas em borracha nitrílica são amplamente utilizadas em serviços de saúde e farmácias hospitalares porque:",
         "Apresentam excelente resistência química a solventes e citostáticos, boa resistência mecânica a rasgos e não provocam alergia ao látex natural.",
         "São feitas de algodão cru e deixam passar todos os líquidos infecciosos.",
         "Dissolvem-se em contato com a água corrente da torneira.",
         "São destinadas unicamente a soldadores industriais de tubulações de gás.",
         "Devem ser trocadas a cada 10 anos de uso contínuo.",
         "A",
         "A borracha nitrílica sintética combina proteção mecânica superior, ampla compatibilidade com saneantes e quimioterápicos e ausência de proteínas do látex.",
         "NR-06 e NR-32",
         "fácil"),
        # 28
        ("Qual é o tipo de calçado de segurança exigido pela NR-32 para trabalhadores que atuam em serviços hospitalares e de saúde em geral?",
         "Calçado completamente fechado (região anterior e calcanhar), solado antiderrapante e confeccionado em material impermeável e lavável.",
         "Chinelos abertos de tiras de borracha de praia.",
         "Tamancos de madeira com salto alto e abertura frontal nos dedos.",
         "Sandálias de couro com solado de feltro de lã escorregadio.",
         "Botas de cano longo com furos circulares nas solas para respiração.",
         "A",
         "A NR-32 proíbe o uso de calçados abertos; o calçado deve ser completamente fechado e antiderrapante para evitar quedas e perfurações por agulhas descartadas.",
         "NR-32, item 32.2.4.7 e NR-06",
         "fácil"),
        # 29
        ("Em relação à proteção ocular contra impactos de partículas volantes multidirecionais e respingos de produtos químicos e biológicos nos olhos:",
         "Os óculos de segurança devem dispor de proteção lateral e ajuste anatômico ao contorno da face (óculos de ampla visão com ventilação indireta).",
         "Podem ser utilizados óculos de natação com lentes escuras espelhadas.",
         "Basta o trabalhador piscar rapidamente os olhos quando ouvir um barulho de vidro quebrando.",
         "Óculos de sol esportivos comprados em camelôs suprem qualquer exigência de segurança.",
         "Os óculos de segurança devem ser retirados sempre que houver risco de respingos.",
         "A",
         "Óculos de ampla visão (goggles) com proteção periférica e vedação evitam a entrada de respingos e aerossóis químicos ou biológicos nos olhos do operador.",
         "NR-06 e NR-32",
         "fácil"),
        # 30
        ("Qual é o equipamento de proteção individual indicado para proteger a pele das mãos e antebraços contra temperaturas extremas frias (ex: manuseio de gelo seco ou ultrafreezers de vacinas a -80ºC na farmácia hospitalar)?",
         "Luvas de proteção criogênica (térmica para baixas temperaturas) com CA específico.",
         "Luvas cirúrgicas de látex ultrafinas número 6.",
         "Luvas de malha de algodão sem dedos.",
         "Manuseio direto com as mãos despidas molhadas em água morna.",
         "Luvas plásticas descartáveis de fechar sanduíches.",
         "A",
         "O contato com superfícies ou recipientes criogênicos a temperaturas ultrabaixas exige luvas isolantes térmicas contra frio extremo (EPI com CA para frio).",
         "NR-06, Anexo I e Manual de Biossegurança",
         "fácil")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-06",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr06_questions()
    print(f"NR-06 questions generated: {len(q)}")
