# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-32: Risco Químico e Risco Físico (30 questões)
- Risco químico (anestésicos, citostáticos): 20 questões
- Risco físico (radiações ionizantes): 10 questões
"""

def get_nr32_quimico_fisico_questions():
    items = [
        # =========================================================
        # RISCO QUÍMICO: ANESTÉSICOS E CITOSTÁTICOS (20 questões)
        # =========================================================
        # 1
        ("Em relação à manipulação de medicamentos quimioterápicos antineoplásicos (citostáticos) na farmácia hospitalar da FHCGV, a NR-32 e normas sanitárias exigem que ela ocorra obrigatoriamente dentro de:",
         "Uma bancada de madeira aberta ao lado da janela da enfermaria.",
         "Cabine de Segurança Biológica (CSB) Classe II Tipo B2, dotada de exaustão de ar 100% externa através de filtro HEPA, sem recirculação de ar para o ambiente.",
         "Uma capela química simples com exaustor doméstico de cozinha.",
         "Um carrinho de emergência móvel posicionado no corredor central.",
         "Uma sala com ar-condicionado de janela convencional em velocidade máxima.",
         "B",
         "A manipulação de antineoplásicos exige Cabine de Segurança Biológica Classe II B2 com 100% de exaustão para o exterior através de filtros HEPA absolutos (NR-32, item 32.3.7.6).",
         "NR-32, item 32.3.7.6 e RDC 220/ANVISA",
         "fácil"),
        # 2
        ("Qual é a conduta obrigatória em relação às trabalhadoras gestantes ou lactantes que atuam no setor de oncologia hospitalar com risco de exposição a quimioterápicos antineoplásicos?",
         "Devem realizar o dobro do número de manipulações de quimioterápicos para aumentar a resistência física.",
         "Devem ser afastadas imediatamente dessas atividades e remanejadas para setores sem exposição a agentes teratogênicos e citotóxicos.",
         "Podem continuar manipulando citostáticos desde que usem duas máscaras cirúrgicas sobrepostas.",
         "Devem ser submetidas a quimioterapia profilática em baixas doses.",
         "Devem ter seus salários reduzidos em 50% enquanto durar a gestação.",
         "B",
         "O item 32.3.7.1.3 da NR-32 proíbe expressamente a exposição de gestantes e lactantes a medicamentos quimioterápicos antineoplásicos devido aos riscos mutagênicos e teratogênicos.",
         "NR-32, item 32.3.7.1.3",
         "fácil"),
        # 3
        ("Em relação aos Equipamentos de Proteção Individual para o manipulador de antineoplásicos citostáticos, a NR-32 estabelece o uso de:",
         "Avental de linho comum aberto na frente com mangas curtas.",
         "Avental impermeável com baixa permeabilidade, frente fechada, mangas compridas com punhos elásticos ajustados e fechamento dorsal.",
         "Camiseta regata de algodão e bermuda jeans confortável.",
         "Jaleco hospitalar padrão de botões frontais com bolsos abertos.",
         "Capa de chuva de PVC industrial transparente de uso em rodovias.",
         "B",
         "O avental para manuseio de citostáticos deve ser impermeável, com baixa liberação de partículas, frente inteiriça sem abertura frontal, mangas longas e punho elástico.",
         "NR-32, item 32.3.7.6.4",
         "média"),
        # 4
        ("Sobre o uso de luvas durante a manipulação de quimioterápicos antineoplásicos na farmácia de oncologia da FHCGV:",
         "O trabalhador deve utilizar duplo enluvamento com luvas apropriadas para citostáticos, sem pó (talco), devendo ser trocadas no máximo a cada 30 minutos ou imediatamente se houver contaminação ou rasgo.",
         "O trabalhador deve usar uma única luva cirúrgica que pode ser lavada e reutilizada por 3 meses.",
         "O uso de luvas é dispensado para permitir maior sensibilidade tátil com agulhas finas.",
         "Devem ser usadas luvas de couro tipo vaqueta com reforço metálico no polegar.",
         "O profissional deve aplicar talco em grande quantidade antes de calçar as luvas.",
         "A",
         "Recomenda-se duplo enluvamento específico para citostáticos, isento de pó, trocado periodicamente a cada 30 minutos para evitar permeação química para a pele.",
         "NR-32 e Diretrizes de Oncologia Farmacêutica",
         "média"),
        # 5
        ("Em caso de acidente com derramamento ou respingo de quimioterápico antineoplásico líquido no piso da área de manipulação, o procedimento de emergência exige o uso imediato do:",
         "'Kit de Derramamento' contendo EPIs adequados (respirador, luvas, óculos, avental), compressas absorventes, neutralizante, pinça para vidros e saco plástico de descarte específico.",
         "Aparelho de lavar piso de alta pressão industrial para espalhar o líquido pelo corredor.",
         "Esfregão seco de algodão comum manipulado com as mãos desnudas.",
         "Ventilador de pedestal para soprar o pó químico para as áreas abertas do hospital.",
         "Aspirador de pó residencial comum com saco de papel reciclável.",
         "A",
         "Todo setor de manipulação deve possuir 'Kit de Derramamento' para contenção imediata e segura de citostáticos com proteção individual e descarte em resíduo químico Grupo B.",
         "NR-32, item 32.3.7.6 e RDC 220/ANVISA",
         "fácil"),
        # 6
        ("A respeito do descarte de sobras e frascos vazios de medicamentos quimioterápicos antineoplásicos, a classificação de resíduos da ANVISA (RDC 222/2018) enquadra-os no:",
         "Grupo A (Biológico infectante comum).",
         "Grupo B (Resíduo Químico perigoso - citostático/teratogênico).",
         "Grupo C (Rejeito radioativo nuclear).",
         "Grupo D (Resíduo comum reciclável de escritório).",
         "Grupo E (Perfurocortante sem risco químico associado).",
         "B",
         "Frascos, ampolas e materiais com resíduos de citostáticos são resíduos perigosos do Grupo B (químicos com propriedades carcinogênicas, mutagênicas ou teratogênicas).",
         "RDC 222/2018 e NR-32",
         "fácil"),
        # 7
        ("Nos centros cirúrgicos da FHCGV onde são administrados gases e vapores anestésicos voláteis (como sevoflurano, isoflurano e óxido nitroso), a NR-32 exige:",
         "A proibição do uso de ar-condicionado durante os atos cirúrgicos para não soprar os gases.",
         "Sistema de exaustão e captação de gases residuais dos aparelhos de anestesia (scavenging system), garantindo a eliminação segura para fora do ambiente e renovação do ar da sala.",
         "A retenção dos gases no interior da sala cirúrgica para anestesiar a equipe médica.",
         "A queima dos gases voláteis com isqueiro aceso próximo ao cilindro de oxigênio.",
         "A colocação de baldes de água com sal no piso para absorver o óxido nitroso.",
         "B",
         "Aparelhos de anestesia devem possuir sistema de captação e exaustão dos gases anestésicos residuais para o exterior (sistema scavenging), com controle de vazamentos.",
         "NR-32, item 32.3.8",
         "média"),
        # 8
        ("A exposição crônica de técnicos e enfermeiros do centro cirúrgico a vapores de gases anestésicos residuais sem exaustão adequada está clinicamente associada a:",
         "Crescimento acelerado dos dentes e unhas das mãos.",
         "Efeitos neurocomportamentais (fadiga, cefaleia), alterações hepáticas, renais e aumento do risco de abortamento espontâneo em trabalhadoras gestantes.",
         "Aumento da acuidade auditiva e melhora da memória recente.",
         "Cura espontânea de diabetes mellitus tipo 1.",
         "Perda instantânea de toda a pigmentação dos cabelos em 24 horas.",
         "B",
         "Vapores anestésicos residuais exercem toxicidade hepática, renal, dores de cabeça, fadiga crônica e aumento estatístico de abortamentos e malformações fetais.",
         "NR-32, item 32.3.8 e ACGIH",
         "média"),
        # 9
        ("O glutaraldeído, substância química amplamente utilizada no passado para desinfecção de alto nível de endoscópios e materiais na CME, teve seu uso restrito e substituído prioritariamente por:",
         "Querosene de aviação ou gasolina automotiva adulterada.",
         "Ácido peracético ou métodos automatizados de esterilização física (como autoclave a vapor ou plasma de peróxido de hidrogênio), devido à alta toxicidade respiratória e ocular do glutaraldeído.",
         "Água sanitária de supermercado com sabão em pó aromatizado.",
         "Imersão em suco puro de limão com vinagre concentrado.",
         "Exposição à luz de velas perfumadas de cera de abelha.",
         "B",
         "Devido à toxicidade e vapores irritantes do glutaraldeído (asma ocupacional, dermatites e alergias), as diretrizes da ANVISA recomendam ácido peracético ou esterilização automatizada.",
         "RDC 15/ANVISA e NR-32",
         "fácil"),
        # 10
        ("Nos locais de esterilização e desinfecção química na CME onde se utilizam agentes químicos como ácido peracético ou glutaraldeído, o ambiente deve dispor de:",
         "Sistema de ventilação e exaustão local exclusivo, lavatórios com água corrente, lava-olhos de emergência e chuveiro de segurança.",
         "Apenas ventilador de teto comum mantido desligado para não agitar os vapores.",
         "Portas e janelas hermeticamente seladas com cimento armado.",
         "Piso acarpetado com feltro de algodão para absorver os vapores químicos.",
         "Apenas uma caixa de fósforos para queimar os vapores ácidos.",
         "A",
         "Áreas com manipulação de saneantes fortes exigem exaustão mecânica, chuveiro de emergência e lava-olhos com fácil acesso para atendimento a acidentes com respingos.",
         "NR-32, item 32.3.4",
         "média"),
        # 11
        ("Em relação ao formaldeído (formol) utilizado para conservação de peças anatômicas no laboratório de patologia e no necrotério da FHCGV:",
         "Trata-se de substância considerada inofensiva e potável segundo os limites da NR-15.",
         "Trata-se de substância tóxica, irritante grave das vias aéreas e classificada como comprovadamente cancerígena para humanos (Grupo 1 pela IARC), exigindo manipulação em capelas de exaustão química com EPIs adequados.",
         "Deve ser manipulado em ambientes sem ventilação para impedir a perda do produto por evaporação.",
         "O profissional deve cheirar o frasco periodicamente para avaliar a sua concentração volumétrica.",
         "A NR-32 proíbe o uso de luvas de borracha durante a manipulação do formol.",
         "B",
         "O formaldeído é comprovadamente carcinogênico humano (câncer nasofaringe e leucemia) e irritante severo; sua manipulação exige capela com exaustão externa e respiradores com filtro para vapores químicos.",
         "IARC, NR-15 e NR-32",
         "fácil"),
        # 12
        ("Qual é o documento técnico obrigatório que deve acompanhar todos os produtos químicos perigosos recebidos no hospital e ficar disponível para consulta dos trabalhadores?",
         "A Certidão Negativa de Débitos Tributários da Secretaria de Fazenda.",
         "A Ficha com Dados de Segurança de Produtos Químicos (antiga FISPQ / atual FDS), contendo propriedades de perigo, primeiros socorros, combate a incêndio e EPIs recomendados.",
         "A Nota Fiscal assinada pelo motorista do caminhão de entrega.",
         "A receita médica manuscrita pelo diretor clínico do hospital.",
         "O boletim de ocorrência policial do bairro onde a fábrica está localizada.",
         "B",
         "A FDS (Ficha com Dados de Segurança, antiga FISPQ) é obrigatória pela NR-26 e NR-32, contendo informações detalhadas sobre toxicidade, primeiros socorros e medidas de segurança.",
         "NR-26, item 26.2 e NR-32, item 32.3",
         "fácil"),
        # 13
        ("No armazenamento de recipientes contendo produtos químicos perigosos (inflamáveis, corrosivos, tóxicos) no almoxarifado do hospital, é PROIBIDO:",
         "Armazená-los em prateleiras resistentes e identificadas com rótulos de perigo.",
         "Armazenar produtos químicos incompatíveis juntos (como substâncias oxidantes ao lado de inflamáveis) e colocar recipientes pesados em alturas perigosas sem bacia de contenção de vazamentos.",
         "Manter o local arejado e com acesso restrito a pessoas autorizadas.",
         "Disponibilizar extintores de incêndio adequados à classe dos produtos químicos.",
         "Utilizar equipamentos de proteção individual durante a movimentação dos frascos.",
         "B",
         "A incompatibilidade química pode gerar reações violentas, liberação de gases tóxicos e fogo. Devem ser segregados com bacias de contenção e ventilação adequada.",
         "NR-32, item 32.3.2 e NR-20",
         "fácil"),
        # 14
        ("Durante o fracionamento de álcool líquido 70% ou manipulação de hipoclorito de sódio concentrado na FHCGV, os profissionais devem utilizar:",
         "Apenas sandálias havaianas e relógio de pulso.",
         "Avental de proteção impermeável, luvas resistentes ao produto químico (ex: nitrílica ou PVC), óculos de segurança ampla visão ou viseira e proteção respiratória apropriada.",
         "Roupas de lã pura sem qualquer proteção facial ou ocular.",
         "Máscara cirúrgica frouxa pendurada na orelha e bermuda de banho.",
         "Apenas anéis de prata para oxidar com os vapores do cloro.",
         "B",
         "O fracionamento de produtos químicos perigosos exige EPIs impermeáveis contra respingos corrosivos (óculos, avental de PVC, luvas nitrílicas) e ventilação adequada.",
         "NR-32 e NR-06",
         "fácil"),
        # 15
        ("Em relação ao transporte interno de recipientes de vidro contendo produtos químicos perigosos (como ácidos, formol ou éter) no hospital:",
         "Os frascos de vidro devem ser transportados soltos nas mãos do trabalhador pelos corredores.",
         "Devem ser transportados em suportes rígidos ou cestas de material resistente com alça e bacia de contenção contra quebras e vazamentos acidentais.",
         "Devem ser rolados pelo chão cerâmico dos corredores por meio de chutes leves.",
         "Podem ser jogados pela janela do terceiro andar para o piso térreo.",
         "Devem ser guardados nos mesmos carrinhos de transporte de alimentos dos pacientes.",
         "B",
         "Frascos de vidro contendo químicos devem ser transportados em recipientes secundários resistentes e antichoque para conter o líquido em caso de quebra acidental.",
         "NR-32, item 32.3.3",
         "fácil"),
        # 16
        ("A rotulagem de produtos químicos no hospital, em conformidade com o Sistema Globalmente Harmonizado (GHS) adotado pela NR-26 e NR-32, deve conter:",
         "Apenas o preço de venda da mercadoria em reais.",
         "Identificação do produto, composição química, palavras de advertência (ex: Perigo), pictogramas de perigo, frases de perigo (H) e frases de precaução (P).",
         "Apenas a foto do prédio da fábrica fornecedora.",
         "A assinatura manuscrita do técnico de segurança do trabalho do turno da manhã.",
         "Apenas a data da última eleição presidencial do país.",
         "B",
         "A rotulagem segundo o GHS/NR-26 exige pictograma de perigo, identificação, palavra de advertência, frases de perigo (frases H) e frases de precaução (frases P).",
         "NR-26 e ABNT NBR 14725",
         "média"),
        # 17
        ("Qual é o pictograma do GHS utilizado para identificar substâncias químicas que apresentam perigo grave à saúde a longo prazo, como toxicidade para órgãos-alvo, carcinogenicidade e mutagenicidade (ex: quimioterápicos citostáticos)?",
         "Uma chama com fundo vermelho (inflamável).",
         "Um losango com a silhueta de busto humano com uma estrela branca no peito (perigo crônico à saúde).",
         "Um peixe e uma árvore mortos (perigo ambiental).",
         "Um ponto de exclamação preto (irritação dérmica).",
         "Uma caveira com tíbias cruzadas em fundo azul.",
         "B",
         "O pictograma de 'perigo à saúde humana' (busto com estrela rompida no tórax) indica carcinogenicidade, mutagenicidade, teratogenicidade e toxicidade respiratória crônica.",
         "GHS e NR-26",
         "difícil"),
        # 18
        ("Sobre o uso de óxido de etileno (EtO) para esterilização de materiais médicos termossensíveis em serviços de saúde terceirizados ou próprios:",
         "O óxido de etileno é um gás inodoro e completamente atóxico que pode ser inalado livremente pelos trabalhadores.",
         "O óxido de etileno é um gás extremamente tóxico, inflamável, mutagênico e carcinogênico humano, exigindo instalações isoladas, autoclaves automatizadas e monitoramento ambiental rigoroso.",
         "O óxido de etileno é utilizado como tempero culinário nas saladas dos pacientes da enfermaria.",
         "A esterilização por óxido de etileno pode ser realizada em panelas de pressão domésticas na copa do hospital.",
         "O trabalhador exposto ao óxido de etileno fica dispensado de exames periódicos de saúde.",
         "B",
         "O óxido de etileno é carcinógeno humano e altamente reativo, sujeito a requisitos estritos da Portaria Interministerial 482/1999 e da NR-32 (item 32.3.9).",
         "NR-32, item 32.3.9 e Portaria 482/1999",
         "difícil"),
        # 19
        ("A avaliação ambiental quantitativa de vapores de formaldeído e xilol nos laboratórios de patologia deve ser realizada pelo SESMT para:",
         "Comprovar que o laboratório não precisa de ar condicionado durante o verão.",
         "Comparar as concentrações no ar com os Limites de Tolerância da NR-15 (e ACGIH) e verificar a eficácia das medidas de engenharia (capelas de exaustão).",
         "Calcular a quantidade de formol que os funcionários podem levar para casa.",
         "Substituir os salários dos funcionários por cotas de reagentes químicos.",
         "Comprovar que o cheiro forte é inofensivo à saúde humana.",
         "B",
         "A medição quantitativa dos vapores no ar compara os níveis com o limite de tolerância da NR-15 e referenciais da ACGIH para controle e enquadramento do PGR.",
         "NR-09, NR-15 e NR-32",
         "média"),
        # 20
        ("Qual a recomendação preventiva para descarte de recipientes vazios ou com restos de anestésicos inalatórios voláteis (ex: frascos de vidro de sevoflurano)?",
         "Quebrar os frascos na pia do posto de enfermagem para evaporar o anestésico.",
         "Acondicionar em recipiente rígido, lacrado e rotulado como Resíduo Químico perigoso (Grupo B), encaminhando para tratamento e destinação final ambientalmente licenciada.",
         "Jogar os frascos no jardim do hospital para afastar mosquitos transmissores de dengue.",
         "Reaproveitar os frascos vazios de anestésicos como copos de água para os acompanhantes.",
         "Descartar no lixo comum reciclável sem esvaziamento prévio do produto.",
         "B",
         "Frascos contendo resíduos químicos perigosos devem ser descartados como Grupo B (resíduos químicos) para tratamento térmico ou destinação adequada.",
         "RDC 222/2018 e NR-32",
         "fácil"),

        # =========================================================
        # RISCO FÍSICO: RADIAÇÕES IONIZANTES (10 questões)
        # =========================================================
        # 21
        ("Em relação à proteção radiológica nos serviços de diagnóstico por imagem (raio-X fixo e móvel, tomografia) da FHCGV, a NR-32 e normas da CNEN estabelecem o princípio ALARA, que significa:",
         "Manter as exposições à radiação tão baixas quanto razoavelmente exequíveis (As Low As Reasonably Achievable), considerando fatores econômicos e sociais.",
         "Aumentar a dosagem de radiação ao máximo possível para obter imagens ultraprecisas em segundos.",
         "Substituir todos os aparelhos de raio-X por câmeras fotográficas convencionais de smartphone.",
         "Permitir que qualquer acompanhante segure o paciente sem avental de proteção durante os disparos.",
         "Operar os equipamentos de raio-X continuamente durante 24 horas ininterruptas.",
         "A",
         "O princípio ALARA (As Low As Reasonably Achievable) orienta a otimização da proteção radiológica para que as doses sejam as menores possíveis mantendo a qualidade diagnóstica.",
         "CNEN NN 3.01, RDC 611/ANVISA e NR-32",
         "fácil"),
        # 22
        ("Quais são os TRÊS fatores fundamentais da física de proteção contra a radiação ionizante externa utilizados para reduzir a dose recebida pelo trabalhador?",
         "Tempo de exposição, distância da fonte emissora e blindagem do ambiente/EPI.",
         "Pressão do ar, temperatura ambiente e luminosidade da sala.",
         "Tamanho da sala, cor das paredes e tipo de lâmpada do teto.",
         "Altura do paciente, peso do operador e tipo de sapato utilizado.",
         "Voltagem da rede elétrica, marca do computador e tipo de piso cerâmico.",
         "A",
         "A tríade fundamental de radioproteção baseia-se em: reduzir o TEMPO, aumentar a DISTÂNCIA (a dose cai com o inverso do quadrado da distância) e utilizar BLINDAGEM adequada.",
         "Princípios Básicos de Radioproteção e NR-32",
         "fácil"),
        # 23
        ("Os Equipamentos de Proteção Individual plumbíferos (avental de borracha com chumbo, protetor de tireoide e óculos plumbíferos) utilizados em raio-X devem apresentar atenuação mínima equivalente a:",
         "0,001 mm de alumínio reciclado.",
         "0,25 mm a 0,5 mm de chumbo (Pb), em conformidade com as normas sanitárias e da CNEN.",
         "10 metros de placas de concreto armado.",
         "50 mm de lâminas de ferro puro magnetizado.",
         "0,1 mm de papelão ondulado de embalagem.",
         "B",
         "Aventais e protetores plumbíferos para radiodiagnóstico geral devem ter espessura mínima equivalente a 0,25 mm de Pb (ou 0,5 mm de Pb para procedimentos de maior intensidade, como hemodinâmica).",
         "NR-32, item 32.4 e RDC 611/2022 ANVISA",
         "média"),
        # 24
        ("Com relação à conservação dos aventais de chumbo (borracha plumbífera) nos setores de imagem da FHCGV, é PROIBIDO:",
         "Guardá-los pendurados em suportes ou cabides próprios para aventais plumbíferos.",
         "Dobrálos sobre bancadas, amassá-los ou sentar-se sobre eles, pois isso provoca rachaduras e fraturas internas na lâmina de chumbo, gerando fendas de escape de radiação.",
         "Higienizá-los com pano umedecido em solução neutra de água e sabão.",
         "Realizar inspeção periódica para verificação de fissuras na blindagem.",
         "Identificá-los com número de registro para controle patrimonial e radiológico.",
         "B",
         "Dobrar ou amassar aventais plumbíferos quebra a camada interna de chumbo, criando fendas invisíveis que expõem o trabalhador a feixes diretos de radiação ionizante.",
         "NR-32, item 32.4 e Manuais de Radioproteção",
         "fácil"),
        # 25
        ("A periodicidade com que os aventais e vestimentas plumbíferas de proteção individual devem ser inspecionados física e radioscopicamente quanto à integridade da blindagem de chumbo é de no mínimo:",
         "A cada 30 anos.",
         "Anualmente (a cada 12 meses), registrando-se os laudos de conformidade.",
         "Semanalmente com uso de lupa de aumento comum.",
         "Apenas após o descarte do equipamento no lixo hospitalar.",
         "Diariamente por pesagem em balança de precisão.",
         "B",
         "As vestimentas plumbíferas devem ser submetidas a teste radioscópico ou radiográfico anual para avaliar a presença de fendas e rachaduras que comprometam a radioproteção.",
         "RDC 611/2022 ANVISA e NR-32",
         "média"),
        # 26
        ("Em relação ao uso do dosímetro individual de tórax pelo profissional ocupacionalmente exposto a radiação ionizante (técnico em radiologia):",
         "O dosímetro deve ser utilizado sob o avental de chumbo (na altura do tórax), durante toda a jornada de trabalho no hospital, e trocado mensalmente para leitura e registro de dose.",
         "O dosímetro deve ser levado para casa e deixado em frente ao aparelho de televisão nos finais de semana.",
         "O dosímetro deve ser compartilhado por todos os técnicos do mesmo turno de plantão.",
         "O dosímetro é de uso opcional caso o trabalhador tenha ingerido leite com aveia antes do plantão.",
         "O dosímetro deve ser colocado diretamente sobre o tubo emissor de raio-X durante os disparos.",
         "A",
         "O dosímetro mede a dose individual recebida pelo operador; é pessoal, intransferível, de troca mensal, e deve ser guardado no dosímetro padrão quando o trabalhador não estiver no setor.",
         "Normas CNEN e NR-32, item 32.4",
         "fácil"),
        # 27
        ("Qual é a conduta imediata em relação à trabalhadora técnica em radiologia que notifica formalmente a sua gravidez à chefia da FHCGV?",
         "Aumentar o número de exames de tomografia realizados por ela durante o primeiro trimestre gestacional.",
         "Remanejá-la imediatamente para atividades sem exposição a radiação ionizante (funções administrativas ou fora das áreas controladas), garantindo que a dose na superfície do abdome não exceda 1 mSv durante todo o período gestacional restante.",
         "Obrigar a gestante a assinar pedido de demissão imediata sem justa causa.",
         "Retirar o dosímetro da trabalhadora para não registrar a radiação recebida pelo feto.",
         "Manter a trabalhadora na mesma função, exigindo que ela use três aventais de chumbo sobrepostos durante 12 horas em pé.",
         "B",
         "A trabalhadora gestante deve ser remanejada para áreas não controladas para proteger o feto de malformações e efeitos teratogênicos; o limite de dose no feto é de 1 mSv durante a gestação.",
         "CNEN NN 3.01 e NR-32, item 32.4.4",
         "média"),
        # 28
        ("A sinalização visual de segurança das salas onde operam equipamentos geradores de radiação ionizante (sala de raio-X e tomografia) deve conter obrigatoriamente:",
         "Apenas uma placa comercial com horário de funcionamento da lanchonete.",
         "O símbolo internacional de radiação ionizante (trifólio magenta ou preto sobre fundo amarelo), aviso de acesso restrito a pessoal autorizado e sinalização luminosa vermelha na porta indicando equipamento em funcionamento/emissão.",
         "Apenas o desenho de uma caveira com fita adesiva cinza comum.",
         "Uma bandeira oficial do Estado do Pará pendurada na fechadura.",
         "Aviso de que o ambiente é totalmente estéril e livre de qualquer forma de energia.",
         "B",
         "As salas de radiação exigem sinalização padronizada com o trifólio de radiação ionizante, controle de acesso e lâmpada vermelha de disparo (sinalização luminosa de aviso).",
         "NR-32, item 32.4.2 e RDC 611/2022",
         "fácil"),
        # 29
        ("Durante a realização de exames com equipamento móvel de raio-X no leito de pacientes na UTI da FHCGV, a equipe de enfermagem e demais pacientes do leito ao lado devem:",
         "Aproximar-se ao máximo do leito examinado para observar a tela do aparelho.",
         "Manter distância de segurança mínima preconizada (no mínimo 2 metros) ou ficar atrás de biombo plumbífero durante o disparo radiográfico, e usar avental de chumbo se precisarem permanecer próximos.",
         "Segurar o tubo do raio-X móvel com as mãos para impedir trepidações no chão.",
         "Colocar toalhas molhadas sobre o tórax para absorver os fótons de raio-X.",
         "Deitar-se no mesmo leito do paciente examinado durante o exame.",
         "B",
         "O uso de raio-X móvel exige aviso sonoro prévio, afastamento das pessoas a uma distância segura (pelo menos 2 metros) ou uso de biombos móveis e aventais plumbíferos.",
         "NR-32, item 32.4 e RDC 611/2022",
         "média"),
        # 30
        ("Em relação à realização de exames radiográficos em pacientes agitados, crianças ou debilitados que necessitem de contenção física:",
         "O operador técnico de radiologia deve segurar o paciente com uma mão e acionar o botão de disparo com a outra mão sem avental.",
         "A contenção deve ser feita prioritariamente por acompanhante do paciente devidamente paramentado com avental plumbífero e protetor de tireoide, sendo proibido ao trabalhador de radiologia segurar o paciente sistematicamente.",
         "A contenção física do paciente é terminantemente proibida por lei em qualquer caso de emergência médica.",
         "Deve-se pedir ao estagiário mais jovem da farmácia que segure o paciente desprotegido.",
         "O paciente deve ser amarrado com correntes de ferro fundido à mesa de exame sem acompanhante.",
         "B",
         "Trabalhadores ocupacionalmente expostos não devem ser utilizados habitualmente para contenção de pacientes durante disparos; essa função cabe a acompanhantes informados e protegidos com EPI plumbífero.",
         "RDC 611/2022 ANVISA e NR-32",
         "média")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-32",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr32_quimico_fisico_questions()
    print(f"Quimico & Fisico questions generated: {len(q)}")
