# -*- coding: utf-8 -*-
"""
Gerador de Questões da NR-17: Ergonomia (30 questões)
- Movimentação manual de cargas: 15 questões
- AEP e AET: 10 questões
- Trabalho em turnos e organização do trabalho: 5 questões
"""

def get_nr17_questions():
    items = [
        # =========================================================
        # 1. MOVIMENTAÇÃO MANUAL DE CARGAS (15 questões)
        # =========================================================
        # 1
        ("O subitem 17.5.1 da NR-17 estabelece que o transporte manual regular de cargas deve ser executado de forma que:",
         "O peso da carga não comprometa a saúde ou a segurança do trabalhador, adotando-se medidas de prevenção técnicas e organizacionais.",
         "O trabalhador carregue no mínimo 100 kg sozinho em cada viagem.",
         "Apenas homens com mais de 50 anos sejam autorizados a levantar pesos.",
         "As cargas pesadas sejam obrigatoriamente arremessadas pelo ar entre os funcionários.",
         "O empregado assine um termo abrindo mão de sua coluna vertebral.",
         "A",
         "A NR-17 (item 17.5.1) determina que nenhum trabalhador deve transportar manualmente cargas cujo peso seja suscetível de comprometer sua saúde ou segurança.",
         "NR-17, item 17.5.1",
         "fácil"),
        # 2
        ("Qual é o limite máximo legal de peso para o transporte manual contínuo de cargas por mulheres trabalhadoras fixado pelo Artigo 390 da CLT?",
         "20 kg para o trabalho contínuo e 25 kg para o trabalho ocasional.",
         "50 kg para o trabalho contínuo e 80 kg para o trabalho ocasional.",
         "5 kg para qualquer atividade sob pena de rescisão.",
         "Não existe nenhum limite de peso para mulheres na legislação brasileira.",
         "10 kg exclusivamente se a trabalhadora for solteira.",
         "A",
         "O Art. 390 da CLT fixa para mulheres o limite máximo de 20 kg para trabalho contínuo e 25 kg para trabalho ocasional no transporte manual de cargas.",
         "CLT Art. 390 e NR-17",
         "fácil"),
        # 3
        ("Durante a técnica correta de levantamento manual de uma caixa pesada do chão, o trabalhador deve adotar a seguinte postura biomecânica protetora:",
         "Flexionar os joelhos mantendo as costas eretas, segurar a carga junto ao corpo e levantar usando a força dos músculos das pernas, sem torcer o tronco.",
         "Manter as pernas totalmente retas e esticadas e curvar as costas a 90 graus forçando a lombar.",
         "Girar o tronco bruscamente para o lado oposto no mesmo instante do levantamento.",
         "Segurar a caixa na ponta dos dedos com os braços esticados para frente bem longe do peito.",
         "Prender a respiração e puxar a carga com a força exclusiva dos músculos do pescoço.",
         "A",
         "O levantamento ergonômico correto utiliza a flexão de pernas, preserva as curvaturas fisiológicas da coluna, aproxima o centro de gravidade da carga do corpo e evita torção espinhal.",
         "Princípios de Biomecânica Ocupacional e NR-17",
         "fácil"),
        # 4
        ("Na transferência de um paciente acamado obeso e dependente para a maca na enfermaria da FHCGV, a melhor prática ergonômica de prevenção de lombalgias é:",
         "Realizar a manobra com o auxílio de mais profissionais (no mínimo 2 a 3 pessoas), ajustando a altura do leito, travando as rodas e utilizando dispositivos de deslizamento (prancha rollboard ou lençol traçador).",
         "Determinar que uma única técnica de enfermagem puxe o paciente sozinha no colo.",
         "Puxar o paciente pelas pernas bruscamente da cama para o chão.",
         "Jogar o paciente de uma cama para a outra com um empurrão rápido.",
         "Exigir que o próprio paciente salte para a maca mesmo que esteja sedado.",
         "A",
         "A movimentação segura de pacientes acamados exige trabalho compartilhado em equipe, regulagem da altura dos leitos, travas acionadas e uso de recursos auxiliares de deslizamento.",
         "NR-17 e Diretrizes de Ergonomia Hospitalar",
         "fácil"),
        # 5
        ("O uso de meios técnicos e dispositivos mecânicos para o transporte e movimentação de cargas e pacientes (como guinchos de transferência elétricos, carrinhos hidráulicos e esteiras) visa:",
         "Eliminar ou reduzir a sobrecarga osteomuscular sobre a coluna vertebral e membros superiores dos trabalhadores de saúde.",
         "Aumentar o esforço físico dos enfermeiros durante o plantão noturno.",
         "Substituir todos os médicos por operadores de guindaste de porto.",
         "Tornar o atendimento médico mais lento e ineficiente de propósito.",
         "Comprovar que o hospital não precisa de enfermeiros concursados.",
         "A",
         "Dispositivos mecânicos de auxílio reduzem drasticamente as forças de compressão discal lombar e cisalhamento, prevenindo hérnias de disco e LER/DORT.",
         "NR-17, item 17.5.2",
         "fácil"),
        # 6
        ("Dentre os fatores de risco ergonômico associados ao levantamento manual de cargas, a distância horizontal entre a carga e o corpo do trabalhador atua:",
         "Aumentando o braço de alavanca e multiplicando a força de compressão exercida sobre as vértebras lombares (L5-S1) conforme a carga se afasta do tronco.",
         "Diminuindo o peso real da carga pela ação da gravidade invertida.",
         "Eliminando qualquer risco de lesão muscular nas costas.",
         "Fazendo com que o trabalhador gaste menos energia física.",
         "Protegendo as articulações dos ombros contra bursites e tendinites.",
         "A",
         "Quanto mais distante a carga estiver do corpo (maior o braço de alavanca), maior será o torque mecânico resistivo e a compressão discal na coluna lombar.",
         "Equação do NIOSH e Biomecânica da Coluna",
         "média"),
        # 7
        ("A Equação de Levantamento do NIOSH (National Institute for Occupational Safety and Health) é uma metodologia amplamente reconhecida na NR-17 para:",
         "Calcular o Limite de Peso Recomendado (LPR) e o Índice de Levantamento (IL) para tarefas de levantamento manual de cargas em postos de trabalho.",
         "Medir a quantidade de calorias consumidas no café da manhã do refeitório.",
         "Estimar a velocidade de digitação em teclados de computador de escritório.",
         "Determinar a quantidade de cloro que deve ser jogada na caixa d'água.",
         "Avaliar a qualidade acústica de microfones em salas de conferência.",
         "A",
         "A fórmula do NIOSH avalia a ergonomia do levantamento manual multiplicando fatores de peso, altura, distância, assimetria, frequência e pega para obter o LPR.",
         "Critérios NIOSH e Manual de Ergonomia NR-17",
         "média"),
        # 8
        ("Se uma tarefa de levantamento de caixas de soro fisiológico apresentar um Índice de Levantamento (IL) do NIOSH SUPERIOR A 1,0 (IL > 1,0):",
         "A tarefa apresenta risco potencial de lesão osteomuscular para uma fração considerável da população trabalhadora, exigindo redesenho ergonômico do posto.",
         "A tarefa é considerada ergonomicamente perfeita e livre de qualquer esforço físico.",
         "O trabalhador deve receber um troféu de levantamento de peso olímpico.",
         "A empresa está isenta de fornecer carrinhos de transporte interno.",
         "O trabalho deve ser executado obrigatoriamente durante 24 horas ininterruptas.",
         "A",
         "IL <= 1,0 é o patamar seguro do NIOSH; valores acima de 1,0 indicam risco biomecânico progressivo que requer intervenções ergonômicas imediatas.",
         "Equação do NIOSH e Ergonomia",
         "média"),
        # 9
        ("A respeito do transporte de caixas e volumes que bloqueiem a visão do trabalhador durante a caminhada:",
         "A NR-17 e as normas preventivas vedam o transporte de cargas cujas dimensões impeçam a visibilidade da rota de circulação pelo trabalhador.",
         "É permitido e incentivado para aguçar a percepção sensorial auditiva do operador.",
         "O trabalhador deve caminhar de costas com a carga sobre a cabeça.",
         "É permitido apenas se outro funcionário for empurrado na frente como batedor.",
         "Deve ser realizado com o trabalhador correndo para evitar cansaço nos braços.",
         "A",
         "Cargas volumosas que obstruem a visão frontal do trajeto aumentam o risco de tropeços, quedas de mesmo nível, colisões e quedas em desníveis.",
         "NR-17 e Prevenção de Acidentes",
         "fácil"),
        # 10
        ("Qual a exigência ergonômica da NR-17 quanto às pegas e alças das caixas e recipientes manipulados manualmente no almoxarifado hospitalar?",
         "Devem permitir empunhadura segura e confortável, com bordas arredondadas e formato que não comprima nervos e vasos sanguíneos da palma das mãos.",
         "Devem ter pontas afiadas de aço cortante para estimular o reflexo neuromuscular.",
         "Devem ser obrigatoriamente lubrificadas com óleo mineral para deslizarem facilmente.",
         "Devem ser dispensadas, devendo o trabalhador prensar a carga com a ponta do nariz.",
         "Devem ser amarradas com linha de costura ultrafina que machuque os dedos.",
         "A",
         "Alças adequadas garantem pega de boa qualidade (power grip), diminuem a força de preensão exigida e reduzem a fadiga dos músculos do antebraço.",
         "NR-17, item 17.5.3",
         "fácil"),
        # 11
        ("Em relação à altura da superfície de trabalho (como bancadas de separação de medicamentos ou mesas de preparo cirúrgico), a NR-17 preconiza que:",
         "A altura deve ser compatível com a estatura do trabalhador e com a natureza da tarefa realizada (mais alta para tarefas visuais de precisão e mais baixa para tarefas com força).",
         "Todas as mesas do hospital devem ter exatamente 40 centímetros de altura do chão.",
         "As mesas devem ser fixadas no teto a 2,5 metros de altura.",
         "A altura da mesa deve ser sorteada mensalmente pelo setor de marcenaria.",
         "O trabalhador deve trabalhar sempre ajoelhado sobre o piso de cerâmica.",
         "A",
         "A altura correta da bancada varia com a biometria do usuário e a demanda do trabalho: cotovelo é o referencial (acima do cotovelo para precisão, abaixo para força muscular).",
         "NR-17, item 17.6 e Princípios de Ergonomia",
         "fácil"),
        # 12
        ("A torção axial do tronco combinada com a inclinação para frente durante o levantamento de peso é considerada um dos movimentos mais nocivos para a coluna porque:",
         "Provoca sobrecarga assimétrica e cisalhamento sobre as fibras do ânulo fibroso do disco intervertebral, aumentando exponencialmente o risco de herniação discal.",
         "Aumenta a circulação de sangue no cérebro causando perda de apetite.",
         "Fortalece instantaneamente todos os ossos da bacia pélvica.",
         "Impede que o trabalhador respire oxigênio por mais de duas horas.",
         "Provoca a descoloração dos sapatos de segurança utilizados.",
         "A",
         "A rotação combinada com flexão estressa criticamente as fibras anulares do disco lombar, facilitando rupturas e expulsão do núcleo pulposo (hérnia de disco).",
         "Biomecânica da Coluna e NR-17",
         "média"),
        # 13
        ("Em relação ao piso dos corredores e setores onde há transporte manual de cargas e movimentação de carrinhos e leitos na FHCGV, a NR-17 e NR-08 exigem que seja:",
         "Plano, nivelado, antiderrapante, livre de obstáculos, fendas, desníveis ou ressaltos que dificultem a movimentação ou causem trancos nos membros superiores.",
         "Inclinado em 45 graus para facilitar o escorregamento dos carrinhos.",
         "Coberto por pedras soltas pontiagudas de cascalho e brita.",
         "Encerado diariamente com óleo lubrificante automotivo.",
         "Construído com buracos profundos para armazenamento de água da chuva.",
         "A",
         "Pisos nivelados, regulares e sem obstáculos diminuem a resistência ao rolamento de carrinhos e eliminam riscos de tropeços e sobrecargas bruscas na coluna.",
         "NR-17 e NR-08",
         "fácil"),
        # 14
        ("Os assentos utilizados nos postos de trabalho onde as atividades podem ser executadas sentadas (como triagem da recepção e bancadas de farmácia) devem atender aos seguintes requisitos da NR-17:",
         "Altura ajustável à estatura do trabalhador e à natureza da função, borda frontal arredondada, encosto com suporte lombar e base com estabilidade.",
         "Assento de pedra granito liso sem encosto e sem qualquer regulagem de altura.",
         "Bancos giratórios de madeira dura com pontas de pregos salientes no encosto.",
         "Cadeiras de praia de plástico dobráveis com altura fixa de 20 centímetros.",
         "Poltronas estofadas com plumas de ganso que façam o operador afundar 50 centímetros.",
         "A",
         "O item 17.6 da NR-17 detalha requisitos de cadeiras: altura ajustável, borda anterior arredondada, encosto anatômico lombar e estabilidade com 5 rodízios.",
         "NR-17, item 17.6.6",
         "fácil"),
        # 15
        ("Para atividades em que os trabalhos devam ser realizados de pé, a NR-17 (subitem 17.6.3) determina que:",
         "Devem ser disponibilizados assentos para serem utilizados nas pausas que possam ser feitas durante a jornada de trabalho, em locais acessíveis aos trabalhadores.",
         "O trabalhador fica expressamente proibido de se sentar durante toda a sua vida profissional.",
         "O trabalhador deve ficar amarrado a um poste de madeira ereto.",
         "A jornada de trabalho em pé deve ser estendida para 24 horas consecutivas.",
         "A empresa deve confiscar todas as cadeiras do estabelecimento para evitar preguiça.",
         "A",
         "O trabalho em pé prolongado gera estase venosa e fadiga lombar; a NR-17 obriga a colocação de assentos para descanso nas pausas de tarefas estáticas.",
         "NR-17, item 17.6.3",
         "fácil"),

        # =========================================================
        # 2. AVALIAÇÃO ERGONÔMICA PRELIMINAR (AEP) E ANÁLISE ERGONÔMICA DO TRABALHO (AET) (10 questões)
        # =========================================================
        # 16
        ("A nova redação da NR-17 estruturou o processo de gestão ergonômica em duas etapas complementares e sucessivas:",
         "A Avaliação Ergonômica Preliminar (AEP) e a Análise Ergonômica do Trabalho (AET).",
         "O Teste de Aptidão Física Militar e a Pesagem Balística.",
         "O Laudo Contábil de Custos e o Balanço Patrimonial de Vendas.",
         "A Entrevista de Demissão e o Teste de DNA Laboratorial.",
         "O Exame Pré-nupcial e a Certidão Negativa de Protestos.",
         "A",
         "A nova NR-17 introduziu a AEP (Avaliação Ergonômica Preliminar integrada ao GRO/PGR) e reservou a AET para situações complexas ou com exigência aprofundada.",
         "NR-17, itens 17.3.1 e 17.3.2",
         "fácil"),
        # 17
        ("A Avaliação Ergonômica Preliminar (AEP) das situações de trabalho deve ser realizada pela organização para:",
         "Identificar os perigos e produzir subsídios para o planejamento das medidas de prevenção incluídas no PGR.",
         "Determinar quais funcionários devem ser transferidos para outro município.",
         "Substituir o exame médico periódico realizado pelo médico do trabalho.",
         "Calcular o imposto sobre a propriedade territorial do prédio hospitalar.",
         "Comprar móveis de escritório de luxo para a sala da presidência.",
         "A",
         "A AEP é a triagem ergonômica inicial obrigatória de todos os postos de trabalho para mapear fatores de risco e alimentar o Inventário de Riscos do PGR.",
         "NR-17, item 17.3.1",
         "fácil"),
        # 18
        ("A organização deve realizar a Análise Ergonômica do Trabalho (AET), um estudo detalhado e aprofundado da situação de trabalho, nas seguintes circunstâncias, EXCETO:",
         "Quando for necessária uma avaliação mais aprofundada da situação ergonômica identificada na AEP.",
         "Quando forem identificadas inadequações ou insuficiências das medidas de prevenção adotadas.",
         "Quando sugerida pelo acompanhamento de saúde dos trabalhadores no PCMSO.",
         "Quando indicada em decorrência de análise de acidentes e doenças relacionadas ao trabalho.",
         "Obrigatoriamente a cada 15 dias para todos os escritórios administrativos sem riscos.",
         "E",
         "A AET não é um documento bimestral de rotina para escritórios simples; ela é disparada por gatilhos técnicos previstos taxativamente no subitem 17.3.2 da NR-17.",
         "NR-17, item 17.3.2",
         "média"),
        # 19
        ("A AET (Análise Ergonômica do Trabalho) contempla o estudo minucioso da atividade real de trabalho, compreendendo:",
         "A análise da demanda, a análise da tarefa prescrita em confronto com a atividade real executada, os fatores ambientais, a biomecânica e a organização do trabalho.",
         "Apenas o tamanho da tela do computador do diretor de compras.",
         "A conferência da marca dos sapatos usados pelos trabalhadores.",
         "O recolhimento de assinaturas de apoio político em anos eleitorais.",
         "A medição da velocidade do vento nas janelas externas do edifício.",
         "A",
         "A metodologia da AET baseia-se na Ergonomia da Atividade, analisando o trabalho real, variabilidades, constrangimentos biomecânicos e organizacionais.",
         "NR-17, item 17.3.3 e Metodologia Francesa de Ergonomia",
         "média"),
        # 20
        ("Qual é o papel dos trabalhadores durante a realização da Avaliação Ergonômica Preliminar (AEP) e da AET pela equipe de SST?",
         "Os trabalhadores devem ser ouvidos e participar ativamente do processo de identificação dos desconfortos, perigos e na proposição de melhorias ergonômicas.",
         "Os trabalhadores devem ser proibidos de falar com o ergonomista sob pena de demissão.",
         "Os trabalhadores devem se esconder nos banheiros enquanto durar a inspeção.",
         "Apenas o presidente da fundação hospitalar tem autorização para emitir opiniões.",
         "Os trabalhadores devem assinar relatórios em branco sem ler o conteúdo.",
         "A",
         "A participação dos operadores reais é pilar da ergonomia; eles vivenciam as exigências do posto e indicam as dificuldades operacionais e dores sentidas.",
         "NR-17, item 17.3.4",
         "fácil"),
        # 21
        ("O relatório da AET deve conter recomendações ergonômicas práticas e aplicáveis que devem ser integradas ao:",
         "Plano de Ação do Programa de Gerenciamento de Riscos (PGR) da organização.",
         "Livro de receitas de sobremesas da copa do hospital.",
         "Arquivo morto de processos judiciais encerrados.",
         "Diário de bordo dos motoristas de ambulância da capital.",
         "Edital de licitação de compra de materiais de limpeza.",
         "A",
         "As medidas ergonômicas apontadas na AET devem ser absorvidas pelo Plano de Ação do PGR, com responsáveis, cronogramas e monitoramento de eficácia.",
         "NR-17, item 17.3.6 e NR-01",
         "fácil"),
        # 22
        ("Em relação às Microempresas (ME) e Empresas de Pequeno Porte (EPP) enquadradas nos graus de risco 1 e 2:",
         "Estão dispensadas da elaboração da AET, mas devem realizar a AEP e implementar as medidas de prevenção ergonômica decorrentes.",
         "Estão autorizadas a submeter seus trabalhadores a cargas de 200 kg nas costas.",
         "Ficam proibidas de comprar cadeiras com rodízios e encosto acolchoado.",
         "Devem fechar as portas caso comprem computadores para seus escritórios.",
         "Não precisam cumprir nenhuma Norma Regulamentadora do Ministério do Trabalho.",
         "A",
         "A NR-17 (item 17.3.7) dispensa ME e EPP graus de risco 1 e 2 da AET completa, mas mantém o dever de realizar a avaliação preliminar e aplicar soluções ergonômicas.",
         "NR-17, item 17.3.7",
         "média"),
        # 23
        ("Os parâmetros de CONFORTO AMBIENTAL para ambientes de trabalho onde são executadas atividades que exijam solicitação intelectual e atenção constante (como postos de enfermagem, farmácia e escritórios) exigem:",
         "Nível de ruído de conforto aceitável (conforme NBR 10152), temperatura operacional entre 18ºC e 25ºC e iluminação adequada e uniforme sem ofuscamento.",
         "Temperatura de 45ºC com ar parado para estimular a transpiração dos funcionários.",
         "Lâmpadas estroboscópicas que pisquem rapidamente a cada segundo no teto.",
         "Ruído de britadeira industrial contínuo para evitar que os empregados durmam.",
         "Escuridão total com janelas cobertas com lona preta em todas as salas.",
         "A",
         "O item 17.8 da NR-17 define parâmetros de conforto: temperatura entre 18ºC e 25ºC em ambientes climatizados, iluminação adequada (NBR ISO/CIE 8995-1) e ruído de conforto.",
         "NR-17, item 17.8",
         "fácil"),
        # 24
        ("A iluminação nos postos de trabalho da FHCGV, seja ela natural ou artificial, deve ser planejada para evitar:",
         "Ofuscamento, reflexos incômodos nas telas de computadores, sombras excessivas e contrastes visuais acentuados.",
         "Que os trabalhadores enxerguem os relógios de parede nos corredores.",
         "A claridade natural do sol nos horários de almoço.",
         "O uso de lâmpadas de LED econômicas e duráveis.",
         "A leitura das receitas médicas e rótulos de medicamentos pelos técnicos.",
         "A",
         "A boa ergonomia visual requer iluminação uniforme, sem cintilação, evitando reflexos em monitores que causem astenopia (fadiga visual) e posturas compensatórias.",
         "NR-17, item 17.8 e NBR ISO/CIE 8995-1",
         "fácil"),
        # 25
        ("Se a fiscalização do trabalho ou a perícia judicial constatar a presença de trabalhadores acometidos por tendinites e lombalgias crônicas em um hospital que nunca realizou AEP nem AET:",
         "O empregador responderá por descumprimento das normas de ergonomia e segurança (NR-17 e NR-01), sujeitando-se a multas administrativas, Termos de Ajuste de Conduta (TAC) do MPT e indenizações por danos morais e materiais aos adoecidos.",
         "A fundação receberá um prêmio de eficiência orçamentária do Ministério da Fazenda.",
         "Os trabalhadores doentes serão obrigados a devolver o dinheiro dos salários recebidos.",
         "O juiz determinará a demolição do prédio hospitalar sem prévio aviso.",
         "O hospital fica autorizado a não pagar o décimo terceiro salário no final do ano.",
         "A",
         "A omissão ergonômica com nexo causal em DORT gera responsabilidade civil objetiva/subjetiva do empregador e sanções severas dos órgãos de fiscalização do trabalho.",
         "Código Civil Art. 927, CLT e NR-17",
         "fácil"),

        # =========================================================
        # 3. TRABALHO EM TURNOS E ORGANIZAÇÃO DO TRABALHO (5 questões)
        # =========================================================
        # 26
        ("A respeito da ORGANIZAÇÃO DO TRABALHO segundo a NR-17 (item 17.4), ela deve levar em consideração:",
         "As normas de produção, o modo operatório, a exigência de tempo, a determinação do conteúdo de tempo, o ritmo de trabalho e o conteúdo das tarefas.",
         "Apenas o signo do zodíaco do trabalhador nascido no mês vigente.",
         "A preferência musical do gerente de compras do hospital.",
         "A distância em quilômetros do hospital até o Oceano Atlântico.",
         "O preço das passagens de avião para viagens de turismo.",
         "A",
         "A organização do trabalho engloba pressões temporais, cadência, ritmo, metas de produção, pausas, complexidade das tarefas e autonomia do operador.",
         "NR-17, item 17.4",
         "fácil"),
        # 27
        ("As PAUSAS regulamentares durante a jornada de trabalho em atividades que exigem sobrecarga muscular estática ou repetitividade de movimentos:",
         "Devem ser usufruídas fora do posto de trabalho, serem computadas como tempo de trabalho efetivo e não podem ser acompanhadas de aumento do ritmo após o retorno.",
         "Devem ser descontadas integralmente do salário do trabalhador no final do mês.",
         "Devem ser pagas com horas extras realizadas de madrugada no dia seguinte.",
         "Devem ser usufruídas enquanto o funcionário lava as privadas do setor.",
         "Ficam proibidas caso o dia da semana seja uma segunda-feira.",
         "A",
         "Pausas ergonômicas são parte integrante da jornada de trabalho (remuneradas), destinadas à recuperação fisiológica sem compensação posterior de sobrecarga.",
         "NR-17, item 17.4.4",
         "fácil"),
        # 28
        ("O trabalho hospitalar em regime de TURNOS e PLANTÕES NOTURNOS (como a escala 12x36 horas) altera os ritmos circadianos biológicos do ser humano, estando associado a:",
         "Distúrbios do ciclo vigília-sono, fadiga crônica, alterações gastrointestinais, desregulação hormonal e aumento do risco de erros e acidentes ocupacionais.",
         "Aumento instantâneo da força física dos ossos dos braços.",
         "Cura espontânea de todas as infecções bacterianas do corpo.",
         "Redução permanente da necessidade de dormir para 10 minutos por dia.",
         "Ganho de visão telescópica noturna natural semelhante à dos felinos.",
         "A",
         "O trabalho noturno perturba o ciclo circadiano, a produção de melatonina e cortisol, favorecendo insônia, irritabilidade, síndrome de burnout e acidentes.",
         "Cronobiologia e NR-17",
         "fácil"),
        # 29
        ("Para minimizar o impacto nocivo do trabalho em turnos rotativos sobre a saúde dos profissionais da FHCGV, a recomendação cronobiológica e ergonômica é:",
         "Adotar preferencialmente a rotação no sentido horário para frente (turno da manhã -> turno da tarde -> turno da noite), com intervalos regulares e salas de descanso apropriadas.",
         "Alternar os plantões a cada duas horas de forma totalmente caótica e imprevisível.",
         "Obrigar os funcionários a não dormirem durante os seus dias de folga.",
         "Proibir a ingestão de alimentos quentes e líquidos durante as madrugadas.",
         "Eliminar qualquer folga semanal durante períodos de 6 meses seguidos.",
         "A",
         "A rotação horária para frente respeita a tendência natural de extensão do relógio circadiano humano (> 24 horas), facilitando a adaptação fisiológica do sono.",
         "Diretrizes de Cronobiologia e Medicina do Trabalho",
         "média"),
        # 30
        ("Em relação às salas de descanso e conforto destinadas aos profissionais de enfermagem em plantões na FHCGV (conforme a Lei Federal nº 14.602/2023 e NR-17):",
         "Devem dispor de ambiente climatizado, leitos adequados, silêncio, privacidade, iluminação controlada e instalações sanitárias privativas higienizadas.",
         "Devem ser localizadas dentro do expurgo de resíduos biológicos com lixo aberto.",
         "Podem ser substituídas por caixas de papelão colocadas no chão dos corredores.",
         "Ficam proibidas para servidores que trabalhem mais de 6 horas por dia.",
         "Devem ser alugadas com cobrança de diária de hotel dos próprios enfermeiros.",
         "A",
         "A Lei 14.602/2023 assegura condições dignas de repouso aos profissionais de enfermagem durante os plantões, com leitos adequados, climatização e salubridade.",
         "Lei 14.602/2023 e NR-17",
         "fácil")
    ]
    
    questions = []
    for item in items:
        questions.append({
            "materia": "NR-17",
            "dificuldade": item[8],
            "enunciado": item[0],
            "alternativas": {
                "A": item[1],
                "B": item[2],
                "C": item[3],
                "D": item[4],
                "E": item[5]
            },
            "resposta_correta": item[6],
            "comentario": item[7],
            "referencia": item[8] if len(item) > 9 else item[7]
        })
    return questions

if __name__ == '__main__':
    q = get_nr17_questions()
    print(f"NR-17 questions generated: {len(q)}")
